### ISSUE TITLE
Mocking private method, which returns nothing

### ISSUE THREAD

**Issue by ImangazalievM** [mockk/mockk#103]
I have the following code:

```kotlin
class MyClass {

    fun myPublicMethod() {
        //...
        myPrivateMethod()
        //...
    }

    private fun myPrivateMethod() {
        //do something
    }

}
```

I want to mock "myPrivateMethod", so I wrote the following test:

```kotlin
class PrivateMethodMockingTest {

    @Test
    fun getAdapter() {
        val myClass = spyk(MyClass())
        every { myClass invoke "myPrivateMethod" withArguments  listOf() } returns Unit

        myClass.myPublicMethod()

        verify {
            myClass invoke "myPrivateMethod"
        }
    }

}
```

But i get the following exception:

```
io.mockk.MockKException: Missing calls inside verify { ... } block.

	at io.mockk.impl.recording.states.VerifyingState.checkMissingCalls(VerifyingState.kt:51)
	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:20)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:42)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:48)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:27)
	at org.quranacademy.quran.data.translations.database.PrivateMethodMockingTest.getAdapter(PrivateMethodMockingTest.kt:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:570)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:253)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
```

I would also note that these constructions do not work:

```kotlin
every { myClass invoke "myPrivateMethod" } just Runs
//or
every { myClass invoke "myPrivateMethod" } returns Unit
```

Instead, I have to use this construction:

```kotlin
every { myClass invoke "myPrivateMethod" withArguments  listOf() } returns Unit
```

**Comment by oleksiyp** [comment]
Seems this behavior is rather a feature than a bug. Dynamic "invoke" require "withArguments" clause. But I am wondering if I can redesign it to work like you mentioned.

**Comment by oleksiyp** [comment]
After thinking about options simplest way would be to introduce:
```
every { myClass invokeNoArgs "myPrivateMethod" } returns Unit
```

I know this sounds like workaround, but few full-blown solutions seems require too high rework.

@ImangazalievM  What do you think?

**Comment by ImangazalievM** [comment]
Looks good. But does it fix the problem with `Missing calls inside verify { ... } block.` error? I cloned this project, but unfortunately, I couldn't run tests.

**Comment by oleksiyp** [comment]
It will fix the problem:
```
verify { myClass invoke "myPrivateMethod" withArguments  listOf() }
```
works.

And:
```
verify { myClass invokeNoArgs "myPrivateMethod" }
```
is same and works too.

Of course
```
verify { myClass invoke "myPrivateMethod" }
```
is not wokring.

**Comment by ImangazalievM** [comment]
Ok. Thanks!
