### ISSUE TITLE
Mocking nullable unsigned types hangs

### ISSUE THREAD

**Issue by cdprete** [mockk/mockk#1031]
Hi.
When trying to mock an **unsigned** **nullable** type with `mockk` `1.12.5` (newer versions are broken for me), the test code just hangs.
Below an example to reproduce the issue:

```kotlin
import io.mockk.every
import io.mockk.impl.annotations.RelaxedMockK
import io.mockk.junit5.MockKExtension
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.ExtendWith

/**
 * @author tk35c
 * @since 23/01/2023
 **/
@ExtendWith(MockKExtension::class)
class TestNullableUnsignedTypes {
    @RelaxedMockK
    private lateinit var foo: Foo

    @Test
    fun `should mock nullable unsigned types correctly`() {
        // given
        every { foo.foo } returns 1u

        // then -> hangs on the mock
        error("We don't reach here")
    }
}

data class Foo(val foo: UInt? = null)
```

By running the test, it's clear that the `error` statement is never reached.

**Comment by Gounlaf** [comment]
Same here. It produces a `StackOverflowError`.

```
java.lang.StackOverflowError
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:26)
	at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:21)
	at kotlin.ULong.toString(ULong.kt:378)
	at java.base/java.lang.String.valueOf(String.java:4461)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
	at io.mockk.Invocation.toString(API.kt:3905)
	at io.mockk.impl.recording.CallRoundBuilder$addSignedCall$signedCall$1.invoke(CallRoundBuilder.kt:29)
	at io.mockk.impl.recording.CallRoundBuilder$addSignedCall$signedCall$1.invoke(CallRoundBuilder.kt:29)
	at io.mockk.impl.recording.CommonCallRecorder.safeExec(CommonCallRecorder.kt:72)
	at io.mockk.impl.log.SafeToString.exec(SafeToString.kt:8)
	at io.mockk.impl.recording.CallRoundBuilder.addSignedCall(CallRoundBuilder.kt:29)
	at io.mockk.impl.recording.states.RecordingState.call(RecordingState.kt:82)
	at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)
	at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:269)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:24)
	at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:21)
	at kotlin.ULong.unbox-impl(ULong.kt)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at kotlin.reflect.jvm.internal.calls.InternalUnderlyingValOfInlineClass.callMethod(InternalUnderlyingValOfInlineClass.kt:23)
	at kotlin.reflect.jvm.internal.calls.InternalUnderlyingValOfInlineClass$Unbound.call(InternalUnderlyingValOfInlineClass.kt:31)
	at kotlin.reflect.jvm.internal.calls.ValueClassAwareCaller.call(ValueClassAwareCaller.kt:199)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
	at kotlin.reflect.jvm.internal.KProperty1Impl.get(KProperty1Impl.kt:35)
	at io.mockk.core.ValueClassSupport.getBoxedValue(ValueClassSupport.kt:23)
	at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:22)
	at kotlin.ULong.unbox-impl(ULong.kt)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at kotlin.reflect.jvm.internal.calls.InternalUnderlyingValOfInlineClass.callMethod(InternalUnderlyingValOfInlineClass.kt:23)
	at kotlin.reflect.jvm.internal.calls.InternalUnderlyingValOfInlineClass$Unbound.call(InternalUnderlyingValOfInlineClass.kt:31)
	at kotlin.reflect.jvm.internal.calls.ValueClassAwareCaller.call(ValueClassAwareCaller.kt:199)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
	at kotlin.reflect.jvm.internal.KProperty1Impl.get(KProperty1Impl.kt:35)
	at io.mockk.core.ValueClassSupport.getBoxedValue(ValueClassSupport.kt:23)
	at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:22)
	at kotlin.ULong.unbox-impl(ULong.kt)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at kotlin.reflect.jvm.internal.calls.InternalUnderlyingValOfInlineClass.callMethod(InternalUnderlyingValOfInlineClass.kt:23)
	at kotlin.reflect.jvm.internal.calls.InternalUnderlyingValOfInlineClass$Unbound.call(InternalUnderlyingValOfInlineClass.kt:31)
	at kotlin.reflect.jvm.internal.calls.ValueClassAwareCaller.call(ValueClassAwareCaller.kt:199)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
	at kotlin.reflect.jvm.internal.KProperty1Impl.get(KProperty1Impl.kt:35)
	at io.mockk.core.ValueClassSupport.getBoxedValue(ValueClassSupport.kt:23)
	at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:22)
	at kotlin.ULong.unbox-impl(ULong.kt)
	[...]
```

**Comment by VasilisDrettas-tomtom** [comment]
Most likely the issue here is the same as https://github.com/mockk/mockk/issues/813
`UInt` is a value class, and it your case it was nullable.

**Comment by grmedias** [comment]
I issue still exist in 1.13.3

To workaround:
I used data class wrapper which take part of handling nullability issue.

Before
method returned ULong?

After
data class ULongWrapper?
data class ULongWrapper(
    val value: ULong,
)
and mockk is ok with it.
