### ISSUE TITLE
Value Class not works on verify() and ArgumentMatchers.eq()

### ISSUE THREAD

**Issue by kylooh** [mockk/mockk#1050]
#### Context
* MockK version: 1.13.2
* OS: MacOS Ventura 13.2 (M1)
* Kotlin version: 1.7.20
* JDK version: 11.0.17
* JUnit version: 5.8.2
* Type of test: Unit test

#### Stack trace
```
java.lang.AssertionError: Verification failed: call 1 of 1: Invoker(#1).invokeValueClass-Ud9lKk0(eq(Boxed(name=Test Object)))). Only one matching call to Invoker(#1)/invokeValueClass-Ud9lKk0(String) happened, but arguments are not matching:
[0]: argument: Test Object, matcher: eq(Boxed(name=Test Object)), result: -

Stack trace:
                                                          io.mockk.impl.InternalPlatform.captureStackTrace           (InternalPlatform.kt:125)                          
                                                            io.mockk.impl.stub.MockKStub.handleInvocation            (MockKStub.kt:255)                                 
                          io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation                  (JvmMockFactoryHelper.kt:24)                       
                                                   io.mockk.proxy.jvm.advice.Interceptor.call                        (Interceptor.kt:21)                                
                                           com.betalpha.saas.cache.adapter.input.Invoker.invokeValueClass-Ud9lKk0    (GuavaCacheFactoryTest.kt:83)                      
                                           com.betalpha.saas.cache.adapter.input.Testing.test                        (GuavaCacheFactoryTest.kt:93)                      
                                           jdk.internal.reflect.NativeMethodAccessorImpl.invoke0                     (NativeMethodAccessorImpl.java:-2)N                
                                           jdk.internal.reflect.NativeMethodAccessorImpl.invoke                      (NativeMethodAccessorImpl.java:62)                 
                                       jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke                      (DelegatingMethodAccessorImpl.java:43)             
                                                                java.lang.reflect.Method.invoke                      (Method.java:566)                                  
                                         org.junit.platform.commons.util.ReflectionUtils.invokeMethod                (ReflectionUtils.java:725)                         
                                     org.junit.jupiter.engine.execution.MethodInvocation.proceed                     (MethodInvocation.java:60)                         
      org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed                     (InvocationInterceptorChain.java:131)              
                                     org.junit.jupiter.engine.extension.TimeoutExtension.intercept                   (TimeoutExtension.java:149)                        
                                     org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod     (TimeoutExtension.java:140)                        
                                     org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod         (TimeoutExtension.java:84)                         
          org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0       (ExecutableInvoker.java:115)                       
                                    org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0             (ExecutableInvoker.java:105)                       
     org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed                     (InvocationInterceptorChain.java:106)              
                           org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed                     (InvocationInterceptorChain.java:64)               
                           org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke              (InvocationInterceptorChain.java:45)               
                           org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke                      (InvocationInterceptorChain.java:37)               
                                    org.junit.jupiter.engine.execution.ExecutableInvoker.invoke                      (ExecutableInvoker.java:104)                       
                                    org.junit.jupiter.engine.execution.ExecutableInvoker.invoke                      (ExecutableInvoker.java:98)                        
                            org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7   (TestMethodTestDescriptor.java:214)                
                       org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute                     (ThrowableCollector.java:73)                       
                            org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod            (TestMethodTestDescriptor.java:210)                
                            org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute                     (TestMethodTestDescriptor.java:135)                
                            org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute                     (TestMethodTestDescriptor.java:66)                 
                             org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6 (NodeTestTask.java:151)                            
                       org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute                     (ThrowableCollector.java:73)                       
                             org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8 (NodeTestTask.java:141)                            
                                     org.junit.platform.engine.support.hierarchical.Node.around                      (Node.java:137)                                    
                             org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9 (NodeTestTask.java:139)                            
                       org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute                     (ThrowableCollector.java:73)                       
                             org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively          (NodeTestTask.java:138)                            
                             org.junit.platform.engine.support.hierarchical.NodeTestTask.execute                     (NodeTestTask.java:95)                             
                                                                     java.util.ArrayList.forEach                     (ArrayList.java:1541)                              
org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll                   (SameThreadHierarchicalTestExecutorService.java:41)
                             org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6 (NodeTestTask.java:155)                            
                       org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute                     (ThrowableCollector.java:73)                       
                             org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8 (NodeTestTask.java:141)                            
                                     org.junit.platform.engine.support.hierarchical.Node.around                      (Node.java:137)                                    
                             org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9 (NodeTestTask.java:139)                            
                       org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute                     (ThrowableCollector.java:73)                       
                             org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively          (NodeTestTask.java:138)                            
                             org.junit.platform.engine.support.hierarchical.NodeTestTask.execute                     (NodeTestTask.java:95)                             
                                                                     java.util.ArrayList.forEach                     (ArrayList.java:1541)                              
org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll                   (SameThreadHierarchicalTestExecutorService.java:41)
                             org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6 (NodeTestTask.java:155)                            
                       org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute                     (ThrowableCollector.java:73)                       
                             org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8 (NodeTestTask.java:141)                            
                                     org.junit.platform.engine.support.hierarchical.Node.around                      (Node.java:137)                                    
                             org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9 (NodeTestTask.java:139)                            
                       org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute                     (ThrowableCollector.java:73)                       
                             org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively          (NodeTestTask.java:138)                            
                             org.junit.platform.engine.support.hierarchical.NodeTestTask.execute                     (NodeTestTask.java:95)                             
org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit                      (SameThreadHierarchicalTestExecutorService.java:35)
                 org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute                     (HierarchicalTestExecutor.java:57)                 
                   org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute                     (HierarchicalTestEngine.java:54)                   
                            org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute                     (EngineExecutionOrchestrator.java:107)             
                            org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute                     (EngineExecutionOrchestrator.java:88)              
                            org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0            (EngineExecutionOrchestrator.java:54)              
                            org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams      (EngineExecutionOrchestrator.java:67)              
                            org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute                     (EngineExecutionOrchestrator.java:52)              
                                        org.junit.platform.launcher.core.DefaultLauncher.execute                     (DefaultLauncher.java:114)                         
                                        org.junit.platform.launcher.core.DefaultLauncher.execute                     (DefaultLauncher.java:86)                          
              org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute                     (DefaultLauncherSession.java:86)                   
                              org.junit.platform.launcher.core.SessionPerRequestLauncher.execute                     (SessionPerRequestLauncher.java:53)                
                                                com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs         (JUnit5IdeaTestRunner.java:57)                     
                                         com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute                     (IdeaTestRunner.java:38)                           
                                           com.intellij.rt.execution.junit.TestsRepeater.repeat                      (TestsRepeater.java:11)                            
                                           com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs         (IdeaTestRunner.java:35)                           
                                                      com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart      (JUnitStarter.java:235)                            
                                                      com.intellij.rt.junit.JUnitStarter.main                        (JUnitStarter.java:54)                             

	at io.mockk.impl.recording.states.VerifyingState.failIfNotPassed(VerifyingState.kt:63)
	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:42)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:64)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalVerify(API.kt:119)
	at io.mockk.MockKKt.verify(MockK.kt:149)
	at io.mockk.MockKKt.verify$default(MockK.kt:140)
	at com.betalpha.saas.cache.adapter.input.Testing.test(GuavaCacheFactoryTest.kt:94)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

#### Minimal reproducible code
```kotlin
import io.mockk.spyk
import io.mockk.verify
import org.junit.jupiter.api.Test

@JvmInline
value class Boxed(val name: String)

class Invoker {

    fun invokeValueClass(boxed: Boxed): String = boxed.name
}

class Testing {

    @Test
    fun test() {
        val boxed = Boxed(name = "Test Object")
        val invoker = spyk<Invoker> { Invoker() }

        invoker.invokeValueClass(boxed)
        verify { invoker.invokeValueClass(eq(boxed)) }
    }
}
```

> Is this a bug? Or just not support such behavior. After check decompile code, seems `CallRecorder.matcher` accepts a `KClass<Boxed>`,  so is that a Kotlin bug?

Thx for reading

**Comment by JirkaKrivanek** [comment]
Happens to me too... But it is RANDOM... I have a lot of test cases and totally randomly, some of them are failing with exactly this problem... Until fixed, we have to stop using MOCKK, as the tests using is are unstable...
