### ISSUE TITLE
Fatal exception in coroutines machinery

### ISSUE THREAD

**Issue by hu553in** [mockk/mockk#1078]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

Code just works.

### Current Behavior

`Fatal exception in coroutines machinery`.

Please see my provided example (and steps to reproduce).

Then please see the issue I have created in Kotlin coroutines repo - https://github.com/Kotlin/kotlinx.coroutines/issues/3705 - as well as the answer to it.

#### Steps to Reproduce

1. Run `main` in my provided example (it is very simple)

#### Context

* MockK version: 1.13.5
* OS: Linux Mint 21.1
* Kotlin version: 1.8.20
* JDK version: 11
* JUnit version: -
* Type of test: -

#### Failure Logs

```
Exception in thread "main" kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[StandardTestDispatcher[scheduler=kotlinx.coroutines.test.TestCoroutineScheduler@73a00e09], Continuation at com.example.demo.DemoApplicationKt$main$1$2.invokeSuspend(DemoApplication.kt:28)@31ddd4a4]){Cancelled}@65004ff6. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
```

#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
Exception in thread "main" kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[StandardTestDispatcher[scheduler=kotlinx.coroutines.test.TestCoroutineScheduler@73a00e09], Continuation at com.example.demo.DemoApplicationKt$main$1$2.invokeSuspend(DemoApplication.kt:28)@31ddd4a4]){Cancelled}@65004ff6. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:144)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
	at kotlinx.coroutines.test.TestDispatcher.processEvent$kotlinx_coroutines_test(TestDispatcher.kt:28)
	at kotlinx.coroutines.test.TestCoroutineScheduler.tryRunNextTaskUnless$kotlinx_coroutines_test(TestCoroutineScheduler.kt:100)
	at kotlinx.coroutines.test.TestCoroutineScheduler.advanceUntilIdleOr$kotlinx_coroutines_test(TestCoroutineScheduler.kt:120)
	at kotlinx.coroutines.test.TestCoroutineScheduler.advanceUntilIdle(TestCoroutineScheduler.kt:113)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTestCoroutine(TestBuilders.kt:237)
	at kotlinx.coroutines.test.TestBuildersKt.runTestCoroutine(Unknown Source)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTestCoroutine$1.invokeSuspend(TestBuilders.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at kotlinx.coroutines.test.TestBuildersJvmKt.createTestResult(TestBuildersJvm.kt:12)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest(TestBuilders.kt:166)
	at kotlinx.coroutines.test.TestBuildersKt.runTest(Unknown Source)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest(TestBuilders.kt:154)
	at kotlinx.coroutines.test.TestBuildersKt.runTest(Unknown Source)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest$default(TestBuilders.kt:147)
	at kotlinx.coroutines.test.TestBuildersKt.runTest$default(Unknown Source)
	at com.example.demo.DemoApplicationKt.main(DemoApplication.kt:25)
	at com.example.demo.DemoApplicationKt.main(DemoApplication.kt)
Caused by: java.lang.ClassCastException: class kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to class kotlinx.coroutines.internal.DispatchedContinuation (kotlin.coroutines.jvm.internal.CompletedContinuation and kotlinx.coroutines.internal.DispatchedContinuation are in unnamed module of loader 'app')
	at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:166)
	at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:118)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:39)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	... 24 more
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

#### Minimal reproducible code (the gist of this issue)

https://github.com/hu553in/fatal-exception-in-coroutines-machinery-example

**Comment by Raibaz** [comment]
This really looks like an issue with kotlin coroutines, not with mockk.

**Comment by hu553in** [comment]
> This really looks like an issue with kotlin coroutines, not with mockk.

@Raibaz they said completely the opposite thing in answer to my issue :)
