### ISSUE TITLE
OpenJDK - Failed to transform classes

### ISSUE THREAD

**Issue by AndreasVolkmann** [mockk/mockk#108]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior
I expected the mock to be successful just like on the Oracle JRE.

### Current Behavior

With OpenJDK it throws an exception when mocking classes.

### Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Use OpenJDK (I use the latest build from https://adoptopenjdk.net/nightly.html?variant=openjdk8-openj9)
2. 
Just create a simple class with a method.
Attempt to mock it and you will see an exception.

3. you get it...

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.8.5
* OS: Windows 10
* Kotlin version: 1.2.50
* JDK version: OpenJ9 jdk8u172-b11
* Type of test: unit test

#### Failure Logs

Please include any relevant log snippets or files here.

#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
2018-07-06 13:14:07,423 [main] WARN  io.mockk.proxy.jvm.transformation.InlineInstrumentation - Failed to transform classes [class com.apurebase.mailing.schedule.MaintenanceJobTest$execute selections should not execute null or blank selections$Example, class java.lang.Object]
java.lang.instrument.UnmodifiableClassException: null
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method) ~[?:1.8.0_172-adoptopenjdk]
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:156) ~[?:1.8.0_172-adoptopenjdk]
	at io.mockk.proxy.jvm.transformation.InlineInstrumentation.execute(InlineInstrumentation.kt:26) ~[mockk-agent-jvm-1.8.5.jar:?]
	at io.mockk.proxy.jvm.ProxyMaker.inline(ProxyMaker.kt:88) ~[mockk-agent-jvm-1.8.5.jar:?]
	at io.mockk.proxy.jvm.ProxyMaker.proxy(ProxyMaker.kt:30) ~[mockk-agent-jvm-1.8.5.jar:?]
	at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:34) ~[mockk-1.8.5.jar:?]
	at io.mockk.impl.instantiation.AbstractMockFactory.newProxy$default(AbstractMockFactory.kt:27) ~[mockk-1.8.5.jar:?]
	at io.mockk.impl.instantiation.AbstractMockFactory.mockk(AbstractMockFactory.kt:44) ~[mockk-1.8.5.jar:?]
	at com.apurebase.mailing.schedule.MaintenanceJobTest.execute selections should not execute null or blank selections(MaintenanceJobTest.kt:113) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172-adoptopenjdk]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_172-adoptopenjdk]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172-adoptopenjdk]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172-adoptopenjdk]
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:515) ~[junit-platform-commons-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115) ~[junit-jupiter-engine-5.3.0-M1.jar:5.3.0-M1]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:170) ~[junit-jupiter-engine-5.3.0-M1.jar:5.3.0-M1]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor$$Lambda$233.28E8B700.execute(Unknown Source) ~[?:?]
	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40) ~[junit-jupiter-engine-5.3.0-M1.jar:5.3.0-M1]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:166) ~[junit-jupiter-engine-5.3.0-M1.jar:5.3.0-M1]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:113) ~[junit-jupiter-engine-5.3.0-M1.jar:5.3.0-M1]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:58) ~[junit-jupiter-engine-5.3.0-M1.jar:5.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:134) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$169.27339290.execute(Unknown Source) ~[?:?]
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:128) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:109) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService$$Lambda$172.27339FC8.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_172-adoptopenjdk]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:138) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$169.27339290.execute(Unknown Source) ~[?:?]
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:128) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:109) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService$$Lambda$172.27339FC8.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_172-adoptopenjdk]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:138) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$169.27339290.execute(Unknown Source) ~[?:?]
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:128) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:109) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:49) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:47) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:184) ~[junit-platform-launcher-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:152) ~[junit-platform-launcher-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.launcher.core.DefaultLauncher$$Lambda$139.272F7E48.accept(Unknown Source) ~[?:?]
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:166) [junit-platform-launcher-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:145) [junit-platform-launcher-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:92) [junit-platform-launcher-1.3.0-M1.jar:1.3.0-M1]
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:74) [junit5-rt.jar:?]
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70) [junit-rt.jar:?]
2018-07-06 13:14:07,519 [main] WARN  io.mockk.proxy.jvm.transformation.InlineInstrumentation - Failed to revert class transformation [class com.apurebase.mailing.schedule.MaintenanceJobTest$execute selections should not execute null or blank selections$Example, class java.lang.Object]
java.lang.instrument.UnmodifiableClassException: null
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:156) ~[?:1.8.0_172-adoptopenjdk]
	at io.mockk.proxy.jvm.transformation.InlineInstrumentation.doCancel(InlineInstrumentation.kt:47) ~[mockk-agent-jvm-1.8.5.jar:?]
	at io.mockk.proxy.jvm.transformation.InlineInstrumentation.access$doCancel(InlineInstrumentation.kt:9) ~[mockk-agent-jvm-1.8.5.jar:?]
	at io.mockk.proxy.jvm.transformation.InlineInstrumentation$execute$cancellation$1.invoke(InlineInstrumentation.kt:20) ~[mockk-agent-jvm-1.8.5.jar:?]
	at io.mockk.proxy.jvm.transformation.InlineInstrumentation$execute$cancellation$1.invoke(InlineInstrumentation.kt:9) ~[mockk-agent-jvm-1.8.5.jar:?]
	at io.mockk.proxy.jvm.transformation.InlineInstrumentation.execute(InlineInstrumentation.kt:30) ~[mockk-agent-jvm-1.8.5.jar:?]
	at io.mockk.proxy.jvm.ProxyMaker.inline(ProxyMaker.kt:88) ~[mockk-agent-jvm-1.8.5.jar:?]
	at io.mockk.proxy.jvm.ProxyMaker.proxy(ProxyMaker.kt:30) ~[mockk-agent-jvm-1.8.5.jar:?]
	at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:34) ~[mockk-1.8.5.jar:?]
	at io.mockk.impl.instantiation.AbstractMockFactory.newProxy$default(AbstractMockFactory.kt:27) ~[mockk-1.8.5.jar:?]
	at io.mockk.impl.instantiation.AbstractMockFactory.mockk(AbstractMockFactory.kt:44) ~[mockk-1.8.5.jar:?]
	at com.apurebase.mailing.schedule.MaintenanceJobTest.execute selections should not execute null or blank selections(MaintenanceJobTest.kt:113) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172-adoptopenjdk]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_172-adoptopenjdk]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172-adoptopenjdk]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172-adoptopenjdk]
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:515) ~[junit-platform-commons-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115) ~[junit-jupiter-engine-5.3.0-M1.jar:5.3.0-M1]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:170) ~[junit-jupiter-engine-5.3.0-M1.jar:5.3.0-M1]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor$$Lambda$233.28E8B700.execute(Unknown Source) ~[?:?]
	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40) ~[junit-jupiter-engine-5.3.0-M1.jar:5.3.0-M1]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:166) ~[junit-jupiter-engine-5.3.0-M1.jar:5.3.0-M1]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:113) ~[junit-jupiter-engine-5.3.0-M1.jar:5.3.0-M1]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:58) ~[junit-jupiter-engine-5.3.0-M1.jar:5.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:134) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$169.27339290.execute(Unknown Source) ~[?:?]
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:128) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:109) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService$$Lambda$172.27339FC8.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_172-adoptopenjdk]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:138) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$169.27339290.execute(Unknown Source) ~[?:?]
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:128) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:109) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService$$Lambda$172.27339FC8.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_172-adoptopenjdk]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:138) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$169.27339290.execute(Unknown Source) ~[?:?]
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:128) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:109) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:49) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:47) ~[junit-platform-engine-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:184) ~[junit-platform-launcher-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:152) ~[junit-platform-launcher-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.launcher.core.DefaultLauncher$$Lambda$139.272F7E48.accept(Unknown Source) ~[?:?]
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:166) [junit-platform-launcher-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:145) [junit-platform-launcher-1.3.0-M1.jar:1.3.0-M1]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:92) [junit-platform-launcher-1.3.0-M1.jar:1.3.0-M1]
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:74) [junit5-rt.jar:?]
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70) [junit-rt.jar:?]

io.mockk.MockKException: Missing calls inside every { ... } block.

	at io.mockk.impl.recording.states.StubbingState.checkMissingCalls(StubbingState.kt:14)
	at io.mockk.impl.recording.states.StubbingState.recordingDone(StubbingState.kt:8)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:42)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:48)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:25)
	at io.mockk.MockKDsl.internalEvery(API.kt:93)
	at io.mockk.MockKKt.every(MockK.kt:79)
	at com.apurebase.mailing.schedule.MaintenanceJobTest.execute selections should not execute null or blank selections(MaintenanceJobTest.kt:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:515)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:170)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor$$Lambda$233.28E8B700.execute(Unknown Source)
	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:166)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:113)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:58)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:134)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$169.27339290.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:128)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:109)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService$$Lambda$172.27339FC8.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$169.27339290.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:128)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:109)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService$$Lambda$172.27339FC8.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$169.27339290.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:128)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:109)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:49)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:47)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:184)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:152)
	at org.junit.platform.launcher.core.DefaultLauncher$$Lambda$139.272F7E48.accept(Unknown Source)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:166)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:145)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:92)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    testImplementation "io.mockk:mockk:1.8.5"
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
package io.mockk.gh

import io.mockk.every
import io.mockk.mockk
import io.mockk.verify
import org.junit.jupiter.api.Test

class Test {

    @Test fun mocking() {
        class Example {
            fun execute() {}
        }

        val example = mockk<Example>()
        every { example.execute() } returns Unit
        example.execute()
        verify { example.execute() }
    }

}
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by oleksiyp** [comment]
Seems in OpenJ on contrary to Sun JDK there is no possibility to instrument "java.lang.Object". I added a check and skipped all non-instrumentable classes(with warning), so now it is working.
