### ISSUE TITLE
Improve `shouldThrow` behaviour to print 

### ISSUE THREAD

**Issue by igorwojda** [mockk/mockk#1088]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

If the `MockKException` exception is thrown in the `shouldThrow` then display the actual cause of the issue, so the developer can easily fix the root problem.

### Current Behavior

```kotlin
@Test
    fun `test`() {
        // given
       // setup mocks

        // when
        val func = { sut.doSth() }

        // then
        func shouldThrow KoInternalException::class
    }
```

The current error points to an incorrect exception being thrown - `MockKException`. Technically this is fine as mock setup is incorrect, but this exception does not provide enough information.

```
Expected class com.lemonappdev.konsist.core.exception.KoInternalException to be thrown expected:<class [com.lemonappdev.konsist.core.exception.KoInternal]Exception> but was:<class [io.mockk.MockK]Exception>
Expected :class com.lemonappdev.konsist.core.exception.KoInternalException
Actual   :class io.mockk.MockKException
<Click to see difference>
```

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.13.5
* OS: MacOs Ventura 13.0
* Kotlin version: 1.8.21
* JDK version: 19
* JUnit version: 5.9.3
* Type of test: unit test

#### Failure Logs

Please include any relevant log snippets or files here.

#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
io.mockk.MockKException: Class cast exception. Probably type information was erased.
In this case use `hint` before call to specify exact return type of a method. 

	at io.mockk.impl.InternalPlatform.prettifyRecordingException(InternalPlatform.kt:83)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:50)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:25)
	at eu.example.schedule.kafka.KafkaAdminImplTest.mockkVoidReturnFails(KafkaAdminImplTest.kt:301)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassCastException: kotlin.Unit cannot be cast to java.lang.Void
	at eu.example.schedule.kafka.KafkaAdminImplTest$mockkVoidReturnFails$1.invoke(KafkaAdminImplTest.kt:87)
	at eu.example.schedule.kafka.KafkaAdminImplTest$mockkVoidReturnFails$1.invoke(KafkaAdminImplTest.kt:24)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:22)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:31)
	... 25 more
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

**Comment by paul-dingemans** [comment]
Your problem is hard to reproduce as there is no clear reproduction path. Ideally, this reproduction path does not use any other dependencies like konsist to ensure that the problem is really caused by mockk.

I think that the line below in the stack trace contains the key to finding your problem:
```
Caused by: java.lang.ClassCastException: kotlin.Unit cannot be cast to java.lang.Void
```

Suppose, I have a test like below:
```
class MyTest {
    class Cls {
        fun op(a: Int) =
            require(a != 100) { "This value is not allowed" }
    }

    @Test
    fun MyTest() {
        val obj1 = Cls()
        assertThrows<IllegalArgumentException> { obj1.op(100) }

        val obj2 = mockk<Cls>()
        assertThrows<IllegalArgumentException> { obj2.op(100) }
    }
}
```
The call `ob1.op(100)` shows that an exception is thrown when calling on a concrete instance.

When calling that on a mock, the stack trace becomes:
```
org.opentest4j.AssertionFailedError: Unexpected exception type thrown ==> expected: <java.lang.IllegalArgumentException> but was: <io.mockk.MockKException>
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:65)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:37)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3082)
...
Caused by: io.mockk.MockKException: no answer found for Cls(#1).op(100) among the configured answers: ()
```
In example above, the stacktrace clearly indicated that no behavior was defined on the mock.


Your example is more complicated. If I would need to guess there is somewhere a Java interoperability problem where a Kotlin `Unit` type is casted to a Java `Void` type. This could be anywhere in `kafka` or any other dependencies in your project. A simple reproducable is required to help you further in this.
