### ISSUE TITLE
Mocking jOOQ 3.15+ fails with "attempted to add a method"

### ISSUE THREAD

**Issue by marcelstoer** [mockk/mockk#1118]
This issue is the continuation of the analysis started and documented at https://stackoverflow.com/q/76665966/131929. Also, this is very closely related to #255 and #477 which both became stale.

I tried to debug further but the exception stems from native JVM code. Hence, I suspect it requires someone intimately familiar with this project to look into it. Allow me to tag the top contributors @oleksiyp, @aSemy and @Raibaz.

### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

Mocking the jOOQ 3.15+ `TableImpl` class should work.

### Current Behavior

It fails with

> java.lang.UnsupportedOperationException: class redefinition failed: attempted to add a method

### Failure Information (for bugs)

Mocking the same class with jOOQ 3.14 works fine. The 3.15+ versions are different in that they also implement interfaces which seems to trip up MockK. With the earlier jOOQ versions MockK prints this trace log

> Taking instance of class org.jooq.impl.TableImpl itself because it is not abstract and no additional interfaces specified.

It fails both on Java 11 and Java 17.

#### Steps to Reproduce

Check out the reproducer at https://github.com/marcelstoer/jooq-mockk-test and run `mvn test`.

**Comment by aSemy** [comment]
I've had a quick look, and though I don't think I can help (I don't have much time, and I haven't worked on any projects that use MockK in a long time), I will summarise in case it is useful:

* v3.14: TableImpl does not implement any interfaces https://github.com/jOOQ/jOOQ/blob/version-3.14.16/jOOQ/src/main/java/org/jooq/impl/TableImpl.java#L82
* v3.15: TableImpl starts implementing some interfaces https://github.com/jOOQ/jOOQ/blob/version-3.15.0/jOOQ/src/main/java/org/jooq/impl/TableImpl.java#L91

The MockK log message,

```
[io.mockk.proxy.common.ProxyMaker] (main) Taking instance of class org.jooq.impl.TableImpl itself because it is not abstract and no additional interfaces specified.
```

originates from `ProxyMaker.kt`:

https://github.com/mockk/mockk/blob/ca59598de4ff5aa1824f7f2d4521ab43941c54af/modules/mockk-agent-api/src/jvmMain/kotlin/io/mockk/proxy/common/ProxyMaker.kt#L129-L146

MockK uses ByteBuddy for instantiating new subclasses, and that's where the `attempted to add a method` error comes from.

This SO post seems to indicate that MockK is using Byte Buddy incorrectly https://stackoverflow.com/questions/40774684/, but it could be something else.


I suspect that this is the MockK function that needs further inspection: https://github.com/mockk/mockk/blob/ca59598de4ff5aa1824f7f2d4521ab43941c54af/modules/mockk-agent/src/jvmMain/kotlin/io/mockk/proxy/jvm/transformation/JvmSubclassInstrumentation.kt#L58-L99

I would encourage you, or anyone else facing this issue, to try poking around in the MockK code. Make a PR that adds your test from https://github.com/marcelstoer/jooq-mockk-test into 
the [test-modules/client-tests](https://github.com/mockk/mockk/tree/master/test-modules/client-tests) subproject, and then try experimenting.  Personally I found MockK quite daunting until I started making some PRs, and then I realised it's not _that_ complicated, and @Raibaz is a really nice maintainer!

**Comment by marcelstoer** [comment]
Thank you @aSemy for the extra documentation. I had gone through all that code before filing this issue (that's how I found #1117 😄 ) but I missed to add pointers to it my description, sorry.

Interesting SO reference. Confirming that an established library like MockK is using its core foundation incorrectly would be quite a thing I guess.

**Comment by marcelstoer** [comment]
I just found another such case in a different library.

@lukehutch's [classgraph](https://github.com/classgraph/classgraph) library cannot be updated beyond 4.8.64 (from early 2020). Starting from 4.8.65 I am getting the dreaded "class redefinition failed: attempted to add a method" error. Since the exception is triggered in native code, I can't pinpoint which exact classe causes it. However, I think I can limit the set of potential culprits to four classes - all in the same inheritance hierarchy. See below

<img width="1269" alt="Screenshot 2024-05-29 at 13 16 10" src="https://github.com/mockk/mockk/assets/624195/c5bef1c5-37d2-4107-9ebf-9a5267dbaf85">

Yet, when I compare the [changes that went into that release](https://github.com/classgraph/classgraph/compare/classgraph-4.8.64...classgraph-4.8.65), I see nothing that would affect the class signatures in any way.

--> I'm as clueless as before

**Comment by marcelstoer** [comment]
Btw, the unit test in #1319 demonstrates that the stacktrace is as follows.

```
java.lang.UnsupportedOperationException: class redefinition failed: attempted to add a method
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:169)
	at io.mockk.proxy.jvm.transformation.JvmInlineInstrumentation.retransform(JvmInlineInstrumentation.kt:28)
	at io.mockk.proxy.common.transformation.RetransformInlineInstrumentation$execute$1.invoke(RetransformInlineInstrumentation.kt:19)
	at io.mockk.proxy.common.transformation.RetransformInlineInstrumentation$execute$1.invoke(RetransformInlineInstrumentation.kt:16)
	at io.mockk.proxy.common.transformation.ClassTransformationSpecMap.applyTransformation(ClassTransformationSpecMap.kt:41)
	at io.mockk.proxy.common.transformation.RetransformInlineInstrumentation.execute(RetransformInlineInstrumentation.kt:16)
	at io.mockk.proxy.jvm.ProxyMaker.inline(ProxyMaker.kt:90)
	at io.mockk.proxy.jvm.ProxyMaker.proxy(ProxyMaker.kt:34)
	at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:34)
	at io.mockk.impl.instantiation.AbstractMockFactory.newProxy$default(AbstractMockFactory.kt:24)
	at io.mockk.impl.instantiation.AbstractMockFactory.mockk(AbstractMockFactory.kt:59)
	at io.mockk.impl.jooq.JooqTest.should mock jOOQ TableImpl class(JooqTest.kt:26)
```

(@aSemy `ProxyMaker#doInterceptedSubclassing()` is not involved here)

**Comment by marcelstoer** [comment]
Ok, a smoking gun at last - maybe. @Raibaz I'd need some guidance on this.

I noticed that, contrary to its name, `ProxyMaker.Companion#getAllSuperclasses(Class)` returns all the parameter's super classes (and interfaces) _plus itself_. That didn't feel right. It would also explain why in some situations a class may be manipulated twice, once as a dedicated class and once as part of the `superclasses` collection.

So, I changed the implementation such that it only returns super classes (and interfaces) like so:
<img width="936" alt="Screenshot 2024-11-06 at 11 38 14" src="https://github.com/user-attachments/assets/391cfe4b-0715-40bd-8df8-cb8c20559165">
(I guess you could say it's now post-order traversal rather than pre-order traversal.)

This fixes it for my use case but other tests started failing.

**Comment by Raibaz** [comment]
Ah, this is interesting indeed!

What are the tests that started failing? The way it looks, the correct behavior is that `getAllSuperclasses(Class)` should not return the class itself, so it may be the case that we need to update the other test cases.

**Comment by marcelstoer** [comment]
`io.mockk.test.BasicClientTest#aVeryBasicClientTest` for example fails with 

```
Failed matching mocking signature for

left matchers: [any()]
io.mockk.MockKException: Failed matching mocking signature for

left matchers: [any()]
	at io.mockk.impl.recording.SignatureMatcherDetector.detect(SignatureMatcherDetector.kt:97)
	at io.mockk.impl.recording.states.RecordingState.signMatchers(RecordingState.kt:39)
	at io.mockk.impl.recording.states.RecordingState.round(RecordingState.kt:31)
	at io.mockk.impl.recording.CommonCallRecorder.round(CommonCallRecorder.kt:50)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:62)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalEvery(API.kt:94)
	at io.mockk.MockKKt.every(MockK.kt:143)
	at io.mockk.test.BasicClientTest.aVeryBasicClientTest(BasicClientTest.kt:22)
```

As this is something rather serious, I suspect that other code relies on `getAllSuperclasses()` returning not just the super classes as its name suggests.

I'll commit my fix to PR  #1319 anyway and would appreciate if you could also take a look, thanks.

**Comment by marcelstoer** [comment]
@Raibaz I rebased my test branch onto master and spent a few more hours on this today. However, with my limited understanding of how mockk works this just leads nowhere, sorry.

After all, I think `getAllSuperclasses(Class)` is required to behave the way it currently behaves. It likely just has a subpar name. I traced the origins of that code all the way back to November 2017 when @oleksiyp first added it with 1c322c74868e8330c8b1453b24ad5b1d4f41de94 (`io.mockk.proxy.MockKProxyMaker#getAllSuperclasses(Class)`). Hence, it always returned the superclasses _and_ the class itself. It should be called something like `getAllSuperclassesAndItself`.

As for the actual issue, I'm more puzzled then ever before. `io.mockk.proxy.jvm.transformation.JvmInlineInstrumentation#retransform` considers all classes as `isModifiableClass`. Yet, when `retransformClasses` is actually called on them, it fails.

<img width="1071" alt="Screenshot 2025-01-15 at 14 05 26" src="https://github.com/user-attachments/assets/309d5bc3-7cdc-4650-af11-25b13dcdf208" />

@Raibaz If you have a minute, I would very much appreciate if you could debug my tiny test in #1319 and see if you spot anything obvious.

**Comment by Raibaz** [comment]
I'm a bit puzzled myself because that's the ByteBuddy part in MockK, that I'm not really familiar with.

May be worth getting in touch with the ByteBuddy team to see if they have any pointers.

**Comment by sgerke-1L** [comment]
We're running into this as well, is there any additional information?

**Comment by bdalenoord** [comment]
Hm, we're running into some issues with this as well, specifically when we're mocking jOOQ-codegen based records since jOOQ 3.20. 

After digging into their changes a bit only one change is visible in the list of classes within `JvmInlineInstrumentation`: a new interface (`FieldsTrait`) was added as an additional interface for the generated class being mocked/causing the failure. 

This interface differs from the others that were already on the class being mocked in that it has no `public` accessibility modifier, making it module-private. 

I have however not been able to reproduce anything similar when building up a minimal sample thusfar. I may dig into it a bit more tomorrow, as this prevents us from updating jOOQ atm, which would become an issue in the near future.

**Comment by marcelstoer** [comment]
@bdalenoord maybe it helps if you start with the test I added in #1319.

**Comment by bdalenoord** [comment]
@marcelstoer strange thing is that our project succeeds with jOOQ 3.19.20 😕 but maybe I can figure something out with your testcase indeed, thx for the pointer.

**Comment by bdalenoord** [comment]
@marcelstoer I've checked out your branch from #1319, and your test fails succesfully there. I've also added a test-case to simulate our situation:
```
    @Test
    fun `should mock jOOQ UpdatableRecordImpl class`() {
        val updateableRecord = mockk<UpdatableRecordImpl<*>>()
        val record = mockk<Record>()
        every { updateableRecord.key() } returns record
        assertEquals(record, updateableRecord.key())
    }
```
where instead of mocking a `TableImpl`, I've mocked a `UpdateableRecordImpl`. That test succeeds with jOOQ version 3.19.14. 

When I update jOOQ to 3.20.2 (the latest, the version that I was trying to update our project to), suddenly, both testcases fail.

As I concluded yesterday, the only difference for `UpdateableRecordImpl` is that a package-private `FieldsTrait`-interface has been added, so I'm gonna dig in that direction a bit further.

**Comment by marcelstoer** [comment]
First things first, do you get the same exception as in my documented case?

> java.lang.UnsupportedOperationException: class redefinition failed: attempted to add a method

If so, can you debug to reproduce the same behavior I documented at https://github.com/mockk/mockk/issues/1118#issuecomment-2592842592? All classes considered modifiable, yet the retransformation then still fails?

@Raibaz 
> May be worth getting in touch with the ByteBuddy team to see if they have any pointers.

Can we ask _you_ to do that (contact user 'raphw')? I am certain it promises better results if they are contacted by the maintainer of a reputable project than by some random dudes.

**Comment by bdalenoord** [comment]
@marcelstoer the exception and top of the stacktrace are exactly the same for both the Table-based as well as the Record-based mock once I switch to jOOQ 3.20.2, and I can confirm that all classes are considered modifiable before attempting retransformation:

![Image](https://github.com/user-attachments/assets/a09058e1-f499-44b5-a3ad-4cdca0dcd1c9)

**Comment by sgerke-1L** [comment]
Do we know which method it tries do add to which class and then fails?

**Comment by bdalenoord** [comment]
@sgerke-1L I don't, and as the error happens in native code I'm not sure how I could be able to figure that out, no way to inspect the runtime at that point.

**Comment by bdalenoord** [comment]
Digging around with Unified Logging I've got some insight into where the failure occurs:
```
[1,523s][debug][redefine,class,load] loading name=org.jooq.impl.UpdatableRecordImpl kind=101 (avail_mem=2819128K)
[1,590s][trace][redefine,class,iklass,purge] Class unloading: should_clean_previous_versions = false
[1,951s][trace][redefine,class,normalize   ] Method matched: new: org.jooq.impl.UpdatableRecordImpl.refresh([Lorg/jooq/Field;)V [0] == old: org.jooq.impl.UpdatableRecordImpl.refresh([Lorg/jooq/Field;)V [0]
[1,951s][trace][redefine,class,normalize   ] Method matched: new: org.jooq.impl.UpdatableRecordImpl.refresh(Ljava/util/Collection;)V [1] == old: org.jooq.impl.UpdatableRecordImpl.refresh(Ljava/util/Collection;)V [1]
[1,951s][trace][redefine,class,normalize   ] Method matched: new: org.jooq.impl.UpdatableRecordImpl.refresh()V [2] == old: org.jooq.impl.UpdatableRecordImpl.refresh()V [2]
[1,951s][trace][redefine,class,normalize   ] Method matched: new: org.jooq.impl.UpdatableRecordImpl.<init>(Lorg/jooq/Table;)V [3] == old: org.jooq.impl.UpdatableRecordImpl.<init>(Lorg/jooq/Table;)V [3]
[1,951s][trace][redefine,class,normalize   ] Method matched: new: org.jooq.impl.UpdatableRecordImpl.<clinit>()V [4] == old: org.jooq.impl.UpdatableRecordImpl.<clinit>()V [4]
[1,951s][info ][redefine,class,normalize   ] redefined class org.jooq.impl.UpdatableRecordImpl methods error: added method: org.jooq.impl.UpdatableRecordImpl.type(Lorg/jooq/Name;)Ljava/lang/Class; [5]
[1,957s][debug][redefine,class,load        ] loading name=org.jooq.impl.UpdatableRecordImpl kind=101 (avail_mem=2945516K)
[1,985s][trace][redefine,class,normalize   ] Method matched: new: org.jooq.impl.UpdatableRecordImpl.refresh([Lorg/jooq/Field;)V [0] == old: org.jooq.impl.UpdatableRecordImpl.refresh([Lorg/jooq/Field;)V [0]
[1,985s][trace][redefine,class,normalize   ] Method matched: new: org.jooq.impl.UpdatableRecordImpl.refresh(Ljava/util/Collection;)V [1] == old: org.jooq.impl.UpdatableRecordImpl.refresh(Ljava/util/Collection;)V [1]
[1,985s][trace][redefine,class,normalize   ] Method matched: new: org.jooq.impl.UpdatableRecordImpl.refresh()V [2] == old: org.jooq.impl.UpdatableRecordImpl.refresh()V [2]
[1,985s][trace][redefine,class,normalize   ] Method matched: new: org.jooq.impl.UpdatableRecordImpl.<init>(Lorg/jooq/Table;)V [3] == old: org.jooq.impl.UpdatableRecordImpl.<init>(Lorg/jooq/Table;)V [3]
[1,985s][trace][redefine,class,normalize   ] Method matched: new: org.jooq.impl.UpdatableRecordImpl.<clinit>()V [4] == old: org.jooq.impl.UpdatableRecordImpl.<clinit>()V [4]
[1,985s][info ][redefine,class,normalize   ] redefined class org.jooq.impl.UpdatableRecordImpl methods error: added method: org.jooq.impl.UpdatableRecordImpl.type(Lorg/jooq/Name;)Ljava/lang/Class; [5]
```

which originates in https://github.com/openjdk/jdk/blob/1a8c8e07fee33861d348f7b41fea0e3fd5bbc0af/src/hotspot/share/prims/jvmtiRedefineClasses.cpp#L1190

But I'm not sure why
```
static bool can_add_or_delete(Method* m) {
      // Compatibility mode
  return (AllowRedefinitionToAddDeleteMethods &&
          (m->is_private() && (m->is_static() || m->is_final())));
}
```
would return false here, I'm not sure.

**Comment by marcelstoer** [comment]
> Digging around with Unified Logging I've got some insight into where the failure occurs. I've added `-Xlog:redefine+class*=trace:stdout` as JVM-arg to obtain these.

This is fantastic, thanks! I learned something today.

> `[2,086s][info ][redefine,class,normalize   ] redefined class org.jooq.impl.TableImpl methods error: added method: org.jooq.impl.TableImpl.type(Lorg/jooq/Name;)Ljava/lang/Class; [22]`

Hhhmm...so it fails for the `type()` method in both cases. Haven't figured out yet what conclusion we can draw from that.

(pity they log an error on INFO)

**Comment by marcelstoer** [comment]
Given enough examples a pattern might emerge. So far with have the jOOQ `TableImpl` and `Record` plus what I found last May.

> [classgraph](https://github.com/classgraph/classgraph) library cannot be updated beyond 4.8.64 (from early 2020)

I should probably add this to my test and run it with your logging JVM-arg.

**Comment by sgerke-1L** [comment]
Great insights, thanks for finding the `type` method. Here is a simple reproducer: https://github.com/mockk/mockk/pull/1366/files

The problem seems to occur when a class is mocked that implements an interface with a default implementation.

**Comment by bdalenoord** [comment]
@sgerke-1L Indeed, with your minimal testcase the output is very similar:
```
[2,514s][trace][redefine,class,normalize          ] Method matched: new: io.mockk.core.ClassImplementingInterfaceWithDefaultMethod.<init>()V [0] == old: io.mockk.core.ClassImplementingInterfaceWithDefaultMethod.<init>()V [0]
[2,515s][info ][redefine,class,normalize          ] redefined class io.mockk.core.ClassImplementingInterfaceWithDefaultMethod methods error: added method: io.mockk.core.ClassImplementingInterfaceWithDefaultMethod.foo()I [1]
[2,522s][debug][redefine,class,load               ] loading name=io.mockk.core.ClassImplementingInterfaceWithDefaultMethod kind=101 (avail_mem=7082288K)
[2,524s][trace][redefine,class,normalize          ] Method matched: new: io.mockk.core.ClassImplementingInterfaceWithDefaultMethod.<init>()V [0] == old: io.mockk.core.ClassImplementingInterfaceWithDefaultMethod.<init>()V [0]
[2,524s][info ][redefine,class,normalize          ] redefined class io.mockk.core.ClassImplementingInterfaceWithDefaultMethod methods error: added method: io.mockk.core.ClassImplementingInterfaceWithDefaultMethod.foo()I [1]
> Task :test-modules:client-tests:jvmTest FAILED
```
and it points to the `foo`-method here, which is the method with a default implementation.

**Comment by sgerke-1L** [comment]
@bdalenoord I've updated https://github.com/mockk/mockk/pull/1366 to include a fix. I've also asked a question in byte-buddy https://github.com/raphw/byte-buddy/issues/1795 to further clarify if this is a bug in byte-buddy or not.

**Comment by sgerke-1L** [comment]
The upstream discussion resulted in the discovery of another potential fix, which is to use `decorate` instead of `redefine`. However, I'm not experienced enough with the mockk implementation to judge if that is a valid approach. I've updated my proposed fix anyway, maybe someone can sponsor a full test run so we'd learn if the test suite already discovers problems with it.

Let me know if there is anything else I can help with, otherwise I'd see the ball in the maintainer's side of the field now.
