### ISSUE TITLE
Implementation not mocked depending on constructor signature

### ISSUE THREAD

**Issue by milgner** [mockk/mockk#1130]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

The following Kotest-based test should pass:

```
class MockkMePlease(val foo: NonEmptySet<Int>) {
    fun doStuff() {
        throw Exception("This should be mocked")
    }
}

class MockkInlineSpec : DescribeSpec({
    describe("NonEmptySet in constructor") {
        it("uses the mock") {
            val mock = mockk<MockkMePlease>()
            justRun { mock.doStuff() }
            mock.doStuff()
            verify { mock.doStuff() }
        }
    }
})
```

### Current Behavior

All three references to `doStuff` - the blocks of `justRun`, `verify` as well as the call from the class under test - invoke the original implementation instead of the mockk-related behaviour.

### Failure Information (for bugs)

Changing the constructor to use a regular `Set` instead of a [`NonEmptySet`](https://apidocs.arrow-kt.io/arrow-core/arrow.core/-non-empty-set/index.html) makes the implementation pass.

#### Steps to Reproduce

See above.

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.13.5
* OS: Linux
* Kotlin version: 1.9.0 (tested with 1.8.20 as well)
* JDK version: openjdk version "17.0.7" 2023-04-18
* JUnit version: 5.9.2
* Type of test: unit test (KOtest)

#### Failure Logs

Please include any relevant log snippets or files here.

#### Stack trace

```
java.lang.Exception: This should be mocked
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    testImplementation("io.arrow-kt:arrow-core:1.2.0")
    testImplementation("io.kotest:kotest-assertions-core:5.6.2")
    testImplementation("io.kotest:kotest-framework-api-jvm:5.6.2")
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
package io.mockk.gh

import io.mockk.*
import io.kotest.core.spec.style.DescribeSpec
import arrow.core.NonEmptySet

class MockkMePlease(val foo: NonEmptySet<Int>) {
    fun doStuff() {
        throw Exception("This should be mocked")
    }
}

class MockkInlineSpec : DescribeSpec({
    describe("NonEmptySet in constructor") {
        it("uses the mock") {
            val mock = mockk<MockkMePlease>()
            justRun { mock.doStuff() }
            mock.doStuff()
            verify { mock.doStuff() }
        }
    }
})
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by i-whammy** [comment]
Hi @milgner , I investigated this issue and found some hypothesis.

As `NonEmptyList` is inlined and has type parameter, the type information is lost in compile.
The problem is comes from both inlined class and type parameter.

```kotlin
// Constructor of NonEmptyList
@JvmInline
public value class NonEmptySet<out A> private constructor(
  private val elements: Set<A>
) : Set<A> by elements, NonEmptyCollection<A> {
```

```kotlin
// minimal reproducible code
class Test : DescribeSpec({
    describe("This will fail") {
        val mock = mockk<DummyMockMePlease>()
        justRun { mock.foo() }
        mock.foo()
        verify { mock.foo() }
    }

    describe("This will success") {
        val mock = mockk<DummyMockMePlease2>()
        justRun { mock.foo() }
        mock.foo()
        verify { mock.foo() }
    }

})

@JvmInline
value class DummyNonEmptySet<E>(val value: Set<E>)

class DummyNonEmptySet2(val value: Set<Any>)

class DummyMockMePlease(val arg0: DummyNonEmptySet<Int>) {
    fun foo() {
        throw Exception("This should be mocked.")
    }
}

class DummyMockMePlease2(val arg0: DummyNonEmptySet2) {
    fun foo() {
        throw Exception("This should be mocked.")
    }
}
```

However, I feel unsure of my hypothesis and do not know how to solve this issue...

**Comment by milgner** [comment]
So I started looking into this again. Now that I am more familiar with Kotlin and a bit more familiar with mockk, too, I thought I might stand a better chance.

As it turns out, the error message with the most recent versions of Kotlin, mockk and Arrow is silghtly more illuminating as there is a stacktrace from Bytebuddy visible now:

```
WARNING: Failed to transform class com/marcusilgner/mockk_repro_1130/MockkMePlease
java.lang.IllegalArgumentException: Unknown type: null
	at net.bytebuddy.description.type.TypeDefinition$Sort.describe(TypeDefinition.java:280)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfParameterizedType$ForLoadedType$ParameterArgumentTypeList.get(TypeDescription.java:5362)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfParameterizedType$ForLoadedType$ParameterArgumentTypeList.get(TypeDescription.java:5334)
	at java.base/java.util.AbstractList$Itr.next(AbstractList.java:373)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor.onParameterizedType(TypeDescription.java:1911)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor$ForDetachment.onParameterizedType(TypeDescription.java:2083)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfParameterizedType.accept(TypeDescription.java:5139)
	at net.bytebuddy.description.type.TypeDescription$Generic$LazyProjection.accept(TypeDescription.java:6302)
	at net.bytebuddy.description.field.FieldDescription$AbstractBase.asToken(FieldDescription.java:200)
	at net.bytebuddy.description.field.FieldDescription$AbstractBase.asToken(FieldDescription.java:123)
	at net.bytebuddy.description.field.FieldList$AbstractBase.asTokenList(FieldList.java:64)
	at net.bytebuddy.dynamic.scaffold.InstrumentedType$Factory$Default$1.represent(InstrumentedType.java:436)
	at net.bytebuddy.ByteBuddy.redefine(ByteBuddy.java:886)
	at net.bytebuddy.ByteBuddy.redefine(ByteBuddy.java:861)
	at io.mockk.proxy.jvm.transformation.InliningClassTransformer.transform(InliningClassTransformer.kt:74)
```

I'll continue looking into this for a bit; luckily I have a couple of free days this week and should be able to spend some time on OSS work :smiley_cat:

**Comment by milgner** [comment]
Since there were [some changes in OpenJDK 24](https://github.com/openjdk/jdk/commit/1d070a3238a1cd8b9359357e6e3f751cd26a3f06), I tried this again today with the latest versions of OpenJDK, Kotlin, Arrow and mockk. Unfortunately, it still doesn't work, even if the error message has changed:

```
java.lang.TypeNotPresentException: Type E not present
	at java.base/sun.reflect.generics.factory.CoreReflectionFactory.findTypeVariable(CoreReflectionFactory.java:111)
	at java.base/sun.reflect.generics.visitor.Reifier.visitTypeVariableSignature(Reifier.java:165)
	at java.base/sun.reflect.generics.tree.TypeVariableSignature.accept(TypeVariableSignature.java:43)
	at java.base/sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
	at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
	at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at java.base/sun.reflect.generics.repository.FieldRepository.computeGenericType(FieldRepository.java:90)
	at java.base/sun.reflect.generics.repository.FieldRepository.getGenericType(FieldRepository.java:82)
	at java.base/java.lang.reflect.Field.getGenericType(Field.java:290)
	at net.bytebuddy.description.type.TypeDescription$Generic$LazyProjection$ForLoadedFieldType.resolve(TypeDescription.java:6689)
	at net.bytebuddy.description.type.TypeDescription$Generic$LazyProjection.accept(TypeDescription.java:6301)
	at net.bytebuddy.description.field.FieldDescription$AbstractBase.asToken(FieldDescription.java:200)
	at net.bytebuddy.description.field.FieldDescription$AbstractBase.asToken(FieldDescription.java:123)
	at net.bytebuddy.description.field.FieldList$AbstractBase.asTokenList(FieldList.java:64)
	at net.bytebuddy.dynamic.scaffold.InstrumentedType$Factory$Default$1.represent(InstrumentedType.java:437)
	at net.bytebuddy.ByteBuddy.redefine(ByteBuddy.java:923)
	at net.bytebuddy.ByteBuddy.redefine(ByteBuddy.java:898)
	at io.mockk.proxy.jvm.transformation.InliningClassTransformer.transform(InliningClassTransformer.kt:78)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:257)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:594)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:221)
	at io.mockk.proxy.jvm.transformation.JvmInlineInstrumentation.retransform(JvmInlineInstrumentation.kt:28)
	at io.mockk.proxy.common.transformation.RetransformInlineInstrumentation$execute$1.invoke(RetransformInlineInstrumentation.kt:19)
	at io.mockk.proxy.common.transformation.RetransformInlineInstrumentation$execute$1.invoke(RetransformInlineInstrumentation.kt:16)
	at io.mockk.proxy.common.transformation.ClassTransformationSpecMap.applyTransformation(ClassTransformationSpecMap.kt:41)
	at io.mockk.proxy.common.transformation.RetransformInlineInstrumentation.execute(RetransformInlineInstrumentation.kt:16)
	at io.mockk.proxy.jvm.ProxyMaker.inline(ProxyMaker.kt:90)
	at io.mockk.proxy.jvm.ProxyMaker.proxy(ProxyMaker.kt:34)
	at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:34)
	at io.mockk.impl.instantiation.AbstractMockFactory.newProxy$default(AbstractMockFactory.kt:24)
	at io.mockk.impl.instantiation.AbstractMockFactory.mockk(AbstractMockFactory.kt:59)
	at com.marcusilgner.mockk_repro_1130.MockkInlineSpec$1$1$1.invokeSuspend(MockkInlineSpec.kt:43)
```

From what I saw so far, I'm starting to think that nothing can be done about it from within mockk or even bytebuddy...
