### ISSUE TITLE
Mockk throwing IncompatibleClassChangeError in Android UI tests

### ISSUE THREAD

**Issue by abdelrhman** [mockk/mockk#1144]
> Just be aware about usual MockK support pattern. 
> Tickets are checked from time to time, replied, discussed, labeled, e.t.c.
> But real fixes are applied in a month-two month period in a bunch.
> If you think this is unacceptable, go on, join the project, change the world.

## Please remove sections wisely

Below information is actually needed to make all the process of fixing faster.
Choose main points. Don't blindly follow this as a set of rules. 
Don't waste much time. Usually, the main thing is to have a good reproducible minimal code.

### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

Mockk shouldn't cause IncompatibleClassChangeError crash on android UI tests

### Current Behavior

What is the current behavior?
0

I am facing a crash happening in my Android UI tests when using mockk
```
at java.lang.VMClassLoader.findLoadedClass(Native Method)
at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
at com.android.dx.stock.ProxyBuilder.loadClass(ProxyBuilder.java:358)
at com.android.dx.stock.ProxyBuilder.buildProxyClass(ProxyBuilder.java:340)
at io.mockk.proxy.android.transformation.AndroidSubclassInstrumentation.subclass(AndroidSubclassInstrumentation.kt:37)
at io.mockk.proxy.common.ProxyMaker.subclass(ProxyMaker.kt:144)
at io.mockk.proxy.common.ProxyMaker.proxy(ProxyMaker.kt:53)
at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:34)
at io.mockk.impl.instantiation.AbstractMockFactory.newProxy$default(AbstractMockFactory.kt:24)
at io.mockk.impl.instantiation.AbstractMockFactory.spyk(AbstractMockFactory.kt:102)
at sample.app.common.loadmore.LoadMoreViewTests.<init>(LoadMoreViewTests.kt:129)
```

### Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

#### Steps to Reproduce
```
// lib.toml
mockk = "1.13.7"
[libraries]
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
mockk-agent = { group = "io.mockk", name = "mockk-agent", version.ref = "mockk" }
[bundles]
mockk = ["mockk-agent", "mockk-android"]
// app/build.gradle
testImplementation(libs.bundles.mockk)
androidTestImplementation(libs.bundles.mockk)
// LoadMoreViewTests.kt
private val clickListener: () -> Unit = spyk {
       every { this@spyk.invoke() } just runs
}
```

Please provide detailed steps for reproducing the issue.

1. following the pervious setup steps when you run the UI test you can see a crash in the logcat 

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.13.7
* OS: Android
* Kotlin version: 1.8.20
* JDK version:
* JUnit version:
* Type of test: android instrumented test

#### Failure Logs

Please include any relevant log snippets or files here.

#### Stack trace

```
at java.lang.VMClassLoader.findLoadedClass(Native Method)
at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
at com.android.dx.stock.ProxyBuilder.loadClass(ProxyBuilder.java:358)
at com.android.dx.stock.ProxyBuilder.buildProxyClass(ProxyBuilder.java:340)
at io.mockk.proxy.android.transformation.AndroidSubclassInstrumentation.subclass(AndroidSubclassInstrumentation.kt:37)
at io.mockk.proxy.common.ProxyMaker.subclass(ProxyMaker.kt:144)
at io.mockk.proxy.common.ProxyMaker.proxy(ProxyMaker.kt:53)
at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:34)
at io.mockk.impl.instantiation.AbstractMockFactory.newProxy$default(AbstractMockFactory.kt:24)
at io.mockk.impl.instantiation.AbstractMockFactory.spyk(AbstractMockFactory.kt:102)
at sample.app.common.loadmore.LoadMoreViewTests.<init>(LoadMoreViewTests.kt:129)
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    testCompile group: 'org.apache.kafka', name: 'kafka_2.12', version: '1.1.0'
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
package io.mockk.gh

import io.mockk.every
import io.mockk.mockk
import org.apache.kafka.common.KafkaFuture
import kotlin.test.Test

class Issue69Test {

    @Test
    fun test() {
        val kafkaFuture: KafkaFuture<Void> = mockk()
        every { kafkaFuture.get(any(), any()) } returns mockk()
        kafkaFuture.get(10, TimeUnit.MILLISECONDS)
    }

}
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by AbdelrahmanTalat** [comment]
Using version 1.13.1 I can't replicate the issue

**Comment by AbdelrahmanTalat** [comment]
The issue starts happening when using version [1.13.4] and above

**Comment by LeonRa** [comment]
This looks like a duplicate of https://github.com/mockk/mockk/issues/1035, for which a fix should be available in an upcoming mockk release
