### ISSUE TITLE
Support selective verify

### ISSUE THREAD

**Issue by Ghedeon** [mockk/mockk#116]
Allow to verify only the call user interested in and skip possible others.

### Expected Behavior

the following test should pass:
```kotlin
    @Test
    fun mockk() {
        val foo: (x: Int) -> Unit = mockk(relaxed = true)

        foo(1)
        foo(2)

        verify{ foo(assert { it == 1 }) }
    }
```

Not sure if `verify` or `verify(atLeast = 1)` should pass but there must be a way to assert only values we care about.

Corresponding mockito test that works:
```kotlin
    @Test
    fun mockito() {
        val foo: (x: Int) -> Unit = mock()

        foo(1)
        foo(2)

        verify(foo).invoke(argWhere { it == 1 })
		// also verify(foo, atLeastOnce()).invoke(argWhere { it == 1 })
    }
```

### Current Behavior

java.lang.AssertionError: Verification matcher assertion failed

#### Context

* MockK version: 1.8.3
* Kotlin version: 1.2.50
* Type of test: unit test

#### Stack trace

```
java.lang.AssertionError: Verification matcher assertion failed

	at io.mockk.AssertMatcher.match(Matchers.kt:325)
	at io.mockk.InvocationMatcher.match(API.kt:3422)
	at io.mockk.impl.verify.UnorderedCallVerifier.matchCall(UnorderedCallVerifier.kt:95)
	at io.mockk.impl.verify.UnorderedCallVerifier.verify(UnorderedCallVerifier.kt:24)
	at io.mockk.impl.recording.states.VerifyingState$recordingDone$outcome$1.invoke(VerifyingState.kt:30)
	at io.mockk.impl.recording.states.VerifyingState$recordingDone$outcome$1.invoke(VerifyingState.kt:10)
	at io.mockk.impl.recording.CommonCallRecorder.safeExec(CommonCallRecorder.kt:66)
	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:29)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:42)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:48)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:27)
	at io.mockk.MockKDsl.internalVerify(API.kt:118)
	at io.mockk.MockKKt.verify(MockK.kt:100)
	at io.mockk.MockKKt.verify$default(MockK.kt:97)
...
```

**Comment by Kerooker** [comment]
I believe this is already possible with Ordering.UNORDERED(default behaviour):

```
@Test
    fun `Tester`(){
        val foo: (x: Int) -> Unit = mockk(relaxed = true)
    
        foo(1)
        foo(2)
    
        verify { foo(1) }
        
        // verify{ foo(2) } //Not necessary, but will work if uncommented.
     
    }
```

**Comment by Ghedeon** [comment]
@Kerooker thank you, can confirm `verify { foo(1) }` works but not the `verify{ foo(assert { it == 1 }) }`. I believe the argument matcher shouldn't affect the `verify` behaviour in terms of number/order of calls.

**Comment by Kerooker** [comment]
I don't think it's possible to assert that way. 
Assert is a Kotlin function, and won't work correctly with mockk. If you need to assert on an argument, you can either use [Mockk's Matchers](http://mockk.io/#matchers):
```
 val foo: (x: Int) -> Unit = mockk(relaxed = true)
    
        foo(1)
        foo(2)
        
        verify { foo(match { it == 1 }) }
```

Or capture the arguments and do something on them, but I wouldn't recommend that approach.

Anyways, `foo(1)` is exactly the same as `foo(match{it == 1})` and `foo(eq(1))`.

Maybe your use case is different from this one? I believe that for this sample, `verify { foo(1) }` is the best approach

**Comment by Ghedeon** [comment]
it's MockK's `assert` from `MockKVerificationScope`

**Comment by Kerooker** [comment]
Yes, I saw that mistake and corrected the comment :P

Why isn't match enough for you?

As I see, you want to see that the argument **matches** what you expected.

**Comment by Ghedeon** [comment]
@Kerooker Well, now that I know about `match` in `verify` it's enough for me ;). I asked about my matching options in `verify` context in `#kotlinlang` slack and was pointed to `assert` by @oleksiyp. Nevertheless, seems like we have a working solution. Maybe another improvement issue is required for `assert` idk..., at this point, it's hard for me to justify its existence. Thanks for the quick response, extremely helpful!
