### ISSUE TITLE
Cannot inline bytecode built with JVM target 11 into bytecode that is being built with JVM target 1.8. Please specify proper '-jvm-target' option

### ISSUE THREAD

**Issue by fctg-kandasas** [mockk/mockk#1168]
> Just be aware about usual MockK support pattern. 
> Tickets are checked from time to time, replied, discussed, labeled, e.t.c.
> But real fixes are applied in a month-two month period in a bunch.
> If you think this is unacceptable, go on, join the project, change the world.

## Please remove sections wisely

Below information is actually needed to make all the process of fixing faster.
Choose main points. Don't blindly follow this as a set of rules. 
Don't waste much time. Usually, the main thing is to have a good reproducible minimal code.

### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Expected Behavior

Please describe the behavior you are expecting

### Current Behavior

What is the current behavior?

### Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1 - Upgrade mockk library to 1.13.8 in Kotlin based JVM 1.8 project
2. step 2
3. started getting compile error "Cannot inline bytecode built with JVM target 11 into bytecode that is being built with JVM target 1.8. Please specify proper '-jvm-target' option"

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.13.8
* OS: Windows
* Kotlin version: 1.8.21
* JDK version: 1.8
* JUnit version:
* Type of test: unit test OR android instrumented test
 Kotest 

#### Failure Logs

Cannot inline bytecode built with JVM target 11 into bytecode that is being built with JVM target 1.8. Please specify proper '-jvm-target' option

Please include any relevant log snippets or files here.

#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
io.mockk.MockKException: Class cast exception. Probably type information was erased.
In this case use `hint` before call to specify exact return type of a method. 

	at io.mockk.impl.InternalPlatform.prettifyRecordingException(InternalPlatform.kt:83)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:50)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:25)
	at eu.example.schedule.kafka.KafkaAdminImplTest.mockkVoidReturnFails(KafkaAdminImplTest.kt:301)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassCastException: kotlin.Unit cannot be cast to java.lang.Void
	at eu.example.schedule.kafka.KafkaAdminImplTest$mockkVoidReturnFails$1.invoke(KafkaAdminImplTest.kt:87)
	at eu.example.schedule.kafka.KafkaAdminImplTest$mockkVoidReturnFails$1.invoke(KafkaAdminImplTest.kt:24)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:22)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:31)
	... 25 more
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    testCompile group: 'org.apache.kafka', name: 'kafka_2.12', version: '1.1.0'
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
package io.mockk.gh

import io.mockk.every
import io.mockk.mockk
import org.apache.kafka.common.KafkaFuture
import kotlin.test.Test

class Issue69Test {

    @Test
    fun test() {
        val kafkaFuture: KafkaFuture<Void> = mockk()
        every { kafkaFuture.get(any(), any()) } returns mockk()
        kafkaFuture.get(10, TimeUnit.MILLISECONDS)
    }

}
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by igorwojda** [comment]
I was able to deep dive into this. I have created a simple script that verifies the JVM target of a few mockk artifacts (others need to be checked as well). It checks if artifacts are compiled with the correct byte code:

mockk-core-jvm-1.13.7.jar - is compiled to bytecode 52 (Java 8) ✅
mockk-core-jvm-1.13.8.jar - is compiled to bytecode 55 (Java 11) ❌

Here is the full run
![image](https://github.com/mockk/mockk/assets/530122/90993286-6313-4d52-a88d-1274f278f376)

#### Steps to Reproduce
1. Download artifacts https://repo1.maven.org/maven2/io/mockk/mockk-core/ (`mockk-core-jvm-1.13.7.jar` `mockk-core-jvm-1.13.8.jar`)
2. In the same directory this script in the `check_bytecode_version.py` file in the same directory as artifacts and run  it `python3 check_bytecode_version.py`
```python
import sys
import subprocess
import os
import tempfile
import shutil

def get_bytecode_version(class_file):
    result = subprocess.run(["javap", "-verbose", class_file], capture_output=True, text=True)
    for line in result.stdout.splitlines():
        if "major version" in line:
            return line.split(":")[-1].strip()

def main(file_path):
    # Java 8 == bytecode version 52.0 (defined in the local.javalibrary.gradle.kts)
    desired_java_version = "8"
    desired_bytecode_version = "52"

    if os.path.exists(file_path):
        print(f"Verify if all classes in {file_path} are compiled to bytecode {desired_bytecode_version} (Java {desired_java_version})")
    else:
        print("File not found:", file_path)

    

    # Create a temporary directory
    temp_dir = "./temp"

    try:
        # Unzip the jar file to the temporary directory
        subprocess.run(["unzip", "-qq", file_path, "-d", temp_dir], check=True)

        # Walk the directory to find all .class files
        for root, _, files in os.walk(temp_dir):
            for file in files:
                print("file", file)
                if file.endswith(".class"):
                    file_path = os.path.join(root, file)
                    version = get_bytecode_version(file_path)
                    if version != desired_bytecode_version:
                        print(f"❌ ERROR {file_path} has incorrect bytecode version {version}")
                        sys.exit(1)
                    else:
                        print(f"✅ SUCCESS {file_path} has correct bytecode version {version}")
        
        print(f"✅✅✅ All classed in {file_path} have correct bytecode")
        print()
    finally:
        # Clean up the temporary directory
        aaa = True
        shutil.rmtree(temp_dir)

if __name__ == "__main__":    
    main("mockk-1.13.7.jar")
    main("mockk-1.13.8.jar")
    main("mockk-core-1.13.7.jar")
    main("mockk-core-1.13.8.jar")
    main("mockk-core-jvm-1.13.7.jar")
    main("mockk-core-jvm-1.13.8.jar")

```

It looks like this PR may have caused the issue
https://github.com/mockk/mockk/pull/1056

Here is failing PR to upgrade mockk v1.13.7 -> v1.13.8 at my repository
https://github.com/LemonAppDev/konsist/pull/640

**Comment by Antimonit** [comment]
Fixed via https://github.com/mockk/mockk/pull/1161

**Comment by frapontillo** [comment]
Any updates on when we will get a new release for this?

**Comment by MMasterson** [comment]
Any updates on this release?

**Comment by mobile-pablo** [comment]
Same issue occurs for me. cc :  @odrotbohm

**Comment by andrademv** [comment]
hey guys! issue was solved in 1.13.7, but is back in 1.13.8

**Comment by dotrothschild** [comment]
Android studio downgrade works: I use it in Android Studio Kotlin, indeed, downgrade to 1.13.7
