### ISSUE TITLE
value class that implements interface or sealed interface cannot be used in `returns`

### ISSUE THREAD

**Issue by taisuke-fujimoto** [mockk/mockk#1178]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

value class that implements interface or sealed interface can be used in `returns`

### Current Behavior

1. value class implements normal interface:
   ClassCastException is thrown when running a mock function with `returns` set.
   ```kotlin
   every { service.execute() } returns ValueClassImplementsInterface(1)

   service.execute() // this throws ClassCastException
   ```
2. value class implements sealed interface:
   `returns` DSL never finishes.
   ```kotlin
   every { service.execute() } returns ValueClassImplementsSealedInterface(1) // never finishes
   ```

The workaround for this is to not use value class.

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.13.8
* OS: Windows 10
* Kotlin version: 1.9.10
* JDK version: 17

#### Stack trace

```
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class test.Result (java.lang.Integer is in module java.base of loader 'bootstrap'; test.Result is in unnamed module of loader 'app')
	at test.SampleService.executeA(SampleService.kt:4)
	at test.AppKt.mockTest1(App.kt:33)
	at test.AppKt.main(App.kt:11)
	at test.AppKt.main(App.kt)
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    implementation("io.mockk:mockk:1.13.8")
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
package test

class SampleService {
    fun executeA(): Result = ResultA(1)

    fun sealedExecute(): SealedResult = SealedResultA("a")
}

interface Result

@JvmInline
value class ResultA(val value: Int): Result

sealed interface SealedResult

@JvmInline
value class SealedResultA(val value: String): SealedResult

fun main() {
    val service = mockk<SampleService>()
    every { service.executeA() } returns ResultA(2)

    try {
        println("mock executeA: ${service.executeA()}")
    } catch (ex: Throwable) {
        ex.printStackTrace()
    }

    every { service.sealedExecute() } returns SealedResultA("AA")
    println("never reach here")
}
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by AlexLombry** [comment]
Any news about this issue ?

**Comment by lbureau-billettiqueservices** [comment]
Just wanted to add that we stumbled upon this problem too for the second time. 

Thank you for your hard work.
