### ISSUE TITLE
MockKException: Failing to instantiate mocks for functions

### ISSUE THREAD

**Issue by leandro-dev** [mockk/mockk#1188]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Expected Behavior

It should execute the tests with success.

### Current Behavior

It's throwing a `MockKException` to instanciate new mock for a function.

`private val function: (StubClass) -> Unit = mockk(relaxed = true)`

#### Steps to Reproduce

1. Clone this sample project: https://github.com/leandro-dev/MockKException_proxy_Function1
2. Run all tests
![image](https://github.com/mockk/mockk/assets/1706622/501e8b8c-bb5c-4475-9a50-ab54802ef25b)

The test execution order is random, please notice that:
- If the test `NoRobo` executes before, it'll fail the test `Robo`. 
- If the test `Robo` executes before, it'll fail the test `NoRobo`.

#### Context

This is a weird bug that happens sometimes on my main project. It dependes on the test execution order, it needs to have mixed tests with and without Robolectric, it also seems to need to have different forms of mock initialization with and without `relaxed = true`.

The way that I configured the sample project will always reproduce this error.

* MockK version: 1.13.8
* OS: MacOS 13.6
* Kotlin version: 1.8.21
* JDK version: 17
* JUnit version: 4.13.2
* Robolectric version: 4.11.1
* Type of test: unit test

#### Stack trace

```
Can't instantiate proxy for class kotlin.Function1
io.mockk.MockKException: Can't instantiate proxy for class kotlin.Function1
	at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:64)
	at io.mockk.impl.instantiation.AbstractMockFactory.newProxy$default(AbstractMockFactory.kt:24)
	at io.mockk.impl.instantiation.AbstractMockFactory.mockk(AbstractMockFactory.kt:59)
	at com.example.myapplication.Robo.<init>(Robo.kt:74)
	at java.base@17.0.6/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base@17.0.6/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base@17.0.6/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base@17.0.6/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base@17.0.6/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at app//org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:250)
	at app//org.robolectric.RobolectricTestRunner$HelperTestRunner.createTest(RobolectricTestRunner.java:574)
	at app//org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:260)
	at app//org.junit.runners.BlockJUnit4ClassRunner$2.runReflectiveCall(BlockJUnit4ClassRunner.java:309)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:306)
	at app//org.robolectric.internal.SandboxTestRunner$HelperTestRunner.methodBlock(SandboxTestRunner.java:359)
	at app//org.robolectric.RobolectricTestRunner$HelperTestRunner.methodBlock(RobolectricTestRunner.java:583)
	at app//org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:286)
	at app//org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:101)
	at java.base@17.0.6/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base@17.0.6/java.lang.Thread.run(Unknown Source)
Caused by: io.mockk.proxy.MockKAgentException: Failed to subclass interface kotlin.jvm.functions.Function1
	at app//io.mockk.proxy.jvm.ProxyMaker.proxy(ProxyMaker.kt:42)
	at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:34)
	... 22 more
Caused by: java.lang.IllegalArgumentException: Could not create type
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:170)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:190)
	at io.mockk.proxy.jvm.transformation.SubclassInstrumentation.subclass(SubclassInstrumentation.kt:50)
	at io.mockk.proxy.jvm.ProxyMaker.subclass(ProxyMaker.kt:130)
	at io.mockk.proxy.jvm.ProxyMaker.proxy(ProxyMaker.kt:39)
	... 23 more
Caused by: java.lang.LinkageError: loader 'app' attempted duplicate class definition for kotlin.jvm.functions.Function1$Subclass2. (kotlin.jvm.functions.Function1$Subclass2 is in unnamed module of loader 'app')
	at java.base/java.lang.ClassLoader.defineClass0(Native Method)
	at java.base/java.lang.System$2.defineClass(Unknown Source)
	at java.base/java.lang.invoke.MethodHandles$Lookup$ClassDefiner.defineClass(Unknown Source)
	at java.base/java.lang.invoke.MethodHandles$Lookup$ClassDefiner.defineClass(Unknown Source)
	at java.base/java.lang.invoke.MethodHandles$Lookup.defineClass(Unknown Source)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.bytebuddy.utility.Invoker$Dispatcher.invoke(Unknown Source)
	at net.bytebuddy.utility.dispatcher.JavaDispatcher$Dispatcher$ForNonStaticMethod.invoke(JavaDispatcher.java:1032)
	at net.bytebuddy.utility.dispatcher.JavaDispatcher$ProxiedInvocationHandler.invoke(JavaDispatcher.java:1162)
	at jdk.proxy3/jdk.proxy3.$Proxy58.defineClass(Unknown Source)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingLookup.injectRaw(ClassInjector.java:1638)
	at net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:118)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$UsingLookup.load(ClassLoadingStrategy.java:519)
	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:101)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6325)
	at io.mockk.proxy.jvm.transformation.SubclassInstrumentation.doInterceptedSubclassing(SubclassInstrumentation.kt:97)
	at io.mockk.proxy.jvm.transformation.SubclassInstrumentation.subclass$lambda$0(SubclassInstrumentation.kt:53)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:168)
	... 27 more
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ Project plugins versions ] -----------------------
plugins {
    id("com.android.application") version "8.1.3" apply false
    id("org.jetbrains.kotlin.android") version "1.8.21" apply false
}

// -----------------------[ Module dependencies ] -----------------------
dependencies {
    implementation("androidx.core:core-ktx:1.8.0")
    implementation("androidx.appcompat:appcompat:1.6.1")
    implementation("com.google.android.material:material:1.3.0")
    testImplementation("junit:junit:4.13.2")
    testImplementation("io.mockk:mockk:1.13.8")
    testImplementation("org.robolectric:robolectric:4.11.1")
}

// -----------------------[ Test Class NoRobo.kt ] -----------------------------
class NoRobo {
    private val stubInterface: StubInterface = mockk()
    private val stubInterfaceTwo: StubInterfaceTwo = mockk(relaxed = true)

    private val function: (StubClass) -> Unit = mockk(relaxed = true)

    @Test
    fun `assertTrue NoRobo`() {
        assertTrue(true)
    }
}

// -----------------------[ Test Class Robo.kt ] -------------------------------
@RunWith(RobolectricTestRunner::class)
class Robo {
    private val stubInterface: StubInterface = mockk()
    private val stubInterfaceTwo: StubInterfaceTwo = mockk(relaxed = true)

    private val function: (StubClass) -> Unit = mockk(relaxed = true)

    @Test
    fun `assertTrue Robo`() {
        assertTrue(true)
    }

}

// -----------------------[ Test Class StubClass.kt ] -------------------------
class StubClass {}

// -----------------------[ Test Class StubInterface.kt ] ---------------------
interface StubInterface {
    suspend fun uselessMethod(): String
}

// -----------------------[ Test Class StubInterfaceTwo.kt ] ------------------
interface StubInterfaceTwo {
    suspend fun execute(): String
}
```

**Comment by afedorychak** [comment]
The simple fix for this issue would be to exclude MockK from being loaded into Robolectric sandbox class loader and you can do this by tweaking your system properties:

```gradle
tasks.withType(Test).configureEach {
    // excluding mockk from Robolectric's sandbox class loader
    systemProperty("org.robolectric.packagesToNotAcquire", "io.mockk")
}
```

But, unfortunately, that's not the fully story.

This exclusion was built into Robolectric 4.4 [originally](https://github.com/robolectric/robolectric/pull/5754).  Later, as a way to deal with the following issues, MockK was [reintroduced](https://github.com/robolectric/robolectric/pull/6516) into the sandbox class loader with the exception of a `io.mock.proxy` package:
 - https://github.com/mockk/mockk/issues/480
 - https://github.com/mockk/mockk/issues/492

That was years ago and today excluding `io.mock` doesn't seem to cause #480 anymore but do causes #492 because its root cause was not addressed. That root cause was summarized in one of the [comments](https://github.com/mockk/mockk/issues/492#issuecomment-743967059) and even the fix was proposed but it got stale and was not adopted.

So we can't exclude `io.mockk` just yet... Now on to why the exclusion fixes this current issue.

Here's a simplified reproduction scenario where, if you run both tests in the same JVM, the second test that gets to run fails:

```kotlin
package robomix  
  
import io.mockk.mockk  
import org.junit.Test  
import org.junit.runner.RunWith  
import org.robolectric.RobolectricTestRunner  
  
class NonRoboTest {  
    @Test  
    fun `non-robolectric test`() {  
        mockk<() -> Unit>()  
    }  
}  
  
@RunWith(RobolectricTestRunner::class)  
class RoboTest {  
  
    @Test  
    fun `robolectric test`() {  
        mockk<() -> Unit>()  
    }  
}
```

Or you can reproduce it with just one test class running under Robolectric if you force multiple sandboxes to be created (e. g. by running tests against different API):

```kotlin
@RunWith(RobolectricTestRunner::class)  
class TwoSandboxes {  
    @Test  
    @Config(sdk = [30])  
    fun test1() {  
        mockk<() -> Unit>()  
    }  
  
    @Test  
    @Config(sdk = [31])  
    fun test2() {  
        mockk<() -> Unit>()  
    }  
}
```

Not excluding MockK means that most of its machinery can now be created more than once per JVM: e. g. when Robolectric and non-Robolectric tests are mixed or two Robolectric test cases use different sandboxes.

When MockK needs to instantiate an interface `T` it generates a dummy implementation class with the name `T$Subclass<N>`. Here N is a counter that grows from 0. This counter is reused for all subclasses generated by MockK. Its creation is triggered by loading `JvmMockKGateway` class (via a companion object). If that class is loaded twice then counter starts from 0 again.

The gotcha here is that when MockK creates such subclass of `T` (using `net.bytebuddy.dynamic.loading.ClassLoadingStrategy.UsingLookup` strategy) it injects it into the **defining class loader of `T`**. If type `T` is not loaded into sandbox it means it is loaded into app's class loader (or the bootstrap). There is just one instance of such class loader per JVM under usual unit-test setup so, depending on the test execution order, it can happen that two instances of MockK may try to inject  the same class, say, `T$Subclass0` into the same class loader which is an error.

That's why the issue is not limited to function types. Any unsealed interface that is not loaded into the sandbox class loader ([list of excluded packages](https://github.com/robolectric/robolectric/blob/master/sandbox/src/main/java/org/robolectric/config/AndroidConfigurer.java#L59-L85) ) will experience the same issue (but don't try this with `java.*` classes because MockK uses a [different strategy](https://github.com/mockk/mockk/blob/master/modules/mockk-agent/src/jvmMain/java/io/mockk/proxy/jvm/ClassLoadingStrategyChooser.java#L34-L35) for those). For instance, in the above example, replacing `() -> Unit` with `kotlin.io.path.CopyActionContext` interface results in the same error.

**Comment by DavidCorrado** [comment]
https://kotlinlang.slack.com/archives/C9EJFT6DB/p1730390436829569
https://github.com/DavidCorrado/MockingUnitTestFailure/blob/main/app/src/test/java/com/example/mocktest/ExampleUnitTest.kt

Also got this issue.  I found it to be related to GraphicsMode on function over the class.  Would be good if we had a real solution here
