### ISSUE TITLE
Bug: cannot Mock Class With Package-Private Parent

### ISSUE THREAD

**Issue by pusolito** [mockk/mockk#119]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

I expect the mock to be created successfully

### Current Behavior

An exception is thrown when mocking class.

### Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Run the sample code

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.8.5
* OS: Mac OS Sierra
* Kotlin version: 1.2.41
* JDK version: 1.8.0_45
* Type of test: unit test

#### Failure Logs

Please include any relevant log snippets or files here.

#### Stack trace

```
[main] WARN io.mockk.proxy.jvm.transformation.InlineInstrumentation - Failed to transform classes [class Foo, class Bar, class java.lang.Object]
java.lang.UnsupportedOperationException: class redefinition failed: attempted to add a method
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
	at io.mockk.proxy.jvm.transformation.InlineInstrumentation.execute(InlineInstrumentation.kt:26)
	at io.mockk.proxy.jvm.ProxyMaker.inline(ProxyMaker.kt:88)
	at io.mockk.proxy.jvm.ProxyMaker.proxy(ProxyMaker.kt:30)
	at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:34)
	at io.mockk.impl.instantiation.AbstractMockFactory.newProxy$default(AbstractMockFactory.kt:27)
	at io.mockk.impl.instantiation.AbstractMockFactory.mockk(AbstractMockFactory.kt:44)
	at FooKt.main(Foo.kt:23)
Exception in thread "main" java.lang.UnsupportedOperationException: class redefinition failed: attempted to add a method
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
	at io.mockk.proxy.jvm.transformation.InlineInstrumentation.doCancel(InlineInstrumentation.kt:47)
	at io.mockk.proxy.jvm.transformation.InlineInstrumentation.access$doCancel(InlineInstrumentation.kt:9)
	at io.mockk.proxy.jvm.transformation.InlineInstrumentation$execute$cancellation$1.invoke(InlineInstrumentation.kt:20)
	at io.mockk.proxy.jvm.transformation.InlineInstrumentation$execute$cancellation$1.invoke(InlineInstrumentation.kt:9)
	at io.mockk.proxy.jvm.transformation.InlineInstrumentation.execute(InlineInstrumentation.kt:30)
	at io.mockk.proxy.jvm.ProxyMaker.inline(ProxyMaker.kt:88)
	at io.mockk.proxy.jvm.ProxyMaker.proxy(ProxyMaker.kt:30)
	at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:34)
	at io.mockk.impl.instantiation.AbstractMockFactory.newProxy$default(AbstractMockFactory.kt:27)
	at io.mockk.impl.instantiation.AbstractMockFactory.mockk(AbstractMockFactory.kt:44)
	at FooKt.main(Foo.kt:23)
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// Foo.kt
import io.mockk.mockk

internal class Foo: Bar()

fun main(args: Array<String>) {
    mockk<Foo>(relaxed = true)
}
```
```java
// Bar.java
class Bar {
    public void foo() { }
}
```

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    testImplementation "io.mockk:mockk:1.8.5"
}

**Comment by oleksiyp** [comment]
Hm. I checked it in a test and it is creating mockk

**Comment by oleksiyp** [comment]
I see you are using JDK version 1.8.0_45, which is pretty old. Just a guess, but may be you can try use 1.8.0_161 which I use right now

**Comment by pusolito** [comment]
This issue still reproduces for me with JDK 1.8.0_181 and mockk 1.8.6.  Are the tests you ran to confirm available?

**Comment by oleksiyp** [comment]
Probably it was not reproduced well. I didnt commit this test

**Comment by pusolito** [comment]
Anything more I can do to help?  This issue is currently blocking my adoption of what is an otherwise fantastic mocking framework.

**Comment by oleksiyp** [comment]
I returned back to reproduction and still not able to do.
I wonder what method retransformation is trying to add.

In next release there will be a possibility to dump class files before transformation by specifying a directory in a system property to put classes in. 
So you can specify in VM options `-Dio.mockk.classdump.path=dump` and get retransformed files from `dump` directory.

Please do it and send to me. Thanks

**Comment by pusolito** [comment]
Thanks for adding the the class dump.  Hopefully it will help get to the bottom of this issue.  I'm still able to reproduce with 1.8.7 using the following code:

``` kotlin
import com.datastax.driver.core.UDTValue
import io.mockk.mockk

fun main(args: Array<String>) {
    mockk<UDTValue>(relaxed = true)
}
```
I've attached the contents of the class dump: [dump.zip](https://github.com/mockk/mockk/files/2347252/dump.zip).

**Comment by oleksiyp** [comment]
Can you please provide a version of Apache DataStax Driver? I need to fetch original UDTValue from it.

**Comment by pusolito** [comment]
It's version 3.3.0.

**Comment by pusolito** [comment]
We’re you able to reproduce this with the latest sample I provided?

**Comment by oleksiyp** [comment]
Not yet

**Comment by pusolito** [comment]
Any update on this issue?

**Comment by oleksiyp** [comment]
I have spent almost all my weekend to fix few issues, but didnt touch this one. Sorry

**Comment by oleksiyp** [comment]
Adding link https://github.com/raphw/byte-buddy/issues/561

**Comment by oleksiyp** [comment]
As mentioned in https://github.com/raphw/byte-buddy/issues/561

> You can now set VisibilityBridgeStrategy.Default.NEVER on the ByteBuddy instance.

Reopening to try to fix it
