### ISSUE TITLE
Test passes when compiled for JDK target 19, but fails when compiled for JDK target 21

### ISSUE THREAD

**Issue by pedro-carneiro** [mockk/mockk#1194]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

Test passes.

### Current Behavior

Test fails.

### Failure Information (for bugs)

Test fails with `io.mockk.MockKException: Missing calls inside verify { ... } block.` when compiled for JDK target version 21.

But it passes if compiled for JDK target version 19.

#### Steps to Reproduce

1. Use the code example at the end of the description
2. Make sure it is compiled for JDK target version 21
3. Run the test, and it fails

#### Context

* MockK version: 1.13.8
* OS: MacOS 14.2.1
* Kotlin version: 1.9.21
* JDK version: 21.0.1
* JUnit version: 5.8.2
* Type of test: unit test

#### Stack trace

```text
io.mockk.MockKException: Missing calls inside verify { ... } block.

	at io.mockk.impl.recording.states.VerifyingState.checkMissingCalls(VerifyingState.kt:52)
	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:21)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:63)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalVerify(API.kt:120)
	at io.mockk.MockKKt.verify(MockK.kt:218)
	at io.mockk.MockKKt.verify$default(MockK.kt:209)
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
import io.mockk.spyk
import io.mockk.verify
import org.junit.jupiter.api.Test

class TestClass {
    private data class SuchClass(
        val suchAttribute: String,
    )

    @Test
    fun test() {
        val s = SuchClass(suchAttribute = "string")
        val spy = spyk<SuchClass>(s)

        spy.suchAttribute

        verify(exactly = 1) { spy.suchAttribute }
    }
}
```

**Comment by benjamineckstein** [comment]
any update on this issue? I am facing exactly the same problem

**Comment by graceful-martin** [comment]
I have correctly set up all versions to reproduce, and the tests pass successfully. Could you provide a project that can reproduce?

**Comment by vmartyniuk107** [comment]
I have the same problem with static classes. For ex:
```
mockkStatic(UUID::class)
every { UUID.randomUUID() } returns fakeUuid
```

io.mockk.MockKException: Missing mocked calls inside every { ... } block: make sure the object inside the block is a mock

**Comment by nsk90** [comment]
looks i am facing similar issue after updating to kotlin 2.3.0
