### ISSUE TITLE
Support Kotlin 1.9.20's enums with mockkObject

### ISSUE THREAD

**Issue by TWiStErRob** [mockk/mockk#1198]
### Expected Behavior

Works as before.

### Current Behavior

Throws strange exception.

#### Steps to Reproduce

1. Clone https://github.com/TWiStErRob/repros/tree/main/mockk/mockkObject-missing-every-on-enum
2. `gradlew test` -> fail
3. Downgrade Kotlin to 1.9.10 (`build.gradle.kts` > `plugins { }`)
4. `gradlew test` -> pass

#### Context

I was updating a project's dependencies and I was faced with a test failure. The test was working previously, so I narrowed it down to the Kotlin from 1.9.10 to 1.9.21.

My hunch is that is that `mockk` does something to `values()`, but doesn't do to `entries`, because it's not aware of it. This causes `mockkObject` to misbehave. Don't go just on this though, I might be wrong, because it was added in 1.9.0.

* MockK version: 1.13.8 or earlier
* OS: Mac / Ubuntu 20 / not relevant
* Kotlin version: 1.9.20/.21/.22
* JDK version: 11 / 17 / not relevant
* JUnit version: 4.13.2 / not relevant
* Type of test: unit test

#### Stack trace

```
Missing mocked calls inside every { ... } block: make sure the object inside the block is a mock
io.mockk.MockKException: Missing mocked calls inside every { ... } block: make sure the object inside the block is a mock
	at app//io.mockk.impl.recording.states.StubbingState.checkMissingCalls(StubbingState.kt:14)
	at app//io.mockk.impl.recording.states.StubbingState.recordingDone(StubbingState.kt:8)
	at app//io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at app//io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:63)
	at app//io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at app//io.mockk.MockKDsl.internalEvery(API.kt:94)
	at app//io.mockk.MockKKt.every(MockK.kt:143)
	at app//com.example.MyEnumTest.test(MyEnumTest.kt:11)
```

Note: I confirmed `mockObject` does what it should with a simple `println(MyEnum.A)`.

#### Minimal reproducible code (the gist of this issue)

```kotlin
enum class MyEnum { A }

mockkObject(MyEnum.A)
every { MyEnum.A.name } returns "not-a"
```

**Comment by Raibaz** [comment]
Sure, go ahead, thanks!
