### ISSUE TITLE
Mocking an interface from a signed dependency fails.

### ISSUE THREAD

**Issue by kainoffke** [mockk/mockk#120]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

A mock should be created successfully using the same protection domain.

### Current Behavior

A `SecurityException` is thrown.

### Failure Information (for bugs)

I am trying to mock the interface `javax.persistence.EntityManager`. This comes from a signed jar.
When creating the mock using byteBuddy,  the `protectionDomain` of the interface is not taken into concern.
This causes a `SecurityException` to be thrown.

#### Steps to Reproduce

Please see the example code.

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.8.5
* OS: macOS 10.13.6
* Kotlin version: 1.2.51
* JDK version: 1.8.0_161
* Type of test: unit test 

#### Stack trace

```
io.mockk.MockKException: Can't instantiate proxy for class javax.persistence.EntityManager

	at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:64)
	at io.mockk.impl.instantiation.AbstractMockFactory.newProxy$default(AbstractMockFactory.kt:27)
	at io.mockk.impl.instantiation.AbstractMockFactory.mockk(AbstractMockFactory.kt:44)
	at io.elegate.mockk.EntityManagerTest.mockEntityManager(EntityManagerTest.kt:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: io.mockk.proxy.MockKAgentException: Failed to subclass interface javax.persistence.EntityManager
	at io.mockk.proxy.jvm.ProxyMaker.proxy(ProxyMaker.kt:38)
	at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:34)
	... 25 more
Caused by: java.lang.IllegalArgumentException: Could not create type
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:139)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:159)
	at io.mockk.proxy.jvm.transformation.SubclassInstrumentation.subclass(SubclassInstrumentation.kt:45)
	at io.mockk.proxy.jvm.ProxyMaker.subclass(ProxyMaker.kt:110)
	at io.mockk.proxy.jvm.ProxyMaker.proxy(ProxyMaker.kt:35)
	... 26 more
Caused by: java.lang.IllegalStateException: Error invoking java.lang.ClassLoader#defineClass
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Direct.defineClass(ClassInjector.java:483)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.inject(ClassInjector.java:186)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:205)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:126)
	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:79)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:4247)
	at io.mockk.proxy.jvm.transformation.SubclassInstrumentation.doInterceptedSubclassing(SubclassInstrumentation.kt:78)
	at io.mockk.proxy.jvm.transformation.SubclassInstrumentation.access$doInterceptedSubclassing(SubclassInstrumentation.kt:16)
	at io.mockk.proxy.jvm.transformation.SubclassInstrumentation$subclass$1.call(SubclassInstrumentation.kt:48)
	at io.mockk.proxy.jvm.transformation.SubclassInstrumentation$subclass$1.call(SubclassInstrumentation.kt:16)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:137)
	... 30 more
Caused by: java.lang.SecurityException: class "javax.persistence.EntityManager$ByteBuddy$GYApLmCp"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:898)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:668)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:761)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Direct.defineClass(ClassInjector.java:479)
	... 40 more
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    compile group: 'org.eclipse.persistence', name: 'org.eclipse.persistence.jpa', version: '2.7.2'

    testCompile group: 'junit', name: 'junit', version: '4.12'
    testCompile "io.mockk:mockk:1.8.5"
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
package io.elegate.mockk

import io.mockk.mockk
import org.junit.Test
import javax.persistence.EntityManager

class EntityManagerTest {

    @Test
    fun mockEntityManager() {
        mockk<EntityManager>()
    }
}
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by oleksiyp** [comment]
Interesting. Thanks for reporting it

**Comment by kainoffke** [comment]
Glad I can help!

I found that ByteBuddy _can_ use the the targets ProtectionDomain.

```
val factory: () -> EntityManager = {
   println("Producing entityManager using custom factory")

   val byteBuddy = ByteBuddy()
   val strategy = ClassLoadingStrategy.Default.INJECTION.with(EntityManager::class.java.protectionDomain)
   byteBuddy.subclass(EntityManager::class.java)
      .make()
      .load(EntityManagerTest::class.java.classLoader, strategy)
      .loaded
      .newInstance()
}
```

I tried using this factory with `registerInstanceFactory` but it is not used.

I am not quite sure about it, but could the solution be to tell ByteBuddy to use the targets _protectionDomain_ if `protectionDomain.codeSource.certificates` is not null? Or maybe even use it generally?

**Comment by oleksiyp** [comment]
Looks related https://discourse.hibernate.org/t/securityexception-with-bytebuddy-and-signed-application-jars/816/3

**Comment by oleksiyp** [comment]
Very simple fix. Done in master

**Comment by kainoffke** [comment]
I can confirm, this fixes the issue.
Thank you very much!
