### ISSUE TITLE
Externally accessing a mocked lateinit object in a spied object fails. 

### ISSUE THREAD

**Issue by oshamahue** [mockk/mockk#124]
I am trying to mock an `lateinit` object inside a spied object. accessing the `lateinit` object externally works fine but accessing internally(within the spied class) causes  `kotlin.UninitializedPropertyAccessException`

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

#### Context

* MockK version:1.8.6
* OS: MacOS High Sierra 10.13.6 (17G65)
* Kotlin version:1.2.60
* JDK version:1.8.0_91
* Type of test: unit test

#### Stack trace

```
kotlin.UninitializedPropertyAccessException: lateinit property a has not been initialized

	at com.oshamahue.mockspytest.B.printA(Data.kt:9)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.mockk.proxy.jvm.advice.MethodCall.call(MethodCall.kt:14)
	at io.mockk.proxy.jvm.advice.SelfCallEliminatorCallable.call(SelfCallEliminatorCallable.kt:14)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper.handleOriginalCall(JvmMockFactoryHelper.kt:81)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper.access$handleOriginalCall(JvmMockFactoryHelper.kt:18)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1$invocation$$inlined$stdFunctions$lambda$1.invoke(JvmMockFactoryHelper.kt:26)
	at io.mockk.impl.stub.MockKStub$handleInvocation$originalPlusToString$1.invoke(MockKStub.kt:162)
	at io.mockk.impl.stub.SpyKStub.defaultAnswer(SpyKStub.kt:14)
	at io.mockk.impl.stub.MockKStub.answer(MockKStub.kt:44)
	at io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:15)
	at io.mockk.impl.recording.states.AnsweringStillAcceptingAnswersState.call(AnsweringStillAcceptingAnswersState.kt:16)
	at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:48)
	at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:209)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:23)
	at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:20)
	at com.oshamahue.mockspytest.B.printA(Data.kt:10)
	at com.oshamahue.mockspytest.ExampleUnitTest.test A value(ExampleUnitTest.kt:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
```

#### Minimal reproducible code (the gist of this issue)

```kotlin

class A(val value: String)
class B {
    lateinit var a: A
    fun printA() {
        print(a.value)
    }
}
class ExampleUnitTest {
    @Test
    fun `test A value`() {
        val a: A = mockk()
        val notSpiedB = B()
        val b = spyk(notSpiedB)
        every { a.value } returns "from mock"
        every { b.a } returns a
        assertEquals("from mock", b.a.value)//successful at this line
        b.printA()//throws exception at this line. 
    }
}
```

**Comment by oleksiyp** [comment]
Unfortunately, Kotlin inlines this check in this case.
```
  public final void printA();
    descriptor: ()V
    flags: (0x0011) ACC_PUBLIC, ACC_FINAL
    Code:
      stack=2, locals=2, args_size=1
         0: aload_0
         1: getfield      #11                 // Field a:Lio/mockk/gh/Issue124Test$A;
         4: dup
         5: ifnonnull     13
         8: ldc           #12                 // String a
        10: invokestatic  #18                 // Method kotlin/jvm/internal/Intrinsics.throwUninitializedPropertyAccessException:(Ljava/lang/String;)V
        13: invokevirtual #36                 // Method io/mockk/gh/Issue124Test$A.getValue:()Ljava/lang/String;
        16: astore_1
        17: getstatic     #42                 // Field java/lang/System.out:Ljava/io/PrintStream;
        20: aload_1
        21: invokevirtual #48                 // Method java/io/PrintStream.print:(Ljava/lang/Object;)V
        24: return
```

So it is very hard to do anything except using `mockk` differently.

```
        val a: A = mockk()
        val notSpiedB = B()
        val b = spyk(notSpiedB)
        every { a.value } returns "from mock"
        b.a = a;
        assertEquals("from mock", b.a.value)//successful at this line
        b.printA()//throws exception at this line. 
```
