### ISSUE TITLE
Regression - Specifying kotlin.time.Duration as return value for `every` leads to ClassCastException

### ISSUE THREAD

**Issue by martijnvanderwoud** [mockk/mockk#1248]
See https://github.com/mockk/mockk/issues/869#issuecomment-2061469561

**Comment by derrenlee** [comment]
Is there a workaround for this? This issue is pretty annoying.

**Comment by VasilisDrettas-tomtom** [comment]
Hi @martijnvanderwoud, I tried to reproduce the issue with the latest version but it's not reproducible anymore. Could you maybe try again?

**Comment by Drekorian** [comment]
@VasilisDrettas-tomtom, I have the same issue while utilizing `kotlin.time.Duration` in the latest release `1.13.13`.

Partial stacktrace:

```
Caused by: java.lang.ClassCastException: class kotlin.time.Duration cannot be cast to class java.lang.Long (kotlin.time.Duration is in unnamed module of loader 'app'; java.lang.Long is in module java.base of loader 'bootstrap')
		at java.base/java.time.OffsetDateTime.until(OffsetDateTime.java:1667)
		at java.base/java.time.Duration.between(Duration.java:490)
```

Similarly, a custom `value class`

```
@JvmInline
value class Vin(val value: String) : VehicleId {
    companion object {
        const val MAX_LENGTH = 17
        const val VIN_FORMAT_REGEX = "(TMB|BSK)[A-HJ-NPR-Z\\d]{8}\\d{6}"
    }
}
```

causes

```
java.lang.ClassCastException: class com.example.Vin cannot be cast to class java.lang.String (com.example.Vin is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap').
```

for a simple declaration like so:

```
every { vin } returns Vin("someVin")
```

Everything works just fine in `1.13.9`.

**Comment by mykhailo-kratiuk** [comment]
I got the same problem. I updated to the latest from 1.13.7 -> 1.13.13. The duration problem (Class cast from Long to Duration) disappeared, but 30+ UT are failing now. This library made my day, thanks

**Comment by VasilisDrettas-tomtom** [comment]
Apologies for that. I made a fix for it here https://github.com/mockk/mockk/pull/1314

**Comment by mykhailo-kratiuk** [comment]
I might have seemed rude in my previous message. Actually, you are doing a great job. Thanks, mate

**Comment by Raibaz** [comment]
Just published v1.13.14, sorry for the delay :)

**Comment by frett** [comment]
thanks! the update did successfully resolve the issue for me

**Comment by StuStirling** [comment]
This issue is still present in `v1.13.14`.

```kotlin
interface MyRepo {
  val duration : Duration?
}

// then in my test
private val repo = mockk<MyRepo> {
  every { duration } returns null
}
```

This results in the following exception:

> Caused by: java.lang.ClassCastException: class java.lang.Long cannot be cast to class kotlin.time.Duration (java.lang.Long is in module java.base of loader 'bootstrap'; kotlin.time.Duration is in unnamed module of loader 'app')
