### ISSUE TITLE
Verify call count on Object methods fail with `spyk(Object)`

### ISSUE THREAD

**Issue by quiqua** [mockk/mockk#125]
### Expected Behavior

Calling `verify(exactly = 2) { geometry.isPoint(any()) }` should ensure that the mentioned functions have been called two times.

### Current Behavior

An AssertionError is thrown: 
```
java.lang.AssertionError: Verification failed: call 1 of 1: Geometry(#1).isPoint(any())) was not called.
Calls to same mock:
1) Geometry(#1).isLineString([[1.0, 1.0], [2.0, 2.0]])

Stack traces:
1)                                                       io.mockk.impl.InternalPlatform.captureStackTrace           (InternalPlatform.kt:123)             
                                                           io.mockk.impl.stub.MockKStub.handleInvocation            (MockKStub.kt:192)                    
...
```

### Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.8.6
* OS: macOS 10.13.6
* Kotlin version: 1.2.51
* JDK version: 1.8.0_181
* Type of test: unit test 

#### Stack trace

```
java.lang.AssertionError: Verification failed: call 1 of 1: Geometry(#1).isPoint(any())) was not called.

Calls to same mock:
1) Geometry(#1).isLineString([[1.0, 1.0], [2.0, 2.0]])

Stack traces:
1)                                                       io.mockk.impl.InternalPlatform.captureStackTrace           (InternalPlatform.kt:123)             
                                                           io.mockk.impl.stub.MockKStub.handleInvocation            (MockKStub.kt:192)                    
                         io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation                  (JvmMockFactoryHelper.kt:23)          
                                                  io.mockk.proxy.jvm.advice.Interceptor.call                        (Interceptor.kt:20)                   
                                                         mockk_spyk_object_bug.Geometry.isLineString                (GeometryTest2.kt:39)                 
                                                     mockk_spyk_object_bug.TestGeometry.testSpyKonObject            (GeometryTest2.kt:28)                 
                                                   sun.reflect.NativeMethodAccessorImpl.invoke0                     (NativeMethodAccessorImpl.java:-2)N   
                                                   sun.reflect.NativeMethodAccessorImpl.invoke                      (NativeMethodAccessorImpl.java:62)    
                                               sun.reflect.DelegatingMethodAccessorImpl.invoke                      (DelegatingMethodAccessorImpl.java:43)
                                                               java.lang.reflect.Method.invoke                      (Method.java:498)                     
                                        org.junit.platform.commons.util.ReflectionUtils.invokeMethod                (ReflectionUtils.java:513)            
                                   org.junit.jupiter.engine.execution.ExecutableInvoker.invoke                      (ExecutableInvoker.java:115)          
                           org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6   (TestMethodTestDescriptor.java:170)   
                                  org.junit.jupiter.engine.execution.ThrowableCollector.execute                     (ThrowableCollector.java:40)          
                           org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod            (TestMethodTestDescriptor.java:166)   
                           org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute                     (TestMethodTestDescriptor.java:113)   
                           org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute                     (TestMethodTestDescriptor.java:58)    
   org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3 (HierarchicalTestExecutor.java:113)   
                      org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely               (SingleTestExecutor.java:66)          
   org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively          (HierarchicalTestExecutor.java:108)   
   org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute                     (HierarchicalTestExecutor.java:79)    
   org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2 (HierarchicalTestExecutor.java:121)   
                                            java.util.stream.ForEachOps$ForEachOp$OfRef.accept                      (ForEachOps.java:184)                 
                                                 java.util.stream.ReferencePipeline$2$1.accept                      (ReferencePipeline.java:175)          
                                                                     java.util.Iterator.forEachRemaining            (Iterator.java:116)                   
                                             java.util.Spliterators$IteratorSpliterator.forEachRemaining            (Spliterators.java:1801)              
                                                      java.util.stream.AbstractPipeline.copyInto                    (AbstractPipeline.java:481)           
                                                      java.util.stream.AbstractPipeline.wrapAndCopyInto             (AbstractPipeline.java:471)           
                                                  java.util.stream.ForEachOps$ForEachOp.evaluateSequential          (ForEachOps.java:151)                 
                                            java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential          (ForEachOps.java:174)                 
                                                      java.util.stream.AbstractPipeline.evaluate                    (AbstractPipeline.java:234)           
                                                     java.util.stream.ReferencePipeline.forEach                     (ReferencePipeline.java:418)          
   org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3 (HierarchicalTestExecutor.java:121)   
                      org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely               (SingleTestExecutor.java:66)          
   org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively          (HierarchicalTestExecutor.java:108)   
   org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute                     (HierarchicalTestExecutor.java:79)    
   org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2 (HierarchicalTestExecutor.java:121)   
                                            java.util.stream.ForEachOps$ForEachOp$OfRef.accept                      (ForEachOps.java:184)                 
                                                 java.util.stream.ReferencePipeline$2$1.accept                      (ReferencePipeline.java:175)          
                                                                     java.util.Iterator.forEachRemaining            (Iterator.java:116)                   
                                             java.util.Spliterators$IteratorSpliterator.forEachRemaining            (Spliterators.java:1801)              
                                                      java.util.stream.AbstractPipeline.copyInto                    (AbstractPipeline.java:481)           
                                                      java.util.stream.AbstractPipeline.wrapAndCopyInto             (AbstractPipeline.java:471)           
                                                  java.util.stream.ForEachOps$ForEachOp.evaluateSequential          (ForEachOps.java:151)                 
                                            java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential          (ForEachOps.java:174)                 
                                                      java.util.stream.AbstractPipeline.evaluate                    (AbstractPipeline.java:234)           
                                                     java.util.stream.ReferencePipeline.forEach                     (ReferencePipeline.java:418)          
   org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3 (HierarchicalTestExecutor.java:121)   
                      org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely               (SingleTestExecutor.java:66)          
   org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively          (HierarchicalTestExecutor.java:108)   
   org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute                     (HierarchicalTestExecutor.java:79)    
                org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute                     (HierarchicalTestExecutor.java:55)    
                  org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute                     (HierarchicalTestEngine.java:43)      
                                       org.junit.platform.launcher.core.DefaultLauncher.execute                     (DefaultLauncher.java:170)            
                                       org.junit.platform.launcher.core.DefaultLauncher.execute                     (DefaultLauncher.java:154)            
                                       org.junit.platform.launcher.core.DefaultLauncher.execute                     (DefaultLauncher.java:90)             
                                               com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs         (JUnit5IdeaTestRunner.java:74)        
                                com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs         (IdeaTestRunner.java:47)              
                                           com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart      (JUnitStarter.java:242)               
                                           com.intellij.rt.execution.junit.JUnitStarter.main                        (JUnitStarter.java:70)                

	at io.mockk.impl.recording.states.VerifyingState.failIfNotPassed(VerifyingState.kt:63)
	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:41)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:42)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:48)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:27)
	at io.mockk.MockKDsl.internalVerify(API.kt:119)
	at io.mockk.MockKKt.verify(MockK.kt:139)
	at io.mockk.MockKKt.verify$default(MockK.kt:136)
	at mockk_spyk_object_bug.TestGeometry.testSpyKonObject(GeometryTest2.kt:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:513)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:170)
	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:166)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:113)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:58)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:113)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:121)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:121)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:121)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:121)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:55)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


Process finished with exit code 255
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.2.51'
}

ext {
    kotlin_version = '1.2.51'
    junit_jupiter_version = '5.2.0'
    junit_platform_version = '1.2.0'
    mockk_version = '1.8.6'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    implementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"

    testImplementation "org.junit.jupiter:junit-jupiter-api:$junit_jupiter_version"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:$junit_jupiter_version"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher:$junit_platform_version"
}

// -----------------------[ CODE STARTS HERE ] -----------------------

package mockk_spyk_object_bug

import io.mockk.spyk
import io.mockk.verify
import org.junit.jupiter.api.Test

object Geometry {

    fun isPoint(coordinates: List<Double>): Boolean {
        return coordinates.count() == 2
    }

    fun isLineString(coordinates: List<List<Double>>): Boolean {
        val validCoordinates = mutableListOf<Boolean>()
        coordinates.forEach {
            validCoordinates.add(isPoint(it))
        }

        return validCoordinates.all { it }
    }
}

class TestGeometry {
    @Test
    fun testSpyKOnObject() {
        val geometry = spyk(Geometry)
        val coordinates = listOf(listOf(1.0, 1.0), listOf(2.0, 2.0))
        geometry.isLineString(coordinates)
        verify(exactly = 2) {
            geometry.isPoint(any())
        }
    }
}

// -----------------------[ CODE ENDS HERE ] -----------------------
```

**Comment by oleksiyp** [comment]
I checked this bug report.

It is possible to create `spyk` of `object`, but it is not a designed use. Inside bytecode all calls to `object` still will go through `INSTANCE` of this object i.e. it is still calling `Geometry.isPoint` while executing `geometry.isLineString`.

So basically I count it is as not a bug. Correct use is:

```
        mockkObject(Geometry) {

            val coordinates = listOf(
                listOf(1.0, 1.0),
                listOf(2.0, 2.0)
            )

            Geometry.isLineString(coordinates)

            verify(exactly = 2) {
                Geometry.isPoint(any())
            }
        }
```

**Comment by quiqua** [comment]
Thanks!
