### ISSUE TITLE
mockkObject/every fails substituting object function call, seems to run method

### ISSUE THREAD

**Issue by carstenhag** [mockk/mockk#1252]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed -> Found some related issues to mockkObject but none describing my issue.

### Repro Project
https://github.com/carstenhag/mockkobjectrepro/blob/master/app/src/test/java/com/example/mockkobjecttest/ExampleUnitTest.kt#L32

### Expected Behavior

A mocked object's function which I am trying to change doesn't run before while I am calling `every{}`.

### Current Behavior

The real function seems to be called while calling `every{}`.

### Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Run `mockkObject` on object provided by Emarsys Android SDK
2. Run `every { emarsysObject.clearContact() } returns Unit`
3. Get a crash because it actually runs the real implementation (`clearContact()`)

#### Context

* MockK version: 1.13.10
* OS: macOS 14.4.1
* Kotlin version: 1.9.23
* JDK version: 17
* JUnit version: 4.13.2
* Type of test: unit test

#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
(exception caused by the real implementation, expected if you run it without initializing it)

java.lang.IllegalStateException: DependencyContainer has to be setup first!
	at com.emarsys.di.EmarsysComponentKt.emarsys(EmarsysComponent.kt:21)
	at com.emarsys.di.EmarsysDependencyInjection.mobileEngageApi(EmarsysDependencyInjection.kt:24)
	at com.emarsys.Emarsys.clearContact(Emarsys.kt:157)
	at com.emarsys.Emarsys.clearContact$default(Emarsys.kt:152)
	at com.example.mockkobjecttest.ExampleUnitTest$mockingEmarsys$1.invoke(ExampleUnitTest.kt:38)
	at com.example.mockkobjecttest.ExampleUnitTest$mockingEmarsys$1.invoke(ExampleUnitTest.kt:38)
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    // Requires an android project / AGP
    implementation("io.mockk:mockk:1.13.10")
    implementation("com.emarsys:emarsys-sdk:3.7.5")
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs_nio:2.0.4")
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
package com.example.mockkobjecttest

import com.emarsys.Emarsys
import io.mockk.every
import io.mockk.mockkObject
import io.mockk.verify
import org.junit.Test

class Issue69Test {

    @Test
    fun mockingEmarsys() {
        val emarsysObject = Emarsys
        mockkObject(emarsysObject)
        every { emarsysObject.clearContact() } returns Unit

        emarsysObject.clearContact()

        verify(exactly = 1) { emarsysObject.clearContact() }
    }

}
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by alexstarkqm** [comment]
Hi, I'm facing the same issue and wonder if this behavior is intended or a bug.

**Comment by shekibobo** [comment]
I'm facing the same issue with the exact same library as the original poster. I've seen `mockkObject` work fine with another library that loves to use singleton `object`s, so I'm confused why it's not working with this particular one. It's possible that it's because this library uses the `@JvmStatic` annotation on all the methods in their singleton `object`.

**Comment by shekibobo** [comment]
Possibly related to #76

**Comment by shekibobo** [comment]
This works for me:

```kotlin
mockkStatic(Emarsys::class)
every { Emarsys.setup(any()) } just runs
every { Emarsys.push } returns emarsysPush
```

**Comment by shekibobo** [comment]
@carstenhag 

Finally finished working through my tests on this, and I've created this helpful rule to configure `Emarsys` for testing push notifications:

```kotlin
class EmarsysRule(config: EmarsysConfig) : ExternalResource() {
    val push = spyk(Push())

    private val component = spyk(DefaultEmarsysComponent(config), "EmarsysTestComponent")

    val emarsys = Emarsys

    init {
        mockkStatic(Emarsys::class)
        DefaultEmarsysDependencies(config, component)

        every { push.setPushToken(any(), any()) }
            .answers { Timber.w("setPushToken(${args.first()})") }
        every { push.setPushToken(any()) }
            .answers { Timber.w("setPushToken(${args.first()})") }
        every { push.clearPushToken(any()) }
            .answers { Timber.w("clearPushToken()") }
        every { push.clearPushToken() }
            .answers { Timber.w("clearPushToken()") }
        every { Emarsys.setContact(any(), any()) }
            .answers { Timber.w("setContact(${args[0]}, ${args[1]})") }

        every { component.push } returns push

        Emarsys.setup(config)
    }

    override fun after() {
        tearDownEmarsysComponent()
    }
}
```
