### ISSUE TITLE
Spring MockMvc fails to perform requests on spyk controllers

### ISSUE THREAD

**Issue by rpmcfong** [mockk/mockk#126]
### Expected Behavior
@countableset and I are using Spring Boot with a Kotlin MVC controller. Mockk and Junit 5 are being used to test it. We expect Spring MockMvc to successfully call `perform` on a controller method annotated with `@RequestMapping` and spied with `spyk`. (This works fine in Mockito 2.19.0)

### Current Behavior
Wrapping a controller with spyk causes MockMvc to fail to call the method annotated with `@RequestMapping`

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Run our test program
1. Notice that the regular controller works fine 
1. Notice that the spyk controller does not work with a failure 

### Suggested fix
We have identified a problem in mockk's use of ByteBuddy where annotations are being lost upon creation of the spy.

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

windows 10/macos 10.13.6

mockk 1.8.6
azul zulu java 1.8.0_181
kotlin 1.2.60
junit 5.20
spring boot 2.0.3.RELEASE

#### Stack trace
```
09:28:04.971 [main] DEBUG org.springframework.test.web.servlet.TestDispatcherServlet - Could not complete request
java.lang.IllegalArgumentException: Name for argument type [java.lang.String] not available, and parameter name information not found in class file either.
	at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.updateNamedValueInfo(AbstractNamedValueMethodArgumentResolver.java:171)
	at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.getNamedValueInfo(AbstractNamedValueMethodArgumentResolver.java:148)
	at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.resolveArgument(AbstractNamedValueMethodArgumentResolver.java:97)
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:124)
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:161)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:131)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
```

#### Minimal reproducible code (the gist of this issue)
Please see full test project: [spring-mockmvc-example.zip](https://github.com/mockk/mockk/files/2307166/spring-mockmvc-example.zip)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
apply plugin: 'kotlin'
apply plugin: 'kotlin-spring

buildscript {
    ext.kotlinVersion = '1.2.60'
    ext.springBootVersion = '2.0.3.RELEASE'

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
        classpath "org.jetbrains.kotlin:kotlin-allopen:$kotlinVersion"
        classpath "org.springframework.boot:spring-boot-gradle-plugin:$springBootVersion"
    }
}
dependencies {
    implementation "org.springframework.boot:spring-boot-starter-web"
    testImplementation "io.mockk:mockk:1.8.6"
    testImplementation "org.springframework.boot:spring-boot-starter-test"
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
    private val spiedController = spyk(DemoController())
    private lateinit var spiedMockMvc: MockMvc

    @Before
    fun beforeEach() {
        spiedMockMvc = MockMvcBuilders.standaloneSetup(spiedController).build()
    }

    @Test
    fun getOnSpiedController() {
        every { spiedController.greet(any()) } returns "nobody"

        val mvcResult = spiedMockMvc.perform(MockMvcRequestBuilders.get("/demo").param("name", "kt")).andReturn()

        assertEquals(HttpStatus.OK.value(), mvcResult.response.status)
        assertEquals("hello nobody", mvcResult.response.contentAsString)
    }
// -----------------------[ YOUR CODE ENDS ]  -----------------------

**Comment by oleksiyp** [comment]
Thanks for great report

**Comment by oleksiyp** [comment]
I didn't check if it works in detail. Patch just looks good to me. Please confirm that it is fixed on release

**Comment by oleksiyp** [comment]
Version 1.8.7 is released. Sorry for long lead time. Please check if everything is OK

**Comment by rpmcfong** [comment]
Yes, I just confirmed that this is now working as expected. Thank you!
