### ISSUE TITLE
verify/coVerify using "wasNot Called" method throws exception "was not can only be called on a mocked object"

### ISSUE THREAD

**Issue by CharlyRien** [mockk/mockk#1270]
### Expected Behavior

using wasNot Called on a mocked class function should just works fine and not throw exception:

`io.mockk.MockKException: was not can only be called on a mocked object`

### Current Behavior

What is the current behavior?

`io.mockk.MockKException: was not can only be called on a mocked object` 
is thrown since mockk 1.13.11

#### Steps to Reproduce

1. create a junit test
```
class ServiceTest {

    interface Repository {
        fun countBy(ids: Set<Long>): Map<Long, Long>
    }

    class Service(private val repo: Repository) {
        fun countBy(ids: Set<Long>) = if (ids.isEmpty()) {
            emptyMap()
        } else {
            repo.countBy(ids)
        }
    }

    private val repo = mockk<Repository>()
    private val service: Service = Service(repo)

    @Test
    fun `my test`() {
        val countBy = service.countBy(emptySet())

        assert(countBy.isEmpty())

        verify { repo.countBy(any()) wasNot Called }
    }
}
```

#### Context

* MockK version: 1.13.11
* OS: multiple (windows/ macos 14.5 / linux)
* Kotlin version: 2.0.0
* JDK version: 21
* JUnit version: 5.10.2
* Type of test: unit test

#### Stack trace

```
was not can only be called on a mocked object
io.mockk.MockKException: was not can only be called on a mocked object
	at io.mockk.MockKVerificationScope.wasNot(API.kt:2190)
	at io.mockk.MockKVerificationScope.wasNot(API.kt:2175)
	at package.ServiceTest.my_test$lambda$0(ServiceTest.kt:31)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:24)
	at io.mockk.impl.eval.RecordedBlockEvaluator$enhanceWithRethrow$1.invoke(RecordedBlockEvaluator.kt:76)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:39)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalVerify(API.kt:120)
	at io.mockk.MockKKt.verify(MockK.kt:218)
	at io.mockk.MockKKt.verify$default(MockK.kt:209)
	at package.ServiceTest.my test(ServiceTest.kt:31)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
//gradle (kts)
dependencies {
    testImplementation("io.mockk:mockk:1.13.11")
}
// kotlin
package your.package

import io.mockk.Called
import io.mockk.mockk
import io.mockk.verify
import org.junit.jupiter.api.Test

class ServiceTest {

    interface Repository {
        fun countBy(ids: Set<Long>): Map<Long, Long>
    }

    class Service(private val repo: Repository) {
        fun countBy(ids: Set<Long>) = if (ids.isEmpty()) {
            emptyMap()
        } else {
            repo.countBy(ids)
        }
    }

    private val repo = mockk<Repository>()
    private val service: Service = Service(repo)

    @Test
    fun `my test`() {
        val countBy = service.countBy(emptySet())

        assert(countBy.isEmpty())

        verify { repo.countBy(any()) wasNot Called }
    }
}
```

**Comment by AdhamGamal** [comment]
I think we can't use `wasNot Called` with methods, now.

You should use:
`verify(exactly=0) { repo.countBy(any()) }`

`wasNot Called` can be used with a mockk object only like:
`verify { repo wasNot Called }`

to check if the object itself not used in anyway.

**Comment by silentrobi** [comment]
Probably it was broken by [this ](https://github.com/mockk/mockk/pull/1174) fix.

**Comment by CharlyRien** [comment]
Thanks @AdhamGamal, 
works fine now 👍
