### ISSUE TITLE
`verify` throws with supper class methods since version 1.13.11

### ISSUE THREAD

**Issue by matiasvigil** [mockk/mockk#1290]
### Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Expected Behavior

Verify does not throw like previous versions and also verifies the call was made.

### Current Behavior

`verify` throws with supper class methods since version 1.13.11

### Failure Information (for bugs)

`verify` throws with supper class methods since version 1.13.11

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. use version 1.13.11 or 1.13.12
2. mockk a sub class
3. mock supper class method
4. verify supper class method
5. see error when running test

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.13.11 and 1.13.12
* OS: macOS
* Kotlin version: 2.0.10
* JDK version: 17
* Type of test: unit test 

#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
was not can only be called on a mocked object
io.mockk.MockKException: was not can only be called on a mocked object
	at io.mockk.MockKVerificationScope.wasNot(API.kt:2190)
	at io.mockk.MockKVerificationScope.wasNot(API.kt:2175)
	at my.package.my_test_class$lambda$11(MyTestClass.kt:102)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:24)
	at io.mockk.impl.eval.RecordedBlockEvaluator$enhanceWithRethrow$1.invoke(RecordedBlockEvaluator.kt:76)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:39)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalVerify(API.kt:120)
	at io.mockk.MockKKt.verify(MockK.kt:218)
	at io.mockk.MockKKt.verify$default(MockK.kt:209)
	at my.package.test.MyTestClass.my test name(MyTestClass:102)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

**Comment by jghowe** [comment]
I am also seeing this issue since `1.13.11`.

**Comment by snijsure** [comment]
I attempting to upgrade mockk from version 

"1.13.3" to 1.13.16 and I am also getting same error  stack trace looks like this.

```
was not can only be called on a mocked object
io.mockk.MockKException: was not can only be called on a mocked object
	at app//io.mockk.MockKVerificationScope.wasNot(API.kt:2196)
	at app//io.mockk.MockKVerificationScope.wasNot(API.kt:2181)
```

**Comment by sofi-kry** [comment]
Still getting this on version `1.13.17`, any updates?

**Comment by sofi-kry** [comment]
Still the same with version `1.14.6`.
