### ISSUE TITLE
Upgrade to jdk 17 fails mockk with "Can't instantiate proxy for class org.w3c.dom.Document"

### ISSUE THREAD

**Issue by hwdavr** [mockk/mockk#1299]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

Junit test runs the same way as with jdk 11.

### Current Behavior

All Junit test using mockk fails after upgrading to jdk 17.

Steps to Reproduce

### Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

#### Steps to Reproduce

Upgrade from JDK 11 to java 17.
Run the tests that are using mockk and was passing with jdk11.

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.13.12
* OS: macOS Sequoia
* Kotlin version: 1.9.0
* JDK version: 17
* JUnit version: 4.13.1
* Type of test: unit test

#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------

Can't instantiate proxy for class org.w3c.dom.Document
io.mockk.MockKException: Can't instantiate proxy for class org.w3c.dom.Document
	at app//io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:64)
	at app//io.mockk.impl.instantiation.AbstractMockFactory.newProxy$default(AbstractMockFactory.kt:24)
	at app//io.mockk.impl.instantiation.AbstractMockFactory.mockk(AbstractMockFactory.kt:59)
	at app//io.mockk.impl.stub.MockKStub$childMockK$1$1$1.invoke(MockKStub.kt:201)
	at app//io.mockk.impl.stub.MockKStub$childMockK$1$1$1.invoke(MockKStub.kt:200)
	at app//io.mockk.impl.InternalPlatform.customComputeIfAbsent(InternalPlatform.kt:44)
	at app//io.mockk.impl.stub.MockKStub$childMockK$1$1.invoke(MockKStub.kt:200)
	at app//io.mockk.impl.recording.CommonCallRecorder.safeExec(CommonCallRecorder.kt:72)
	at app//io.mockk.impl.log.SafeToString.exec(SafeToString.kt:8)
	at app//io.mockk.impl.stub.MockKStub.childMockK(MockKStub.kt:199)
	at app//io.mockk.impl.recording.PermanentMocker.permamentize(PermanentMocker.kt:48)
	at app//io.mockk.impl.recording.PermanentMocker.mock(PermanentMocker.kt:24)
	at app//io.mockk.impl.recording.states.RecordingState.mockPermanently(RecordingState.kt:123)
	at app//io.mockk.impl.recording.states.RecordingState.round(RecordingState.kt:33)
	at app//io.mockk.impl.recording.CommonCallRecorder.round(CommonCallRecorder.kt:50)
	at app//io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:62)
	at app//io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at app//io.mockk.MockKDsl.internalEvery(API.kt:94)
	at app//io.mockk.MockKKt.every(MockK.kt:143)
	at app//sg.com.singaporepower.spservices.repository.XmlParseRepositoryTest.getBannerSustainability public on success response(XmlParseRepositoryTest.kt:38)
	at java.base@17.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base@17.0.11/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base@17.0.11/java.lang.reflect.Method.invoke(Unknown Source)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at app//org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at app//org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at app//org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at app//org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at app//org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at app//org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:108)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
	at java.base@17.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base@17.0.11/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base@17.0.11/java.lang.reflect.Method.invoke(Unknown Source)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy2/jdk.proxy2.$Proxy5.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: io.mockk.proxy.MockKAgentException: Failed to subclass interface org.w3c.dom.Document
	at app//io.mockk.proxy.jvm.ProxyMaker.proxy(ProxyMaker.kt:42)
	at app//io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:34)
	... 66 more
Caused by: java.lang.IllegalArgumentException: Could not create type
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:170)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:190)
	at io.mockk.proxy.jvm.transformation.SubclassInstrumentation.subclass(SubclassInstrumentation.kt:50)
	at io.mockk.proxy.jvm.ProxyMaker.subclass(ProxyMaker.kt:130)
	at io.mockk.proxy.jvm.ProxyMaker.proxy(ProxyMaker.kt:39)
	... 67 more
Caused by: java.lang.IllegalStateException: Failed to invoke 'privateLookupIn' method from java.lang.invoke.MethodHandles$Lookup.
	at io.mockk.proxy.jvm.ClassLoadingStrategyChooser.chooseClassLoadingStrategy(ClassLoadingStrategyChooser.java:47)
	at io.mockk.proxy.jvm.transformation.SubclassInstrumentation.chooseClassLoadingStrategy(SubclassInstrumentation.kt:101)
	at io.mockk.proxy.jvm.transformation.SubclassInstrumentation.doInterceptedSubclassing(SubclassInstrumentation.kt:97)
	at io.mockk.proxy.jvm.transformation.SubclassInstrumentation.subclass$lambda$0(SubclassInstrumentation.kt:53)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:168)
	... 71 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.mockk.proxy.jvm.ClassLoadingStrategyChooser.chooseClassLoadingStrategy(ClassLoadingStrategyChooser.java:38)
	... 75 more
Caused by: java.lang.IllegalAccessException: module java.xml does not open org.w3c.dom to unnamed module @4e1d422d
	at java.base/java.lang.invoke.MethodHandles.privateLookupIn(Unknown Source)
	... 80 more
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

**Comment by Pscheidl** [comment]
Starting with Java 16, it's not possible to remove private or final modifiers via reflection. And that's exactly what mockk has to do in your case. 

The package must be opened explicitly. There's a JVM arg for this: `--add-opens java.xml/org.w3c.dom=ALL-UNNAMED`. 

Both Gradle and Maven have a way to supply additional JVM args on test start. In case of Gradle, that'd be `task.test.jvmArgs`. 

Adding the flag solves the issue.
