### ISSUE TITLE
Method `every { ... }` doesn't mock, but calls the real method (in case of overloaded methods)

### ISSUE THREAD

**Issue by cbxp** [mockk/mockk#1300]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

I want to mock out the real method, so it should not be called.

### Current Behavior

Mockk calls the real method (which sleeps 5 seconds and throws an fails). 

NB! It happens when the mocked class has 2+ overloaded methods with **parameters of different generic types** (`List<String> ` vs `List<Int>`).

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.13.12
* OS: MacOS
* Kotlin version: 2.0.20
* JDK version: 21
* JUnit version: 5.11.1
* Type of test: unit test

#### Stack trace

```kotlin
java.lang.RuntimeException: Don't call real method from tests ([])!

	at io.github.asolntsev.JustSomeMockkTest$MyService.hello(JustSomeMockkTest.kt:27)
	at io.github.asolntsev.JustSomeMockkTest.usingMockk$lambda$0(JustSomeMockkTest.kt:12)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:24)
	at io.mockk.impl.eval.RecordedBlockEvaluator$enhanceWithRethrow$1.invoke(RecordedBlockEvaluator.kt:76)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:39)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalEvery(API.kt:94)
	at io.mockk.MockKKt.every(MockK.kt:143)
	at io.github.asolntsev.JustSomeMockkTest.usingMockk(JustSomeMockkTest.kt:12)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
dependencies {
  testImplementation("io.mockk:mockk:1.13.12")
  testImplementation("org.assertj:assertj-core:3.26.3")
  testImplementation("org.junit.jupiter:junit-jupiter:5.11.1")
  testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.11.1")
}
```

```kotlin
package io.github.asolntsev

import io.mockk.every
import io.mockk.mockk
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class JustSomeMockkTest {
  @Test fun usingMockk() {
    val service = mockk<MyService>()
    every { service.hello(any<List<String>>()) } returns "Hello"

    assertThat(service.hello(listOf("bob"))).isEqualTo("Hello")
  }

  class MyService {
    fun hello(names: List<String>): String {
      Thread.sleep(5000)
      throw RuntimeException("Don't call real method from tests (${names})!")
    }
    fun hello(ages: List<Int>): List<String> {
      throw RuntimeException("Don't call real method from tests (${ages})!")
    }
  }
}
```

**Comment by nininea** [comment]
have the same issue on junit 4.13.2

`
import io.mockk.MockKAnnotations
import io.mockk.every
import io.mockk.impl.annotations.MockK
import kotlinx.coroutines.test.runTest
import org.junit.Assert
import org.junit.Before
import org.junit.Test

class tests {
    @MockK(relaxed = true)
    lateinit var userSessionManager: UserSessionManager

    @MockK
    lateinit var stringProvider: StringProvider

    @Before
    fun before() {
        println("Before is called")
        MockKAnnotations.init(this)
    }

    @Test
    fun `simple test`() =
        runTest {
            every { userSessionManager.isLoggedIn } returns true
            Assert.assertEquals(userSessionManager.isLoggedIn, true)
        }

}`

assertions is failing in this case and original field is called instead of mockked one

**Comment by ferinagy** [comment]
Hi, we are also seing this with mockk version `1.14.0`. Interestingly, it seems a bit non-deterministic. When I run the test from above:

```kotlin
    @Test fun usingMockk() {
        val service = mockk<MyService>()

        every { service.hello(any<List<String>>()) } returns "Hello"
        assertEquals("Hello", service.hello(listOf("bob")))

        every { service.hello(any<List<Int>>()) } returns listOf("Hello")
        assertEquals(listOf("Hello"), service.hello(listOf(1)))
    }

    class MyService {
        fun hello(names: List<String>): String {
            Thread.sleep(5000)
            throw RuntimeException("Don't call real method1 from tests (${names})!")
        }
        fun hello(ages: List<Int>): List<String> {
            throw RuntimeException("Don't call real method2 from tests (${ages})!")
        }
    }
```
I sometimes see mathod1 failing (after 5s) and sometimes method2 (so first call was mocked without calling real method):
```
Don't call real method1 from tests ([])!
java.lang.RuntimeException: Don't call real method1 from tests ([])!
	at at.beeone.george.insurance.viewmodel.DataProcessingViewModelTest$MyService.hello(DataProcessingViewModelTest.kt:37)
	at at.beeone.george.insurance.viewmodel.DataProcessingViewModelTest.usingMockk$lambda$0(DataProcessingViewModelTest.kt:27)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:24)
	at io.mockk.impl.eval.RecordedBlockEvaluator$enhanceWithRethrow$1.invoke(RecordedBlockEvaluator.kt:76)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:39)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalEvery(API.kt:94)
```
```
Don't call real method2 from tests ([])!
java.lang.RuntimeException: Don't call real method2 from tests ([])!
	at at.beeone.george.insurance.viewmodel.DataProcessingViewModelTest$MyService.hello(DataProcessingViewModelTest.kt:40)
	at at.beeone.george.insurance.viewmodel.DataProcessingViewModelTest.usingMockk$lambda$1(DataProcessingViewModelTest.kt:30)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:24)
	at io.mockk.impl.eval.RecordedBlockEvaluator$enhanceWithRethrow$1.invoke(RecordedBlockEvaluator.kt:76)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:39)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalEvery(API.kt:94)
```
My setup:
MockK version: 1.14.0
OS: MacOS
Kotlin version: 2.1.20
JDK version: 21
JUnit version: 4.13.2
Type of test: unit test

**Comment by bakarJc** [comment]
We had the same issue, for some reason, including the mockito-core dependency fixed it for us:

`<dependency>
    <groupId>org.mockito</groupId>
    <artifactId>mockito-core</artifactId>
    <version>5.17.0</version>
    <scope>test</scope>
</dependency>`

I am not sure but my guess is that Mockk is using some dependency versions that are not jdk 21 compatible yet, and mockito-core brings in the jdk21 compatible version of the same dependencies. It could be something else though

**Comment by marvinelsen** [comment]
We are facing the same issue with `io.mockk:mockk:1.14.5` using JDK21 and Kotlin `2.2.20`. Interestingly, we first started seeing this issue once we updated our [kotest](https://github.com/kotest/kotest) version from `5.9.1` to `6.0.3`. In our case, we are trying to mock a function call chain like this:

```kotlin
every { createSomeObject(any()).getSomeAttribute() } returns 1
```
 
In this scenario the function `createSomeObject()` is called during the `every` invocation. The same code still works with `io.mockk:mockk:1.14.5` and kotest version `5.9.1`.
