### ISSUE TITLE
Need help in verifying a call with a collection parameter

### ISSUE THREAD

**Issue by SchlauFuchs** [mockk/mockk#1301]
### Prerequisites
- A class to spy in that has a method with a collection argument:

```kotlin
    class TestExample
    {
        /**
         * call accepts all kind of collections of Bean
         */
        fun addElements(elements: Collection<Bean>){
            // NO OP
        }
    }

    data class Bean(val id: Int = 0,
                    val name: String = "") {

    }
```

- a test that verifies the call:

```kotlin
import io.mockk.spyk
import io.mockk.verify
import org.junit.jupiter.api.Test

class TestCompare {

    @Test
    fun thisDoesNotWork(){
        // lets spy on the TestExample
        val underTest = spyk(TestExample())

        // putting a bean into a map and then call the test method with the values of the map, to produce a collection
        // of a type I have no control over
        val bean = Bean()
        val payload = mapOf(1 to bean)
        underTest.addElements(payload.values)

        // now verify that the method was called with a bean collection. This will fail as the collections are not 'equal'
        verify { underTest.addElements(listOf(bean)) }

    }
}
```
Demo project is attached.

- (/) I am running the latest version
- (/) I checked the documentation and found no answer
- (/) I checked to make sure that this issue has not already been filed

### Expected Behavior
above test passes

### Current Behavior
above test fails

### Failure Information (for bugs)
Not enough information online how to verify a method call that has an interface parameter

#### Steps to Reproduce
run test on attached example project

#### Context
* MockK version: "1.13.2"
* OS: Windows 11
* Kotlin version: 2.0.20
* JDK version: 17
* JUnit version: Jupiter
* Type of test: unit test 

#### Stack trace
```
Verification failed: call 1 of 1: TestExample(#1).addElements(eq([Bean(id=0, name=)]))). Only one matching call to TestExample(#1)/addElements(Collection) happened, but arguments are not matching:
[0]: argument: [Bean(id=0, name=)], matcher: eq([Bean(id=0, name=)]), result: -

Stack trace:
                                                                                   io.mockk.impl.InternalPlatform.captureStackTrace            (InternalPlatform.kt:125)                          
                                                                                     io.mockk.impl.stub.MockKStub.handleInvocation             (MockKStub.kt:255)                                 
                                                   io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation                   (JvmMockFactoryHelper.kt:24)                       
                                                                            io.mockk.proxy.jvm.advice.Interceptor.call                         (Interceptor.kt:21)                                
                                                                                          TestCompare$TestExample.addElements                  (TestCompare.kt:18)                                
                                                                                                      TestCompare.thisDoesNotWork              (TestCompare.kt:30)                                
                                                                    jdk.internal.reflect.NativeMethodAccessorImpl.invoke0                      (NativeMethodAccessorImpl.java:-2)N                
                                                                    jdk.internal.reflect.NativeMethodAccessorImpl.invoke                       (NativeMethodAccessorImpl.java:77)                 
                                                                jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke                       (DelegatingMethodAccessorImpl.java:43)             
                                                                                         java.lang.reflect.Method.invoke                       (Method.java:568)                                  
                                                                  org.junit.platform.commons.util.ReflectionUtils.invokeMethod                 (ReflectionUtils.java:728)                         
                                                              org.junit.jupiter.engine.execution.MethodInvocation.proceed                      (MethodInvocation.java:60)                         
                               org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed                      (InvocationInterceptorChain.java:131)              
                                                              org.junit.jupiter.engine.extension.TimeoutExtension.intercept                    (TimeoutExtension.java:156)                        
                                                              org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod      (TimeoutExtension.java:147)                        
                                                              org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod          (TimeoutExtension.java:86)                         
                       org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0        (InterceptingExecutableInvoker.java:103)           
                                                 org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0              (InterceptingExecutableInvoker.java:93)            
                              org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed                      (InvocationInterceptorChain.java:106)              
                                                    org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed                      (InvocationInterceptorChain.java:64)               
                                                    org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke               (InvocationInterceptorChain.java:45)               
                                                    org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke                       (InvocationInterceptorChain.java:37)               
                                                 org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke                       (InterceptingExecutableInvoker.java:92)            
                                                 org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke                       (InterceptingExecutableInvoker.java:86)            
                                                     org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7    (TestMethodTestDescriptor.java:218)                
                                                org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute                      (ThrowableCollector.java:73)                       
                                                     org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod             (TestMethodTestDescriptor.java:214)                
                                                     org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute                      (TestMethodTestDescriptor.java:139)                
                                                     org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute                      (TestMethodTestDescriptor.java:69)                 
                                                      org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6  (NodeTestTask.java:151)                            
                                                org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute                      (ThrowableCollector.java:73)                       
                                                      org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8  (NodeTestTask.java:141)                            
                                                              org.junit.platform.engine.support.hierarchical.Node.around                       (Node.java:137)                                    
                                                      org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9  (NodeTestTask.java:139)                            
                                                org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute                      (ThrowableCollector.java:73)                       
                                                      org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively           (NodeTestTask.java:138)                            
                                                      org.junit.platform.engine.support.hierarchical.NodeTestTask.execute                      (NodeTestTask.java:95)                             
                                                                                              java.util.ArrayList.forEach                      (ArrayList.java:1511)                              
                         org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll                    (SameThreadHierarchicalTestExecutorService.java:41)
                                                      org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6  (NodeTestTask.java:155)                            
                                                org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute                      (ThrowableCollector.java:73)                       
                                                      org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8  (NodeTestTask.java:141)                            
                                                              org.junit.platform.engine.support.hierarchical.Node.around                       (Node.java:137)                                    
                                                      org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9  (NodeTestTask.java:139)                            
                                                org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute                      (ThrowableCollector.java:73)                       
                                                      org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively           (NodeTestTask.java:138)                            
                                                      org.junit.platform.engine.support.hierarchical.NodeTestTask.execute                      (NodeTestTask.java:95)                             
                                                                                              java.util.ArrayList.forEach                      (ArrayList.java:1511)                              
                         org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll                    (SameThreadHierarchicalTestExecutorService.java:41)
                                                      org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6  (NodeTestTask.java:155)                            
                                                org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute                      (ThrowableCollector.java:73)                       
                                                      org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8  (NodeTestTask.java:141)                            
                                                              org.junit.platform.engine.support.hierarchical.Node.around                       (Node.java:137)                                    
                                                      org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9  (NodeTestTask.java:139)                            
                                                org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute                      (ThrowableCollector.java:73)                       
                                                      org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively           (NodeTestTask.java:138)                            
                                                      org.junit.platform.engine.support.hierarchical.NodeTestTask.execute                      (NodeTestTask.java:95)                             
                         org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit                       (SameThreadHierarchicalTestExecutorService.java:35)
                                          org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute                      (HierarchicalTestExecutor.java:57)                 
                                            org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute                      (HierarchicalTestEngine.java:54)                   
                                                     org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute                      (EngineExecutionOrchestrator.java:198)             
                                                     org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute                      (EngineExecutionOrchestrator.java:169)             
                                                     org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute                      (EngineExecutionOrchestrator.java:93)              
                                                     org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0             (EngineExecutionOrchestrator.java:58)              
                                                     org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams       (EngineExecutionOrchestrator.java:141)             
                                                     org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute                      (EngineExecutionOrchestrator.java:57)              
                                                                 org.junit.platform.launcher.core.DefaultLauncher.execute                      (DefaultLauncher.java:103)                         
                                                                 org.junit.platform.launcher.core.DefaultLauncher.execute                      (DefaultLauncher.java:85)                          
                                                              org.junit.platform.launcher.core.DelegatingLauncher.execute                      (DelegatingLauncher.java:47)                       
org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses        (JUnitPlatformTestClassProcessor.java:119)         
org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000                   (JUnitPlatformTestClassProcessor.java:94)          
                              org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop                         (JUnitPlatformTestClassProcessor.java:89)          
                                                    org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop                         (SuiteTestClassProcessor.java:62)                  
                                                                    jdk.internal.reflect.NativeMethodAccessorImpl.invoke0                      (NativeMethodAccessorImpl.java:-2)N                
                                                                    jdk.internal.reflect.NativeMethodAccessorImpl.invoke                       (NativeMethodAccessorImpl.java:77)                 
                                                                jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke                       (DelegatingMethodAccessorImpl.java:43)             
                                                                                         java.lang.reflect.Method.invoke                       (Method.java:568)                                  
                                                                  org.gradle.internal.dispatch.ReflectionDispatch.dispatch                     (ReflectionDispatch.java:36)                       
                                                                  org.gradle.internal.dispatch.ReflectionDispatch.dispatch                     (ReflectionDispatch.java:24)                       
                                                          org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch                     (ContextClassLoaderDispatch.java:33)               
                                   org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke                       (ProxyDispatchAdapter.java:94)                     
                                                                                               jdk.proxy1.$Proxy2.stop                         (-:-1)                                             
                                                        org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run                          (TestWorker.java:193)                              
                                                          org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName (TestWorker.java:129)                              
                                                          org.gradle.api.internal.tasks.testing.worker.TestWorker.execute                      (TestWorker.java:100)                              
                                                          org.gradle.api.internal.tasks.testing.worker.TestWorker.execute                      (TestWorker.java:60)                               
                                                   org.gradle.process.internal.worker.child.ActionExecutionWorker.execute                      (ActionExecutionWorker.java:56)                    
                                      org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call                         (SystemApplicationClassLoaderWorker.java:119)      
                                      org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call                         (SystemApplicationClassLoaderWorker.java:66)       
                                                       worker.org.gradle.process.internal.worker.GradleWorkerMain.run                          (GradleWorkerMain.java:69)                         
                                                       worker.org.gradle.process.internal.worker.GradleWorkerMain.main                         (GradleWorkerMain.java:74)                         
java.lang.AssertionError: Verification failed: call 1 of 1: TestExample(#1).addElements(eq([Bean(id=0, name=)]))). Only one matching call to TestExample(#1)/addElements(Collection) happened, but arguments are not matching:
[0]: argument: [Bean(id=0, name=)], matcher: eq([Bean(id=0, name=)]), result: -

Stack trace:
                                                                                   io.mockk.impl.InternalPlatform.captureStackTrace            (InternalPlatform.kt:125)                          
                                                                                     io.mockk.impl.stub.MockKStub.handleInvocation             (MockKStub.kt:255)                                 
                                                   io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation                   (JvmMockFactoryHelper.kt:24)                       
                                                                            io.mockk.proxy.jvm.advice.Interceptor.call                         (Interceptor.kt:21)                                
                                                                                          TestCompare$TestExample.addElements                  (TestCompare.kt:18)                                
                                                                                                      TestCompare.thisDoesNotWork              (TestCompare.kt:30)                                
                                                                    jdk.internal.reflect.NativeMethodAccessorImpl.invoke0                      (NativeMethodAccessorImpl.java:-2)N                
                                                                    jdk.internal.reflect.NativeMethodAccessorImpl.invoke                       (NativeMethodAccessorImpl.java:77)                 
                                                                jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke                       (DelegatingMethodAccessorImpl.java:43)             
                                                                                         java.lang.reflect.Method.invoke                       (Method.java:568)                                  
                                                                  org.junit.platform.commons.util.ReflectionUtils.invokeMethod                 (ReflectionUtils.java:728)                         
                                                              org.junit.jupiter.engine.execution.MethodInvocation.proceed                      (MethodInvocation.java:60)                         
                               org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed                      (InvocationInterceptorChain.java:131)              
                                                              org.junit.jupiter.engine.extension.TimeoutExtension.intercept                    (TimeoutExtension.java:156)                        
                                                              org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod      (TimeoutExtension.java:147)                        
                                                              org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod          (TimeoutExtension.java:86)                         
                       org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0        (InterceptingExecutableInvoker.java:103)           
                                                 org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0              (InterceptingExecutableInvoker.java:93)            
                              org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed                      (InvocationInterceptorChain.java:106)              
                                                    org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed                      (InvocationInterceptorChain.java:64)               
                                                    org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke               (InvocationInterceptorChain.java:45)               
                                                    org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke                       (InvocationInterceptorChain.java:37)               
                                                 org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke                       (InterceptingExecutableInvoker.java:92)            
                                                 org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke                       (InterceptingExecutableInvoker.java:86)            
                                                     org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7    (TestMethodTestDescriptor.java:218)                
                                                org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute                      (ThrowableCollector.java:73)                       
                                                     org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod             (TestMethodTestDescriptor.java:214)                
                                                     org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute                      (TestMethodTestDescriptor.java:139)                
                                                     org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute                      (TestMethodTestDescriptor.java:69)                 
                                                      org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6  (NodeTestTask.java:151)                            
                                                org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute                      (ThrowableCollector.java:73)                       
                                                      org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8  (NodeTestTask.java:141)                            
                                                              org.junit.platform.engine.support.hierarchical.Node.around                       (Node.java:137)                                    
                                                      org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9  (NodeTestTask.java:139)                            
                                                org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute                      (ThrowableCollector.java:73)                       
                                                      org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively           (NodeTestTask.java:138)                            
                                                      org.junit.platform.engine.support.hierarchical.NodeTestTask.execute                      (NodeTestTask.java:95)                             
                                                                                              java.util.ArrayList.forEach                      (ArrayList.java:1511)                              
                         org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll                    (SameThreadHierarchicalTestExecutorService.java:41)
                                                      org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6  (NodeTestTask.java:155)                            
                                                org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute                      (ThrowableCollector.java:73)                       
                                                      org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8  (NodeTestTask.java:141)                            
                                                              org.junit.platform.engine.support.hierarchical.Node.around                       (Node.java:137)                                    
                                                      org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9  (NodeTestTask.java:139)                            
                                                org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute                      (ThrowableCollector.java:73)                       
                                                      org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively           (NodeTestTask.java:138)                            
                                                      org.junit.platform.engine.support.hierarchical.NodeTestTask.execute                      (NodeTestTask.java:95)                             
                                                                                              java.util.ArrayList.forEach                      (ArrayList.java:1511)                              
                         org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll                    (SameThreadHierarchicalTestExecutorService.java:41)
                                                      org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6  (NodeTestTask.java:155)                            
                                                org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute                      (ThrowableCollector.java:73)                       
                                                      org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8  (NodeTestTask.java:141)                            
                                                              org.junit.platform.engine.support.hierarchical.Node.around                       (Node.java:137)                                    
                                                      org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9  (NodeTestTask.java:139)                            
                                                org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute                      (ThrowableCollector.java:73)                       
                                                      org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively           (NodeTestTask.java:138)                            
                                                      org.junit.platform.engine.support.hierarchical.NodeTestTask.execute                      (NodeTestTask.java:95)                             
                         org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit                       (SameThreadHierarchicalTestExecutorService.java:35)
                                          org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute                      (HierarchicalTestExecutor.java:57)                 
                                            org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute                      (HierarchicalTestEngine.java:54)                   
                                                     org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute                      (EngineExecutionOrchestrator.java:198)             
                                                     org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute                      (EngineExecutionOrchestrator.java:169)             
                                                     org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute                      (EngineExecutionOrchestrator.java:93)              
                                                     org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0             (EngineExecutionOrchestrator.java:58)              
                                                     org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams       (EngineExecutionOrchestrator.java:141)             
                                                     org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute                      (EngineExecutionOrchestrator.java:57)              
                                                                 org.junit.platform.launcher.core.DefaultLauncher.execute                      (DefaultLauncher.java:103)                         
                                                                 org.junit.platform.launcher.core.DefaultLauncher.execute                      (DefaultLauncher.java:85)                          
                                                              org.junit.platform.launcher.core.DelegatingLauncher.execute                      (DelegatingLauncher.java:47)                       
org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses        (JUnitPlatformTestClassProcessor.java:119)         
org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000                   (JUnitPlatformTestClassProcessor.java:94)          
                              org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop                         (JUnitPlatformTestClassProcessor.java:89)          
                                                    org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop                         (SuiteTestClassProcessor.java:62)                  
                                                                    jdk.internal.reflect.NativeMethodAccessorImpl.invoke0                      (NativeMethodAccessorImpl.java:-2)N                
                                                                    jdk.internal.reflect.NativeMethodAccessorImpl.invoke                       (NativeMethodAccessorImpl.java:77)                 
                                                                jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke                       (DelegatingMethodAccessorImpl.java:43)             
                                                                                         java.lang.reflect.Method.invoke                       (Method.java:568)                                  
                                                                  org.gradle.internal.dispatch.ReflectionDispatch.dispatch                     (ReflectionDispatch.java:36)                       
                                                                  org.gradle.internal.dispatch.ReflectionDispatch.dispatch                     (ReflectionDispatch.java:24)                       
                                                          org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch                     (ContextClassLoaderDispatch.java:33)               
                                   org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke                       (ProxyDispatchAdapter.java:94)                     
                                                                                               jdk.proxy1.$Proxy2.stop                         (-:-1)                                             
                                                        org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run                          (TestWorker.java:193)                              
                                                          org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName (TestWorker.java:129)                              
                                                          org.gradle.api.internal.tasks.testing.worker.TestWorker.execute                      (TestWorker.java:100)                              
                                                          org.gradle.api.internal.tasks.testing.worker.TestWorker.execute                      (TestWorker.java:60)                               
                                                   org.gradle.process.internal.worker.child.ActionExecutionWorker.execute                      (ActionExecutionWorker.java:56)                    
                                      org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call                         (SystemApplicationClassLoaderWorker.java:119)      
                                      org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call                         (SystemApplicationClassLoaderWorker.java:66)       
                                                       worker.org.gradle.process.internal.worker.GradleWorkerMain.run                          (GradleWorkerMain.java:69)                         
                                                       worker.org.gradle.process.internal.worker.GradleWorkerMain.main                         (GradleWorkerMain.java:74)                         
	at io.mockk.impl.recording.states.VerifyingState.failIfNotPassed(VerifyingState.kt:63)
	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:42)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:64)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalVerify(API.kt:119)
	at io.mockk.MockKKt.verify(MockK.kt:149)
	at io.mockk.MockKKt.verify$default(MockK.kt:140)
	at TestCompare.thisDoesNotWork(TestCompare.kt:33)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

```
 
[mockk-collection-validation.zip](https://github.com/user-attachments/files/17220153/mockk-collection-validation.zip)

**Comment by Raibaz** [comment]
When you call `verify`, you should not use actual objects for parameters, but rather matchers for the type you are asserting your metod is being called with.

So, your `verify` block should look like this: `verify { underTest.addElements(any<Collection>()) }`

You can also do assertions on the content of the collection being passed: for instance, you could use a slot to [capture](https://mockk.io/#capturing) the collection and then assert that it has size 1.

**Comment by SchlauFuchs** [comment]
I was looking into capturing now and found this workaround:
```kotlin
verify { underTest.addElements(
              withArg<Collection<Bean>> { 
             // validating the collection content myself here
    }
}
```
While this works, it needs quite a few more lines than necessary. But we can keep this closed
