### ISSUE TITLE
Version 1.13.13 breaks mocks declared in companion objects

### ISSUE THREAD

**Issue by rolgalan** [mockk/mockk#1318]
### Expected Behavior

A minor library bump should not contain significant behavioral changes hidden in the release notes that break the update in the clients.

### Current Behavior

Update from version 1.13.12 to 1.13.13 now [run unmockkAll after each JUnit 5 test](https://github.com/mockk/mockk/pull/1297).

This breaks **any statically declared mock at class level**, which is a pattern followed by some developers to overcome the performance overhead of mocks declaration.

#### Steps to Reproduce

1. Declare any mock in a static way at class level (inside a companion object) 
2. Define two tests
3. Run them

The static mock will be cleared up after the first test is finished due to `io.mockk.MockKException: no answer found for <Class.method()> among the configured answers: ()`, so the second test will fail.

Check the reproducible example at the bottom for more details.

#### Context

**The goal to open this ticket is to bring bigger visibility about this issue and guidance to solve it**, as I do not expect a new version required to solve this. However I would kindly ask to mockk maintainers to be more explicit about this in the release notes, so anyone updating to this version will have more clarity about this problem and knows what to expect.

#### How to solve it in clients code

This can be solved by **moving the mocked objects to be declared at instance level**, but then you will pay the performance initialization after each test, which might not be accepted by some teams.

Alternatively this can be solved by applying the changing the junit 5 [Test Instance lifecycle](https://junit.org/junit5/docs/current/user-guide/#writing-tests-test-instance-lifecycle) from the default _per method_ to _per class_ by adding `@TestInstance(Lifecycle.PER_CLASS)` to the test class. This will fix most of the cases, however if the class is also declaring some instance level mocks, these will require to be reset after each test with a `@BeforeEach` (or refactor the test).

#### Failure Logs

Please include any relevant log snippets or files here.

#### Stack trace

```
no answer found for ComplexClass(#1).one() among the configured answers: ()
io.mockk.MockKException: no answer found for ComplexClass(#1).one() among the configured answers: ()
	at app//io.mockk.impl.stub.MockKStub.defaultAnswer(MockKStub.kt:93)
	at app//io.mockk.impl.stub.MockKStub.answer(MockKStub.kt:44)
	at app//io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:16)
	at app//io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)
	at app//io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:271)
	at app//io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:25)
	at app//io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:21)
```

#### Minimal reproducible code (the gist of this issue)

In the below example `aaa` will finish successfully, whereas `aab` will fail.

```kotlin
import io.mockk.every
import io.mockk.mockk
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class BreakingChange {

    @Test
    fun `aaa`() {
        assertEquals(1, complexClass.one())
    }

    @Test
    fun `aab`() {
        assertEquals(1, complexClass.one())
    }

    companion object {
        private val complexClass = mockk<ComplexClass> {
            every { one() } returns 1
        }
    }
}

class ComplexClass() {
    fun one() = 1
}
```

**Comment by Ufkoku** [comment]
It also messes with parametrized tests

```
@ParameterizedTest
@MethodSource("provideAvailableTestData")
```

**Comment by cloudshiftchris** [comment]
It also breaks parallel tests.  https://github.com/mockk/mockk/issues/1329

**Comment by kmayoral** [comment]
> No changes required here, closing as it already provides a workaround.

Can you clarify the workaround please?
