### ISSUE TITLE
Unable to verify lambda that takes a data class as an argument

### ISSUE THREAD

**Issue by sarimmehdi** [mockk/mockk#1322]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Expected Behavior

Test should run

### Current Behavior

Test fails

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.13.13
* OS: Ubuntu 24.04.1 LTS
* Kotlin version: 2.0.21
* JDK version: 17
* JUnit version: 5.11.2
* Type of test: unit test

#### Stack trace
```
Receiver class kotlin.reflect.KClass$Subclass0 does not define or inherit an implementation of the resolved method 'abstract boolean isValue()' of interface kotlin.reflect.KClass.
java.lang.AbstractMethodError: Receiver class kotlin.reflect.KClass$Subclass0 does not define or inherit an implementation of the resolved method 'abstract boolean isValue()' of interface kotlin.reflect.KClass.
	at io.mockk.impl.recording.JvmSignatureValueGenerator.signatureValue(JvmSignatureValueGenerator.kt:19)
	at io.mockk.impl.recording.states.RecordingState.matcher(RecordingState.kt:46)
	at io.mockk.impl.recording.CommonCallRecorder.matcher(CommonCallRecorder.kt:52)
	at io.mockk.MockKMatcherScope.match(API.kt:695)
	at io.mockk.MockKMatcherScope.any(API.kt:745)
	at com.sarim.puzzle.data.usecase.DummyTest.dummy_test_to_show_issue_with_mockk$lambda$2(DummyTest.kt:14)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:24)
	at io.mockk.impl.eval.RecordedBlockEvaluator$enhanceWithRethrow$1.invoke(RecordedBlockEvaluator.kt:76)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:39)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalVerify(API.kt:120)
	at io.mockk.MockKKt.verify(MockK.kt:218)
	at io.mockk.MockKKt.verify$default(MockK.kt:209)
	at com.sarim.puzzle.data.usecase.DummyTest.dummy test to show issue with mockk(DummyTest.kt:13)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
```
#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
junitVersion = "5.11.2"

junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junitVersion" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junitVersion" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junitVersion" }

testImplementation(libs.junit.jupiter.api)
testRuntimeOnly(libs.junit.jupiter.engine)
testImplementation(libs.junit.jupiter.params)
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
import io.mockk.verify
import org.junit.jupiter.api.Test

class DummyTest {

    @Test
    fun `dummy test to show issue with mockk`() {
        val lambdaFunc: (SomeDataClass) -> Unit = { }
        dummyFunc(lambdaFunc)

        verify(exactly = 1) {
            lambdaFunc(any<SomeDataClass>(any()))     // using lambdaFunc(any<SomeDataClass>(any<AnotherDataClass>())) gives Argument type mismatch error
        }
    }
}

data class AnotherDataClass(val arg1: String, val arg2: String)

sealed class SomeSealedClass {
    data class SomeDataClass(val anotherDataClass: AnotherDataClass): SomeSealedClass()
}

fun dummyFunc(
    onEvent: (SomeDataClass) -> Unit
) {
    onEvent(SomeDataClass(AnotherDataClass("arg1", "arg2")))
}
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by sarimmehdi** [comment]
I was finally able to solve this issue and posted my answer here: https://stackoverflow.com/questions/22507447/verify-if-inherited-super-class-method-was-called-from-method-being-tested-or-no
