### ISSUE TITLE
verifying private method was called through public method fails

### ISSUE THREAD

**Issue by wfeng-fsde** [mockk/mockk#139]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Expected Behavior

I have a customized data class object and I'm passing it to a private method when I call a public method. I expect to verify that the private method is called.

### Current Behavior

The verification says that the private method was never called. See the minimal working example.

### Failure Information (for bugs)

See the description of the error message

#### Steps to Reproduce

see the minimal working example

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.8.6
* OS: macOS High Sierra version 10.13.6
* Kotlin version: 1.2.60
* JDK version: 1.8
* JUnit version: 4
* Type of test: unit test

#### Failure Logs

```doing something: MyData(type=GOOD)

java.lang.AssertionError: Verification failed: call 1 of 1: Foo(#1).doSomethingPrivate(any())) was not called.

Calls to same mock:
1) Foo(#1).doSomething()
```

#### Stack trace

```
1)                                 io.mockk.impl.InternalPlatform.captureStackTrace      (InternalPlatform.kt:123)             
                                     io.mockk.impl.stub.MockKStub.handleInvocation       (MockKStub.kt:192)                    
   io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation             (JvmMockFactoryHelper.kt:23)          
                            io.mockk.proxy.jvm.advice.Interceptor.call                   (Interceptor.kt:20)                   
                           com.salesforceiq.graph.gdpr.MyTest$Foo.doSomething            (DataSubjectDeleteTest.kt:163)        
                               com.salesforceiq.graph.gdpr.MyTest.testFoo                (DataSubjectDeleteTest.kt:173)        
                             sun.reflect.NativeMethodAccessorImpl.invoke0                (NativeMethodAccessorImpl.java:-2)N   
                             sun.reflect.NativeMethodAccessorImpl.invoke                 (NativeMethodAccessorImpl.java:62)    
                         sun.reflect.DelegatingMethodAccessorImpl.invoke                 (DelegatingMethodAccessorImpl.java:43)
                                         java.lang.reflect.Method.invoke                 (Method.java:498)                     
                        org.junit.runners.model.FrameworkMethod$1.runReflectiveCall      (FrameworkMethod.java:50)             
              org.junit.internal.runners.model.ReflectiveCallable.run                    (ReflectiveCallable.java:12)          
                          org.junit.runners.model.FrameworkMethod.invokeExplosively      (FrameworkMethod.java:47)             
               org.junit.internal.runners.statements.InvokeMethod.evaluate               (InvokeMethod.java:17)                
                                   org.junit.runners.ParentRunner.runLeaf                (ParentRunner.java:325)               
                         org.junit.runners.BlockJUnit4ClassRunner.runChild               (BlockJUnit4ClassRunner.java:78)      
                         org.junit.runners.BlockJUnit4ClassRunner.runChild               (BlockJUnit4ClassRunner.java:57)      
                                 org.junit.runners.ParentRunner$3.run                    (ParentRunner.java:290)               
                                 org.junit.runners.ParentRunner$1.schedule               (ParentRunner.java:71)                
                                   org.junit.runners.ParentRunner.runChildren            (ParentRunner.java:288)               
                                   org.junit.runners.ParentRunner.access$000             (ParentRunner.java:58)                
                                 org.junit.runners.ParentRunner$2.evaluate               (ParentRunner.java:268)               
                                   org.junit.runners.ParentRunner.run                    (ParentRunner.java:363)               
                                       org.junit.runner.JUnitCore.run                    (JUnitCore.java:137)                  
                         com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs    (JUnit4IdeaTestRunner.java:68)        
          com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs    (IdeaTestRunner.java:47)              
                     com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart (JUnitStarter.java:242)               
                     com.intellij.rt.execution.junit.JUnitStarter.main                   (JUnitStarter.java:70)                

	at io.mockk.impl.recording.states.VerifyingState.failIfNotPassed(VerifyingState.kt:63)
	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:41)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:42)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:48)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:27)
	at io.mockk.MockKDsl.internalVerify(API.kt:119)
	at io.mockk.MockKKt.verify(MockK.kt:139)
	at io.mockk.MockKKt.verify$default(MockK.kt:136)
	at com.salesforceiq.graph.gdpr.MyTest.testFoo(DataSubjectDeleteTest.kt:174)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


Process finished with exit code 255

```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    testCompile group: 'org.apache.kafka', name: 'kafka_2.12', version: '1.1.0'
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
class MyTest {
    enum class MyType {
        GOOD,
        BAD
    }
    data class MyData(val type: MyType)

    class Foo {
        fun doSomething() : Boolean {
            val t = MyData(MyType.GOOD)
            doSomethingPrivate(t)
            return true
        }
        private fun doSomethingPrivate(data: MyData) {
            println("doing something: $data")
        }
    }

    @Test
    fun testFoo() {
        val foo = spyk(Foo())
        foo.doSomething()
        verify { foo["doSomethingPrivate"](any<MyData>()) }
    }

}
```

**Comment by wfeng-fsde** [comment]
nvm, I need to set `recordPrivateCalls` to `true` in order for this to work.
