### ISSUE TITLE
Feature: More explicit error needed for undeclared 'every'

### ISSUE THREAD

**Issue by dave08** [mockk/mockk#141]
### Expected Behavior

A proper error should be given to help the user know what's wrong. In this case, for some reason the `every`s didn't get declared before the `verifyAll` checked it. If not possible, maybe even an (optional) dump of the current mock state of that object would be extremely helpful for debugging such problems.

### Current Behavior

This is the error I got:
```
io.mockk.MockKException: Bad recording sequence. State: AnsweringState
    at io.mockk.impl.recording.states.CallRecordingState.cancelAndThrowBadRecordingState(CallRecordingState.kt:30)
    at io.mockk.impl.recording.states.CallRecordingState.estimateCallRounds(CallRecordingState.kt:20)
    at io.mockk.impl.recording.CommonCallRecorder.estimateCallRounds(CommonCallRecorder.kt:50)
    at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:38)
    at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:27)
    at io.mockk.MockKDsl.internalVerify(API.kt:119)
    at io.mockk.MockKDsl.internalVerify$default(API.kt:110)
    at io.mockk.MockKDsl.internalVerifyAll(API.kt:193)
    at io.mockk.MockKKt.verifyAll(MockK.kt:187)
    at io.mockk.MockKKt.verifyAll$default(MockK.kt:184)
```

### Failure Information (for bugs)

Using the Kodein module:
```
        private val TestModule = Kodein.Module("Test") {
            bind() from multiton { packageName: String ->
                mockk<SharedPreferences>().apply {
                    every { edit().putStringSet(any(), any()).apply() } just Runs
                    every { edit().putString(any(), any()).apply() } just Runs
                }
            }
        }
```
And the Spek test:
```
class SomeTest : Spek({
      val kodein by memoized { Kodein { import(TestModule) } }

     	val prefsProvider by kodein.factory<String, SharedPreferences>()

    it("should do something") {
         verifyAll {
            prefsProvider("settingsFile").edit().putString("ns.setting1", "value").apply()
            prefsProvider("settingsFile")
                    .edit().putStringSet("ns.setting1", setOf("set", "of", "things")).apply()
        }
   }
})

It was solved by putting the `every` in `beforeEachTest` block.

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.8.6
* OS: Linux Mint 18
* Kotlin version: 1.2.61
* JDK version: 7
* JUnit version: I think 4 (whatever Spek uses with junitPlatformTest)
* Type of test: unit test

**Comment by Raibaz** [comment]
The exception that is thrown now explicitly mentions the function that was lacking an answer. I think this can be closed.
