### ISSUE TITLE
Instrumentation Tests below Android P

### ISSUE THREAD

**Issue by daveteal** [mockk/mockk#148]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Expected Behavior

According to documentation, mockk can be used in Android Instrumented (Espresso) tests.  It should be able to mock objects, and be able to pass into the application context.

### Current Behavior

Running tests fail to return back mock objects via module.

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.8.7
* OS: Windows - Android 5.1.1
* Kotlin version: Latest
* JDK version: 8
* Type of test: android instrumented test

#### Stack trace

```
java.lang.AssertionError
at com.android.dx.DexMaker.generateClassLoader(DexMaker.java:385)
at com.android.dx.DexMaker.generateAndLoad(DexMaker.java:434)
at com.android.dx.stock.ProxyBuilder.buildProxyClass(ProxyBuilder.java:304)
at io.mockk.proxy.android.transformation.AndroidSubclassInstrumentation.subclass(AndroidSubclassInstrumentation.kt:21)
at io.mockk.proxy.common.ProxyMaker.subclass(ProxyMaker.kt:140)
at io.mockk.proxy.common.ProxyMaker.proxy(ProxyMaker.kt:60)
at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:34)
at io.mockk.impl.instantiation.AbstractMockFactory.newProxy$default(AbstractMockFactory.kt:27)
at io.mockk.impl.instantiation.AbstractMockFactory.mockk(AbstractMockFactory.kt:45)
at com.package.mockModules.MockServiceModule.returnServiceObject(MockServiceModule.kt:27)
at com.package.espressoTest.preSteps(espressoTest.kt:41)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at android.support.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:76)
at android.support.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:527)
at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at android.support.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:101)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:384)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1853)
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
@Module
open class ServiceModule {
    // ServiceObject is an open class due to being less than Android P
    @Provides
    @Singleton
    open fun returnServiceObject() : ServiceObject = ServiceObject()
}

class MockServiceModule : ServiceModule () {
    override fun returnServiceObject() : ServiceObject = mockk(relaxed = true)
}

// In Tests
. . . 
@Before
fun preSteps() {
  val mockModule = MockServiceModule ()
  val mockServiceObject= mockModule.returnServiceObject()

  coEvery { mockServiceObject.discoverService(any(), any()) } returns mockk()

 // Set up mock application component with mockModule
   
}
```

**Comment by tmurakami** [comment]
@oleksiyp you cannot call `ProxyBuilder#withSharedClassLoader`on pre-Nougat devices.
Calling it will invoke `BaseDexClassLoader#addDexPath` which does not exist on pre-Nougat.

**Comment by oleksiyp** [comment]
@tmurakami thanks

**Comment by michaelbukachi** [comment]
So what is the current available solution to the above issue?

**Comment by klemenk161** [comment]
@tmurakami is there anything I can do to bypass this? Since I updated from mockk 1.8.0, all my pre-P test fail with this exact error.

**Comment by tmurakami** [comment]
Unfortunately, there seems to be no workaround other than using mockk 1.8.0.

In the version 1.8.0, `ProxyBuilder#withSharedClassLoader` won't be called if `classTransformer` is null.
https://github.com/mockk/mockk/blob/1.8/agent/android/src/main/java/io/mockk/proxy/android/AndroidMockKProxyMaker.java#L151-L194
According to the following code, `classTransformer` will be null on pre-P devices.
https://github.com/mockk/mockk/blob/1.8/agent/android/src/main/java/io/mockk/proxy/android/AndroidMockKAgentFactory.java#L93-L118
Thus, this error won't occur in that version.

However, in 1.8.1, the above condition seems to be missing.
https://github.com/mockk/mockk/blob/1.8.1/agent/android/src/main/kotlin/io/mockk/proxy/android/transformation/AndroidSubclassInstrumentation.kt#L15-L24
This code has not been changed until now, so this error will occur even in the latest version.

**Comment by oleksiyp** [comment]
Seems it is not only the issue happening with pre Android-P mocking. `onlyMethods` is not correct to apply in this case. I need to spend more time testing and fixing it

**Comment by tmurakami** [comment]
On pre-P devices that cannot enable inline mocking, MockK needs to generate a proxy class with non-final functions including abstract functions. However, since the `getMethodsToProxy` function returns only the abstract methods of the original class, the proxy class won't implement non-final functions. Thus, I think that stubbing a non-final function will fail on pre-P devices.

To avoid this, simply do not call `onlyMethods` on pre-P devices, as implemented in version 1.8.

**Comment by oleksiyp** [comment]
I fixed both issues and now releasing new version

**Comment by oleksiyp** [comment]
Please check version 1.8.12 or 1.8.12.kotlin13

**Comment by oleksiyp** [comment]
Fixed. Closing because of no activity
