### ISSUE TITLE
Stubing a function that returns "Nothing" throws a NullPointerException

### ISSUE THREAD

**Issue by raverona** [mockk/mockk#158]
### Expected Behavior

I expected that I would be able to stub, that is, define the behavior of a function, from a mocked class, that returns the Kotlin class `Nothing` using `every { ... }`.

### Current Behavior

the `every` block throws a `NullPointerException`.

### Failure Information (for bugs)

It doesn't make a difference if you use `throws` or an `answers` block after the `every` block.

#### Steps to Reproduce

1. Create a class with a method that returns the class `Nothing` from Kotlin
2. Create a test class and use `mockk()` to mock the class you created on step 1
3. Create a JUnit test method and stub the method you created on step 1 with an `every` block inside it
4. Run your test

#### Context

* MockK version: 1.8.9
* OS: Ubuntu 18.04.1
* Kotlin version: 1.2.71
* JDK version: 1.8
* JUnit version: 4.12
* Type of test: unit test

#### Stack trace

```
java.lang.NullPointerException
	at myMockkTest.TestClassTest$testMockk$1.invoke(TestClassTest.kt:18)
	at myMockkTest.TestClassTest$testMockk$1.invoke(TestClassTest.kt:13)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:22)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:31)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:25)
	at io.mockk.MockKDsl.internalEvery(API.kt:93)
	at io.mockk.MockKKt.every(MockK.kt:104)
	at myMockkTest.TestClassTest.testMockk(TestClassTest.kt:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
    testCompile group: 'io.mockk', name: 'mockk', version: '1.8.9'
    classpath group: 'org.jetbrains.kotlin', name: 'kotlin-gradle-plugin', version: '1.2.71'
    compile group: 'org.jetbrains.kotlin', name: 'kotlin-stdlib-jdk8'
    compile group: 'org.jetbrains.kotlin', name: 'kotlin-reflect'
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
package myMockkTest

import io.mockk.every
import io.mockk.mockk
import org.junit.Test

class TestClass {
    fun alwaysThrows() : Nothing {
        throw RuntimeException("this can be any exception")
    }
}

class TestClassTest {
    val targetClass = mockk<TestClass>()

    @Test
    fun testMockk() {
        every { targetClass.alwaysThrows() } answers {
            throw IllegalArgumentException("this is a test")
        }
    }
}
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by oleksiyp** [comment]
So the situation is following. Code after Nothing should never be executed. Because of synthetic nature of method calls in `every { ... }` block it returns from fake `alwaysThrows`. Just right after such call Kotlin compiler inserts "throw null" which gives us NPE.

![npe_on_nothing](https://user-images.githubusercontent.com/5249932/47312743-73443880-d63d-11e8-83c8-49fb79a1577d.png)

Thinking about what can be done here. It is definitelly not possible to mock such call (as Kotlin compiler does not allow to do that), warning on Nothing or forbidding it may be an option

**Comment by Kerooker** [comment]
Would it be possible to create a specific every { } just for Nothing return type? Then instead of expecting it to return something, we could assume it's Nothing when () -> Nothing is the stubbed method

**Comment by oleksiyp** [comment]
It is quite hard to mock even with the special construct. The only possible way is to catch NPE, read stack and detect it is happening inside `every {...}` block and continue operation. I am not aware of any other approach. Kind of hack

**Comment by Kerooker** [comment]
Pretty hackish hahah

Do you think this is an issue with Kotlin itself? I mean, should this be possible within the language?

**Comment by oleksiyp** [comment]
It is just a corner case of mocking. Mocking itself is a pretty magical thing working on a bytecode level, so this is just one of such aspects that breaks the contract of language.

**Comment by oleksiyp** [comment]
Fixed the way that if NPE is catched it checks if last call had Nothing as a returnType and skip this NPE. As I said it is a hack

**Comment by oleksiyp** [comment]
Please verify the fix in version 1.8.11 or 1.8.11.kotlin13

**Comment by raverona** [comment]
Awesome, will test today

**Comment by oleksiyp** [comment]
Closing because of no activity
