### ISSUE TITLE
java.lang.IllegalAccessError on version 1.8.10.kotlin13 when trying to mock private functions with parameters

### ISSUE THREAD

**Issue by YawaraNes** [mockk/mockk#165]
I was trying to integrate this library for my Unit Tests when I started to obtain the following error:

```
java.lang.IllegalAccessError: tried to access method kotlin.collections.ArraysKt___ArraysJvmKt.copyOfRange([Ljava/lang/Object;II)[Ljava/lang/Object; from class kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance

	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:217)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:106)
	at io.mockk.InternalPlatformDsl.dynamicCall(InternalPlatformDsl.kt:124)
	at io.mockk.MockKMatcherScope$DynamicCall.invoke(API.kt:1717)
	at com.farmapremium.elmo.diskdatasource.DiskDataSourceImplTest$storeFile() must not call save() method when the InputStream is null and must return an empty String$1.invoke(DiskDataSourceImplTest.kt:74)
	at com.farmapremium.elmo.diskdatasource.DiskDataSourceImplTest$storeFile() must not call save() method when the InputStream is null and must return an empty String$1.invoke(DiskDataSourceImplTest.kt:12)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:22)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:31)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:25)
	at io.mockk.MockKDsl.internalEvery(API.kt:93)
	at io.mockk.MockKKt.every(MockK.kt:104)
	at com.farmapremium.elmo.diskdatasource.DiskDataSourceImplTest.storeFile() must not call save() method when the InputStream is null and must return an empty String(DiskDataSourceImplTest.kt:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


Process finished with exit code 255
```

I put here the steps to reproduce extracted from the example on the docs (https://mockk.io/#private-functions-mocking--dynamic-calls):

```
        class Car {
            fun drive() = accelerate(108)

            private fun accelerate(power: Int) = "going faster"
        }

        val mock = spyk<Car>()

        every { mock["accelerate"](108) } returns "going not so fast"

        assert(mock.drive() == "going not so fast")
```

If I run it with version `1.8.10`, it works.
If I run it with version `1.8.10.kotlin13`, it does not work.

It seems that only affects to private functions with parameters (maybe it helps).

**Comment by oleksiyp** [comment]
What version of Kotlin are you using in this cases?

**Comment by YawaraNes** [comment]
Oops... I thought I was using Kotlin version `1.3.0` but I was using `1.2.71`. Upgrading it solved the issue.

Sorry about that! And thanks for helping me realizing it.
