### ISSUE TITLE
Bug: cannot throw a checked exception when stubbing an interface function with no @Throws

### ISSUE THREAD

**Issue by tmurakami** [mockk/mockk#169]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

Just as with the JVM version, MockK should be able to throw a checked exception for any interface function on Android.

### Current Behavior

`java.lang.reflect.UndeclaredThrowableException` is thrown.

#### Context

* MockK version: 1.8.11
* Kotlin version: 1.2.71 and 1.3.0
* JDK version: Open JDK 11.0.1
* JUnit version: 4.12
* Type of test: Android Instrumented Test (On Android 9 Pie emulators)

#### Stack trace

```
java.lang.Exception: Unexpected exception, expected<com.example.mockktest.MyException> but was<java.lang.reflect.UndeclaredThrowableException>
at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:384)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
Caused by: java.lang.reflect.UndeclaredThrowableException
at $Proxy2.doIt(Unknown Source)
at com.example.mockktest.MyTest.test(MyTest.kt:18)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
... 22 more
Caused by: com.example.mockktest.MyException
at com.example.mockktest.MyTest.test(MyTest.kt:17)
... 28 more
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
package com.example.mockktest

import io.mockk.every
import io.mockk.mockk
import org.junit.Test

interface Foo {
    fun doIt()
}

class MyException : Exception()

class MyTest {
    @Test(expected = MyException::class)
    fun test() {
        val mock = mockk<Foo>()
        every { mock.doIt() } throws MyException()
        mock.doIt()
    }
}

```

On JVM, this code works well.

### Reason

A proxy generated by `java.lang.reflect.Proxy` cannot throw a checked exception that is not declared with `throws` clause of the interface method.

**Comment by tmurakami** [comment]
Dexmaker 2.21.0, which is fixed to correctly implement the interface, has been released.
https://github.com/linkedin/dexmaker/releases/tag/2.21.0
Since proxies generated by Dexmaker can throw any checked exception, this issue could be closed by using that.

**Comment by gerardoeg** [comment]
Have anyone found a work-around for this?

**Comment by gerardoeg** [comment]
Update: seems like the issue is only present on an emulator android 14, it worked on Android 13 physical, I hope this might help someone else.
