### ISSUE TITLE
[Android] An error 'No answer found...' occurs when mocking an interface on pre-L

### ISSUE THREAD

**Issue by tmurakami** [mockk/mockk#170]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

The specified answer should be executed.
See the reproducible code below.

### Current Behavior

An error `No answer found...` occurs even though an answer is set.
This issue will only occur when mocking an interface on pre-Lollipop devices.

#### Context

* MockK version: 1.8.12.kotlin13
* Kotlin version: 1.3.0
* JDK version: Open JDK 11.0.1
* Type of test: Android Instrumented Test (On pre-L, API < 21)

#### Stack trace

```
io.mockk.MockKException: no answer found for: Callable(#1).call()
at io.mockk.impl.stub.MockKStub.defaultAnswer(MockKStub.kt:94)
at io.mockk.impl.stub.MockKStub.answer(MockKStub.kt:46)
at io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:15)
at io.mockk.impl.recording.states.AnsweringStillAcceptingAnswersState.call(AnsweringStillAcceptingAnswersState.kt:16)
at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:48)
at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:223)
at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:23)
at io.mockk.proxy.common.ProxyInvocationHandler.invoke(ProxyInvocationHandler.kt:36)
at $Proxy2.call(Native Method)
at com.example.mockktest.MyTest.test(MyTest.kt:14)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:388)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
package com.example.mockktest

import io.mockk.every
import io.mockk.mockk
import org.junit.Assert.assertEquals
import org.junit.Test
import java.util.concurrent.Callable

class MyTest {
    @Test
    fun test() {
        val mock = mockk<Callable<String>>()
        every { mock.call() } returns "test"
        assertEquals("test", mock.call())
    }
}
```

### Reason

https://github.com/mockk/mockk/blob/1.8.12.kotlin13/dsl/common/src/main/kotlin/io/mockk/API.kt#L3337
I think both names should be tested by `!=`, not `!==`.

On pre-L devices, the following code will fail.

```kotlin
package com.example.mockktest

import org.junit.Assert.assertEquals
import org.junit.Test
import java.lang.reflect.Proxy
import java.util.IdentityHashMap

class ProxyTest {
    @Test
    fun test() {
        val names = IdentityHashMap<String, Nothing>()
        val proxy = Proxy.newProxyInstance(
            javaClass.classLoader,
            arrayOf(Runnable::class.java)
        ) { _, method, _ ->
            names[method.name] = null
            null
        } as Runnable
        proxy.run()
        proxy.run()
        // On pre-L, this line will fail because two `method.name`s aren't the same reference.
        assertEquals(1, names.keys.size)
    }
}
```

MockK-Android uses `java.lang.reflect.Proxy` to generate a proxy of an interface, and a `MethodDescription` is generated from the `java.lang.reflect.Method` object which is an argument of `ProxyInvocationHandler`. Therefore, comparing two `MethodDescription`s of the same interface method will always fail on those devices.

**Comment by oleksiyp** [comment]
Thank you for the report

**Comment by oleksiyp** [comment]
It is `!==` because of the following comment in `Method` class in JDK8.
Unfortunately, it is not a public contract.

```
    // This is guaranteed to be interned by the VM in the 1.4
    // reflection implementation
    private String              name;
```

**Comment by oleksiyp** [comment]
`v1.8.13` or `v1.8.13.kotlin13` is out. Please check if it can be closed

**Comment by tmurakami** [comment]
I confirmed that it has been fixed.
Thank you.
