### ISSUE TITLE
Bug: safe call operator throws a class cast exception on relaxed mock of suspending function.

### ISSUE THREAD

**Issue by laurencegw** [mockk/mockk#174]
### Expected Behavior

Expecting safe call operator `?` to work on a mockk with a suspending function. For example:

    myMock?.suspendingFunction()

This is only if you use `relaxed=true` and you do not explicitly mock the suspending function.

### Current Behavior

An exception is thrown. Trace below.

Workaround is to explicitly stub the function in the mock.

#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
09:58:06.850 [main] DEBUG io.mockk.impl.instantiation.AbstractMockFactory - Creating mockk for MyClass name=#1, moreInterfaces=[]
09:58:08.829 [main] DEBUG io.mockk.impl.instantiation.AbstractMockFactory - Creating mockk for Any name=child of #1#2, moreInterfaces=[]
09:58:09.558 [main] DEBUG io.mockk.impl.recording.states.AnsweringState - Answering Any(child of #1#2) on MyClass(#1).doSomething(lambda {})
Exception in thread "main" java.lang.ClassCastException: net.bytebuddy.renamed.java.lang.Object$ByteBuddy$TQXmKWMf$ByteBuddy$cOMbH44C cannot be cast to kotlin.Unit
	at finova.marketmaker.core.bots.bot.PlaygroundKt$main$1.invokeSuspend(playground.kt:21)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask$DefaultImpls.run(Dispatched.kt:235)
	at kotlinx.coroutines.DispatchedContinuation.run(Dispatched.kt:81)
	at kotlinx.coroutines.EventLoopBase.processNextEvent(EventLoop.kt:123)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:45)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:35)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

val kotlinVersion = "1.3.0"
val kotlinXVersion = "1.0.0"
val junitJupiterVersion = "5.2.0"
val ktorVersion = "1.0.0-beta-3"
val koinVersion = "1.0.1"
val http4kVersion = "3.100.0"

plugins {
    java
    kotlin("jvm") version "1.3.0"
}

repositories {
    maven { setUrl("http://dl.bintray.com/kotlin/kotlin-eap") }
    maven { setUrl("https://dl.bintray.com/kotlin/ktor") }
    maven { setUrl("https://dl.bintray.com/ekito/koin") }
    maven { setUrl("http://jcenter.bintray.com") }
    mavenCentral()
    jcenter()
}

dependencies {
    compile(kotlin("stdlib-jdk8"))
    compile("org.jetbrains.kotlin", "kotlin-reflect", kotlinVersion)
    compile("org.jetbrains.kotlinx", "kotlinx-coroutines-core", kotlinXVersion)

    //Test
    testCompile("io.ktor", "ktor-server-test-host", ktorVersion)
    testCompile("org.junit.jupiter", "junit-jupiter-api", junitJupiterVersion)
    testImplementation("io.mockk", "mockk", "1.8.12.kotlin13")
    testRuntime("org.junit.jupiter", "junit-jupiter-engine", junitJupiterVersion)
}

configure<JavaPluginConvention> {
    sourceCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "1.8"
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
import io.mockk.mockk
import kotlinx.coroutines.runBlocking

class MyClass {
    suspend fun doSomething() {

    }
}

fun main(args: Array<String>) {
    runBlocking {
        val myMock: MyClass = mockk(relaxed = true)

        var myPossiblyNullInstance: MyClass? = null

        myPossiblyNullInstance = myMock

        myPossiblyNullInstance?.doSomething()
    }
}
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by oleksiyp** [comment]
Thanks for the report. Seems very weird to me. Safe call should just call in case it is non-null. But here we have class cast. Need to reproduce and check bytecode.

**Comment by laurencegw** [comment]
Cool - digging the framework by the way. Just flipped to it. Good job.

**Comment by oleksiyp** [comment]
To sum up, this happening because Kotlin reflection is buggy. https://youtrack.jetbrains.com/issue/KT-13077

MockK has few workarounds here and there to overcome this, besides that it uses Java reflection in most cases and Kotlin one only as a secondary source of information.

**Comment by oleksiyp** [comment]
Versions 1.9 & 1.9.kotlin12 were released with this change included. Please check it and close the ticket if everything is OK.

**Comment by laurencegw** [comment]
Just upgraded to 1.9 and used a relaxed mock of a suspending function. All good. Thanks. And once again - great project.
