### ISSUE TITLE
Bug: parentheses in test name leads to failing test

### ISSUE THREAD

**Issue by pauldingemans** [mockk/mockk#179]
### Expected Behavior

The name of a test should not have impact on the test results.

### Current Behavior

A test for which the name between the backticks contains a pair of parentheses leads to a failing test. For example removing the closing parentheses makes the test succeed again.

#### Steps to Reproduce

Run given example. One test will fail, the other succeeds although the content of the test method is identical.

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.8.13.kotlin13
* OS: MacOs Mojave
* Kotlin version: 1.3
* JDK version: 1.8.0_172
* JUnit version: 5.3.1
* Type of test: unit test

#### Stack trace

The failing tests produces following output:
```

java.lang.VerifyError: Inconsistent stackmap frames at branch target 116
Exception Details:
  Location:
    com/bol/swaps/contentstatus/api/detail/MyClassTest$Some name including parentheses (some text)$1.invokeSuspend(Ljava/lang/Object;)Ljava/lang/Object; @94: if_acmpne
  Reason:
    Current frame's stack size doesn't match stackmap.
  Current Frame:
    bci: @94
    flags: { }
    locals: { 'com/bol/swaps/contentstatus/api/detail/MyClassTest$Some name including parentheses (some text)$1', 'java/lang/Object', 'kotlinx/coroutines/CoroutineScope', 'java/lang/Object' }
    stack: { 'java/lang/Object', 'java/lang/Object', 'java/lang/Object' }
  Stackmap Frame:
    bci: @116
    flags: { }
    locals: { 'com/bol/swaps/contentstatus/api/detail/MyClassTest$Some name including parentheses (some text)$1', 'java/lang/Object', top, 'java/lang/Object' }
    stack: { 'java/lang/Object', 'java/lang/Object' }
  Bytecode:
    0x0000000: b800 1f4e 2ab4 0023 aa00 0000 0000 0079
    0x0000010: 0000 0000 0000 0001 0000 0018 0000 005b
    0x0000020: 2b59 c100 2599 000a c000 25b4 0029 bf57
    0x0000030: 2ab4 002b 4dbb 002d 592a 01b7 0031 c000
    0x0000040: 07b8 0037 04b8 003d b600 4357 2ab4 0047
    0x0000050: b600 4d2a 2a04 b500 23b6 0053 592d a600
    0x0000060: 162d b02b 59c1 0025 9900 0ac0 0025 b400
    0x0000070: 29bf 572b c000 55b6 0059 b800 5fb2 0065
    0x0000080: b0bb 0067 5912 69b7 006c bf            
  Stackmap Table:
    append_frame(@32,Top,Object[#113])
    same_locals_1_stack_item_frame(@47,Object[#113])
    same_frame(@99)
    same_locals_1_stack_item_frame(@114,Object[#113])
    full_frame(@116,{Object[#2],Object[#113],Top,Object[#113]},{Object[#113],Object[#113]})
    same_frame(@129)


	at com.bol.swaps.contentstatus.api.detail.MyClassTest.Some name including parentheses (some text)$contentstatus_app(MyClassTest.kt:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:515)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:171)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:105)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:110)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:110)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

```

#### Minimal reproducible code (the gist of this issue)

```kotlin
package com.bol.swaps.contentstatus.api.detail

import io.mockk.clearMocks
import io.mockk.coEvery
import io.mockk.mockk
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withContext
import org.junit.Assert.assertTrue
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test

class MyClass {
    suspend fun someSuspendingFunction() = withContext(Dispatchers.Default) { false }
}

class MyClassTest {
    val myClass = mockk<MyClass>()

    @BeforeEach
    fun setUp() {
        clearMocks(myClass)
    }

    // Failing test
    @Test
    internal fun `Some name including parentheses (some text)`() = runBlocking {
        coEvery {
            myClass.someSuspendingFunction()
        } returns true

        assertTrue(myClass.someSuspendingFunction())
    }

    // Test succeeds
    @Test
    internal fun `Some name not including parentheses`() = runBlocking {
        coEvery {
            myClass.someSuspendingFunction()
        } returns true

        assertTrue(myClass.someSuspendingFunction())
    }
}
```

**Comment by oleksiyp** [comment]
Thanks for the report

**Comment by oleksiyp** [comment]
Not clear right now if it is related to MockK at all. Stack trace suggests it got stuck somewhere in JUnit 5
