### ISSUE TITLE
Method mocking not working below Android P (API 28)

### ISSUE THREAD

**Issue by RiccardoM** [mockk/mockk#181]
### Expected Behavior
The mocks initialized inside Android instrumented tests are working properly on pre Android P devices..

### Current Behavior
The mocks initialized inside Android are not working at all. Instead a semi-mock with full-working methods is created without respecting the mock declarations. 

#### Steps to Reproduce

1. Assume we have a Java class that is defined as follows inside a library ([ThirtyInchMVP](https://github.com/grandcentrix/ThirtyInch))

```java
public abstract class TiPresenter<V extends TiView> {
    @VisibleForTesting final List<TiLifecycleObserver> mLifecycleObservers = new ArrayList<>();

    @RestrictTo(SUBCLASSES)
    public void sendToView(final ViewAction<V> action) {
        final V view = getView();
        if (view != null) {
            runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    action.call(view);
                }
            });
        } else {
            mPostponedViewActions.add(action);
        }
    }
}
```

2. Also, assume we have the following extension function
```kotlin
@SuppressLint("RestrictedApi")
fun <V : TiView> TiPresenter<V>.deliverToView(block: V.() -> Unit) = sendToView { block(it) }
```

3. We create an instance of the presenter

```kotlin
class MainPresenter @Inject constructor(): TiPresenter<MainView>() {

    fun homeClicked() {
        deliverToView { showMessage(MainView.Message.HELLO_WORLD) }
    }

    fun dashboardClicked() {
        deliverToView { showMessage(MainView.Message.THIS_IS_A_TESTABLE_APP) }
    }

    fun notificationsClicked() {
        deliverToView { showMessage(MainView.Message.HAPPY_TESTING) }
    }

}
```

4. We define an utility extension function, used to mock any instance of `TiPresenter`
```kotlin
inline fun <reified P : TiPresenter<*>> mockPresenter(block: P.() -> Unit = {}): P {
    return mockk(relaxed = true, relaxUnitFun = true, block = block).apply {
        every { state } returns TiPresenter.State.INITIALIZED
        every { config } returns TiConfiguration.DEFAULT
    }
}
```

5. We test the presenter

```kotlin
class ExampleInstrumentedTest {
    private val presenterMock = mockPresenter<MainPresenter> {
        every { homeClicked() } just runs
        every { dashboardClicked() } just runs
        every { notificationsClicked() } just runs
    }

    @Test fun test() {
        presenterMock.homeClicked()
        verify { presenterMock.homeClicked() }
    }

}
```

6. Try running this test inside a Pre-Android P device or emulator, and the test will fail with the stacktrace present below. The stacktrace explicitly tells that `mPostponedViewActions.add(action);`, present in the `else` branch inside the `sendToView` method, cannot be invoked on a null object. This means that the `sendToView` method is not mocked, and the real method is called instead. It also tells that the presenter is not a new object, otherwise the field would have been initialized. It looks like a sort of semi-mock with no initialization but fully working methods.
  Running it on an Android P device or emulator, however, makes it pass.  
  I've tested the running on an Android O (API 27) emulator, an Android L (API 21) OnePlus One and an Android P (API 28) emulator.

#### Context
* MockK version: 1.8.13-kotlin13
* OS: Windows 10
* Kotlin version: 1.3.0
* JDK version: 1.8.0
* JUnit version: 4.12
* Type of test: Android instrumented test

#### Stack trace
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.concurrent.LinkedBlockingQueue.add(java.lang.Object)' on a null object reference
at net.grandcentrix.thirtyinch.TiPresenter.sendToView(TiPresenter.java:411)
at net.grandcentrix.thirtyinch.kotlin.TiPresenterKt.deliverToView(TiPresenter.kt:21)
at it.riccardomontagnin.testablemvpapp.presenter.MainPresenter.homeClicked(MainPresenter.kt:14)
at it.riccardomontagnin.testablemvpapp.ExampleInstrumentedTest$presenterMock$1$1.invoke(ExampleInstrumentedTest.kt:24)
at it.riccardomontagnin.testablemvpapp.ExampleInstrumentedTest$presenterMock$1$1.invoke(ExampleInstrumentedTest.kt:21)
at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:24)
at io.mockk.impl.eval.RecordedBlockEvaluator$enhanceWithNPERethrow$1.invoke(RecordedBlockEvaluator.kt:74)
at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:36)
at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:25)
at io.mockk.MockKDsl.internalEvery(API.kt:93)
at io.mockk.MockKKt.every(MockK.kt:104)
at it.riccardomontagnin.testablemvpapp.ExampleInstrumentedTest.<init>(ExampleInstrumentedTest.kt:24)
at java.lang.reflect.Constructor.newInstance(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:384)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1853)
```

#### Minimal reproducible code (the gist of this issue)

```gradle
dependencies {
    // ThirtyInch MVP
    def thirtyinchVersion = '0.9.0'
    implementation "net.grandcentrix.thirtyinch:thirtyinch:$thirtyinchVersion"
    implementation "net.grandcentrix.thirtyinch:thirtyinch-kotlin:$thirtyinchVersion"

    // MockK
    def mockkVersion = "1.8.12.kotlin13"
    testImplementation "io.mockk:mockk:$mockkVersion"
    androidTestImplementation "io.mockk:mockk-android:$mockkVersion"
}
```

A full, not-working example code is present at [this Github repo](https://github.com/RiccardoM/TestableMVPApp).

**Comment by oleksiyp** [comment]
Thank you for so detailed report

**Comment by Spheniscine** [comment]
I think this issue is related to #182 , which suggests a workaround: open the classes and functions/properties under test.
