### ISSUE TITLE
every/verify {} block were run several times. Recorded calls count differ between runs 

### ISSUE THREAD

**Issue by easazade** [mockk/mockk#203]
### What i want to achieve :
i want to mock the behavior of a spy object.
this is the test i run :
```kotlin

@Test
    fun test6() {
        val repo = mockk<IDesignsDataSource>()
        val wallpaperHandler = mockk<WallpaperHandler>()
        val viewModel = DesignsViewModel(repo, wallpaperHandler, Schedulers.trampoline(), Schedulers.trampoline())
        val spyVm = spy(viewModel)
        every { spyVm.getAllPosts(1) } answers {
            spyVm.getAllPostTask.progress.accept(true)
            spyVm.getAllPostTask.progress.accept(false)
            spyVm.getAllPostTask.success.accept(result)
        }
        spyVm.getAllPosts(1)
        verify {
            spyVm.getAllPostTask.progress.accept(true)
            spyVm.getAllPostTask.progress.accept(false)
            spyVm.getAllPostTask.success.accept(result)
        }

    }

```

### What i get (Error) :
```
io.mockk.MockKException: every/verify {} block were run several times. Recorded calls count differ between runs
Round 1: IDesignsDataSource(#1).getAllItems(1), Observable(temporary mock).subscribeOn(io.reactivex.internal.schedulers.TrampolineScheduler@1db7157f), Observable(temporary mock).observeOn(io.reactivex.internal.schedulers.TrampolineScheduler@1db7157f), Observable(temporary mock).subscribe(ir.alirezaisazade.mars.viewmodels.DesignsViewModel$getAllPosts$1@138aa3cc, ir.alirezaisazade.mars.viewmodels.DesignsViewModel$getAllPosts$2@10a98392), Disposable(temporary mock).hashCode()
Round 2: IDesignsDataSource(#1).getAllItems(1), Observable(temporary mock).subscribeOn(io.reactivex.internal.schedulers.TrampolineScheduler@1db7157f), Observable(temporary mock).observeOn(io.reactivex.internal.schedulers.TrampolineScheduler@1db7157f), Observable(temporary mock).subscribe(ir.alirezaisazade.mars.viewmodels.DesignsViewModel$getAllPosts$1@56382bc9, ir.alirezaisazade.mars.viewmodels.DesignsViewModel$getAllPosts$2@591a4f8e), Disposable(temporary mock).hashCode(), Disposable(temporary mock).equals(Disposable(temporary mock))

	at io.mockk.impl.recording.SignatureMatcherDetector$detect$1.invoke(SignatureMatcherDetector.kt:25)
	at io.mockk.impl.recording.SignatureMatcherDetector.detect(SignatureMatcherDetector.kt:86)
	at io.mockk.impl.recording.states.RecordingState.signMatchers(RecordingState.kt:38)
	at io.mockk.impl.recording.states.RecordingState.round(RecordingState.kt:30)
	at io.mockk.impl.recording.CommonCallRecorder.round(CommonCallRecorder.kt:45)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:59)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:25)
	at io.mockk.MockKDsl.internalEvery(API.kt:93)
	at io.mockk.MockKKt.every(MockK.kt:104)
	at ir.alirezaisazade.mars.TestTest.test6(TestTest.kt:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)


Process finished with exit code -1

```

**Comment by easazade** [comment]
and for what its worth I think it is much better library than Mockito

**Comment by oleksiyp** [comment]
Right.  If it is fixed, please close the ticket
