### ISSUE TITLE
An error 'No answer found...' when mocking interface with lamdba argument

### ISSUE THREAD

**Issue by tomdevroomen** [mockk/mockk#208]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

### Expected Behavior

When defining an `every` when the mocked call has lambda argument it works in both ways
With this interface:
`interface JsonRepository {  
    fun saveAsJson(entity: Any, idSupplier: () -> UUID): JsonEntity  
}`

I'd expect mocking notations should have the same result when mocking a lamdba argument
`every { saveAsJson(any(), any() } answers { value }`
should do the same as
`every { saveAsJson(any()) { any() } } answers { value }`

### Current Behavior

```kotlin
    every { saveAsJson(any()) { any() } } answers { value }
``` 
will result in a 
`io.mockk.MockKException: no answer found for: JsonRepository(#1).saveAsJson(object, lambda {})`

#### Steps to Reproduce

See code

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.8.13.kotlin13
* OS: macOS 10.14.1
* Kotlin version: 1.3.10
* JDK version: jdk-10.0.2
* JUnit version: Kotlin-test 3.1.11
* Type of test: Unit test with ShouldSpec

#### Stack trace

```
13:47:13.249 [kotlintest-engine-0] DEBUG io.mockk.impl.recording.states.AnsweringStillAcceptingAnswersState - Answering JsonStorage(#1) on JsonStorage(#1).toString()
13:47:13.250 [kotlintest-engine-0] DEBUG io.mockk.impl.recording.states.AnsweringStillAcceptingAnswersState - Throwing io.mockk.MockKException: no answer found for: JsonStorage(#1).saveAsJson(Entity(id=7c86185b-6f75-41a9-b3d8-593d2ba1d004), lambda {}) on JsonStorage(#1).saveAsJson(Entity(id=7c86185b-6f75-41a9-b3d8-593d2ba1d004), lambda {})
13:47:13.254 [kotlintest-engine-0] DEBUG io.kotlintest.runner.junit5.JUnitTestRunnerListener - completeTestCase Description(parents=[MockingShouldWork, Mocking should result in the same behaviour], name=should work) with result TestResult(status=Error, error=io.mockk.MockKException: no answer found for: JsonStorage(#1).saveAsJson(Entity(id=7c86185b-6f75-41a9-b3d8-593d2ba1d004), lambda {}), reason=null, metaData={})
13:47:13.255 [kotlintest-engine-0] DEBUG io.kotlintest.runner.junit5.JUnitTestRunnerListener - completeTestCase Description(parents=[MockingShouldWork], name=Mocking should result in the same behaviour) with result TestResult(status=Success, error=null, reason=null, metaData={})
13:47:13.256 [kotlintest-engine-0] DEBUG io.kotlintest.runner.junit5.JUnitTestRunnerListener - completeSpec [Description(parents=[], name=MockingShouldWork)]
13:47:13.260 [kotlintest-engine-0] DEBUG io.kotlintest.runner.junit5.JUnitTestRunnerListener - Notifying junit of test case completion [engine:kotlintest]/[spec:MockingShouldWork]/[test:Mocking should result in the same behaviour]/[test:should work]=TestResult(status=Error, error=io.mockk.MockKException: no answer found for: JsonStorage(#1).saveAsJson(Entity(id=7c86185b-6f75-41a9-b3d8-593d2ba1d004), lambda {}), reason=null, metaData={})

io.mockk.MockKException: no answer found for: JsonStorage(#1).saveAsJson(Entity(id=7c86185b-6f75-41a9-b3d8-593d2ba1d004), lambda {})

	at io.mockk.impl.stub.MockKStub.defaultAnswer(MockKStub.kt:95)
	at io.mockk.impl.stub.MockKStub.answer(MockKStub.kt:48)
	at io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:16)
	at io.mockk.impl.recording.states.AnsweringStillAcceptingAnswersState.call(AnsweringStillAcceptingAnswersState.kt:16)
	at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:48)
	at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:224)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:24)
	at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:20)
	at io.mockk.proxy.jvm.advice.BaseAdvice.handle(BaseAdvice.kt:42)
	at io.mockk.proxy.jvm.advice.jvm.JvmMockKProxyInterceptor.interceptNoSuper(JvmMockKProxyInterceptor.java:45)
	at io.floriday.pdfgeneratorapi.integration.JsonStorage$ByteBuddy$zahk5t5V.saveAsJson(Unknown Source)
	at io.floriday.pdfgeneratorapi.integration.MockingShouldWork$3$1.invoke(MockingShouldWork.kt:32)
	at io.floriday.pdfgeneratorapi.integration.MockingShouldWork$3$1.invoke(MockingShouldWork.kt:9)
	at io.kotlintest.runner.jvm.TestSetExecutor.execute(TestSetExecutor.kt:40)
	at io.kotlintest.runner.jvm.TestCaseExecutor.executeTestIfActive(TestCaseExecutor.kt:69)
	at io.kotlintest.runner.jvm.TestCaseExecutor.access$executeTestIfActive(TestCaseExecutor.kt:14)
	at io.kotlintest.runner.jvm.TestCaseExecutor$execute$3.invoke(TestCaseExecutor.kt:43)
	at io.kotlintest.runner.jvm.TestCaseExecutor.execute(TestCaseExecutor.kt:53)
	at io.kotlintest.runner.jvm.SharedInstanceSpecRunner$callingThreadContext$1.registerTestCase(SharedInstanceSpecRunner.kt:29)
	at io.kotlintest.TestContext.registerTestCase(TestContext.kt:41)
	at io.kotlintest.specs.AbstractShouldSpec$ShouldScope.should(AbstractShouldSpec.kt:69)
	at io.floriday.pdfgeneratorapi.integration.MockingShouldWork$3.invoke(MockingShouldWork.kt:29)
	at io.floriday.pdfgeneratorapi.integration.MockingShouldWork$3.invoke(MockingShouldWork.kt:9)
	at io.kotlintest.specs.AbstractShouldSpec$invoke$1.invoke(AbstractShouldSpec.kt:35)
	at io.kotlintest.specs.AbstractShouldSpec$invoke$1.invoke(AbstractShouldSpec.kt:28)
	at io.kotlintest.runner.jvm.TestSetExecutor.execute(TestSetExecutor.kt:40)
	at io.kotlintest.runner.jvm.TestCaseExecutor.executeTestIfActive(TestCaseExecutor.kt:69)
	at io.kotlintest.runner.jvm.TestCaseExecutor.access$executeTestIfActive(TestCaseExecutor.kt:14)
	at io.kotlintest.runner.jvm.TestCaseExecutor$execute$3.invoke(TestCaseExecutor.kt:43)
	at io.kotlintest.runner.jvm.TestCaseExecutor.execute(TestCaseExecutor.kt:53)
	at io.kotlintest.runner.jvm.SharedInstanceSpecRunner$execute$1.invoke(SharedInstanceSpecRunner.kt:14)
	at io.kotlintest.runner.jvm.SharedInstanceSpecRunner$execute$1.invoke(SharedInstanceSpecRunner.kt:8)
	at io.kotlintest.runner.jvm.SpecRunner$interceptSpec$chain$1.invoke(SpecRunner.kt:36)
	at io.kotlintest.runner.jvm.SpecRunner$interceptSpec$chain$1.invoke(SpecRunner.kt:11)
	at io.kotlintest.runner.jvm.SpecRunner.interceptSpec(SpecRunner.kt:37)
	at io.kotlintest.runner.jvm.SharedInstanceSpecRunner.execute(SharedInstanceSpecRunner.kt:11)
	at io.kotlintest.runner.jvm.TestEngine.executeSpec(TestEngine.kt:110)
	at io.kotlintest.runner.jvm.TestEngine.access$executeSpec(TestEngine.kt:15)
	at io.kotlintest.runner.jvm.TestEngine$submitSpec$1.run(TestEngine.kt:90)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    testImplementation("io.mockk:mockk:1.8.13.kotlin13")
    testImplementation("io.kotlintest:kotlintest-runner-junit5:3.1.11")
    testImplementation("io.kotlintest:kotlintest-extensions-spring:3.1.11")
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
package io.floriday.pdfgeneratorapi.integration

import io.kotlintest.properties.Gen
import io.kotlintest.specs.ShouldSpec
import io.mockk.every
import io.mockk.mockk
import java.util.*

internal class MockingShouldWork : ShouldSpec() {

    private val jsonStorage: JsonStorage = mockk()

    init {
        // Switch between the every statements to reproduce
//        every { jsonStorage.saveAsJson(any(), any()) } answers {
//            JsonEntity(
//                Gen.uuid().random().first(),
//                firstArg()
//            )
//        }
        every { jsonStorage.saveAsJson(any()) { any() } } answers {
            JsonEntity(
                Gen.uuid().random().first(),
                firstArg()
            )
        }

        "Mocking should result in the same behaviour" {
            should("work") {
                val entity = Entity(Gen.uuid().random().first())
                jsonStorage.saveAsJson(entity) { entity.id }
            }
        }
    }
}

interface JsonStorage {
    fun saveAsJson(entity: Any, idSupplier: () -> UUID): JsonEntity
}

data class Entity(val id: UUID)
data class JsonEntity(val id: UUID, val payload: Any)

// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by oleksiyp** [comment]
These notations shouldn't have the same meaning. `{ any() }` is some lambda that calls `any()` matcher, and `any()` is any lambda. Besides, lambdas are not comparable, so an instance always unique and that way not possible `{ any() }` will be equal to anything. I am closing this ticket.

**Comment by FareesHussain** [comment]
@tomdevroomen did you find any workaround for this?

**Comment by FareesHussain** [comment]
> These notations shouldn't have the same meaning. `{ any() }` is some lambda that calls `any()` matcher, and `any()` is any lambda. Besides, lambdas are not comparable, so an instance always unique and that way not possible `{ any() }` will be equal to anything. I am closing this ticket.

@oleksiyp but this is same if we use any<Unit>() too.
I tried calling the same function that is called internally, but it shows the same kind if error, 

any suggestions on what to use instead?

**Comment by AyoolaAjebeku-tomtom** [comment]
Try this:
`every { saveAsJson(any(), any<() -> UUID>()) } answers { value }`
