### ISSUE TITLE
Bug:cannot verify launch in spyk for CoroutineScope

### ISSUE THREAD

**Issue by erikhuizinga** [mockk/mockk#210]
<details>
<summary>Prerequisites</summary>

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

</details>

### Expected Behavior

I can verify that a method calls `CoroutineScope.launch { }`.

### Current Behavior

I cannot verify that a method calls `CoroutineScope.launch { }`. Instead, I get cryptic exceptions.

#### Context

* MockK version: 1.8.13.kotlin13
* OS: macOS Mojave 10.14.2 (18C54)
* Kotlin version: 1.3.11
  * Kotlin coroutines core version: 1.1.0
* Android Studio 3.2.1
  * JRE: 1.8.0_152-release-1136-b06 x86_64
  * JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
* JUnit version: 4.12
* Type of test: unit test OR ~android instrumented test~

#### Stack trace

<details>
<summary>Stacktrace 1</summary>

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
Exception in thread "main" java.lang.RuntimeException: Exception while trying to handle coroutine exception
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handlerException(CoroutineExceptionHandler.kt:57)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleExceptionViaHandler(CoroutineExceptionHandler.kt:47)
	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:163)
	at kotlinx.coroutines.JobSupport.tryFinalizeFinishingState(JobSupport.kt:225)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:799)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:742)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:117)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:51)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:160)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at com.example.LaunchTest$test$1.invoke(LaunchTest.kt:20)
	at com.example.LaunchTest$test$1.invoke(LaunchTest.kt:11)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:24)
	at io.mockk.impl.eval.RecordedBlockEvaluator$enhanceWithNPERethrow$1.invoke(RecordedBlockEvaluator.kt:74)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:36)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:27)
	at io.mockk.MockKDsl.internalVerify(API.kt:119)
	at io.mockk.MockKKt.verify(MockK.kt:139)
	at io.mockk.MockKKt.verify$default(MockK.kt:136)
	at com.example.LaunchTest.test(LaunchTest.kt:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
	Suppressed: java.lang.ClassCastException: kotlin.coroutines.CoroutineContext$Element$ByteBuddy$p9HB8JT3$ByteBuddy$OKTKpkps cannot be cast to kotlin.coroutines.ContinuationInterceptor
		at kotlin.coroutines.jvm.internal.ContinuationImpl.intercepted(ContinuationImpl.kt:111)
		at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt.intercepted(IntrinsicsJvm.kt:137)
		at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:25)
		... 44 more
Caused by: java.lang.ClassCastException: kotlin.coroutines.CoroutineContext$Element$ByteBuddy$p9HB8JT3$ByteBuddy$OKTKpkps cannot be cast to kotlinx.coroutines.CoroutineExceptionHandler
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleExceptionViaHandler(CoroutineExceptionHandler.kt:42)
	... 50 more

java.lang.AssertionError: Verification failed: call 2 of 13: CoroutineContext(child of 🔍#1#2).plus(eq(EmptyCoroutineContext))) was not called

	at io.mockk.impl.recording.states.VerifyingState.failIfNotPassed(VerifyingState.kt:63)
	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:41)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:42)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:60)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:27)
	at io.mockk.MockKDsl.internalVerify(API.kt:119)
	at io.mockk.MockKKt.verify(MockK.kt:139)
	at io.mockk.MockKKt.verify$default(MockK.kt:136)
	at com.example.LaunchTest.test(LaunchTest.kt:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

</details>

<details>
<summary>Stacktrace 2</summary>

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
Exception in thread "main" java.lang.RuntimeException: Exception while trying to handle coroutine exception
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handlerException(CoroutineExceptionHandler.kt:57)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleExceptionViaHandler(CoroutineExceptionHandler.kt:47)
	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:163)
	at kotlinx.coroutines.JobSupport.tryFinalizeFinishingState(JobSupport.kt:225)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:799)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:742)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:117)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:51)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:160)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at com.example.LaunchTest$test$1.invoke(LaunchTest.kt:21)
	at com.example.LaunchTest$test$1.invoke(LaunchTest.kt:11)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:24)
	at io.mockk.impl.eval.RecordedBlockEvaluator$enhanceWithNPERethrow$1.invoke(RecordedBlockEvaluator.kt:74)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:36)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:27)
	at io.mockk.MockKDsl.internalVerify(API.kt:119)
	at io.mockk.MockKKt.verify(MockK.kt:139)
	at io.mockk.MockKKt.verify$default(MockK.kt:136)
	at com.example.LaunchTest.test(LaunchTest.kt:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
	Suppressed: java.lang.ClassCastException: kotlin.coroutines.CoroutineContext$Element$ByteBuddy$1NpSiLMp$ByteBuddy$YOo8QGVO cannot be cast to kotlin.coroutines.ContinuationInterceptor
		at kotlin.coroutines.jvm.internal.ContinuationImpl.intercepted(ContinuationImpl.kt:111)
		at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt.intercepted(IntrinsicsJvm.kt:137)
		at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:25)
		... 44 more
Caused by: java.lang.ClassCastException: kotlin.coroutines.CoroutineContext$Element$ByteBuddy$1NpSiLMp$ByteBuddy$YOo8QGVO cannot be cast to kotlinx.coroutines.CoroutineExceptionHandler
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleExceptionViaHandler(CoroutineExceptionHandler.kt:42)
	... 50 more

io.mockk.MockKException: Class cast exception. Probably type information was erased.
In this case use `hint` before call to specify exact return type of a method. 

	at io.mockk.impl.InternalPlatform.prettifyRecordingException(InternalPlatform.kt:75)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:62)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:27)
	at io.mockk.MockKDsl.internalVerify(API.kt:119)
	at io.mockk.MockKKt.verify(MockK.kt:139)
	at io.mockk.MockKKt.verify$default(MockK.kt:136)
	at com.example.LaunchTest.test(LaunchTest.kt:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
Caused by: java.lang.ClassCastException: kotlin.coroutines.CoroutineContext$Element$ByteBuddy$1NpSiLMp$ByteBuddy$YOo8QGVO cannot be cast to kotlinx.coroutines.CoroutineId
	at kotlinx.coroutines.CoroutineContextKt.getCoroutineName(CoroutineContext.kt:77)
	at kotlinx.coroutines.AbstractCoroutine.nameString$kotlinx_coroutines_core(AbstractCoroutine.kt:125)
	at kotlinx.coroutines.JobSupport.toDebugString(JobSupport.kt:936)
	at kotlinx.coroutines.JobSupport.toString(JobSupport.kt:933)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at java.util.AbstractCollection.toString(AbstractCollection.java:462)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at io.mockk.impl.recording.SignedCall.toString(SignedCall.kt)
	at java.lang.String.valueOf(String.java:2994)
	at kotlin.text.StringsKt__StringBuilderKt.appendElement(StringBuilder.kt:61)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:2274)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:2291)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:2290)
	at io.mockk.impl.recording.SignatureMatcherDetector.detect(SignatureMatcherDetector.kt:99)
	at io.mockk.impl.recording.states.RecordingState.signMatchers(RecordingState.kt:38)
	at io.mockk.impl.recording.states.RecordingState.round(RecordingState.kt:30)
	at io.mockk.impl.recording.CommonCallRecorder.round(CommonCallRecorder.kt:45)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:59)
	... 32 more
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

</details>

#### Minimal reproducible code (the gist of this issue)

```groovy
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    def coroutines_version = '1.1.0'
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutines_version"

    def junit_vintage_version = "4.12"
    testImplementation "junit:junit:$junit_vintage_version"

    def mockk_version = '1.8.13.kotlin13'
    testImplementation "io.mockk:mockk:$mockk_version"
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
package com.example

import io.mockk.spyk
import io.mockk.verify
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.launch
import org.junit.Test

class LaunchTest {
    @Test
    fun test() {
        val launcher = Launcher()
        val scopeSpy = spyk(CoroutineScope(Dispatchers.Default + Job()), name = "🔍")
        val block: suspend CoroutineScope.() -> Unit = {}

        launcher.doTheThingsThatLaunchersDo(scopeSpy, block)

        verify { scopeSpy.launch(block = block) } // Fails with stacktrace 1
        verify { scopeSpy.launch(block = any()) } // Fails with stacktrace 2
    }
}

class Launcher {
    fun doTheThingsThatLaunchersDo(
        scope: CoroutineScope,
        block: suspend CoroutineScope.() -> Unit
    ) = scope.launch(block = block)
}
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by erikhuizinga** [comment]
Got any workaround or solution? Judging by you reaction: I guess not. 🙁

**Comment by oleksiyp** [comment]
I have quite different error message:

```
2018-12-29 17:51:24 [main] DEBUG i.m.i.i.AbstractMockFactory - Creating spyk for ContextScope name=🔍#1, moreInterfaces=[]
2018-12-29 17:51:25 [main] DEBUG i.m.i.r.states.AnsweringState - Answering [JobImpl{Active}@3b7ff809, CommonPool] on ContextScope(🔍#1).getCoroutineContext()
2018-12-29 17:51:25 [main] DEBUG i.m.i.i.AbstractMockFactory - Creating mockk for CoroutineContext name=child of 🔍#1#2, moreInterfaces=[]
2018-12-29 17:51:25 [main] DEBUG i.m.i.i.AbstractMockFactory - Creating mockk for CoroutineContext name=child^2 of 🔍#1#2#3, moreInterfaces=[]
2018-12-29 17:51:25 [main] DEBUG i.m.i.i.AbstractMockFactory - Creating mockk for CoroutineContext name=child^3 of 🔍#1#2#3#4, moreInterfaces=[]
2018-12-29 17:51:25 [main] DEBUG i.m.i.i.AbstractMockFactory - Creating mockk for Element name=child^3 of 🔍#1#2#3#5, moreInterfaces=[]
2018-12-29 17:51:25 [main] DEBUG i.m.i.i.AbstractMockFactory - Creating mockk for CoroutineContext name=child^4 of 🔍#1#2#3#4#6, moreInterfaces=[]
2018-12-29 17:51:25 [main] DEBUG i.m.i.i.AbstractMockFactory - Creating mockk for Job name=child^4 of 🔍#1#2#3#4#7, moreInterfaces=[]
2018-12-29 17:51:25 [main] DEBUG i.m.i.i.AbstractMockFactory - Creating mockk for ChildHandle name=child^5 of 🔍#1#2#3#4#7#8, moreInterfaces=[]
2018-12-29 17:51:25 [main] DEBUG i.m.i.i.AbstractMockFactory - Creating mockk for ContinuationInterceptor name=child^5 of 🔍#1#2#3#4#6#9, moreInterfaces=[]
2018-12-29 17:51:25 [main] DEBUG i.m.i.i.AbstractMockFactory - Creating mockk for Continuation name=child^6 of 🔍#1#2#3#4#6#9#10, moreInterfaces=[]

java.lang.AssertionError: Verification failed: call 2 of 11: CoroutineContext(child of 🔍#1#2).plus(eq(EmptyCoroutineContext))) was not called

	at io.mockk.impl.recording.states.VerifyingState.failIfNotPassed(VerifyingState.kt:63)
	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:41)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:42)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:60)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:27)
	at io.mockk.MockKDsl.internalVerify(API.kt:119)
	at io.mockk.MockKKt.verify(MockK.kt:139)
	at io.mockk.MockKKt.verify$default(MockK.kt:136)
	at io.mockk.gh.Issue210Test.test(Issue210Test.kt:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:83)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:74)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

```

**Comment by erikhuizinga** [comment]
Hmm, it is different, but almost the same as my stacktrace 1:

```
java.lang.AssertionError: Verification failed: call 2 of 13: CoroutineContext(child of 🔍#1#2).plus(eq(EmptyCoroutineContext))) was not called
```

**Comment by erikhuizinga** [comment]
So: it seems MockK tries to verify 13 (!) calls (or eleven in your case), while I just try to verify one call.

**Comment by oleksiyp** [comment]
In verify block `launch` get executed instead of being intercepted.

**Comment by erikhuizinga** [comment]
Wow, nice find. That solves the failing test.

However, it would be nice to somehow know that I'm trying to verify an extension method (static method). Can MockK detect this could be a cause of failure?

And another idea: have an alias for `mockStatic`: `mockExtensions`.

**Comment by oleksiyp** [comment]
Dont think there is possibility to distinguish, except mocking everything. And having alias will actually confuse people even more

**Comment by oleksiyp** [comment]
This the case which is not possible to make simpler and instead of having nice wrap better to expose complexity to the user and hope he/she understands what he/she does. Docs briefly describes mocking extension function

**Comment by erikhuizinga** [comment]
I'm not sure this is possible, but you might be able to distinguish extension functions from others using [`val KCallable<*>.extensionReceiverParameter: KParameter?`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.reflect.full/extension-receiver-parameter.html). If that doesn't return null, it is an extension function.

Now, that doesn't solve this problem, but it's a start. I don't know much about MockK's internals, but if it detects an unmocked extension function call is to be verified or mocked, MockK might be able to remind the user to mock that extension function's class explicitly, instead of the receiver's class.

**Comment by oleksiyp** [comment]
The problem is that mockk detects calls of only instrumented classes. Other calls are kept intact. So till the moment we specified classes(either in mockkStatic or mockk/spyk function) it is not possible to intercept and check what functions are: extensions or regular. So only solution is to instrument all which is way too heavy I think.
