### ISSUE TITLE
Help: InvocationTargetException Error

### ISSUE THREAD

**Issue by juxeii** [mockk/mockk#213]
I get a `InvocationTargetException ` for this code:
```
import io.kotlintest.specs.StringSpec
import io.mockk.mockk

interface IMyInterface{
    fun foo()
}

class MessageGatewayTest : StringSpec({
    val myMock = mockk<IMyInterface>()
})
```
No matter which type I want to mock, the error stack is always the same:
```
java.lang.reflect.InvocationTargetException
2019-01-02 16:32:47.756 ERROR TestEngine - Error during test engine run
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Constructor.call(CallerImpl.kt:41)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:106)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Constructor.call(CallerImpl.kt:41)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:106)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflect_api(KCallableImpl.kt:152)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:110)
	at kotlin.reflect.full.KClasses.createInstance(KClasses.kt:283)
	at io.kotlintest.runner.jvm.JvmKt.instantiateSpec(jvm.kt:12)
	at io.kotlintest.runner.jvm.TestEngine.createSpec(TestEngine.kt:100)
	at io.kotlintest.runner.jvm.TestEngine.access$createSpec(TestEngine.kt:15)
	at io.kotlintest.runner.jvm.TestEngine$submitSpec$1.run(TestEngine.kt:78)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflect_api(KCallableImpl.kt:152)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at kotlin.reflect.full.KClasses.createInstance(KClasses.kt:283)
Caused by: java.lang.ExceptionInInitializerError
	at com.jforex.dzjforex.test.login.MessageGatewayTest$1.invoke(LoginTest.kt:36)
	at io.kotlintest.runner.jvm.JvmKt.instantiateSpec(jvm.kt:12)
	at com.jforex.dzjforex.test.login.MessageGatewayTest$1.invoke(LoginTest.kt:10)
	at io.kotlintest.runner.jvm.TestEngine.createSpec(TestEngine.kt:100)
	at io.kotlintest.specs.AbstractStringSpec.<init>(AbstractStringSpec.kt:21)
	at io.kotlintest.specs.StringSpec.<init>(specs.kt:32)
	at io.kotlintest.runner.jvm.TestEngine.access$createSpec(TestEngine.kt:15)
	at com.jforex.dzjforex.test.login.MessageGatewayTest.<init>(LoginTest.kt:10)
	... 18 more
	at io.kotlintest.runner.jvm.TestEngine$submitSpec$1.run(TestEngine.kt:78)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Caused by: java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@7db0cb37
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:384)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:358)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:326)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:312)
	at io.mockk.proxy.jvm.JvmMockKAgentFactory.initInstrumentation(JvmMockKAgentFactory.kt:122)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.mockk.proxy.jvm.JvmMockKAgentFactory.init(JvmMockKAgentFactory.kt:31)
	at java.lang.Thread.run(Thread.java:748)
	at io.mockk.impl.JvmMockKGateway.<init>(JvmMockKGateway.kt:45)
	at io.mockk.impl.JvmMockKGateway.<clinit>(JvmMockKGateway.kt:163)
	... 23 more
Caused by: java.lang.ExceptionInInitializerError
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at com.jforex.dzjforex.test.login.MessageGatewayTest$1.invoke(LoginTest.kt:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.jforex.dzjforex.test.login.MessageGatewayTest$1.invoke(LoginTest.kt:10)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.kotlintest.specs.AbstractStringSpec.<init>(AbstractStringSpec.kt:21)
	at net.bytebuddy.agent.Attacher.install(Attacher.java:84)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:379)
	at io.kotlintest.specs.StringSpec.<init>(specs.kt:32)
	... 30 more
Caused by: com.sun.tools.attach.AttachNotSupportedException: no providers installed
	at com.jforex.dzjforex.test.login.MessageGatewayTest.<init>(LoginTest.kt:10)
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
	... 36 more
	... 18 more
Caused by: java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@7db0cb37
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:384)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:358)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:326)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:312)
	at io.mockk.proxy.jvm.JvmMockKAgentFactory.initInstrumentation(JvmMockKAgentFactory.kt:122)
	at io.mockk.proxy.jvm.JvmMockKAgentFactory.init(JvmMockKAgentFactory.kt:31)
	at io.mockk.impl.JvmMockKGateway.<init>(JvmMockKGateway.kt:45)
	at io.mockk.impl.JvmMockKGateway.<clinit>(JvmMockKGateway.kt:163)
	... 23 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.bytebuddy.agent.Attacher.install(Attacher.java:84)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:379)
	... 30 more
Caused by: com.sun.tools.attach.AttachNotSupportedException: no providers installed
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
	... 36 more

java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Constructor.call(CallerImpl.kt:41)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:106)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflect_api(KCallableImpl.kt:152)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:110)
	at kotlin.reflect.full.KClasses.createInstance(KClasses.kt:283)
	at io.kotlintest.runner.jvm.JvmKt.instantiateSpec(jvm.kt:12)
	at io.kotlintest.runner.jvm.TestEngine.createSpec(TestEngine.kt:100)
	at io.kotlintest.runner.jvm.TestEngine.access$createSpec(TestEngine.kt:15)
	at io.kotlintest.runner.jvm.TestEngine$submitSpec$1.run(TestEngine.kt:78)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ExceptionInInitializerError
	at com.jforex.dzjforex.test.login.MessageGatewayTest$1.invoke(LoginTest.kt:36)
	at com.jforex.dzjforex.test.login.MessageGatewayTest$1.invoke(LoginTest.kt:10)
	at io.kotlintest.specs.AbstractStringSpec.<init>(AbstractStringSpec.kt:21)
	at io.kotlintest.specs.StringSpec.<init>(specs.kt:32)
	at com.jforex.dzjforex.test.login.MessageGatewayTest.<init>(LoginTest.kt:10)
	... 18 more
Caused by: java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@7db0cb37
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:384)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:358)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:326)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:312)
	at io.mockk.proxy.jvm.JvmMockKAgentFactory.initInstrumentation(JvmMockKAgentFactory.kt:122)
	at io.mockk.proxy.jvm.JvmMockKAgentFactory.init(JvmMockKAgentFactory.kt:31)
	at io.mockk.impl.JvmMockKGateway.<init>(JvmMockKGateway.kt:45)
	at io.mockk.impl.JvmMockKGateway.<clinit>(JvmMockKGateway.kt:163)
	... 23 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.bytebuddy.agent.Attacher.install(Attacher.java:84)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:379)
	... 30 more
Caused by: com.sun.tools.attach.AttachNotSupportedException: no providers installed
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
	... 36 more

UnknownClass > initializationError FAILED
    java.lang.reflect.InvocationTargetException
        Caused by: java.lang.ExceptionInInitializerError
            Caused by: java.lang.IllegalStateException
                Caused by: java.lang.reflect.InvocationTargetException
                    Caused by: com.sun.tools.attach.AttachNotSupportedException
```
I use gradle 5 with:
```
dependencies {
    compile(kotlin("stdlib-jdk8"))

    testCompile("io.kotlintest:kotlintest-runner-junit5:3.1.11")
    testCompile("io.mockk:mockk:1.8.13")
}

tasks.withType<Test> {
    useJUnitPlatform()
}
```
Any ideas what is wrong here?

EDIT: I hacked the following to the build.gradle
`testImplementation(files(Jvm.current().toolsJar))`
Now everything works, but it is not a nice workaround.

**Comment by oleksiyp** [comment]
Thanks for the report

**Comment by oleksiyp** [comment]
I tried to reproduce your problem without success from IDEA:
```
2019-01-04 07:15:22 [main] DEBUG i.k.runner.junit5.KotlinTestEngine - configurationParameters=LauncherConfigurationParameters []
2019-01-04 07:15:22 [main] DEBUG i.k.runner.junit5.KotlinTestEngine - uniqueId=[engine:kotlintest]
2019-01-04 07:15:22 [main] DEBUG i.k.runner.junit5.KotlinTestEngine - LauncherDiscoveryRequest [
classpathRootSelectors=[]
classpathResourceSelectors=[]
classSelectors=[test.MessageGatewayTest]
methodSelectors=[]
directorySelectors=[]
fileSelectors=[]
moduleSelectors=[]
packageSelectors=[]
uniqueIdSelectors=[]
uriSelectors=[]
engineFilters=[]
postDiscoveryFilters=[]
classnameFilters=[]
packageNameFilters=[]
]
2019-01-04 07:15:22 [main] DEBUG i.k.runner.jvm.TestDiscovery - Loaded 1 classes from classnames...
2019-01-04 07:15:23 [main] DEBUG i.k.runner.jvm.TestDiscovery - ...which has filtered to 1 non abstract classes
2019-01-04 07:15:23 [main] DEBUG i.k.runner.jvm.TestDiscovery - 1 classes after applying discovery extensions2019-01-04 07:15:23 [main] DEBUG i.k.runner.junit5.KotlinTestEngine - configurationParameters=LauncherConfigurationParameters []
2019-01-04 07:15:23 [main] DEBUG i.k.runner.junit5.KotlinTestEngine - uniqueId=[engine:kotlintest]
2019-01-04 07:15:23 [main] DEBUG i.k.runner.junit5.KotlinTestEngine - LauncherDiscoveryRequest [
classpathRootSelectors=[]
classpathResourceSelectors=[]
classSelectors=[test.MessageGatewayTest]
methodSelectors=[]
directorySelectors=[]
fileSelectors=[]
moduleSelectors=[]
packageSelectors=[]
uniqueIdSelectors=[]
uriSelectors=[]
engineFilters=[]
postDiscoveryFilters=[]
classnameFilters=[]
packageNameFilters=[]
]
2019-01-04 07:15:23 [main] DEBUG i.k.runner.junit5.KotlinTestEngine - JUnit execution request [configurationParameters=LauncherConfigurationParameters []; rootTestDescriptor=KotlinTestEngineDescriptor: [engine:kotlintest]]
2019-01-04 07:15:23 [main] DEBUG i.k.r.junit5.JUnitTestRunnerListener - Engine started; classes=[[class test.MessageGatewayTest]]
2019-01-04 07:15:23 [main] DEBUG io.kotlintest.runner.jvm.TestEngine - Submitting 1 specs
2019-01-04 07:15:23 [main] DEBUG io.kotlintest.runner.jvm.TestEngine - Waiting for spec execution service to terminate
2019-01-04 07:15:23 [kotlintest-engine-0] DEBUG i.m.i.i.AbstractMockFactory - Creating mockk for IMyInterface name=#1, moreInterfaces=[]
2019-01-04 07:15:24 [kotlintest-engine-0] DEBUG i.k.r.junit5.JUnitTestRunnerListener - prepareSpec [Description(parents=[], name=MessageGatewayTest)]2019-01-04 07:15:24 [kotlintest-engine-0] DEBUG i.k.r.junit5.JUnitTestRunnerListener - completeSpec [Description(parents=[], name=MessageGatewayTest)]
2019-01-04 07:15:24 [kotlintest-engine-0] DEBUG i.k.r.junit5.JUnitTestRunnerListener - Notifying junit that spec finished [engine:kotlintest]/[spec:MessageGatewayTest] TestExecutionResult [status = SUCCESSFUL, throwable = null]Empty test suite.
2019-01-04 07:15:24 [main] DEBUG i.k.r.junit5.JUnitTestRunnerListener - Engine finished; throwable=[null]
Disconnected from the target VM, address: '127.0.0.1:35531', transport: 'socket'

Process finished with exit code 0
```
and from Gradle:
```
Testing started at 7:18 ...
7:18:27: Executing task 'test'...

> Task :discoverMainScriptsExtensions
> Task :compileKotlin NO-SOURCE
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :discoverTestScriptsExtensions
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /home/oleksiyp/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.3.10/71d0fa967493eb76648b575edf1762cb2d0c7f10/kotlin-stdlib-jdk8-1.3.10.jar (version 1.3)
    /home/oleksiyp/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.3.10/4d147bf43060dc43d61b096e24da1e67dfe0c032/kotlin-stdlib-jdk7-1.3.10.jar (version 1.3)
    /home/oleksiyp/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.2.71/7512db3b3182753bd2e48ce8d345abbadc40fe6b/kotlin-reflect-1.2.71.jar (version 1.2)
    /home/oleksiyp/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.3.10/b178c1501609c6e4ee8be635513cb023a466457d/kotlin-stdlib-1.3.10.jar (version 1.3)
    /home/oleksiyp/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.3.10/1b19d99229dcedad7caf50534dce38fe82845269/kotlin-stdlib-common-1.3.10.jar (version 1.3)
w: Consider providing an explicit dependency on kotlin-reflect 1.3 to prevent strange errors
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
w: /home/oleksiyp/workspace/playground-gradle-5/src/test/kotlin/test/IMyInterface.kt: (11, 9): Variable 'myMock' is never used
> Task :compileTestKotlin
> Task :compileTestJava NO-SOURCE
> Task :processTestResources
> Task :testClasses
> Task :test
2019-01-04 07:18:28 [Test worker] DEBUG i.k.runner.junit5.KotlinTestEngine - configurationParameters=LauncherConfigurationParameters []
2019-01-04 07:18:28 [Test worker] DEBUG i.k.runner.junit5.KotlinTestEngine - uniqueId=[engine:kotlintest]
2019-01-04 07:18:28 [Test worker] DEBUG i.k.runner.junit5.KotlinTestEngine - LauncherDiscoveryRequest [
classpathRootSelectors=[]
classpathResourceSelectors=[]
classSelectors=[test.IMyInterface, test.MessageGatewayTest]
methodSelectors=[]
directorySelectors=[]
fileSelectors=[]
moduleSelectors=[]
packageSelectors=[]
uniqueIdSelectors=[]
uriSelectors=[]
engineFilters=[]
postDiscoveryFilters=[]
classnameFilters=[]
packageNameFilters=[]
]
2019-01-04 07:18:28 [Test worker] DEBUG i.k.runner.jvm.TestDiscovery - Loaded 2 classes from classnames...
2019-01-04 07:18:29 [Test worker] DEBUG i.k.runner.jvm.TestDiscovery - ...which has filtered to 1 non abstract classes
2019-01-04 07:18:29 [Test worker] DEBUG i.k.runner.jvm.TestDiscovery - 1 classes after applying discovery extensions
2019-01-04 07:18:29 [Test worker] DEBUG i.k.runner.junit5.KotlinTestEngine - JUnit execution request [configurationParameters=LauncherConfigurationParameters []; rootTestDescriptor=KotlinTestEngineDescriptor: [engine:kotlintest]]
2019-01-04 07:18:29 [Test worker] DEBUG i.k.r.junit5.JUnitTestRunnerListener - Engine started; classes=[[class test.MessageGatewayTest]]
2019-01-04 07:18:29 [Test worker] DEBUG io.kotlintest.runner.jvm.TestEngine - Submitting 1 specs
2019-01-04 07:18:29 [Test worker] DEBUG io.kotlintest.runner.jvm.TestEngine - Waiting for spec execution service to terminate
2019-01-04 07:18:29 [kotlintest-engine-0] DEBUG i.m.i.i.AbstractMockFactory - Creating mockk for IMyInterface name=#1, moreInterfaces=[]
2019-01-04 07:18:30 [kotlintest-engine-0] DEBUG i.k.r.junit5.JUnitTestRunnerListener - prepareSpec [Description(parents=[], name=MessageGatewayTest)]
2019-01-04 07:18:30 [Test worker] DEBUG i.k.r.junit5.JUnitTestRunnerListener - Engine finished; throwable=[null]
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1/userguide/command_line_interface.html#sec:command_line_warnings
BUILD SUCCESSFUL in 2s
5 actionable tasks: 5 executed
7:18:30: Task execution finished 'test'.
```

I can assume that you probably running it from JRE and ByteBuddy needs JDK. Can you check this thing?

**Comment by juxeii** [comment]
I had this problem when running it directly via Gradle or within IDEA.
I checked that JDK is correct, maybe I overlooked something.
Can you give me some hints on where else to check for JRE vs JDK?

**Comment by oleksiyp** [comment]
Check this thread https://github.com/mockito/mockito/issues/978 . I think the conclusion would be that you need to point your JAVA_HOME to JDK as BB uses it and not running JDK.

**Comment by juxeii** [comment]
JAVA_HOME is set to JDK.
The funny thing is that I have another Kotlin project where I do not need the "hack" above.
I double checked the build.gradle but could not find any clue on why the one project works while the other does not.

**Comment by oleksiyp** [comment]
Very weird. What OS are you running it?
