### ISSUE TITLE
Can't mock or stub java.util.Date in Android instrumentation tests 

### ISSUE THREAD

**Issue by mateot1** [mockk/mockk#253]
### Expected Behavior
I should be able to mock or stub out a `Date` object in Android instrumentation tests like I can on JVM tests

### Current Behavior
Instrumentation tests that try to create a mock of `java.util.Date` with `mockk<Date>()` or stub out a property/function that returns `Date` via `every` fail with an exception. This is not the case for JVM tests. 

#### Steps to Reproduce

1. mock or stub out a response of the type `java.Util.Date` in an android test
2. run the test

#### Context

* MockK version: 1.9
* OS: Android P emulator, lower sdks seem to work for mocking, but not stubbing 
* Kotlin version: 1.3.21
* JDK version: 
* JUnit version: 4.12
* Type of test: android instrumented test

#### Stack trace
Android P emulator:
```
java.lang.AssertionError: java.lang.ClassNotFoundException: Didn't find class "java/util/Date_Proxy" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/data/app/com.example.myapplication.test-pQ7AVVhnFroMqntREiiA9A==/base.apk", zip file "/data/app/com.example.myapplication-8uPfFemdvXPWVhH6GiGw4w==/base.apk", zip file "/data/user/0/com.example.myapplication/app_dxmaker_cache/Generated_-432639836.jar"],nativeLibraryDirectories=[/data/app/com.example.myapplication.test-pQ7AVVhnFroMqntREiiA9A==/lib/x86, /data/app/com.example.myapplication-8uPfFemdvXPWVhH6GiGw4w==/lib/x86, /system/lib]]
at com.android.dx.stock.ProxyBuilder.buildProxyClass(ProxyBuilder.java:313)
at io.mockk.proxy.android.transformation.AndroidSubclassInstrumentation.subclass(AndroidSubclassInstrumentation.kt:37)
at io.mockk.proxy.common.ProxyMaker.subclass(ProxyMaker.kt:140)
at io.mockk.proxy.common.ProxyMaker.proxy(ProxyMaker.kt:60)
at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:34)
at io.mockk.impl.instantiation.AbstractMockFactory.newProxy$default(AbstractMockFactory.kt:29)
at io.mockk.impl.instantiation.AbstractMockFactory.mockk(AbstractMockFactory.kt:58)
at com.example.myapplication.ExampleInstrumentedTest.testMockDate(ExampleInstrumentedTest.kt:108)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at android.support.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:101)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:384)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
Caused by: java.lang.ClassNotFoundException: Didn't find class "java/util/Date_Proxy" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/data/app/com.example.myapplication.test-pQ7AVVhnFroMqntREiiA9A==/base.apk", zip file "/data/app/com.example.myapplication-8uPfFemdvXPWVhH6GiGw4w==/base.apk", zip file "/data/user/0/com.example.myapplication/app_dxmaker_cache/Generated_-432639836.jar"],nativeLibraryDirectories=[/data/app/com.example.myapplication.test-pQ7AVVhnFroMqntREiiA9A==/lib/x86, /data/app/com.example.myapplication-8uPfFemdvXPWVhH6GiGw4w==/lib/x86, /system/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
at com.android.dx.stock.ProxyBuilder.loadClass(ProxyBuilder.java:324)
at com.android.dx.stock.ProxyBuilder.buildProxyClass(ProxyBuilder.java:306)
... 35 more
Suppressed: java.io.IOException: No original dex files found for dex location /data/user/0/com.example.myapplication/app_dxmaker_cache/Generated_-432639836.jar
at dalvik.system.DexFile.openDexFileNative(Native Method)
at dalvik.system.DexFile.openDexFile(DexFile.java:354)
at dalvik.system.DexFile.<init>(DexFile.java:101)
at dalvik.system.DexFile.<init>(DexFile.java:75)
at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
at dalvik.system.DexPathList.addDexPath(DexPathList.java:226)
at dalvik.system.BaseDexClassLoader.addDexPath(BaseDexClassLoader.java:155)
at dalvik.system.BaseDexClassLoader.addDexPath(BaseDexClassLoader.java:148)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.dx.DexMaker.generateClassLoader(DexMaker.java:370)
at com.android.dx.DexMaker.generateAndLoad(DexMaker.java:434)
at com.android.dx.stock.ProxyBuilder.buildProxyClass(ProxyBuilder.java:304)
... 35 more
```

< Android P for stubbing (mocking seems okay):
```
io.mockk.MockKException: Missing calls inside every { ... } block.
at io.mockk.impl.recording.states.StubbingState.checkMissingCalls(StubbingState.kt:14)
at io.mockk.impl.recording.states.StubbingState.recordingDone(StubbingState.kt:8)
at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:48)
at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:60)
at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:25)
at io.mockk.MockKDsl.internalEvery(API.kt:92)
at io.mockk.MockKKt.every(MockK.kt:104)
at com.example.myapplication.ExampleInstrumentedTest.testDateStub(ExampleInstrumentedTest.kt:19)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at android.support.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:101)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:384)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
package com.example.myapplication

import android.support.test.runner.AndroidJUnit4
import io.mockk.every
import io.mockk.mockk
import junit.framework.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import java.util.*

@RunWith(AndroidJUnit4::class)
class ExampleInstrumentedTest {

    @Test
    fun testDateStub() {
        val mockObject = mockk<ModelWithDate>()
        val realDate = Date()
        every { mockObject.date } returns realDate
        assertTrue(mockObject.date == realDate)
    }

    @Test
    fun testMockDate() {
        val mockDate = mockk<Date>()
        every { mockDate.time } returns 1000L
        assertTrue(mockDate.time == 1000L)
    }

    class ModelWithDate(val date: Date)
}
```

**Comment by oleksiyp** [comment]
Probably there is no hope, but I will check

**Comment by francescocervone** [comment]
Any updates about this issue?

**Comment by priyankshah217** [comment]
I am also facing the same issue while mocking object in dagger module using mockk.

```
@Module
class MockUserModule {
    @Provides
    fun getMockUser(): User {
        val user = mockk<User>()
        every { user.salt }.returns("Abc")
        every { user.username }.returns("Abc")
        every { user.shA256 }.returns("Abc")
        return user
    }
}
```

**Comment by francescocervone** [comment]
@oleksiyp this issue should be marked as `important`.

**Comment by UnitOneOnline** [comment]
i am experiencing same problem here

i am trying to stub a property which returns Date or Timestamp. Presumably this is mockk problem.

error is:

E/TestRunner: java.lang.AssertionError: java.lang.ClassNotFoundException: Didn't find class "java/util/Date_Proxy" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/data/app/biz.klaxon.mobileapp.test-ycvUaZyzR7hEB6d5bR2_Og==/base.apk", zip file "/data/app/biz.klaxon.mobileapp-x4hg7yOoylp2RtjtbWUonw==/base.apk", zip file "/data/user/0/biz.klaxon.mobileapp/app_dxmaker_cache/Generated_-432639836.jar"],nativeLibraryDirectories=[/data/app/biz.klaxon.mobileapp.test-ycvUaZyzR7hEB6d5bR2_Og==/lib/x86, /data/app/biz.klaxon.mobileapp-x4hg7yOoylp2RtjtbWUonw==/lib/x86, /system/lib]]

**Comment by a-shatou** [comment]
Any solution to this issue so far?

**Comment by soygabimoreno** [comment]
I am trying to mock a `Date` too... :-(

**Comment by IngJaycee** [comment]
This issue is still present on:  mockk_version = '1.9.1'
do you have an update on this?

`java.lang.AssertionError: java.lang.ClassNotFoundException: Didn't find class "java/util/Date_1_Proxy" on path: DexPathList[[zip file "/data/user/0/com.insulet.omnipodview/app_dxmaker_cache/Generated_-1966060335.jar"],nativeLibraryDirectories=[/system/lib64, /product/lib64]]
	at com.android.dx.stock.ProxyBuilder.buildProxyClass(ProxyBuilder.java:347)
	at io.mockk.proxy.android.transformation.AndroidSubclassInstrumentation.subclass(AndroidSubclassInstrumentation.kt:37)
`

**Comment by v-mas** [comment]
I had the same problem in 1.10.6 but after changing to 1.12.3 it is resolved
