### ISSUE TITLE
Verifications fail with Missing calls inside verify { ... } block when ran on CLI but pass in IDE

### ISSUE THREAD

**Issue by mp911de** [mockk/mockk#259]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

Verification is properly evaluated.

### Current Behavior

The test fails with: `Missing calls inside verify { ... } block`

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. See code
2. Run `CriteriaExtensionsUnitTests`

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.9.1
* OS: MacOS 10.14.2
* Kotlin version: tested on 1.3.11 and 1.3.21
* JDK version: JRE 1.8.0_121-b13
* JUnit version: 4.12
* Type of test: JUnit 4 test

#### Stack trace

```
io.mockk.MockKException: Missing calls inside verify { ... } block.
	at org.springframework.data.cassandra.core.query.CriteriaExtensionsUnitTests.inValues(varags) extension should support nullable values(CriteriaExtensionsUnitTests.kt:66)
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
class CriteriaExtensionsUnitTests {

	val criteria = mockk<Criteria>(relaxed = true)

	@Test
	fun `inValues(Collection) extension should call its Java counterpart`() {

		val c = listOf("foo", "bar")

		criteria.inValues(c)

		verify { criteria.`in`(c) }
	}
}
```

```kotlin
/**
 * Extension for [Criteria. in] providing an `inValues` alias since `in` is a reserved keyword in Kotlin.
 */
fun <T : Any?> Criteria.inValues(c: Collection<T>): Criteria = `in`(c)
```

```java
public class Criteria {
	public Criteria in(Collection<?> values) {
		return this;
	}
}
```

See also: https://github.com/spring-projects/spring-data-cassandra/blob/master/spring-data-cassandra/src/test/kotlin/org/springframework/data/cassandra/core/query/CriteriaExtensionsUnitTests.kt#L75-L81

**Comment by oleksiyp** [comment]
Thanks for the report. Will check

**Comment by oleksiyp** [comment]
Spent some time on this issue. Instrumention is OK. Turned off parallel testing , but that did not help. In trace logs call doesn't get intercepted. Probably something related to class loading. Will spend more time on weekends

**Comment by mp911de** [comment]
Can this be related to Surefire 2.22.1?

**Comment by oleksiyp** [comment]
Very probable, as JUnut 4.12 is widely used and no other things to interact with. ByteBuddy seems to be working  as one test passing and transformed classes are OK

**Comment by oleksiyp** [comment]
Seems problem appears when building with 2.19 and above Surefire plugin.

**Comment by oleksiyp** [comment]
I experimented a lot with this error.

Turned on debugging, double-checked all the maps inside of mockk, e.t.c. Nothing too suspicious. Looks like not always instrumentation take place at the moment it is requested, maybe not for all threads at a time, or maybe there is a race condition in mockk code. Actually I am starting to understand it better, but let's see. The problem now is to reproduce it without surefire.

Currently, all my achievement in reproduction and differentiation is that I know if I put `sleep(500)` after mock intialization it won't fail.

![image](https://user-images.githubusercontent.com/5249932/54056263-d6e79080-41ef-11e9-9bb4-c33b0f2773a5.png)

**Comment by oleksiyp** [comment]
Good news :smile: 

I reproduced it.

![image](https://user-images.githubusercontent.com/5249932/54057348-fdf39180-41f2-11e9-8526-0100d1715d3b.png)

**Comment by oleksiyp** [comment]
@mp911de please try the same test with version `1.9.2` or `1.9.2.kotlin12`. Thanks

**Comment by mp911de** [comment]
Thanks a lot. The fix addressed the issue.

**Comment by m0skit0** [comment]
I'm still experiencing this issue with 1.9.3 in Android with spied property and Robolectric. Here's an example when testing a RecyclerView adapter.

```
    @Spy
    private val channelListAdapter = ChannelListAdapter()

    @Test
    fun `when setting new item list should call notifyDataSetChanged`() {
        channelListAdapter.channelList = channelList
        channelListAdapter.filteredChannelList.shouldBe(channelList)
        verify { channelListAdapter.notifyDataSetChanged() }
    }
```

```
io.mockk.MockKException: Missing calls inside verify { ... } block.

	at io.mockk.impl.recording.states.VerifyingState.checkMissingCalls(VerifyingState.kt:52)
	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:21)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:60)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalVerify(API.kt:118)
	at io.mockk.MockKKt.verify(MockK.kt:139)
	at io.mockk.MockKKt.verify$default(MockK.kt:136)
	at org.m0skit0.android.technicaltestgen.view.TestUnitChannelListAdapter.when setting new item list should call notifyDataSetChanged(TestUnitChannelListAdapter.kt:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by m0skit0** [comment]
I still have the error on 1.9.3 when verifying spied objects.

```
class Testable {
    fun someMethod() {
        println("Test")
    }
}

internal class TestMockKBug {

    @SpyK
    private val testable = Testable()

    @Test
    fun `testbug`() {
        testable.someMethod()
        verify { testable.someMethod() }
    }
}
```
