### ISSUE TITLE
Error creating a real object android.net.NetworkCapabilities after a mock in Android instrumented test

### ISSUE THREAD

**Issue by lavruk** [mockk/mockk#260]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

The test should not fail with `NoSuchMethodException`

### Current Behavior

The Android instrumentation test fails with the error: `java.lang.NoSuchMethodException: clearAll []`

### Failure Information (for bugs)

It seems that the issue is only reproduced on Android 9 (Pie), I was not able to reproduce it on Android 8.
Link to the source https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-9.0.0_r33/core/java/android/net/NetworkCapabilities.java 

#### Steps to Reproduce

1. Create a mock of android.net.NetworkCapabilities
2. Call NetworkRequest.Builder().build()
3. Run the instrumentation test and observe the error

#### Context

* MockK version: 1.9.1
* OS: Android 9
* Kotlin version: 1.3.21
* JDK version: 1.8.0_191-b12
* JUnit version: 4.12
* Type of test:  android instrumented test

#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
java.lang.NoSuchMethodException: clearAll []
at java.lang.Class.getMethod(Class.java:2068)
at java.lang.Class.getDeclaredMethod(Class.java:2047)
at io.mockk.proxy.android.MethodDescriptor.getMethod(MethodDescriptor.kt:22)
at io.mockk.proxy.android.advice.Advice.getOrigin(Advice.kt:37)
at java.lang.reflect.Method.invoke(Native Method)
at io.mockk.proxy.android.AndroidMockKDispatcher.getOrigin(AndroidMockKDispatcher.java:117)
at android.net.NetworkCapabilities.clearAll(Unknown Source:14)
at android.net.NetworkCapabilities.<init>(NetworkCapabilities.java:60)
at android.net.NetworkRequest$Builder.<init>(NetworkRequest.java:148)
at mockk.test.ExampleInstrumentedTest.testNetworkCapabilities(ExampleInstrumentedTest.kt:22)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at android.support.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:101)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:384)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
package mockk.test

import android.net.NetworkCapabilities
import android.net.NetworkRequest
import android.support.test.runner.AndroidJUnit4
import io.mockk.mockk

import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class ExampleInstrumentedTest {
    @Test
    fun testNetworkCapabilities() {
        // mock
        mockk<NetworkCapabilities>()

        // creates a real NetworkCapabilities object in the Builder
        NetworkRequest.Builder().build()
    }
}

```

**Comment by oleksiyp** [comment]
Thank you for the report

**Comment by oleksiyp** [comment]
Can it be reverted with `unmockk` methods?

**Comment by lavruk** [comment]
I have tried `unmockkAll()` and `unmockkObject(mockk)`, it didn't help :(

**Comment by z1231994** [comment]
I got the same error too .

**Comment by tomwijgers** [comment]
Same for me. Fails creating a WebView when it tries to get network info

**Comment by 4face-studi0** [comment]
Same here with `NotificationManager.notify` 

```
java.lang.NoSuchMethodException: checkFileUriExposed [class java.lang.String]
at java.lang.Class.getMethod(Class.java:2068)
at java.lang.Class.getDeclaredMethod(Class.java:2047)
at io.mockk.proxy.android.MethodDescriptor.getMethod(MethodDescriptor.kt:22)
at io.mockk.proxy.android.advice.Advice.getOrigin(Advice.kt:37)
at java.lang.reflect.Method.invoke(Native Method)
at io.mockk.proxy.android.AndroidMockKDispatcher.getOrigin(AndroidMockKDispatcher.java:117)
at android.net.Uri.checkFileUriExposed(Unknown Source:14)
```

**Comment by malvinstn** [comment]
I have the same issue with `NotificationChannel` as well: 
```
java.lang.NoSuchMethodException: android.app.NotificationChannel.getTrimmedString [class java.lang.String]
at java.lang.Class.getMethod(Class.java:2072)
at java.lang.Class.getDeclaredMethod(Class.java:2050)
at io.mockk.proxy.android.MethodDescriptor.getMethod(MethodDescriptor.kt:22)
at io.mockk.proxy.android.advice.Advice.getOrigin(Advice.kt:37)
at java.lang.reflect.Method.invoke(Native Method)
at io.mockk.proxy.android.AndroidMockKDispatcher.getOrigin(AndroidMockKDispatcher.java:117)
at android.app.NotificationChannel.getTrimmedString(Unknown Source:14)
at android.app.NotificationChannel.<init>(NotificationChannel.java:188)
```

**Comment by KlaartjeDB** [comment]
Any news on this issue? I have reproduced it as well.
