### ISSUE TITLE
mockkObject runs real object's initialization code

### ISSUE THREAD

**Issue by BastianVoigt** [mockk/mockk#261]
### Expected Behavior

When mocking an object, the actual object's code should not be called

### Current Behavior

The Object's initialization code is called by the EveryBlockEvaluator.

#### Steps to Reproduce

Given this code:

    object SomeObject {
      init {
        throw Exception("Gotcha 1!")
      }
      fun someMethod(): String {
        throw Exception("Gotcha 2!")
      }
    }

    class Test {
      @Test fun someTest() {
         mockkObject(SomeObject::class) {
             every { SomeObject.someMethod() } returns "FakeResult"
         }
      }
    }

The test fails with Exception "GOTCHA1"

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.9.1
* OS: Ubuntu Linux
* Kotlin version: 1.3.21
* JDK version: 8
* JUnit version: 4
* Type of test: unit test

**Comment by oleksiyp** [comment]
This is simplest case. Will check but have doubts. Can you meanwhile enable logback logging and send trace level logs

**Comment by BastianVoigt** [comment]
22:23:07,443 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
22:23:07,443 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
22:23:07,444 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/home/bvoigt/privat/projects/mockkbug/out/test/resources/logback.xml]
22:23:07,540 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
22:23:07,541 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
22:23:07,549 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
22:23:07,618 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
22:23:07,618 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
22:23:07,618 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
22:23:07,619 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to TRACE
22:23:07,619 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
22:23:07,619 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
22:23:07,620 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@e45f292 - Registering current configuration as safe fallback point

2019-02-27 22:23:07 [main] TRACE io.mockk.impl.JvmMockKGateway - Starting JVM MockK implementation. Java version = 1.8.0_191. 
2019-02-27 22:23:07 [main] TRACE i.m.proxy.jvm.JvmMockKAgentFactory - Byte buddy agent installed
2019-02-27 22:23:07 [main] TRACE i.m.p.jvm.dispatcher.BootJarLoader - Bootstrap class loaded io.mockk.proxy.jvm.dispatcher.JvmMockKDispatcher
2019-02-27 22:23:07 [main] TRACE i.m.p.jvm.dispatcher.BootJarLoader - Bootstrap class loaded io.mockk.proxy.jvm.dispatcher.JvmMockKWeakMap
2019-02-27 22:23:07 [main] TRACE i.m.p.jvm.dispatcher.BootJarLoader - Bootstrap class loaded io.mockk.proxy.jvm.dispatcher.JvmMockKWeakMap$StrongKey
2019-02-27 22:23:07 [main] TRACE i.m.p.jvm.dispatcher.BootJarLoader - Bootstrap class loaded io.mockk.proxy.jvm.dispatcher.JvmMockKWeakMap$WeakKey
2019-02-27 22:23:08 [main] TRACE i.m.i.instantiation.JvmInstantiator - Building empty instance void
2019-02-27 22:23:08 [main] TRACE i.m.proxy.jvm.ObjenesisInstantiator - Creating new empty instance of class java.lang.Void
2019-02-27 22:23:08 [main] DEBUG i.m.i.i.JvmStaticMockFactory - Creating object mockk for KClassImpl
2019-02-27 22:23:08 [main] TRACE i.m.i.i.JvmStaticMockFactory - Building object proxy for KClassImpl hashcode=50a638b5
2019-02-27 22:23:08 [main] TRACE i.m.p.j.t.InlineInstrumentation - Retransforming [class kotlin.reflect.jvm.internal.KClassImpl, interface kotlin.reflect.KClass, interface kotlin.reflect.KDeclarationContainer, interface kotlin.reflect.KAnnotatedElement, interface kotlin.reflect.KClassifier, interface kotlin.reflect.jvm.internal.KClassifierImpl, class kotlin.reflect.jvm.internal.KDeclarationContainerImpl, interface kotlin.jvm.internal.ClassBasedDeclarationContainer, class java.lang.Object]
2019-02-27 22:23:08 [main] TRACE io.mockk.proxy.jvm.ProxyMaker - Taking instance of class kotlin.reflect.jvm.internal.KClassImpl itself because it is final.
2019-02-27 22:23:08 [main] TRACE io.mockk.proxy.jvm.ProxyMaker - Attaching to object mock for class kotlin.reflect.jvm.internal.KClassImpl
2019-02-27 22:23:09 [main] DEBUG io.mockk.impl.stub.CommonClearer - Clearing [KClassImpl(object KClassImpl)] mocks ClearOptions(answers=true, recordedCalls=true, childMocks=true, verificationMarks=true, exclusionRules=true)
2019-02-27 22:23:09 [main] DEBUG i.m.i.r.states.AnsweringState - Answering class SomeObject on KClassImpl(object KClassImpl).getJClass()
2019-02-27 22:23:09 [main] DEBUG i.m.i.r.states.AnsweringState - Answering 296347592 on KClassImpl(object KClassImpl).hashCode()
2019-02-27 22:23:09 [main] DEBUG i.m.i.r.states.AnsweringState - Answering class SomeObject on KClassImpl(object KClassImpl).getJClass()
2019-02-27 22:23:09 [main] DEBUG i.m.i.r.states.AnsweringState - Answering 296347592 on KClassImpl(object KClassImpl).hashCode()
2019-02-27 22:23:09 [main] TRACE i.m.i.recording.CommonCallRecorder - Starting stubbing

java.lang.Exception: Gotcha

	at SomeObject.someFunction(SomeObject.kt:3)
	at SomeTest$someTest$1$1.invoke(SomeTest.kt:9)
	at SomeTest$someTest$1$1.invoke(SomeTest.kt:5)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:24)
	at io.mockk.impl.eval.RecordedBlockEvaluator$enhanceWithNPERethrow$1.invoke(RecordedBlockEvaluator.kt:74)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:36)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalEvery(API.kt:92)
	at io.mockk.MockKKt.every(MockK.kt:104)
	at SomeTest.someTest(SomeTest.kt:9)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by oleksiyp** [comment]
You mocked KClass somewhere else, maybe because of that

**Comment by oleksiyp** [comment]
Ah sorry

**Comment by oleksiyp** [comment]
Should be `mockkObject(SomeObject) {...}`

**Comment by BastianVoigt** [comment]
OK, now it works. The initialization of SomeObject is still called though. Is this on purpose?

**Comment by oleksiyp** [comment]
Yes initialization is fine. mockkObject is a way to actually create in place spy

**Comment by BastianVoigt** [comment]
OK fine then ...

**Comment by absentmindedguy** [comment]
Is there anyway to... override or prevent or mock the initialisation of objects?

**Comment by oleksiyp** [comment]
You can create a mock of an object, but it will be another instance and violate singleton assumption of only one object in the system.

**Comment by OliverCulleyDeLange** [comment]
> Is there anyway to... override or prevent or mock the initialisation of objects?

I also want to know this. Calling down to the real implementation isn't what i expect when I'm mocking something. For example, if the method i'm mocking calls down into some native code that isn't on the classpath for testing.

**Comment by NathanMDT** [comment]
> You can create a mock of an object, but it will be another instance and violate singleton assumption of only one object in the system.

How is that done? I thought that's what mockkObject was doing.
