### ISSUE TITLE
NullPointerException when use LocalDateTime args

### ISSUE THREAD

**Issue by bulbulpaul** [mockk/mockk#265]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

#### Explanation/Details
I created a function that takes LocalDateTime as an argument, and made that function Mock. At that time NullPointerExeption occurred when defining the argument part of LocalDateTime to be Mocked with any ().

But, NullPointerException is occurring when error message creation of the MockKException.
https://github.com/mockk/mockk/blob/d3d0ec621d4b9232a156bb95841af374e1c68173/mockk/common/src/main/kotlin/io/mockk/impl/recording/SignatureMatcherDetector.kt#L98-L100

So, I have two problems.
- This Issue may have problems with above NullPointerException.
- This may have a problem that cannot be defined using any ().

#### Context

* MockK version: I tried 1.8.13.kotlin13 and 1.9.1
* OS: MacOS 
* Kotlin version:  1.3.20
* JDK version: 11
* JUnit version: 5
* Type of test: unit test

#### Stack trace

```
2019-03-03 10:51:59.265  INFO 51974 --- [           main] c.m.e.i.IssueSampleApplicationTests      : Starting IssueSampleApplicationTests on MBP15UAQ-A041 with PID 51974 (started by nookada in /Users/nookada/dev/merrylab/sandbox/issue-sample)
2019-03-03 10:51:59.268  INFO 51974 --- [           main] c.m.e.i.IssueSampleApplicationTests      : No active profile set, falling back to default profiles: default
2019-03-03 10:52:02.644  INFO 51974 --- [           main] c.m.e.i.IssueSampleApplicationTests      : Started IssueSampleApplicationTests in 4.178 seconds (JVM running for 8.104)

java.lang.NullPointerException
	at java.base/java.time.LocalDateTime.toString(LocalDateTime.java:1972)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
	at com.merrylab.example.issuesample.User.toString(ExampleComponent.kt)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
	at java.base/java.util.AbstractCollection.toString(AbstractCollection.java:473)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
	at io.mockk.impl.recording.SignedCall.toString(SignedCall.kt)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at kotlin.text.StringsKt__StringBuilderKt.appendElement(StringBuilder.kt:61)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:2291)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:2308)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:2307)
	at io.mockk.impl.recording.SignatureMatcherDetector.detect(SignatureMatcherDetector.kt:99)
	at io.mockk.impl.recording.states.RecordingState.signMatchers(RecordingState.kt:38)
	at io.mockk.impl.recording.states.RecordingState.round(RecordingState.kt:30)
	at io.mockk.impl.recording.CommonCallRecorder.round(CommonCallRecorder.kt:45)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:59)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:25)
	at io.mockk.MockKDsl.internalEvery(API.kt:93)
	at io.mockk.MockKKt.every(MockK.kt:104)
	at com.merrylab.example.issuesample.IssueSampleApplicationTests.error(IssueSampleApplicationTests.kt:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:532)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:171)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:108)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
data class User(val id: Long, val name: String, val createTimestamp: LocalDateTime, val updateTimestamp: LocalDateTime)

@Service
class ExampleService(val exampleRepository: ExampleRepository) {

    fun save(user: User) {
        exampleRepository.insert(user)
    }
}


@Repository
class ExampleRepository {

    fun insert(user: User) {

    }
}
```
Test Code
```kotlin
@ExtendWith(SpringExtension::class)
@SpringBootTest
class IssueSampleApplicationTests {

    val exampleRepository = mockk<ExampleRepository>()

    val exampleService = ExampleService(exampleRepository)

    val ldt = LocalDateTime.of(2019, 3, 1, 0,0)

    @Test
    fun exampleSuccess() {
        every { exampleRepository.insert(User(1, "expect", ldt, ldt)) } just Runs   // success

        exampleService.save(User(1, "expect", ldt, ldt))

        verify { exampleRepository.insert(User(1, "expect", ldt, ldt)) }
    }

    @Test
    fun exampleError() {
        every { exampleRepository.insert(User(1, "expect", any(), any())) } just Runs  // throw NullPointerException

        exampleService.save(User(1, "expect", ldt, ldt))

        verify { exampleRepository.insert(User(1, "expect", any(), any())) }
    }
}
```

**Comment by oleksiyp** [comment]
Thanks, will check later

**Comment by stavling** [comment]
I'm also running into this issue, any updates on this one? :) Can't find anything in the docs about it.

**Comment by trohovsky** [comment]
I am also running into this issue.

**Comment by alexandrklimov** [comment]
This issue is still actual.
kotlin 1.4.30
mockk 1.9.3

**Comment by Endhuine** [comment]
I think this is not an issue:
While defining a mock for a function you can use a [matcher](https://github.com/mockk/mockk#matchers) on one or more of that function parameters, so if you have:
```kotlin
fun foo(arg: String)
```
you can ask mockk to match `arg` with a matcher. 
But in your example, you are asking mockk to match an argument inside a constructor of that function's argument.
To make it clear, you have a `User` and a function to `save(user)`
```kotlin
data class User(val id: Long, val name: String, val createTimestamp: LocalDateTime, val updateTimestamp: LocalDateTime)
fun save(user: User)
```
and you are trying to match `createTimestamp` and `updateTimestamp` which are not a parameter of `save(user)`.

The error sure could be confusing, what is going on here is this: 
- mockk query `save(user)` to find how many parameters are required for this function and found out is **1**. 
- Checks how many matchers are present in the `every` block and found out is **2**. 
- Tries to see if those matchers (which are looking for `LocalDateTime`) can match the single parameter of type `User` and find out it cannot.
- Tries to print an error: `Failing matching mocking signature for...` and fails to tell you: your `save(user` function does not match those two any LocalDateTime matcher. 

So if you want to do a partial match of a complex parameter such `User` you should use `match {}` instead
```Kotlin
every { save(match { it.id == 1L && it.name == "expect" }) } just Runs
```

**Comment by Raibaz** [comment]
@Endhuine has a point, I don't think this is an issue. Closing it.
