### ISSUE TITLE
Mocking private class extension functions

### ISSUE THREAD

**Issue by erikhuizinga** [mockk/mockk#269]
### Expected Behavior

I can mock and verify private extension functions.

### Current Behavior

I can't mock nor verify private extension functions (or I don't know how).

I've searched for this issue, because I can imagine other users have run into this too, but I didn't find anything related.

#### Steps to Reproduce

See MWE below.

#### Context

* MockK version: 1.9.1
* OS: macOS 10.14.3 (18D109)
* Kotlin version: 1.3.21
* JDK version:
  - JRE: 1.8.0_152-release-1248-b01 x86_64
  - JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
* JUnit version: 4.12
* Type of test: unit test OR ~android instrumented test~

#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------

io.mockk.MockKException: can't find function extension() for dynamic call

	at io.mockk.InternalPlatformDsl.dynamicCall(InternalPlatformDsl.kt:122)
	at io.mockk.MockKMatcherScope$DynamicCall.invoke(API.kt:1861)
	at com.example.PrivateExtensionFunctionTest$$special$$inlined$with$lambda$1.invoke(PrivateExtensionFunctionTest.kt:15)
	at com.example.PrivateExtensionFunctionTest$$special$$inlined$with$lambda$1.invoke(PrivateExtensionFunctionTest.kt:9)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:24)
	at io.mockk.impl.eval.RecordedBlockEvaluator$enhanceWithNPERethrow$1.invoke(RecordedBlockEvaluator.kt:74)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:36)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:25)
	at io.mockk.MockKDsl.internalEvery(API.kt:92)
	at io.mockk.MockKKt.every(MockK.kt:104)
	at com.example.PrivateExtensionFunctionTest.test(PrivateExtensionFunctionTest.kt:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
package com.example

import io.mockk.every
import io.mockk.mockkStatic
import io.mockk.spyk
import io.mockk.verify
import org.junit.Test

class PrivateExtensionFunctionTest {
    @Test
    fun test() = mockkStatic(A::class) {
        val bSpy = spyk<B>(recordPrivateCalls = true)

        with(A()) {
            every { bSpy["extension"]() } answers { println("Hello, MockK!") }
            a(bSpy)
            verify { bSpy.b() }
        }
    }
}

class A {
    fun a(b: B) = b.extension()
    private fun B.extension() = b()
}

class B {
    fun b(): Unit = TODO("not implemented!")
}

// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by oleksiyp** [comment]
Hi. The first thing to consider is that you need to mock the class where a function is declared to achieve mocking, so it will be `A`. I don't know if currently extension functions are callable through dynamic calls. I will check later this.

**Comment by oleksiyp** [comment]
Seems it works for extension functions:

```
package abc

import io.mockk.every
import io.mockk.spyk
import io.mockk.verify
import org.junit.Test

class PrivateExtensionFunctionTest {

    class A {
        fun a(b: B) = b.extension()
        private fun B.extension() = b()
    }

    class B {
        fun b(): Unit = TODO("not implemented!")
    }

    @Test
    fun test() {
        val a = spyk<A>()
        val b = spyk<B>()

        every { a["extension"](b) } answers { println("Hello, MockK!") }
        a.a(b)
        verify(exactly = 0) { b.b() }
    }
}
```

**Comment by erikhuizinga** [comment]
Thank you, very nice! I'm closing this as there is a solution to my original issue.

To the reader: note that `B` is only mocked (spied on) because we want to verify that `b.b()` is never actually called. To mock `every { a["extension"](b) } answers { println("Hello, MockK!") }` we don't need to mock (or spy on) `b`, because `extension` is class `A`'s function with `b` as a parameter (under the hood).

I have some questions though, so I hope you can answer them:

Why is it not necessary to use `val a = spyk<A>(recordPrivateCalls = true)`? We do mock a private function (the extension) with the `["extension"]` notation. I don't think that should be possible if private calls aren't recorded. Is this a bug? Or a feature? This is probably related to the fact that `verify { a["extension"](b) }` fails unless you do use `val a = spyk<A>(recordPrivateCalls = true)`. So it seems that a spy can always mock private functions? But it cannot verify them, unless explicitly recording them?
