### ISSUE TITLE
Bug: unmockkStatic fail to unmock and result in NoSuchMethodException

### ISSUE THREAD

**Issue by jeffreyfhow23** [mockk/mockk#270]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Expected Behavior

`unmockkStatic` should unmock things that were previously mocked with `mockStatic`

### Current Behavior

`unmockkStatic` is not unmocking things that were previously mocked with `mockStatic` that had an `every{}` block defined

#### Steps to Reproduce
1. Run `MockkTest` (see below) as a class so that all tests are run together
2. Notice how the tests succeed
3. Uncomment the `every{}` block in `otherTest()`
4. Notice how the tests fails despite `unmockkStatic` being called. This happens at the `bitmap.compress(format, 100, outStream)` line, which throws a `NoSuchMethodException`

#### Context
Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.9
* OS: API 28 (Since only API 28+ and above can use mockkStatic)
* Kotlin version: 1.3.21
* JDK version: 1.8.0_191
* JUnit version: 4.12
* Type of test: android instrumented test

#### Stack trace
```
java.lang.NoSuchMethodException: checkRecycled [class java.lang.String]
at java.lang.Class.getMethod(Class.java:2068)
at java.lang.Class.getDeclaredMethod(Class.java:2047)
at io.mockk.proxy.android.MethodDescriptor.getMethod(MethodDescriptor.kt:22)
at io.mockk.proxy.android.advice.Advice.getOrigin(Advice.kt:37)
at java.lang.reflect.Method.invoke(Native Method)
at io.mockk.proxy.android.AndroidMockKDispatcher.getOrigin(AndroidMockKDispatcher.java:117)
at android.graphics.Bitmap.checkRecycled(Unknown Source:14)
at android.graphics.Bitmap.compress(Bitmap.java:1335)
at com.myapp.FileHelper.saveBitmapToTempDirectory(FileHelper.kt:14)
at com.myapp.MockkTest.testSaveBitmapToTempDirectoryWithSuccess(MockkTest.kt:37)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:388)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
```

#### Minimal reproducible code (the gist of this issue)
```
class FileHelper @Inject constructor(private val application: Application) {
    fun saveBitmapToTempDirectory(bitmap: Bitmap, filename: String, format: Bitmap.CompressFormat): File {
        val tempDirectory = File(application.cacheDir, "images").apply { mkdirs() }
        val file = File(tempDirectory, "$filename.${format.name.toLowerCase()}")
        FileOutputStream(file).use { outStream ->
            bitmap.compress(format, 100, outStream)
        }
        return file
    }
}
```

```
@RunWith(AndroidJUnit4::class)
class MockkTest {

    @Test
    fun otherTest(){
        val application = InstrumentationRegistry.getInstrumentation().targetContext.applicationContext as Application
        val bitmap = BitmapFactory.decodeResource(application.resources, R.drawable.androidguy)
        val mockInputStream = mockk<InputStream>(relaxed = true)

        //The following code triggers the break
        mockkStatic(BitmapFactory::class)
        // every {
        //    BitmapFactory.decodeStream(mockInputStream)
        // } returns bitmap
        unmockkStatic(BitmapFactory::class)

        // Tests other things...
    }


    @Test
    fun testSaveBitmapToTempDirectoryWithSuccess() {
        val application = InstrumentationRegistry.getInstrumentation().targetContext.applicationContext as Application
        val file = FileHelper(application).saveBitmapToTempDirectory(
            BitmapFactory.decodeResource(application.resources, R.drawable.androidguy),
            "bitmap",
            Bitmap.CompressFormat.PNG
        )
        Assert.assertTrue(file.absolutePath.endsWith("bitmap.png"))
    }
}
```

**Comment by oleksiyp** [comment]
Thank you for the report

**Comment by jeffreyfhow23** [comment]
Thanks for looking into

**Comment by IsaacBerman** [comment]
Has there been any update on this?

**Comment by MageJohn** [comment]
So this seems to only happen when the static class has a `static {}` initialization block. If this block runs after the static class is mocked, the initialization that the block performs will be broken. While the class is mocked this is fine, but once the class is unmocked the initialization block isn't run again and so later code that uses the class will most likely fail.

For me, I was successfully able to work around the issue by accessing something on the static class *before* mocking, so that the initialization block was run on the real class.
