### ISSUE TITLE
Instrumented tests not running on Android 8.0 and bellow

### ISSUE THREAD

**Issue by luanalbineli** [mockk/mockk#277]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed. May it be related to https://github.com/mockk/mockk/issues/188?
- [X] I checked the documentation and found no answer

### Expected Behavior

MockK mock fragment/activity dependencies in  instrumented tests correctly on Android 8.0 and bellow.

### Current Behavior

It seens like the dependencies are not beeing mocked.

### Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

#### Steps to Reproduce

The problem occurs on Android 8.0 and bellow, and it happens when a mocked object have a dependency. I'm currently using Dagger 2 to control my DI. I've mocked the component corrently for tests, but when I try to mock a response with `every()` the test crashes, outputting me a NPE when the suposed mocked object tries to access it's null dependency.

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.9.2
* OS: From Android 4.2 to 8.0
* Kotlin version: 1.3.21
* JDK version: - 
* JUnit version: 4.12
* Type of test: android instrumented test

#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.mockkdagger.repository.RepositoryDependency.dependencyValue()' on a null object reference
at com.mockkdagger.repository.MainRepository.getValue(MainRepository.kt:8)
at com.mockkdagger.MainActivityTest$test_check_textview_content$1.invoke(MainActivityTest.kt:70)
at com.mockkdagger.MainActivityTest$test_check_textview_content$1.invoke(MainActivityTest.kt:35)
at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:24)
at io.mockk.impl.eval.RecordedBlockEvaluator$enhanceWithNPERethrow$1.invoke(RecordedBlockEvaluator.kt:74)
at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:36)
at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
at io.mockk.MockKDsl.internalEvery(API.kt:92)
at io.mockk.MockKKt.every(MockK.kt:104)
at com.mockkdagger.MainActivityTest.test_check_textview_content(MainActivityTest.kt:69)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at androidx.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:104)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:388)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1932)
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

#### Minimal reproducible code (the gist of this issue)

The code used bellow can be found here: https://github.com/luanalbineli/mockk-dagger2-instrumented-tests

```kotlin
class MainActivity : AppCompatActivity() {
    @Inject
    lateinit var mMainRepository: MainRepository

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        (applicationContext as DaggerComponentProvider).component.inject(this)

        mMainRepository.getValue().observe(this, Observer { value ->
            text_main_activity_hello.text = value
        })
    }
}

class RepositoryDependency @Inject constructor() {
    fun dependencyValue() = "RepositoryDependency"
}

class MainRepository @Inject constructor(private val repositoryDependency: RepositoryDependency) {
    fun getValue() = MutableLiveData<String>().also {
        it.value = "MainRepository_${repositoryDependency.dependencyValue()}"
    }
}

@Singleton
@Component(modules = [
    RepositoryModuleTest::class
])
interface AppComponentTest: AppComponent {
    @Component.Builder
    interface Builder {
        fun build(): TestAppComponent
    }

    fun inject(test: MainActivityTest)
}

@Module
object RepositoryModuleTest {
    @Provides
    @JvmStatic
    @Singleton
    fun mainRepository(): MainRepository = mockk() // <--- Here I use MockK
}

@RunWith(AndroidJUnit4::class)
class MainActivityTest {
    @Rule
    @JvmField
    val taskExecutorRule = InstantTaskExecutorRule()

    @Rule
    @JvmField
    val mActivityRule = ActivityTestRule(MainActivity::class.java, true, false)

    private val mContext: Context = InstrumentationRegistry.getInstrumentation().targetContext

    private val mApp = mContext.applicationContext as DaggerComponentProvider

    private val testAppComponent by lazy {
        DaggerAppComponentTest.builder()
            .build()
    }

    @Inject
    lateinit var mMainRepository: MainRepository

    @Before
    fun daggerTestSetup() {
        mApp.component = testAppComponent
        testAppComponent.inject(this)
    }

    @Test
    fun test_check_textview_content() {
        val expectedStringValue = "EXPECTED_STRING_VALUE"
        val getValueExpectedResultLiveData = MutableLiveData<String>().also {
            it.value = expectedStringValue
        }

        every {
            mMainRepository.getValue() // Fails here
        } returns getValueExpectedResultLiveData

        mActivityRule.launchActivity(null)

        onView(withId(R.id.text_main_activity_hello))
            .check(matches(withText(expectedStringValue)))
    }
}
```

**Comment by luanalbineli** [comment]
Hi @oleksiyp , do you have any news about it?

Sorry to call you directly, but we to define if we'll use MockK or Mockito on your instrumented tests.
Thanks in advance \o/

**Comment by oleksiyp** [comment]
TBH, debugging android instrumented test is very sophisticated and slow thing, so if you feel that Mockito is doing job don't hesitate to choose it, MockK AIT support is not perfect. Need some time to get it to good quality

**Comment by oleksiyp** [comment]
Just to mention, that behind dexmaker stands LinkedIn and as I understand full time employees. As I said it is just not perfect now, with time things should improve.

**Comment by oleksiyp** [comment]
I analyzed your code and not able to understand how mock is created.

**Comment by luanalbineli** [comment]
Hi @oleksiyp ,

I've forgot to add the test component/module for it. I've updated the question with two new classes: `RepositoryModuleTest` and `AppComponentTest`. The first is the one that uses MockK. 

I also forgot to mention that I've tested with AS 3.3, 3.4 and 3.5 (canary 7 and 8). If you download the sample code (https://github.com/luanalbineli/mockk-dagger2-instrumented-tests), you need to use AS 3.5.

Thanks.

**Comment by mkhitarstdev** [comment]
I have same issue, below Android 8.0 my instrumented tests fails

**Comment by mokkun** [comment]
Same here was a bit confused to why my tests were suddenly failing on Android N, just to realise that I often run them on my Android 10 device. Not a blocker, but it would be nice to have this caveat documented somewhere.

**Comment by Martinsbl** [comment]
I think I might have this issue too. My instrumentation tests fail on my 
* Nexus 5X running Android 8.1.0 (API 27)
* Motorola Moto G running Android 7.0 (API 24)
but tests run fine on devices with API 28 or above

MockK version: 1.12.3 & 1.12.5
Kotlin version: 1.7.10
