### ISSUE TITLE
Bug: ClassLoaderStrategy while mocking javax.sql.DataSource

### ISSUE THREAD

**Issue by atomcat1978** [mockk/mockk#280]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

Test should run as it did with version 1.9.2

### Current Behavior

Test fails: 
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access using Lookup on io.mockk.proxy.jvm.ClassLoadingStrategyChooser (file:/Users/tom/.m2/repository/io/mockk/mockk-agent-jvm/1.9.3/mockk-agent-jvm-1.9.3.jar) to interface javax.sql.DataSource
WARNING: Please consider reporting this to the maintainers of io.mockk.proxy.jvm.ClassLoadingStrategyChooser
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

java.lang.NoClassDefFoundError: io/mockk/proxy/jvm/advice/jvm/JvmMockKProxyInterceptor

	at java.sql/javax.sql.DataSource$Subclass0.getConnection(Unknown Source)
// Rest removed
```
Also no warnings in v. 1.9.2 as opposed to the one above.

#### Steps to Reproduce

Try this test:

```
package bug

import io.mockk.every
import io.mockk.mockk
import org.junit.Test
import javax.sql.DataSource

class TestFails {
    private val dataSource = mockk<DataSource>()

    @Test
    fun failing() {
        every { dataSource.getConnection(any(), any()) } returns null
    }
}
```

#### Context

* MockK version: 1.9.3
* OS: MackOs Mojave v. 10.14.2
* Kotlin version: 
* JDK version: 
   * java 10.0.2 2018-07-17
   * Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
   * Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
* JUnit version: 4.12
* Type of test: Unit test

#### Stack trace

Run the test example above!

**Comment by oleksiyp** [comment]
Thanks for the report. Related to #276

**Comment by atomcat1978** [comment]
👍Thanks for taking a look at it!

**Comment by Happy-Neko** [comment]
Any news on this issue?
Having the same problem with Java 11, Kotlin 1.3 and Mockk **1.9.3**.

    Illegal reflective access using Lookup on io.mockk.proxy.jvm.ClassLoadingStrategyChooser (file:gradle/caches/modules-2/files-2.1/io.mockk/mockk-agent-jvm/1.9.3/d6f7b4d893caf1cda2bb28ee637b247ced5d5eab/mockk-agent-jvm-1.9.3.jar) to interface org.w3c.dom.NodeList

Same test with Mockk **1.9.2** works fine.

**Comment by agebhar1** [comment]
Consider to re-open this issue because it still exists. Thx!

**Comment by lrstndm** [comment]
It seems to be an issue when mocking the interface DataSource. I am using Hikari as data source implementation, therefore switching the mock to `private val dataSource = mockk<HikariDataSource>()` fixed the problem for me.

I am not sure if this is happening to other interfaces also and if mocking interfaces should work.

**Comment by wfhartford** [comment]
I encountered this same error when mocking the `SSLSession` interface. I was able to work around it with a simple hand-coded stub.

**Comment by ephemient** [comment]
Running into this with Java 11 and Robolectric.
```
    java.lang.NoClassDefFoundError: io/mockk/proxy/jvm/advice/jvm/JvmMockKProxyInterceptor
        at java.xml/org.xml.sax.Attributes$Subclass4.getLength(Unknown Source)
```

**Comment by jimirocks** [comment]
I encountered the same problem trying to mock `javax.lang.model.element.Element`
```kotlin
mockk<Element> {
            every { simpleName } returns mockk {
                every { toString() } returns "ExampleEntity"
            }
        }
```
```
10:41:00.981 [main] DEBUG io.mockk.impl.instantiation.AbstractMockFactory - Creating mockk for Element name=#1
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access using Lookup on io.mockk.proxy.jvm.ClassLoadingStrategyChooser (file:/home/jimi/.gradle/caches/modules-2/files-2.1/io.mockk/mockk-agent-jvm/1.10.0/9b42a88de1f13e6a11fc512e9147a09c4b4bd3bf/mockk-agent-jvm-1.10.0.jar) to interface javax.lang.model.element.Element
WARNING: Please consider reporting this to the maintainers of io.mockk.proxy.jvm.ClassLoadingStrategyChooser
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release


java.lang.NoClassDefFoundError: io/mockk/proxy/jvm/advice/jvm/JvmMockKProxyInterceptor

	at java.compiler@11.0.9.1/javax.lang.model.element.Element$Subclass0.getSimpleName(Unknown Source)
	at com.gooddata.data.apt.IgnoredPropertyTest$should build from elements$classElement$1$1.invoke(IgnoredPropertyTest.kt:23)
	at com.gooddata.data.apt.IgnoredPropertyTest$should build from elements$classElement$1$1.invoke(IgnoredPropertyTest.kt:17)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:24)
	at io.mockk.impl.eval.RecordedBlockEvaluator$enhanceWithNPERethrow$1.invoke(RecordedBlockEvaluator.kt:74)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:36)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalEvery(API.kt:92)
	at io.mockk.MockKKt.every(MockK.kt:98)
	at com.gooddata.data.apt.IgnoredPropertyTest.should build from elements(IgnoredPropertyTest.kt:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:212)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:208)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:128)
Caused by: java.lang.ClassNotFoundException: io.mockk.proxy.jvm.advice.jvm.JvmMockKProxyInterceptor
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 79 more
```

**Comment by Tmilly** [comment]
Any update on this? Im stuck on Java version 1.8 until this is fixed because anything higher causes this when mocking `javax.sql.DataSource`

**Comment by ptramsey** [comment]
I'm also seeing this exact behavior, trying to mock javax.xml.parsers.DocumentBuilder and org.w3c.dom.Node.

**Comment by eddiellopez** [comment]
I'm experiencing the same issue after migrating to JDK 11 on Android. I've seen this when trying to mock `javax.net.ssl.HttpsURLConnection` and `javax.net.ssl.SSLSocketFactory`. Mockk 1.11.0.

**Comment by mpost** [comment]
Similar to other reports i am seeing the exception when trying to mockk the `SSLSession` on java13.

**Comment by ikovalyov** [comment]
Java 11, DataSource, 

```
io/mockk/proxy/jvm/advice/jvm/JvmMockKProxyInterceptor
java.lang.NoClassDefFoundError: io/mockk/proxy/jvm/advice/jvm/JvmMockKProxyInterceptor
```

**Comment by ikovalyov** [comment]
Do you know if this will be released soon? 👍

**Comment by btegenbosch** [comment]
You can work around it until the fix has been releases by simply removing the direct reference to the `DataSource` interface.

```
interface MockDataSource : DataSource

private val mockDataSource = mockk<MockDataSource>()
```

**Comment by angryziber** [comment]
Workaround works for abstract classes as well, e.g. `HttpExchange` from module `jdk.httpserver`

**Comment by ikovalyov** [comment]
Do you know of it was released https://github.com/mockk/mockk/releases/tag/1.12.1 here?
