### ISSUE TITLE
Bug: private property in object is not possible to call dynamically

### ISSUE THREAD

**Issue by timnew** [mockk/mockk#284]
### Expected Behavior

I have a object as following.

```kt
object Analytica {
  private lateinit var repository: AnalyticaRepository
}
```
The `repository` is accessed by all nested classes. And in production. There is no direct set to the property, and in production, will be initialized by a relatively complicated process that involves dependency injection and the others.

In test, I have following code:

```kt
val repository = mockkClass(AnalyticaRepository::class, relaxed = true) {

mockkObject(Analytica, recordPrivateCalls = true)

every { Analytica getProperty "repository" } propertyType AnalyticaRepository::class returns repository
```

### Issue

I would expect the `every` clause setup the the mock properly, but in practise, it throws an exception:

```
java.lang.IllegalArgumentException: Callable expects 0 arguments, but 1 were provided.
	at kotlin.reflect.jvm.internal.FunctionCaller.checkArguments(FunctionCaller.kt:43)
	at kotlin.reflect.jvm.internal.FunctionCaller$FieldGetter.call(FunctionCaller.kt:163)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:107)
	at kotlin.reflect.jvm.internal.KProperty1Impl.get(KProperty1Impl.kt:33)
	at io.mockk.InternalPlatformDsl.dynamicGet(InternalPlatformDsl.kt:147)
	at io.mockk.MockKMatcherScope.getProperty(API.kt:1695)
         at <where the every clause is>
         at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:22)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:31)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:25)
	at io.mockk.MockKDsl.internalEvery(API.kt:93)
	at io.mockk.MockKKt.every(MockK.kt:104)
         at <where the every clause is again>
```

### My assumption

I traced the code a little bit to understand the issue, and seems the issue is caused by I'm using `getProperty` on property for `object`:

1. I assume `KProperty1Impl` is designed to be used for instance property, so it passed `this` as `receiver`.
2. But the property is declared on `object`, which is equivalent to `static` property that doesn't need `receiver` at all. So the reflected `FunctionCaller.arity` returns `0` rather than `1`.
The inconsistent context caused the error.

### Proposed solution

Not sure it is possible to provide a `getStaticProperty` similar to `getProperty`, but avoid to pass the `this`.

OR

Allow `getProperty` to check the `receiver` if it is a `singleton` object, avoid to pass receiver to underneath `FunctionCaller`

#### Context

* MockK version: 1.8.7
* OS: macOS 10.14.2
* Kotlin version: 1.3.10
* JDK version: Android BuildTools 28 + Java8 
* JUnit version: 4.12
* Type of test: Plain JUnit Test
  
#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    testImplementation 'junit:junit:4.12'
    testImplementation "io.mockk:mockk:1.8.7"
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
package io.mockk.gh

import io.mockk.every
import io.mockk.mockkObject
import io.mockk.unmockkAll
import org.assertj.core.api.Assertions.assertThat
import org.junit.After
import org.junit.Before
import org.junit.Test

class TestTest {
  object TestHost {
    private lateinit var property: String

    fun foo() = "Value is $property"
  }

  @Before
  fun setUp() {
    mockkObject(TestHost)
  }

  @Test
  fun `it should pass`() {
    every { TestHost getProperty "property" } returns "Something"

    assertThat(foo()).isEqualTo("Value is Something")
  }

  @After
  fun tearDown() {
    unmockkAll()
  }
}

// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by timnew** [comment]
This is not stale issue 😂

**Comment by polson** [comment]
I also have this issue.  It works okay if your private properties are intialized using `lazy`.

**Comment by weaselflink** [comment]
Sadly the given example code also does not work for regular classes:
```kotlin
import io.mockk.every
import io.mockk.mockkObject
import io.mockk.unmockkAll
import org.assertj.core.api.Assertions.assertThat
import org.junit.After
import org.junit.Before
import org.junit.Test

class TestTest2 {
  class TestHost2 {
    private lateinit var property: String

    fun foo() = "Value is $property"
  }
  val testHost = mockk<TestHost2>()

  @Test
  fun `it should pass`() {
    every { testHost getProperty "property" } returns "Something"

    assertThat(testHost.foo()).isEqualTo("Value is Something")
  }
}
```

Does not pass but gives `io.mockk.MockKException: Missing calls inside every { ... } block.`
Am I missing something about `getProperty`?

**Comment by timnew** [comment]
@weaselflink Very interesting point.

I think in your test, there is a little bit bug, the mock is created in the strict mode and `foo()` was not being setup before invoked, so you ended up a different error. But the idea stands

I extended the experiment a little bit

```kt
class TestCase1 {
  object TestHost {
    private lateinit var property: String

    fun foo() = "Value is $property"
  }

  @Before
  fun setUp() {
    mockkObject(TestHost)
  }

  @Test
  fun `it should pass`() {
    every { TestHost getProperty "property" } returns "Something"

    assertThat(TestHost.foo()).isEqualTo("Value is Something")
  }

  @After
  fun tearDown() {
    unmockkAll()
  }
}

class TestCase2 {
  class TestHost {
    private lateinit var property: String

    fun foo() = "Value is $property"
  }

  lateinit var testHost: TestHost

  @Before
  fun setup() {
    testHost = spyk(TestHost(), recordPrivateCalls = true)
  }

  @Test
  fun `it should pass`() {
    every { testHost getProperty "property" } returns "Something"

    assertThat(testHost.foo()).isEqualTo("Value is Something")
  }
}

class TestCase3 {
  class TestHost {
    private var property: String = ""

    fun foo() = "Value is $property"
  }

  lateinit var testHost: TestHost

  @Before
  fun setup() {
    testHost = spyk(TestHost(), recordPrivateCalls = true)
  }

  @Test
  fun `it should pass`() {
    every { testHost getProperty "property" } returns "Something"

    assertThat(testHost.foo()).isEqualTo("Value is Something")
  }
}

class TestCase4 {
  class TestHost {
    var property: String = ""

    fun foo() = "Value is $property"
  }

  lateinit var testHost: TestHost

  @Before
  fun setup() {
    testHost = spyk(TestHost(), recordPrivateCalls = true)
  }

  @Test
  fun `it should pass`() {
    every { testHost getProperty "property" } returns "Something"

    assertThat(testHost.foo()).isEqualTo("Value is Something")
  }
}

class TestCase5 {
  class TestHost {
    lateinit var property: String

    fun foo() = "Value is $property"
  }

  lateinit var testHost: TestHost

  @Before
  fun setup() {
    testHost = spyk(TestHost(), recordPrivateCalls = true)
  }

  @Test
  fun `it should pass`() {
    every { testHost getProperty "property" } returns "Something"

    assertThat(testHost.foo()).isEqualTo("Value is Something")
  }
}

class TestCase6 {
  class TestHost {
    var property: String = ""

    fun foo() = "Value is $property"
  }

  lateinit var testHost: TestHost

  @Before
  fun setup() {
    testHost = spyk(TestHost(), recordPrivateCalls = true)
  }

  @Test
  fun `it should pass`() {
    every { testHost getProperty "property" } returns "Something"

    assertThat(testHost.foo()).isEqualTo("Value is Something")
  }
}

class TestCase7 {
  class TestHost {
    var property: String = ""

    fun foo() = "Value is $property"
  }

  lateinit var testHost: TestHost

  @Before
  fun setup() {
    testHost = spyk(TestHost(), recordPrivateCalls = true)
  }

  @Test
  fun `it should pass`() {
    every { testHost.property } returns "Something"

    assertThat(testHost.foo()).isEqualTo("Value is Something")
  }
}

class TestCase8 {
  class TestHost {
    var property: String = ""
      get() = "get"

    fun foo() = "Value is $property"
  }

  lateinit var testHost: TestHost

  @Before
  fun setup() {
    testHost = spyk(TestHost(), recordPrivateCalls = true)
  }

  @Test
  fun `it should pass`() {
    every { testHost.property } returns "Something"

    assertThat(testHost.foo()).isEqualTo("Value is Something")
  }
}

class TestCase9 {
  class TestHost {
    var property: String = ""
      get() = "get"

    fun foo() = "Value is $property"
  }

  lateinit var testHost: TestHost

  @Before
  fun setup() {
    testHost = spyk(TestHost(), recordPrivateCalls = true)
  }

  @Test
  fun `it should pass`() {
    every { testHost getProperty "property" } returns "Something"

    assertThat(testHost.foo()).isEqualTo("Value is Something")
  }
}

class TestCase10 {
  class TestHost {
    private var property: String = ""
      get() = "get"

    fun foo() = "Value is $property"
  }

  lateinit var testHost: TestHost

  @Before
  fun setup() {
    testHost = spyk(TestHost(), recordPrivateCalls = true)
  }

  @Test
  fun `it should pass`() {
    every { testHost getProperty "property" } returns "Something"

    assertThat(testHost.foo()).isEqualTo("Value is Something")
  }
}
```

And I found 
* `TestCase1` throws `java.lang.IllegalArgumentException: Callable expects 0 arguments, but 1 were provided.`
* `TestCase2` `TestCase3` throw `io.mockk.MockKException: Missing calls inside every { ... } block.`
* `TestCase4` `TestCase6` `TestCase7`  failed due to foo returns `Value is ` instead of `Value is Something`
* `TestCase5` throws `kotlin.UninitializedPropertyAccessException: lateinit property property has not been initialized`
* `TestCase8` `TestCase9` `TestCase10` passed

**Comment by timnew** [comment]
The learning I have from the experiments is that Mockk can only mock method but not the field. And Kotlin compiler is smart enough to avoid generating getter and setter when a plain field is enough.

So it is not the mockk's fault, but more about how Kotlin compiler works. 
To prove my point, I have the following test, which is identical to `TestCase7`, except I turn the property into `open`, which enforce `Kotlin` compiler to generate getter and setter, so it would pass now

```kt
class TestCase7_2 {
open   class TestHost {
   open  var property: String = ""

    fun foo() = "Value is $property"
  }

  lateinit var testHost: TestHost

  @Before
  fun setup() {
    testHost = spyk(TestHost(), recordPrivateCalls = true)
  }

  @Test
  fun `it should pass`() {
    every { testHost.property } returns "Something"

    assertThat(testHost.foo()).isEqualTo("Value is Something")
  }
}
```

I think the original issue is still valid, but mocking property has more issues than that, as there are so many factors that could make the mock fails, which makes the property mock become a mystery to work on. So maybe in mockk guideline can add `avoiding mock property when possible`

**Comment by oleksiyp** [comment]
It is quite unreal to deoptimize this case. So closing

**Comment by timnew** [comment]
@oleksiyp Can we mention this in the readme or doc, as it is quite easy to catch people about it.

**Comment by ecejmsr** [comment]
I'm trying to do something similar. For the TestCase05 did you have to make it open like mentioned above for TestCase07 for the `kotlin.UninitializedPropertyAccessException: lateinit property property has not been initialized`. I'm assuming the getter/setter for the lateinit property are not generated therefore I can't use `every { testHost getProperty "property" } returns "Something"`.

**Comment by wp292519413** [comment]
> ```kotlin
> TestCase3
> ```
How to solve the problem in TestCase3?

**Comment by Nodrex** [comment]
I have the same problem so how is progress going on this bug?
``` 
val spy = spyk(MemoryManager, recordPrivateCalls = true) 
every { spy.getProperty("adLifecycleObserverMap") }  answers { 
             fieldValue  
        }
```
This does not work :(
