### ISSUE TITLE
mocked suspending function does not answer

### ISSUE THREAD

**Issue by gladed** [mockk/mockk#288]
In Version 1.9.3, calling a mocked suspending function throws "no answer found" even if an answer was provided.

```kotlin
val call = mockk<suspend () -> Int>()
coEvery { call() } returns 5
runBlocking { assertEquals(5, call()) } // throws MockKException below
```

* This works if the mocked function does not `suspend`.
* A workaround is to wrap the suspending function in an interface (but it would be cleaner to be able to mock the suspending function directly.)

Here's the exception:
```
io.mockk.MockKException: no answer found for: Function1(#8).invoke(continuation {})
	at io.mockk.impl.stub.MockKStub.defaultAnswer(MockKStub.kt:90)
	at io.mockk.impl.stub.MockKStub.answer(MockKStub.kt:42)
	at io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:16)
	at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)
	at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:263)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:25)
	at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:20)
	at io.mockk.proxy.jvm.advice.BaseAdvice.handle(BaseAdvice.kt:42)
	at io.mockk.proxy.jvm.advice.jvm.JvmMockKProxyInterceptor.interceptNoSuper(JvmMockKProxyInterceptor.java:45)
	at kotlin.jvm.functions.Function1$Subclass3.invoke(Unknown Source)
	at ScopingStoreTest$put an item$1$2.invokeSuspend(ScopingStoreTest.kt:56)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:53)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:35)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at MyTest$myTest$1.invokeSuspend(MyTest.kt:56)
        ...
```

**Comment by oleksiyp** [comment]
Seems it is a bit tricky. And I think it was working before.

Got following message:
```
java.lang.UnsupportedOperationException: This class is an internal synthetic class generated by the Kotlin compiler, such as an anonymous class for a lambda, a SAM wrapper, a callable reference, etc. It's not a Kotlin class or interface, so the reflection library has no idea what declarations does it have. Please use Java reflection to inspect this class: class io.mockk.gh.Issue288Test$suspendLambdaShouldBeMockable$x$1
```

for this code that mimics what mockk does:

```
        val x: suspend () -> Int = { 5 }
        x::class.java.methods.first { it.name == "invoke" }.kotlinFunction
```

**Comment by oleksiyp** [comment]
I found some workaround - check if the actual last argument is a continuation, not just method types. Sad that more and more workarounds are needed, but I think anyway it has it's value.

**Comment by PaulWoitaschek** [comment]
I was injecting a suspending function through the constructor. A workaround is to declare a regular interface with an `invoke` function and pass a method reference to the object under test. Then the call side for the actual mocking stays identically.

So for example my class under test had a function declared in the constructor:
```kotlin
private val api: suspend (Key) -> Value
```

As a workaround instead of mocking the suspending function
```kotlin
private val api : suspend (Int) -> String = mockk()
```

I created an interface:
```kotlin
private interface TestApi<Key,Value> {
  suspend operator fun invoke(key: Key): Value
}
```

and I'm passing a method reference: 
```kotlin
private val api: TestApi<Int,String> = mockk()
val repo = Repository(
  api = api::invoke
)
```

Now at the mocking side the usage stays the same:

```kotlin
coEvery { api(key) } returns freshValue
```

**Comment by PaulWoitaschek** [comment]
Please put an `important` label.

**Comment by DevSrSouza** [comment]
I think I am getting the same thing

```kotlin
    @Test
    fun `should listen to publish of a String`() {
        val localEventScope = LocalEventScope()

        val onReceiveMock = mockk<suspend (String) -> Unit>()
        coEvery { onReceiveMock.invoke(any<String>()) } returns Unit

        localEventScope.listen<String>(this, Dispatchers.Default, onReceiveMock)

        localEventScope.publish("test string")

        coVerify { onReceiveMock.invoke(any()) }
    }
```

```
Exception in thread "Test worker @coroutine#4" io.mockk.MockKException: no answer found for: Function2(#1).invoke(test string, continuation {})
	at io.mockk.impl.stub.MockKStub.defaultAnswer(MockKStub.kt:90)
	at io.mockk.impl.stub.MockKStub.answer(MockKStub.kt:42)
	at io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:16)
	at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)
	at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:263)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:25)
	at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:20)
	at io.mockk.proxy.jvm.advice.BaseAdvice.handle(BaseAdvice.kt:42)
	at io.mockk.proxy.jvm.advice.jvm.JvmMockKProxyInterceptor.interceptNoSuper(JvmMockKProxyInterceptor.java:45)
	at kotlin.jvm.functions.Function2$Subclass0.invoke(Unknown Source)
	at br.com.devsrsouza.eventkt.scopes.LocalEventScope$publish$1.invokeSuspend(LocalEventScope.kt:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:457)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:154)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at br.com.devsrsouza.eventkt.scopes.LocalEventScope.publish(LocalEventScope.kt:9)
	at br.com.devsrsouza.eventkt.LocalEventScopeTest.should listen to publish of a String(LocalEventScopeTest.kt:19)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:106)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:117)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by gabrielprado-mb** [comment]
Any news about this issue?

**Comment by mkruczkowski** [comment]
I have also experienced this, is there a chance to fix it?

**Comment by kdotdi** [comment]
@gladed Could you please explain what do you exactly mean by

> wrap the suspending function in an interface

?

**Comment by PaulWoitaschek** [comment]
@kdotdi See my post which shows an example for that.

**Comment by gladed** [comment]
```kotlin
interface Suspender {
    suspend fun foo(): Int
}

@Test
fun suspendMockTest() {
    val happyMock = mockk<Suspender>()
    coEvery { happyMock.foo() } returns 5
    runBlocking { assertEquals(5, happyMock.foo()) } // Pass

    val sadMock = mockk<suspend () -> Int>()
    coEvery { sadMock() } returns 5
    runBlocking { assertEquals(5, sadMock()) } // throws MockKException
}
```

**Comment by manuel047** [comment]
I still run into the same issue. Keep getting a MockKException. Any ideas why? I have this:
```kotlin
interface LoginRepository {
    suspend fun login(request: Request): Result<T>
}

@Test
Fun testLogin() = coroutineTestRule.TestCoroutineDispatcher.runBlockingtest {
	val loginRepository = mockk<LoginRepository>()
         val request = mockk<Request>()

coEvery { loginRepository.login(request) } returns Result.Success 

Viewmodel.login()

assertEquals(Result.Success, livedata.value)
}
```

**Comment by GurpreetSK95** [comment]
I'm getting the same error for the following code:
```
flow { emit(httpClient.get<String>(UrlMap.getUrl(UrlMap.trendingRepositories))) }
                .take(1)
                .map { Json.nonstrict.parse(TrendingRepositoriesResponse.serializer(), it).results }
                .map { FetchEvent(FetchAction.FETCH_SUCCESS, it) }
                .catch {
                    emit(
                        FetchEvent(
                            FetchAction.FETCH_FAILED,
                            null,
                            listOf(it.toApplicationError())
                        )
                    )
                }
                .flowOn(schedulers.io())
```

This is the failing test:
```
    @Test
    fun `fetching repositories succeeds - cache failure, remote success`() {
        val expectedEvents = listOf(
            FetchEvent<List<TrendingRepository>>(FetchAction.IN_FLIGHT, null),
            FetchEvent(FetchAction.FETCH_SUCCESS, getTrendingRepos())
        )
        coEvery { httpClient.get<String>(UrlMap.getUrl(UrlMap.trendingRepositories)) }
            .returns(
                Json.stringify(
                    TrendingRepositoriesResponse.serializer(),
                    TrendingRepositoriesResponse(getTrendingRepos())
                )
            )

        val emittedEvents = mutableListOf<FetchEvent<List<TrendingRepository>>>()
        runBlocking {
            repo
                .fetchMostPopularMovies()
                .toCollection(emittedEvents)
        }

        expectedEvents.assertEqualTo(emittedEvents)
    }
```

**Comment by p1415604x** [comment]
Cannot really use this workaround @gladed  is providing. I am mocking object that is injected via DI and that object's suspend method has to return value. I cannot wrap anything within interfaces as it would mess up the production code.

**Comment by PaulWoitaschek** [comment]
@p1415604x doesn't my workaround work?

**Comment by renukame** [comment]
In version 1.10.0 i am still getting the same error **Exception in thread "main @coroutine#5" io.mockk.MockKException: no answer found for:**

I am using Room db and calling its dao methods which are suspended 

Example

interface TestDao{
         suspend fun getValue():String{}
}


class Test{
      fun test(){
           Globalscope.launch(Dispatchers.IO)
                                                     {
                                   val value = db.testDao.getValue()}}

}

@Test
class TestClass{
          val testDao= mockk<TestDao>()
        coEvery { db.testDao() } returns testDao
        coEvery { testDao.getValue("k1", "s1") } return ""
}

**Comment by Bwaim** [comment]
Any news on this bug ?
I'm having the same bug mocking an object having a suspend function. Any workaround for this case ?

**Comment by zakrodionov** [comment]
The same error. CoEvery works only if you transfer it to setup.

**Comment by Gozde027** [comment]
I'm having the same issue, any update?

**Comment by Tgo1014** [comment]
Also having this same issue

**Comment by hiteshchopra11** [comment]
Any update? facing same issue

**Comment by oalpayli** [comment]
Any update? same here

**Comment by pvegh** [comment]
3rd birthday coming up, let's throw a party. Who brings cake?
It's marked with Critical, Important, and Bug, better to remove those labels, looks like many users have been waiting for a fix all this time.

**Comment by thaibt** [comment]
Hello, no contribution here - just following with the same issue.

**Comment by thaibt** [comment]
> ```kotlin
> interface Suspender {
>     suspend fun foo(): Int
> }
> 
> @Test
> fun suspendMockTest() {
>     val happyMock = mockk<Suspender>()
>     coEvery { happyMock.foo() } returns 5
>     runBlocking { assertEquals(5, happyMock.foo()) } // Pass
> 
>     val sadMock = mockk<suspend () -> Int>()
>     coEvery { sadMock() } returns 5
>     runBlocking { assertEquals(5, sadMock()) } // throws MockKException
> }
> ```

I have similar code above utilizing an interface that I mockked... I am curious what is the difference with yours that it is passing but mine is not...?

**Comment by andrebarrett** [comment]
I came across this issue myself today. I used this as a workaround:

`
        val mockSubMessage = mockk<SubMessage<String>>()

        val slot = slot<suspend (SubMessage<String>) -> Unit>()

        every { mockConsumer.handler(capture(slot)) } returns Unit
        
        consumerProcess.start()

        slot.captured(mockSubMessage)

`

Instead of using the framework to `coVerify` or in my particular case `coAnswer` you can capture the suspend function and call it yourself.

In instances where an actual suspend function is passed through dependency injection for example, you already have the ability to pass a real function rather than a mock. This can be any function that does the verify for you. 

This particular workaround may not suitable in all the cases mentioned already. It could help someone who is doing something similar to myself, however, so I thought I would share.
