### ISSUE TITLE
Bug: capture does not work for argument of type Set

### ISSUE THREAD

**Issue by pueffl** [mockk/mockk#295]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
1.9.3
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

### Expected Behavior
slot<Set<Long>>() works as expected in every {...} expression

### Current Behavior

What is the current behavior?
The following exception occurs:
io.mockk.MockKException: Failed matching mocking signature for

left matchers: [slotCapture<String>(), slotCapture<Set>(), slotCapture<String>()]

	at io.mockk.impl.recording.SignatureMatcherDetector.detect(SignatureMatcherDetector.kt:99)
	at io.mockk.impl.recording.states.RecordingState.signMatchers(RecordingState.kt:39)
	at io.mockk.impl.recording.states.RecordingState.round(RecordingState.kt:31)
	at io.mockk.impl.recording.CommonCallRecorder.round(CommonCallRecorder.kt:50)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:59)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalEvery(API.kt:92)
	at io.mockk.MockKKt.every(MockK.kt:104)
	at com.eight.backend.support.MockkTest.test(MockkTest.kt:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

### Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Just create and execute the following class:

class MockkTest {

    fun testCall(first: String, second: String, third: Set<Long>) {
    }

    @Test
    fun test() {
        val commandPrefixCaptor = slot<String>()
        val commandSuffixCaptor = slot<String>()
        val commandUidsCaptor = slot<Set<Long>>()

        every { testCall(capture(commandPrefixCaptor),
                capture(commandSuffixCaptor), capture(commandUidsCaptor)) }
    }
}

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.9.3
* OS: Fedora 30
* Kotlin version: 1.3.31
* JDK version: 1.8.0_191 (Not sure if IntelliJ uses this version)
* JUnit version: 4.12
* Type of test: unit test

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
buildscript {
    ext.kotlin_version = '1.3.31'
    ext {
        compileSdkVersion = 28
        minSdkVersion = 23
        targetSdkVersion = 28

        versions = [
                'gradle'            : '3.4.0',
                'kotlin'            : '1.3.31',
                'koin'              : '1.0.2',
                'room'              : '2.0.0',
                'ktlint'            : '0.30.0',
                'lifecycle'         : '2.0.0',
                'appcompat'         : '1.0.2',
                'androidxAnnotation': '1.0.1',
                'material'          : '1.0.0',
                'test'              : '1.1.0',
                'testRunner'        : '1.1.1',
                'espresso'          : '3.1.1',
                'constraintlayout'  : '1.1.3',
                'recyclerview'      : '1.0.0',
                'paging'            : '2.1.0',
                'work'              : '1.0.1',
                'gson'              : '2.8.2',
                'navigation'        : '1.0.0',
                'legacy_support'    : '1.0.0',
                'mime4j'            : '0.8.1',
                'timber'            : '4.7.1',
                'okio'              : '1.14.0',
                'commonsIo'         : '2.4',
                'jsoup'             : '1.11.2',
                'mockk'             : '1.9.3',
                'jzlib'             : '1.0.7', // get rid of this
                'jutf7'             : '1.0.0', // get rid of this
                'robolectric'       : '4.1',
                'mockito'           : '2.18.0',
                'mockitoKotlin'     : '1.5.0'
        ]
    }
...

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${versions.kotlin}"
    implementation "org.koin:koin-core:${versions.koin}"
    implementation "org.koin:koin-android:${versions.koin}"
    implementation "commons-io:commons-io:${versions.commonsIo}"
    implementation "com.jakewharton.timber:timber:${versions.timber}"

    testImplementation "androidx.test:core:${versions.test}"
    testImplementation "androidx.test:runner:${versions.testRunner}"
    testImplementation "androidx.test:rules:${versions.testRunner}"
    testImplementation "androidx.test.ext:junit:${versions.test}"
    testImplementation "androidx.test.ext:truth:${versions.test}"
    testImplementation "org.robolectric:robolectric:${versions.robolectric}"
    testImplementation "org.koin:koin-test:${versions.koin}"
    testImplementation "io.mockk:mockk:${versions.mockk}"
    testImplementation "org.mockito:mockito-core:${versions.mockito}"
    testImplementation "com.squareup.okio:okio:${versions.okio}"
    testImplementation "com.jcraft:jzlib:${versions.jzlib}"

    androidTestImplementation "io.mockk:mockk-android:${versions.mockk}"
    androidTestImplementation "androidx.test.espresso:espresso-core:${versions.espresso}"
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
See code above
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by jivimberg** [comment]
Don't you need to create a mock for the class before being able to mock `testCall`?

This seems to work:

```
class MockkTest {

    fun testCall(first: String, second: String, third: Set<Long>) {
    }

    @Test
    fun test() {
        val mock = mockk<MockkTest>()

        val commandPrefixCaptor = slot<String>()
        val commandSuffixCaptor = slot<String>()
        val commandUidsCaptor = slot<Set<Long>>()

        every {
            mock.testCall(capture(commandPrefixCaptor),
                    capture(commandSuffixCaptor), capture(commandUidsCaptor))
        }
    }
}
```

**Comment by pueffl** [comment]
Thx, a lot, seems I missed that.

**Comment by Raibaz** [comment]
Is this still happening? I just tried executing this

```
class Issue295Test {

    class TestClass {
        fun testCall(first: String, second: String, third: Set<Long>) {}
    }

    @Test
    fun test() {
        val mock = mockk<TestClass>()

        val commandPrefixCaptor = slot<String>()
        val commandSuffixCaptor = slot<String>()
        val commandUidsCaptor = slot<Set<Long>>()

        every {
            mock.testCall(capture(commandPrefixCaptor), capture(commandSuffixCaptor), capture(commandUidsCaptor))
        } just runs

        mock.testCall("foo", "bar", setOf(1L))
        
        assertEquals(setOf(1L), commandUidsCaptor.captured)

    }
}
```

And it passes successfully.

@pueffl, can you please confirm if this is still happening with mockk 1.10.2?
