### ISSUE TITLE
verify runs out of memory when calling a function very large number of times

### ISSUE THREAD

**Issue by lukaszkalnik** [mockk/mockk#298]
### Expected Behavior
`verify` doesn't run out of memory even with large number of repetitions.

### Current Behavior
I'm writing tests for an SDK which sends data over BLE. 
Each sent frame has a 2-byte sequence number to prevent replay attacks, increased with every frame. Obviously after 65536 frames we cut the connection because otherwise we would have an overflow of the 2 bytes and the sequence would start counting from 0.

So the test (source code below) tests if after 65536 writes the next `encoder.write()` will return a `Failure` with `MaxSequenceExceededException`. `encoder.write()` is a suspending function, that's why we call it in a `runBlocking` block; we use `repeat(65536)` to simulate repeated writing.

By this opportunity we also check if `aes.encrypt()` is **never** called (because `aes.encryptionEnabled == false`). Unfortunately, the line
```
verify(inverse = true) { aes.encrypt(any(), any()) }
```
crashes the test (after a considerable amount of time, like 30 seconds or so on my machine) with an OutOfMemoryError (see stack trace).

When I remove this line, the test runs fine (and finishes immediately, without waiting).

#### Context

* MockK version: 1.9.3
* OS: macOS 10.14.4
* Kotlin version: 1.3.31
* JDK version: 1.8.0_144
* JUnit version: JUnit Jupiter 5.4.2
* Type of test: unit test

#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at java.lang.StringBuilder.append(StringBuilder.java:76)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:484)
	at java.lang.StringBuilder.append(StringBuilder.java:166)
	at java.lang.StringBuilder.append(StringBuilder.java:76)
	at kotlin.text.StringsKt__StringBuilderKt.appendElement(StringBuilder.kt:59)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:2299)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:2316)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:2315)
	at io.mockk.impl.verify.VerificationHelpers.stackTraces(VerificationHelpers.kt:20)
	at io.mockk.impl.verify.UnorderedCallVerifier$matchCall$result$2.invoke(UnorderedCallVerifier.kt:77)
	at io.mockk.impl.verify.UnorderedCallVerifier$matchCall$result$2.invoke(UnorderedCallVerifier.kt:16)
	at io.mockk.impl.recording.CommonCallRecorder.safeExec(CommonCallRecorder.kt:72)
	at io.mockk.impl.log.SafeToString.exec(SafeToString.kt:10)
	at io.mockk.impl.verify.UnorderedCallVerifier.matchCall(UnorderedCallVerifier.kt:72)
	at io.mockk.impl.verify.UnorderedCallVerifier.verify(UnorderedCallVerifier.kt:33)
	at io.mockk.impl.recording.states.VerifyingState$recordingDone$outcome$1.invoke(VerifyingState.kt:31)
	at io.mockk.impl.recording.states.VerifyingState$recordingDone$outcome$1.invoke(VerifyingState.kt:11)
	at io.mockk.impl.recording.CommonCallRecorder.safeExec(CommonCallRecorder.kt:72)
	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:30)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:60)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalVerify(API.kt:118)
	at io.mockk.MockKKt.verify(MockK.kt:139)
	at io.mockk.MockKKt.verify$default(MockK.kt:136)
	at FrameEncoderTest.when max sequence number exceeded then disconnect(FrameEncoderTest.kt)
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
import io.mockk.*
import kotlinx.coroutines.runBlocking
import org.assertj.core.api.Assertions.*
import org.junit.jupiter.api.*

class FrameEncoderTest {

    private val state = mockk<StateStore>()

    private val aes = mockk<AESStore>()

    private val disconnectFromGateway = mockk<DisconnectFromGateway>()

    private val encoder = DefaultFrameEncoder(state, WriteSequenceStore(), aes, disconnectFromGateway)

  @Test
    fun `when max sequence number exceeded then disconnect`() {
        // encoder.write() calls internally state.writeCharacteristic()
        coEvery { state.writeCharacteristic(any()) } returns Success(Unit)
        // on MaxSequenceExceededException we disconnect from the "gateway" BLE device
        coEvery { disconnectFromGateway.execute(any()) } returns Success(Unit)
        every { aes.encryptionEnabled } returns false

        val result = runBlocking {
            repeat(65536) { encoder.write(Frame(0, listOf(0))) }
            encoder.write(Frame(0, listOf(0)))
        }
        assertThat(result).isInstanceOf(Failure::class.java)
        val exception = (result as Failure).failure
        assertThat(exception).isInstanceOf(MaxSequenceExceededException::class.java)

        verify(inverse = true) { aes.encrypt(any(), any()) }

        coVerify(exactly = 1) { disconnectFromGateway.execute(any()) }
    }
}
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by oleksiyp** [comment]
Seems it is trying to big gigantic message with all stack traces inside

**Comment by oleksiyp** [comment]
Try use `exactly = 0` instead of `inverse = true`

**Comment by lukaszkalnik** [comment]
With `exactly = 0` the test passes very quickly. So this would be a workaround. Thank you!

**Comment by lukaszkalnik** [comment]
But now I have the same OutOfMemoryError when verifying positive case (` verify { aes.encrypt(any(), any()) }`):
```
    @Test
    fun `when max sequence number exceeded then disconnect`() {
        coEvery { state.writeCharacteristic(any()) } returns Success(Unit)
        coEvery { disconnectFromGateway.execute(any()) } returns Success(Unit)
        every { aes.encryptionEnabled } returns true
        every { aes.encrypt(any(), any()) } returns listOf(1)

        val result = runBlocking {
            repeat(65536) { encoder.write(Frame(0, listOf(0))) }
            encoder.write(Frame(0, listOf(0)))
        }
        assertThat(result).isInstanceOf(Failure::class.java)
        val exception = (result as Failure).failure
        assertThat(exception).isInstanceOf(MaxSequenceExceededException::class.java)

        verify { aes.encrypt(any(), any()) }
        coVerify(exactly = 1) { disconnectFromGateway.execute(any()) }
    }
```

**Comment by lukaszkalnik** [comment]
Ok, for some reason this last test runs correctly locally on my machine, but runs out of memory on our Jenkins during mock Android jar creation (although this is a pure JUnit test, no dependencies on Android framework and no instrumentation). I suspect this is a problem with our Jenkins setup then.

**Comment by oleksiyp** [comment]
Clearing mocks may help, but as you understand probably there is linear dependnecy between number of calls recorded and memory occupied

**Comment by lukaszkalnik** [comment]
You are right, it was enough to turn off mock recording and the test runs fine:
```
        excludeRecords {
            aes.encryptionEnabled
            aes.encrypt(any(), any())
        }
```
And obviously removing `verify { aes.encrypt(any(), any()) }`.

Thank you for the suggestion, it pointed me in the right direction!
