### ISSUE TITLE
Bug: mocking KeyStore

### ISSUE THREAD

**Issue by isolino** [mockk/mockk#299]
I have a class that make usage of KeyStore.class, but when a try to write a test to it, the test fails because I'm not mocking in the correct way.

#### Context

* MockK version: 1.8.1
* Kotlin version: 1.3.21
* JDK version: 1.7
* JUnit 5
* Type of test: unit test
the test class is under test package NOT androidTest

#### Failure Logs

Please include any relevant log snippets or files here.

#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
java.security.KeyStoreException: -752267e98a1c1ad7 not found

	at java.security.KeyStore.getInstance(KeyStore.java:851)
	at br.com.meupag.investimentos.features.login.KeyStoreTest$Testing KeyStore Usage$1.invoke(KeyStoreTest.kt:22)
	at br.com.meupag.investimentos.features.login.KeyStoreTest$Testing KeyStore Usage$1.invoke(KeyStoreTest.kt:11)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:22)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:31)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:25)
	at br.com.meupag.investimentos.features.login.KeyStoreTest.Testing KeyStore Usage(KeyStoreTest.kt:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.security.NoSuchAlgorithmException: -752267e98a1c1ad7 KeyStore not available
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
	at java.security.Security.getImpl(Security.java:695)
	at java.security.KeyStore.getInstance(KeyStore.java:848)
	... 30 more
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    testImplementation "io.mockk:mockk:1.8.1"
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
package br.com.blablabla

import io.mockk.every
import io.mockk.mockk
import io.mockk.mockkObject
import io.mockk.verify
import org.junit.Before
import org.junit.Test
import java.security.KeyStore

class KeyStoreTest {

    private val keystore : KeyStore = mockk()

    @Before
    fun mockingStatics(){
        mockkObject(KeyStore::class)
    }

    @Test
    fun `Testing KeyStore Usage`(){
        every { KeyStore.getInstance(any()) } returns keystore

        SUTWithKeyStoreDependency().methodUnderTest()

        verify {
            KeyStore.getInstance(any())//checking if the static method was called
            keystore.load(any())//checking if de load method was called
        }
    }
}

class SUTWithKeyStoreDependency{
    lateinit var keyStore : KeyStore

    fun methodUnderTest(){
        keyStore = KeyStore.getInstance("AndroidKeyStore")
        keyStore.load(null)
    }
}
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by oleksiyp** [comment]
Try to follow medium article about advanced features(check link at https://mockk.io). Most probable you need static mock

**Comment by allypally** [comment]
> Try to follow medium article about advanced features(check link at https://mockk.io). Most probable you need static mock

Can I assume from the fact that you labelled this a bug that the advice you gave here wont solve the issue?
