### ISSUE TITLE
Verify class extension function.

### ISSUE THREAD

**Issue by jaychang0917** [mockk/mockk#309]
I have no idea why the `verify` tries to check the `item.copy()`.

```kotlin
class FooTest {
    @Test
    fun test() {
        val cart = ShopCart(Item(10))
        val cartSpy = spyk(cart)
        val controller = ShopCartController(cartSpy)

        controller.updateCart()

        with(controller) {
            verify {
                cartSpy.itemUpdated()
            }
        }
    }
}

class ShopCartController(private val cart: ShopCart) {
    fun updateCart() {
        cart.itemUpdated()
    }

    fun ShopCart.itemUpdated() = copy(
        item = item.copy(price = 20)
    )
}

data class Item(val price: Int)

data class ShopCart(val item: Item)
```

### Expected Behavior
The test should pass as `itemUpdated()` is called.

### Current Behavior
The test fails and throws the following stacktrace:
```
java.lang.AssertionError: Verification failed: call 2 of 3: Item(child of #1#2).copy(eq(20))) was not called

  at io.mockk.impl.recording.states.VerifyingState.failIfNotPassed(VerifyingState.kt:66)
  at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:42)
  at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
  at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:60)
  at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
  at io.mockk.MockKDsl.internalVerify(API.kt:118)
  at io.mockk.MockKKt.verify(MockK.kt:139)
  at io.mockk.MockKKt.verify$default(MockK.kt:136)
  at com.FooTest.test(Test.kt:17)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
  at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
  at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
  at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
  at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
  at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

#### Context
* MockK version: 1.9.3
* OS: MacOS
* Kotlin version: 1.3.31
* JDK version: 8
* JUnit version: 4
* Type of test: unit test

**Comment by oleksiyp** [comment]
It seems related to an extension function mocking. 

Bear in mind that `itemUpdated` in byte code actually receiving `ShopCart` as the first argument.
And `this` is actually your controller which is not mock.

Extension functions always understanding byte code level, unfortunately. No way you can make it better.
