### ISSUE TITLE
Unit Test: wasNot called not fired in an abstract static class method while verify(exactly = 0) {} works fine

### ISSUE THREAD

**Issue by programadorthi** [mockk/mockk#310]
- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Expected Behavior

`wasNot called` should be fired when verify an abstract static class method

### Current Behavior

`wasNot called` was not fired while `verify(exactly = 0) {}` works fine.

#### Steps to Reproduce

Classes used in the tests: 
https://developer.android.com/reference/androidx/paging/PageKeyedDataSource.html
https://developer.android.com/reference/androidx/paging/PageKeyedDataSource.LoadInitialCallback.html

Create the class:
```
class MyPageKeyedDataSource : PageKeyedDataSource<Int, Any>() {
    override fun loadInitial(
        params: LoadInitialParams<Int>,
        callback: LoadInitialCallback<Int, Any>
    ) {}

    override fun loadAfter(params: LoadParams<Int>, callback: LoadCallback<Int, Any>) {
        callback.onResult(emptyList(), null)
    }

    override fun loadBefore(params: LoadParams<Int>, callback: LoadCallback<Int, Any>) {}
}
```

Apply the test:
```
@Test
    fun `should test`() {
        val loadInitialParams = mockk<LoadInitialParams<Int>>()
        val loadInitialCallback = mockk<LoadInitialCallback<Int, Any>>()

        val myDataSource = MyPageKeyedDataSource()

        myDataSource.loadInitial(loadInitialParams, loadInitialCallback)

        // This version is not fired
        verify { loadInitialCallback.onResult(any(), any(), any()) wasNot called }
        
        // This version works fine
        verify(exactly = 0) { loadInitialCallback.onResult(any(), any(), any()) }
    }
```

#### Context

* MockK version: 1.9.3.kotlin12
* OS: Windows 10
* Kotlin version: 1.3.20
* JDK version: 1.8.0_152-release
* JUnit version: 4.12
* Type of test: unit test

#### Stack trace

```
java.lang.AssertionError: Verification failed: call 1 of 1: LoadInitialCallback(#9).onResult(any(), any(), any())) was not called

	at io.mockk.impl.recording.states.VerifyingState.failIfNotPassed(VerifyingState.kt:66)
	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:42)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:60)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalVerify(API.kt:118)
	at io.mockk.MockKKt.verify(MockK.kt:139)
	at io.mockk.MockKKt.verify$default(MockK.kt:136)
```

**Comment by oleksiyp** [comment]
Ohh, this is always misleading. `wasNotCalled` is for objects not methods.

**Comment by oleksiyp** [comment]
Sorry for late reply
