### ISSUE TITLE
Unable to verify when using reactivex.Single

### ISSUE THREAD

**Issue by kdani41** [mockk/mockk#318]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior
- Single.just().map should be called.
- Verification should be able to verify statements inside the map.

### Current Behavior
- map is not called.
- Original method is called but single map is not getting called.
- Verification is unable to defect what happens in map.

MockK version: 1.9.3
OS: MacOS
Kotlin version: 1.3.20
JDK version: 1.8
JUnit version: 4.12
Type of test: unit test

#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
java.lang.AssertionError: Verification failed: call 1 of 2: Temp(#2).callA()) was not called.

Calls to same mock:
1) Temp(#2).format()

Stack traces:
1)                                 io.mockk.impl.InternalPlatform.captureStackTrace      (InternalPlatform.kt:121)             
                                     io.mockk.impl.stub.MockKStub.handleInvocation       (MockKStub.kt:247)                    
   io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation             (JvmMockFactoryHelper.kt:25)          
                            io.mockk.proxy.jvm.advice.Interceptor.call                   (Interceptor.kt:20)                   
                       com.Temp.format                 (Temp.kt:10)                          
                   com.TempTest.sample                 (TempTest.kt:14)                      
                             sun.reflect.NativeMethodAccessorImpl.invoke0                (NativeMethodAccessorImpl.java:-2)N   
                             sun.reflect.NativeMethodAccessorImpl.invoke                 (NativeMethodAccessorImpl.java:62)    
                         sun.reflect.DelegatingMethodAccessorImpl.invoke                 (DelegatingMethodAccessorImpl.java:43)
                                         java.lang.reflect.Method.invoke                 (Method.java:498)                     
                        org.junit.runners.model.FrameworkMethod$1.runReflectiveCall      (FrameworkMethod.java:50)             
              org.junit.internal.runners.model.ReflectiveCallable.run                    (ReflectiveCallable.java:12)          
                          org.junit.runners.model.FrameworkMethod.invokeExplosively      (FrameworkMethod.java:47)             
               org.junit.internal.runners.statements.InvokeMethod.evaluate               (InvokeMethod.java:17)                
                                   org.junit.runners.ParentRunner.runLeaf                (ParentRunner.java:325)               
                         org.junit.runners.BlockJUnit4ClassRunner.runChild               (BlockJUnit4ClassRunner.java:78)      
                         org.junit.runners.BlockJUnit4ClassRunner.runChild               (BlockJUnit4ClassRunner.java:57)      
                                 org.junit.runners.ParentRunner$3.run                    (ParentRunner.java:290)               
                                 org.junit.runners.ParentRunner$1.schedule               (ParentRunner.java:71)                
                                   org.junit.runners.ParentRunner.runChildren            (ParentRunner.java:288)               
                                   org.junit.runners.ParentRunner.access$000             (ParentRunner.java:58)                
                                 org.junit.runners.ParentRunner$2.evaluate               (ParentRunner.java:268)               
                                   org.junit.runners.ParentRunner.run                    (ParentRunner.java:363)               
                                       org.junit.runner.JUnitCore.run                    (JUnitCore.java:137)                  
                         com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs    (JUnit4IdeaTestRunner.java:68)        
          com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs    (IdeaTestRunner.java:47)              
                     com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart (JUnitStarter.java:242)               
                     com.intellij.rt.execution.junit.JUnitStarter.main                   (JUnitStarter.java:70)                

        at io.mockk.impl.recording.states.VerifyingState.failIfNotPassed(VerifyingState.kt:66)
        at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:42)
        at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
        at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:60)
        at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
        at io.mockk.MockKDsl.internalVerify(API.kt:118)
        at io.mockk.MockKKt.verify(MockK.kt:139)
        at io.mockk.MockKKt.verify$default(MockK.kt:136)
        at com.TempTest.sample(TempTest.kt:15)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
        at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
        at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
        at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

#### Minimal reproducible code (the gist of this issue)

```gradle
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    testImplementation "io.mockk:mockk:1.9.3",
}
```
### Code to test
```kotlin
class Temp(val abc : Pojo) {

    fun format() = Single.just(1).map {
        callA()
        abc.item = 12
    }

    fun callA() = Unit
}

class Pojo(var item : Int)
```

### Test Case
```kotlin 
class TempTest {

    @Test
    fun sample() {
        val abc = mockk<Pojo>(relaxed = true)
        val temp = spyk(Temp(abc))

        temp.format()
        verify {
            temp.callA()
            abc.item = 12
        }
    }
}
```

**Comment by kdani41** [comment]
I missed to call `.test` on single. Sorry not related to the library.
