### ISSUE TITLE
Cannot verify callback, unless I spyk the object or use its static method (see SO comments for details)

### ISSUE THREAD

**Issue by ber4444** [mockk/mockk#333]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

### Expected Behavior

Able to verify callbacks.

### Current Behavior

java.lang.AssertionError: Verification failed: call 1 of 1: Function1(#2).invoke(any())) was not called

#### Context

* MockK version:1.9.3
* OS:Linux, OS X
* Kotlin version:1.3.41
* JDK version:8 and 10
* JUnit version:4.12
* Type of test: unit test

#### Stack trace

```
java.lang.AssertionError: Verification failed: call 1 of 1: MyCallback(#2).invoke(any())) was not called

	at io.mockk.impl.recording.states.VerifyingState.failIfNotPassed(VerifyingState.kt:66)
	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:42)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:60)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalVerify(API.kt:118)
	at io.mockk.MockKKt.verify(MockK.kt:139)
	at io.mockk.MockKKt.verify$default(MockK.kt:136)
```

#### Minimal reproducible code (the gist of this issue)

see https://stackoverflow.com/questions/56998477/cannot-test-callbacks-with-mockk-invokeany-was-not-called

**Comment by oleksiyp** [comment]
Original code(on SO) doesn't seem to represent a valid case. Please submit help wanted with description what you want to achieve if needed.
