### ISSUE TITLE
coVerification fails on spy method

### ISSUE THREAD

**Issue by PepeGuerrero** [mockk/mockk#339]
### Expected Behavior

A verification on a suspend function of a spy object is possible.

### Current Behavior

The verification fails always.

### Failure Information (for bugs)

I was trying to verify a call on a suspend function belonging to a spy object, the implementation of the function is generated code by retrofit. Since version 2.6.0 retrofit allows the use of the suspend modifier.
The assertion error returned is: 

`java.lang.AssertionError: Verification failed: call 1 of 1: $Proxy7(#1).getTest(eq(continuation {}))). Only one matching call to $Proxy7(#1)/getTest(Continuation) happened, but arguments are not matching:
[0]: argument: continuation {}, matcher: eq(continuation {}), result: -
`

#### Steps to Reproduce

1. Create a spy on a retrofit service exposing an endpoint as a suspend function
2. Trigger a call to said endpoint in a test
3. Coverify this call

#### Context

* MockK version: 1.9.3
* OS: Mac OS 10.14.5
* Kotlin version: 1.3.41
* JDK version: OpenJDK 1.8.0_152-release (embedded in AS 3.4.2)
* JUnit version: 4.12
* Type of test: unit test
* Retrofit version: 2.6.1

#### Minimal reproducible code (the gist of this issue)

```kotlin
package com.example.myapplication

import io.mockk.coEvery
import io.mockk.coVerify
import io.mockk.every
import io.mockk.mockk
import io.mockk.spyk
import okhttp3.OkHttpClient
import org.junit.Test
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory

class TestSubjectTest {

    val okhttp = OkHttpClient.Builder().build()

    val testApi = spyk(Retrofit.Builder()  // THIS DOES NOT WORK
        .baseUrl("https://jsonplaceholder.typicode.com")
        .addConverterFactory(GsonConverterFactory.create())
        .client(okhttp).build().create(TestApi::class.java))

//    val testApi: TestApi = mockk {   // THIS WORKS
//        coEvery { getTest() } returns Dto(1, 1, "", false)
//    }

    val testSubject = TestSubject(testApi)

    @Test
    fun test() {

        testSubject.test()

        coVerify { testApi.getTest() }
    }
}
```

```kotlin
package com.example.myapplication

import retrofit2.http.GET

interface TestApi {

    @GET("/todos/1")
    suspend fun getTest(): Dto
}

data class Dto(val userId: Int, val id: Int, val title: String, val completed: Boolean)
```

```kotlin
package com.example.myapplication

import kotlinx.coroutines.runBlocking

class TestSubject(private val testApi: TestApi) {
    fun test() {
        runBlocking {
            testApi.getTest()
        }
    }
}
```

**Comment by oleksiyp** [comment]
Have you tried timeout parameter on coVerify?

**Comment by oleksiyp** [comment]
Seems it is not a problem

**Comment by PepeGuerrero** [comment]
Timeout makes no difference, same result. Do you think the problem is related with the way I'm using it or maybe Retrofit?

**Comment by PepeGuerrero** [comment]
I have included the original stack trace of the issue, I don't know if it is relevant.

**Comment by oleksiyp** [comment]
Belive that it is more sophisticated thing then misuse. Seems generated by retrofit method is not detected as `suspend`

**Comment by PepeGuerrero** [comment]
Should we ping Jake Wharton?

**Comment by oleksiyp** [comment]
Think more on mockk side, but not 100% sure

**Comment by PepeGuerrero** [comment]
Ok, let me know anything I can do to help, so far I've tried including kotlin reflection standalone lib as a dependency to see if it was a reflection problem, but it did nothing.

**Comment by PepeGuerrero** [comment]
hey @oleksiyp, any news on this? something I could do? so far I didn't find anything relevant.

**Comment by PepeGuerrero** [comment]
I have found a new symptom of this issue and I'm thinking it is related with mockk's proxy adding a parameter on suspend function calls (the coroutine continuation). 

This can lead to many failures, for example the one portrayed below, or the latest one I found where, when spying a retrofit api class, retrofit tries to parse this additional argument resulting in:

`java.lang.IllegalArgumentException: No Retrofit annotation found. (parameter #4)
    for method P******Api.get********rl`

having the original method only three parameters.

**Comment by erikhuizinga** [comment]
The simplest MWE tests that fail with:

- Kotlin v1.3.50
- Kotlin coroutines v1.3.0
- JUnit 4.12
- MockK v1.9.3

```kotlin
@Test
fun `suspend lambda mock invocation can be verified`() = runBlocking {
    val lambdaMock = mockk<suspend () -> Unit>(relaxed = true, name = "🤡")
    lambdaMock()
    coVerify(exactly = 1) { lambdaMock() }
}

@Test
fun `suspend lambda spy invocation can be verified`() = runBlocking {
    val lambdaSpy = spyk<suspend () -> Unit>(name = "🔍")
    lambdaSpy()
    coVerify(exactly = 1) { lambdaSpy() }
}
```

Stacktraces:

<details>

```
java.lang.AssertionError: Verification failed: call 1 of 1: Function1(🤡#1).invoke(eq(continuation {}))). Only one matching call to Function1(🤡#1)/invoke(Any) happened, but arguments are not matching:
[0]: argument: continuation {}, matcher: eq(continuation {}), result: -

Stack trace:
                                                io.mockk.impl.InternalPlatform.captureStackTrace                              (InternalPlatform.kt:121)             
                                                  io.mockk.impl.stub.MockKStub.handleInvocation                               (MockKStub.kt:247)                    
                io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation                                     (JvmMockFactoryHelper.kt:25)          
                                         io.mockk.proxy.jvm.advice.Interceptor.call                                           (Interceptor.kt:20)                   
                                          io.mockk.proxy.jvm.advice.BaseAdvice.handle                                         (BaseAdvice.kt:42)                    
                        io.mockk.proxy.jvm.advice.jvm.JvmMockKProxyInterceptor.interceptNoSuper                               (JvmMockKProxyInterceptor.java:45)    
                                      kotlin.jvm.functions.Function1$Subclass0.invoke                                         (-:-1)                                
com.example.SuspendLambdaTest$suspend lambda mock invocation can be verified$1.invokeSuspend                                  (SuspendLambdaTest.kt:13)             
                           kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith                                     (ContinuationImpl.kt:33)              
                                             kotlinx.coroutines.DispatchedTask.run                                            (Dispatched.kt:241)                   
                                          kotlinx.coroutines.EventLoopImplBase.processNextEvent                               (EventLoop.common.kt:270)             
                                          kotlinx.coroutines.BlockingCoroutine.joinBlocking                                   (Builders.kt:79)                      
                                     kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking                                    (Builders.kt:54)                      
                                                 kotlinx.coroutines.BuildersKt.runBlocking                                    (-:1)                                 
                                     kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default                            (Builders.kt:36)                      
                                                 kotlinx.coroutines.BuildersKt.runBlocking$default                            (-:1)                                 
                                                 com.example.SuspendLambdaTest.suspend lambda mock invocation can be verified (SuspendLambdaTest.kt:11)             
                                          sun.reflect.NativeMethodAccessorImpl.invoke0                                        (NativeMethodAccessorImpl.java:-2)N   
                                          sun.reflect.NativeMethodAccessorImpl.invoke                                         (NativeMethodAccessorImpl.java:62)    
                                      sun.reflect.DelegatingMethodAccessorImpl.invoke                                         (DelegatingMethodAccessorImpl.java:43)
                                                      java.lang.reflect.Method.invoke                                         (Method.java:498)                     
                                     org.junit.runners.model.FrameworkMethod$1.runReflectiveCall                              (FrameworkMethod.java:50)             
                           org.junit.internal.runners.model.ReflectiveCallable.run                                            (ReflectiveCallable.java:12)          
                                       org.junit.runners.model.FrameworkMethod.invokeExplosively                              (FrameworkMethod.java:47)             
                            org.junit.internal.runners.statements.InvokeMethod.evaluate                                       (InvokeMethod.java:17)                
                                                org.junit.runners.ParentRunner.runLeaf                                        (ParentRunner.java:325)               
                                      org.junit.runners.BlockJUnit4ClassRunner.runChild                                       (BlockJUnit4ClassRunner.java:78)      
                                      org.junit.runners.BlockJUnit4ClassRunner.runChild                                       (BlockJUnit4ClassRunner.java:57)      
                                              org.junit.runners.ParentRunner$3.run                                            (ParentRunner.java:290)               
                                              org.junit.runners.ParentRunner$1.schedule                                       (ParentRunner.java:71)                
                                                org.junit.runners.ParentRunner.runChildren                                    (ParentRunner.java:288)               
                                                org.junit.runners.ParentRunner.access$000                                     (ParentRunner.java:58)                
                                              org.junit.runners.ParentRunner$2.evaluate                                       (ParentRunner.java:268)               
                                                org.junit.runners.ParentRunner.run                                            (ParentRunner.java:363)               
                                                    org.junit.runner.JUnitCore.run                                            (JUnitCore.java:137)                  
                                      com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs                            (JUnit4IdeaTestRunner.java:68)        
                       com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs                            (IdeaTestRunner.java:47)              
                                  com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart                         (JUnitStarter.java:242)               
                                  com.intellij.rt.execution.junit.JUnitStarter.main                                           (JUnitStarter.java:70)                

	at io.mockk.impl.recording.states.VerifyingState.failIfNotPassed(VerifyingState.kt:66)
	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:42)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:60)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalCoVerify(API.kt:143)
	at io.mockk.MockKKt.coVerify(MockK.kt:162)
	at io.mockk.MockKKt.coVerify$default(MockK.kt:159)
	at com.example.SuspendLambdaTest$suspend lambda mock invocation can be verified$1.invokeSuspend(SuspendLambdaTest.kt:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.example.SuspendLambdaTest.suspend lambda mock invocation can be verified(SuspendLambdaTest.kt:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


java.lang.AssertionError: Verification failed: call 1 of 1: Function1(🔍#4).invoke(eq(continuation {}))). Only one matching call to Function1(🔍#4)/invoke(Any) happened, but arguments are not matching:
[0]: argument: continuation {}, matcher: eq(continuation {}), result: -

Stack trace:
                                               io.mockk.impl.InternalPlatform.captureStackTrace                             (InternalPlatform.kt:121)             
                                                 io.mockk.impl.stub.MockKStub.handleInvocation                              (MockKStub.kt:247)                    
               io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation                                    (JvmMockFactoryHelper.kt:25)          
                                        io.mockk.proxy.jvm.advice.Interceptor.call                                          (Interceptor.kt:20)                   
                                         io.mockk.proxy.jvm.advice.BaseAdvice.handle                                        (BaseAdvice.kt:42)                    
                       io.mockk.proxy.jvm.advice.jvm.JvmMockKProxyInterceptor.interceptNoSuper                              (JvmMockKProxyInterceptor.java:45)    
                                     kotlin.jvm.functions.Function1$Subclass0.invoke                                        (-:-1)                                
com.example.SuspendLambdaTest$suspend lambda spy invocation can be verified$1.invokeSuspend                                 (SuspendLambdaTest.kt:20)             
                          kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith                                    (ContinuationImpl.kt:33)              
                                            kotlinx.coroutines.DispatchedTask.run                                           (Dispatched.kt:241)                   
                                         kotlinx.coroutines.EventLoopImplBase.processNextEvent                              (EventLoop.common.kt:270)             
                                         kotlinx.coroutines.BlockingCoroutine.joinBlocking                                  (Builders.kt:79)                      
                                    kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking                                   (Builders.kt:54)                      
                                                kotlinx.coroutines.BuildersKt.runBlocking                                   (-:1)                                 
                                    kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default                           (Builders.kt:36)                      
                                                kotlinx.coroutines.BuildersKt.runBlocking$default                           (-:1)                                 
                                                com.example.SuspendLambdaTest.suspend lambda spy invocation can be verified (SuspendLambdaTest.kt:18)             
                                         sun.reflect.NativeMethodAccessorImpl.invoke0                                       (NativeMethodAccessorImpl.java:-2)N   
                                         sun.reflect.NativeMethodAccessorImpl.invoke                                        (NativeMethodAccessorImpl.java:62)    
                                     sun.reflect.DelegatingMethodAccessorImpl.invoke                                        (DelegatingMethodAccessorImpl.java:43)
                                                     java.lang.reflect.Method.invoke                                        (Method.java:498)                     
                                    org.junit.runners.model.FrameworkMethod$1.runReflectiveCall                             (FrameworkMethod.java:50)             
                          org.junit.internal.runners.model.ReflectiveCallable.run                                           (ReflectiveCallable.java:12)          
                                      org.junit.runners.model.FrameworkMethod.invokeExplosively                             (FrameworkMethod.java:47)             
                           org.junit.internal.runners.statements.InvokeMethod.evaluate                                      (InvokeMethod.java:17)                
                                               org.junit.runners.ParentRunner.runLeaf                                       (ParentRunner.java:325)               
                                     org.junit.runners.BlockJUnit4ClassRunner.runChild                                      (BlockJUnit4ClassRunner.java:78)      
                                     org.junit.runners.BlockJUnit4ClassRunner.runChild                                      (BlockJUnit4ClassRunner.java:57)      
                                             org.junit.runners.ParentRunner$3.run                                           (ParentRunner.java:290)               
                                             org.junit.runners.ParentRunner$1.schedule                                      (ParentRunner.java:71)                
                                               org.junit.runners.ParentRunner.runChildren                                   (ParentRunner.java:288)               
                                               org.junit.runners.ParentRunner.access$000                                    (ParentRunner.java:58)                
                                             org.junit.runners.ParentRunner$2.evaluate                                      (ParentRunner.java:268)               
                                               org.junit.runners.ParentRunner.run                                           (ParentRunner.java:363)               
                                                   org.junit.runner.JUnitCore.run                                           (JUnitCore.java:137)                  
                                     com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs                           (JUnit4IdeaTestRunner.java:68)        
                      com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs                           (IdeaTestRunner.java:47)              
                                 com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart                        (JUnitStarter.java:242)               
                                 com.intellij.rt.execution.junit.JUnitStarter.main                                          (JUnitStarter.java:70)                

	at io.mockk.impl.recording.states.VerifyingState.failIfNotPassed(VerifyingState.kt:66)
	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:42)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:60)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalCoVerify(API.kt:143)
	at io.mockk.MockKKt.coVerify(MockK.kt:162)
	at io.mockk.MockKKt.coVerify$default(MockK.kt:159)
	at com.example.SuspendLambdaTest$suspend lambda spy invocation can be verified$1.invokeSuspend(SuspendLambdaTest.kt:21)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.example.SuspendLambdaTest.suspend lambda spy invocation can be verified(SuspendLambdaTest.kt:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


Process finished with exit code 255
```

</details>

**Comment by jdiazcano** [comment]
I'm also having the same problem, and definitely not only related to retrofit as the title suggests as seen in the latest comment.

**Comment by mkruczkowski** [comment]
I'm also facing it.
Any news about that?
Any workaround at least?

**Comment by mkruczkowski** [comment]
It looks like it is related to this one:
https://github.com/mockk/mockk/issues/288

**Comment by palatin** [comment]
As a workaround I use java reflection
```kotlin
@Test
fun `verify suspend spy`() = runBlocking {
    val spy = spyk<suspend (String) -> Unit>()
    spy("test")
    coVerify { spy::class.java.getMethod("invoke", Any::class.java, Any::class.java)
        .invoke(spy, "test", any())
    }
}
```

**Comment by LouisFn** [comment]
I have the same issue as @PepeGuerrero . Has anyone found a solution?

**Comment by DevSrSouza** [comment]
Any updates on this one?

**Comment by DevSrSouza** [comment]
Hi folks, we build a solution based on @palatin example.

```kotlin
import io.mockk.MockKMatcherScope
import kotlin.coroutines.Continuation

inline fun <reified P1 : Any> MockKMatcherScope.suspendReflectionInvoke(
    instance: Any,
    name: String,
) {
    val function = instance::class.java.getMethod(
        name,
        P1::class.java,
        Continuation::class.java
    )

    function.invoke(instance, any<P1>(), any<Continuation<*>>())
}
```

Usage:

```kotlin
verify {
    suspendReflectionInvoke<FirstParam>(retrofitInterface, "function_name")
}
```

We also have to create functions for the amount of parameters that we required.

**Comment by PFCJeong** [comment]
Can't believe there hasn't been any fix on this  even though it was listed in the To-Do list marked as Critical to Fix. @DevSrSouza workaround is awesome btw, thanks for sharing this to us.

**Comment by tomrader** [comment]
Just mock with `relaxed = true`.  Had same issue.  Your API interface just needs relaxed = true and this will respect your mocked calls.

**Comment by hkupty** [comment]
This seems to be the same as #608 and #554, unless I'm missing something.

**Comment by msamyatl** [comment]
I believe I may have found the underlying issue. It looks like mockk will increment the number of times a function was called when 1. the function is actually called and 2. the function suspends. 

I reproduced this with the following example:

```
    @Test
    fun `mockk bug`() = runBlocking {
        val a = spyk(A())

        a.sum(listOf(1, 2))
        delay(2000)
        coVerify(exactly = 1) { a.sum(any()) }
    }

    class A {
        suspend fun sum(list: List<Int>): Int {
            delay(20)
            return list.sum()
        }
    }
```

This produces the following error:
```
Verification failed: call 1 of 1: A(#1).sum(any(), any())). 2 matching calls found, but needs at least 1 and at most 1 calls
Calls:
1) A(#1).sum([1, 2], continuation {})
2) A(#1).sum(null, continuation {})
```

The first call is legitimate, but the second call is there because the function `sum` suspends when `delay` is executed, and for some reason, mockk counts these as two invocations of the function as opposed to just one.

If I remove `delay(20)`, the test passes normally.
