### ISSUE TITLE
Bug: captureNullable is broken

### ISSUE THREAD

**Issue by DrMetallius** [mockk/mockk#353]
@Test
    fun testNullableCapture() {
        class Mock {
            fun call(arg: String?) {
            }
        }

        val list = mutableListOf<String?>()
        val test: Mock = mockk {
            every { call(captureNullable(list)) } just Runs
        }

        val args = listOf("One", "Two", "Three", null)
        for (arg in args) {
            test.call(arg)
        }

        assertEquals(args, list)
    }

This code will throw the following exception:

    io.mockk.MockKException: no answer found for: Mock(#3).call(null)

        at io.mockk.impl.stub.MockKStub.defaultAnswer(MockKStub.kt:90)
        at io.mockk.impl.stub.MockKStub.answer(MockKStub.kt:42)
        at io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:16)
        at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)
        at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:263)
        at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:25)
        at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:20)
        at ru.raiffeisen.corp.loginrecovery.data.NetworkGatewayImplTest$testNullableCapture$Mock.call(NetworkGatewayImplTest.kt:46)
        at ru.raiffeisen.corp.loginrecovery.data.NetworkGatewayImplTest.testNullableCapture(NetworkGatewayImplTest.kt:56)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.mockito.internal.runners.DefaultInternalRunner$1$1.evaluate(DefaultInternalRunner.java:44)
        at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
        at ru.raiffeisen.corp.unittest.RxJavaTestSchedulerRule$apply$1.evaluate(RxJavaTestSchedulerRule.kt:28)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:74)
        at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:80)
        at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
        at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)

However, if I change the line to `val args = listOf("One", "Two", "Three")`, everything is fine. I suspect that the problem is that the class `CaptureNullableMatcher` is supposed to override `TypedMatcher.checkType` to allow for null, but it doesn't and that's why the code doesn't work.

I would fix this issue myself and submit a pull request, but unfortunately I couldn't get to MockK to build and run tests in some reasonable time. Hope this issue is fixed in the near future.

I am using MockK 1.9.3 on Android.

**Comment by oleksiyp** [comment]
Similiar to https://github.com/mockk/mockk/issues/323

**Comment by Raibaz** [comment]
@DrMetallius you're right, overriding `checkType` in the `CaptureNullableMatcher` to accept null values fixes it.

**Comment by sgulyaev** [comment]
My same pull request was hanging for 2 months. I am new to OSS. Do i made something wrong?
