### ISSUE TITLE
NullPointerException mocking NavController on instrumentation tests with Mockk

### ISSUE THREAD

**Issue by juawcevada-circle** [mockk/mockk#355]
### Expected Behavior

I should be able to mock NavController on a Espresso test.

### Current Behavior

Im having this crash when I'm mocking NavController on a Espresso test:
`java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object androidx.collection.SparseArrayCompat.get(int)' on a null object reference
at androidx.navigation.NavGraph.findNode(NavGraph.java:171)
at androidx.navigation.NavGraph.findNode(NavGraph.java:166)
at androidx.navigation.ui.NavigationUI.findStartDestination(NavigationUI.java:570)
at androidx.navigation.ui.AppBarConfiguration$Builder.<init>(AppBarConfiguration.java:124)
at androidx.navigation.ui.ToolbarKt.setupWithNavController$default(Toolbar.kt:82)`

#### Steps to Reproduce

Have a fragment with this the toolbar set up with NavControler:
`        val navController = findNavController()
        toolbar.setupWithNavController(navController)`

Mock the Nav controller on the Espresso test:
`    private val navController :NavController =  mockk(relaxed = true)`

This should work with mockito, I didn't test it but google has a sample with it on their documentation:
https://developer.android.com/guide/navigation/navigation-testing

#### Context

* MockK version:1.9.3
* Kotlin version:1.3.31
* JDK version:1.8
* Type of test:instrumented test

#### Failure Logs

Please include any relevant log snippets or files here.

#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
io.mockk.MockKException: Class cast exception. Probably type information was erased.
In this case use `hint` before call to specify exact return type of a method. 

	at io.mockk.impl.InternalPlatform.prettifyRecordingException(InternalPlatform.kt:83)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:50)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:25)
	at eu.example.schedule.kafka.KafkaAdminImplTest.mockkVoidReturnFails(KafkaAdminImplTest.kt:301)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassCastException: kotlin.Unit cannot be cast to java.lang.Void
	at eu.example.schedule.kafka.KafkaAdminImplTest$mockkVoidReturnFails$1.invoke(KafkaAdminImplTest.kt:87)
	at eu.example.schedule.kafka.KafkaAdminImplTest$mockkVoidReturnFails$1.invoke(KafkaAdminImplTest.kt:24)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:22)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:31)
	... 25 more
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    testCompile group: 'org.apache.kafka', name: 'kafka_2.12', version: '1.1.0'
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object androidx.collection.SparseArrayCompat.get(int)' on a null object reference
at androidx.navigation.NavGraph.findNode(NavGraph.java:171)
at androidx.navigation.NavGraph.findNode(NavGraph.java:166)
at androidx.navigation.ui.NavigationUI.findStartDestination(NavigationUI.java:570)
at androidx.navigation.ui.AppBarConfiguration$Builder.<init>(AppBarConfiguration.java:124)
at androidx.navigation.ui.ToolbarKt.setupWithNavController$default(Toolbar.kt:82)
at com.fundingcircle.investors.android.uk.features.sell.view.ConfirmSaleFragment.setUpToolbar(ConfirmSaleFragment.kt:60)
at com.fundingcircle.investors.android.uk.features.sell.view.ConfirmSaleFragment.onViewCreated(ConfirmSaleFragment.kt:40)
at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:892)
at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1696)
at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:293)
at androidx.fragment.app.testing.FragmentScenario$1.perform(FragmentScenario.java:312)
at androidx.fragment.app.testing.FragmentScenario$1.perform(FragmentScenario.java:291)
at androidx.test.core.app.ActivityScenario.lambda$onActivity$1$ActivityScenario(ActivityScenario.java:535)
at androidx.test.core.app.ActivityScenario$$Lambda$0.run(Unknown Source:4)
at android.app.Instrumentation$SyncRunnable.run(Instrumentation.java:2124)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6938)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by oleksiyp** [comment]
Not sure about this one. Can you provide a sample project? Because it is pretty hard to deal with all this boilerplate project setup.

**Comment by smellouk** [comment]
Hi, I'm having the same issue with apollo client on instrumentation tests

@oleksiyp you can check with apollo client 
```
@Test
  fun testSomething() {
    every {
      apolloClient.query(any<QueryClass>()) // <--- //java.lang.NullPointerException: Attempt to invoke virtual method //`ResponseFieldMapperFactory`
    } returns call
  }
```
