### ISSUE TITLE
AbstractMethodError sometimes when mocking Deferred

### ISSUE THREAD

**Issue by SamerAdra** [mockk/mockk#368]
### Expected Behavior

Setting up a mock of the cancel method on a Deferred should succeed.

### Current Behavior

Sometimes it works and sometimes it throws an AbstractMethodError.

### Failure Information (for bugs)

Test fails to setup mock.

#### Steps to Reproduce

Run unit test setting up mock on Deferred's cancel method.

#### Stack trace

```
java.lang.AbstractMethodError: kotlinx.coroutines.Deferred$Subclass0.cancel()V

	at my.package:MyMethod$deferred1$1$1.invoke(MyClassTest.kt:123)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:24)
	at io.mockk.impl.eval.RecordedBlockEvaluator$enhanceWithNPERethrow$1.invoke(RecordedBlockEvaluator.kt:74)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:36)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalEvery(API.kt:92)
	at io.mockk.MockKKt.every(MockK.kt:104)
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
`        val deferred1 = mockk<Deferred<Boolean>> {
            every { cancel() } just Runs
        }`
```

**Comment by oleksiyp** [comment]
I've seen something similar, let me check.

**Comment by oleksiyp** [comment]
#231 looks similar and it is due to Kotlin bug.

**Comment by Kris-Li-lqx** [comment]
Hi team,

I'm seeing a similar issue exception stack trace. 

```
java.lang.IllegalStateException: check fails

	at myPackage.ABCCall.call(ABCCall.java:123)
	at myPackage.MyTest$mockABCCall$1$1.invoke(MyTest.kt:35)
	at myPackage.MyTest$mockABCCall$1$1.invoke(MyTest.kt:30)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:24)
	at io.mockk.impl.eval.RecordedBlockEvaluator$enhanceWithNPERethrow$1.invoke(RecordedBlockEvaluator.kt:74)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:36)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalEvery(API.kt:92)
	at io.mockk.MockKKt.every(MockK.kt:104)


//My mockk code

@ExtendWith(MockKExtension::class)
class MyTest {									// line 30

	private val mockABCCall = mockk<ABCCall>()

	@Test
    fun setUp() {
    	val response = Response()
    	every { mockABCCall.call(ofType(Request::class))} returns response  //line 35

    	.....
    }
}


//Dependant Java client
public class ABCCall(Request: input) Response {
	if (some checks) {
		// test failed for this exception since some variables are missing in ABCCall mock 
                // but I don't know why this code would ever be executed in the every block
		throw new IllegalStateException("check fails");		// line 123
	}
	return response;
}
```

May I know if the method in the "every" block would be executed? Thank you so much!

**Comment by tonisives** [comment]
I get this error when mocking the `Files` with mockkStatic

code
```
Files.write(path, encoded.toByteArray(), StandardOpenOption.CREATE)
```

test
```
mockkStatic(Files::class)
every { Files.write(any(), any<ByteArray>(), any()) } returns mockk()
```

It only happens when using Java 17 compiler. If I switch to 11 the test works.

Error:
`java.lang.AbstractMethodError at StoreTest.kt:37`
