### ISSUE TITLE
arg(0) inside answers block is null when extension function is mocked

### ISSUE THREAD

**Issue by jnizet** [mockk/mockk#369]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

I expect `arg(0)` inside an `answers` block to return the actual argument of the mocked extension function. 

### Current Behavior

`arg(0)` returns null

#### Steps to Reproduce

Execute the following test:

```
import io.mockk.every
import io.mockk.mockk
import org.junit.Test
import org.junit.jupiter.api.Assertions.assertEquals
import java.util.*

interface Foo {
    fun find(id: String): Optional<String>

    fun findOrNull(id: String) = find(id).orElse(null)
}
fun Foo.extFindOrNull(id: String) = find(id).orElse(null)

class ReproTest {
    @Test
    fun `passes with actual method`() {
        val mockFoo = mockk<Foo>()
        every { mockFoo.findOrNull(any()) } answers { arg<String>(0).toUpperCase() }

        assertEquals("HELLO", mockFoo.findOrNull("hello"))
    }

    @Test
    fun `fails with extension function`() {
        val mockFoo = mockk<Foo>()
        every { mockFoo.extFindOrNull(any()) } answers { arg<String>(0).toUpperCase() }

        assertEquals("HELLO", mockFoo.extFindOrNull("hello"))
    }
}
```

The first test passes, but the second fails with the following error:

```
kotlin.TypeCastException: null cannot be cast to non-null type kotlin.String

	at ReproTest$fails with extension function$2.invoke(ReproTest.kt:32)
	at ReproTest$fails with extension function$2.invoke(ReproTest.kt:14)
	at io.mockk.MockKStubScope$answers$1.invoke(API.kt:2149)
	at io.mockk.MockKStubScope$answers$1.invoke(API.kt:2126)
	at io.mockk.FunctionAnswer.answer(Answers.kt:19)
	at io.mockk.impl.stub.AnswerAnsweringOpportunity.answer(AnswerAnsweringOpportunity.kt:13)
	at io.mockk.impl.stub.MockKStub.answer(MockKStub.kt:54)
	at io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:16)
	at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)
	at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:263)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:25)
	at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:20)
	at java.util.Optional.orElse(Optional.java:253)
	at ReproTestKt.extFindOrNull(ReproTest.kt:12)
	at ReproTest.fails with extension function(ReproTest.kt:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

#### Context

* MockK version: 1.9.3
* OS: macOS
* Kotlin version: 1.3.50
* JDK version: 1.8.0_212
* JUnit version: 5.5.2
* Type of test: unit test

**Comment by sgulyaev** [comment]
It looks like yoa are trying to mock **module wide** extension function.

To achive this currently you need to use **mockkStatic**

This works for me:

```
@Test
fun 'mock module wide extension'() {
    val mockFoo = mockk<Foo>()

    mockkStatic("io.mockk.gh.IssueExtArgKt")
    every { mockFoo.extFindOrNull(any()) } answers {
        arg<String>(1).toUpperCase()
    }

    assertEquals("HELLO", mockFoo.extFindOrNull("hello"))
}

```
Also notice that "hello" located under index "**1**" in this case.

**Comment by sgulyaev** [comment]
However i don't know how to explain why your code works if remove Optional

```
interface Foo {
    fun find(id: String): String?

    fun findOrNull(id: String): String? = find(id)
}


fun Foo.extFindOrNull(id: String): String? = find(id)
```

**Comment by jnizet** [comment]
Oh! you're abslutely right. I missed that. Thanks, and sorry for the noise. 

What is troubling is that using `returns` works fine, without having to use mockkStatic. Does that work by accident, or can I assume this is a supported feature that will stay supported in the future?

```
    @Test
    fun `passes when using returns`() {
        val mockFoo = mockk<Foo>()
        every { mockFoo.extFindOrNull(any()) } returns "HELLO"

        assertEquals("HELLO", mockFoo.extFindOrNull("hello"))
    }
```

**Comment by oleksiyp** [comment]
In this case, it is a kind of supported, but not recommended.

It works because `extFindOrNull` is not intercepted and calls the original `find` and `orElse`. Due to chained mocking functionality `find` returns mock and `orElse` is also recorded on this second mock.

**Comment by jnizet** [comment]
Thanks @oleksiyp . I'm going to close this issue.
