### ISSUE TITLE
 Execution failed for task ':transformClassesAndResourcesWithProguardForPlaystoreDebugAndroidTest'.

### ISSUE THREAD

**Issue by alphaguy4** [mockk/mockk#377]
I am facing below issue on `gradle build`task. 
```
> Task :transformClassesAndResourcesWithProguardForPlaystoreDebugAndroidTest FAILED
:transformClassesAndResourcesWithProguardForPlaystoreDebugAndroidTest (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 7.144 secs.
AAPT2 aapt2-3.3.2-5309881-osx Daemon #6: shutdown
AAPT2 aapt2-3.3.2-5309881-osx Daemon #7: shutdown
AAPT2 aapt2-3.3.2-5309881-osx Daemon #8: shutdown

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesAndResourcesWithProguardForPlaystoreDebugAndroidTest'.
> Job failed, see logs for details

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':transformClassesAndResourcesWithProguardForPlaystoreDebugAndroidTest'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:119)
	at org.gradle.api.internal.tasks.execution.ResolvePreviousStateExecuter.execute(ResolvePreviousStateExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:93)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:45)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:94)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:67)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:315)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:305)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:101)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:49)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.RuntimeException: Job failed, see logs for details
	at com.android.build.gradle.internal.transforms.ProGuardTransform.transform(ProGuardTransform.java:209)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:239)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:235)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:230)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:47)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.run(ExecuteActionsTaskExecuter.java:284)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:273)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:258)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:67)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:145)
	at org.gradle.internal.execution.impl.steps.ExecuteStep.execute(ExecuteStep.java:49)
	at org.gradle.internal.execution.impl.steps.CancelExecutionStep.execute(CancelExecutionStep.java:34)
	at org.gradle.internal.execution.impl.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:69)
	at org.gradle.internal.execution.impl.steps.TimeoutStep.execute(TimeoutStep.java:49)
	at org.gradle.internal.execution.impl.steps.CatchExceptionStep.execute(CatchExceptionStep.java:33)
	at org.gradle.internal.execution.impl.steps.CreateOutputsStep.execute(CreateOutputsStep.java:50)
	at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:43)
	at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:29)
	at org.gradle.internal.execution.impl.steps.CacheStep.executeWithoutCache(CacheStep.java:134)
	at org.gradle.internal.execution.impl.steps.CacheStep.lambda$execute$3(CacheStep.java:83)
	at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:82)
	at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:36)
	at org.gradle.internal.execution.impl.steps.PrepareCachingStep.execute(PrepareCachingStep.java:33)
	at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:38)
	at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:23)
	at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
	at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.lambda$execute$1(SkipUpToDateStep.java:91)
	at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:91)
	at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:36)
	at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:34)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:91)
	... 32 more
Caused by: java.io.IOException: Please correct the above warnings first.
	at proguard.Initializer.execute(Initializer.java:485)
	at proguard.ProGuard.initialize(ProGuard.java:271)
	at proguard.ProGuard.execute(ProGuard.java:113)
	at com.android.build.gradle.internal.transforms.BaseProguardAction.runProguard(BaseProguardAction.java:66)
	at com.android.build.gradle.internal.transforms.ProGuardTransform.doMinification(ProGuardTransform.java:274)
	at com.android.build.gradle.internal.transforms.ProGuardTransform.access$000(ProGuardTransform.java:67)
	at com.android.build.gradle.internal.transforms.ProGuardTransform$1.run(ProGuardTransform.java:178)
	at com.android.builder.tasks.Job.runTask(Job.java:47)
	at com.android.build.gradle.tasks.SimpleWorkQueue$EmptyThreadContext.runTask(SimpleWorkQueue.java:41)
	at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:282)
```

```
Kotlin version: 1.3.10
Mockk: 1.9
Gradle Version: 5.1
```
Tried adding below to proguard file but it didn't work
```
-dontwarn io.mockk.**
-keep class io.mockk.** { *; }
```

**Note:** Turning off proguard fixes the problem but i want this solution.

Please help me out.
Thanks

**Comment by alphaguy4** [comment]
@oleksiyp is there any workaround for this?

**Comment by oleksiyp** [comment]
@alphaguy4 I am not aware of any

**Comment by alphaguy4** [comment]
@oleksiyp  My project using Mockito 1.9 for java code testing. Recently i have started adding kotlin files and testing with mockk. 
Is there any know issue if we include Mockito1.9 and mockk1.9 both ? 
Also, adding 
```
-dontwarn io.mockk.**
-keep class io.mockk.** { *; }
```
Didnt help ! !

**Comment by oleksiyp** [comment]
There was a resolution of few issues very early days to make mockito & mockk. I am not aware of any other submitted reports in this regard. So most probably there is no issues

**Comment by alphaguy4** [comment]
@oleksiyp 
Adding list of warning from the logs 

```
Warning: io.mockk.junit5.MockKExtension: can't find superclass or interface org.junit.jupiter.api.extension.TestInstancePostProcessor
Warning: io.mockk.junit5.MockKExtension: can't find superclass or interface org.junit.jupiter.api.extension.ParameterResolver
Warning: io.mockk.InternalPlatformDsl: can't find referenced class kotlinx.coroutines.BuildersKt
Warning: io.mockk.InternalPlatformDsl: can't find referenced class kotlinx.coroutines.BuildersKt
Warning: io.mockk.InternalPlatformDsl$runCoroutine$1: can't find referenced class kotlinx.coroutines.CoroutineScope
Warning: io.mockk.InternalPlatformDsl$runCoroutine$1: can't find referenced class kotlinx.coroutines.CoroutineScope
Warning: io.mockk.InternalPlatformDsl$runCoroutine$1: can't find referenced class kotlinx.coroutines.CoroutineScope
Warning: io.mockk.impl.log.Slf4jLogger: can't find referenced class org.slf4j.Logger
Warning: io.mockk.impl.log.Slf4jLogger: can't find referenced class org.slf4j.Logger
Warning: io.mockk.impl.log.Slf4jLogger: can't find referenced class org.slf4j.Logger
Warning: io.mockk.impl.log.Slf4jLogger: can't find referenced class org.slf4j.Logger
Warning: io.mockk.impl.log.Slf4jLogger: can't find referenced class org.slf4j.Logger
Warning: io.mockk.impl.log.Slf4jLogger: can't find referenced class org.slf4j.Logger
Warning: io.mockk.impl.log.Slf4jLogger: can't find referenced class org.slf4j.Logger
Warning: io.mockk.impl.log.Slf4jLogger: can't find referenced class org.slf4j.Logger
Warning: io.mockk.impl.log.Slf4jLogger: can't find referenced class org.slf4j.Logger
Warning: io.mockk.impl.log.Slf4jLogger: can't find referenced class org.slf4j.Logger
Warning: io.mockk.impl.log.Slf4jLogger: can't find referenced class org.slf4j.Logger
Warning: io.mockk.impl.log.Slf4jLogger: can't find referenced class org.slf4j.Logger
Warning: io.mockk.impl.log.Slf4jLogger: can't find referenced class org.slf4j.Logger
Warning: io.mockk.impl.log.Slf4jLogger: can't find referenced class org.slf4j.Logger
Warning: io.mockk.impl.log.Slf4jLogger: can't find referenced class org.slf4j.Logger
Warning: io.mockk.impl.log.Slf4jLogger: can't find referenced class org.slf4j.Logger
Warning: io.mockk.impl.log.Slf4jLogger: can't find referenced class org.slf4j.LoggerFactory
Warning: io.mockk.impl.log.Slf4jLogger: can't find referenced class org.slf4j.LoggerFactory
Warning: io.mockk.impl.log.Slf4jLogger: can't find referenced class org.slf4j.Logger
Warning: io.mockk.impl.log.Slf4jLogger: can't find referenced class org.slf4j.Logger
Warning: io.mockk.junit5.MockKExtension: can't find referenced class org.junit.jupiter.api.extension.TestInstancePostProcessor
Warning: io.mockk.junit5.MockKExtension: can't find referenced class org.junit.jupiter.api.extension.ParameterResolver
Warning: io.mockk.junit5.MockKExtension: can't find referenced class org.junit.jupiter.api.extension.ParameterContext
Warning: io.mockk.junit5.MockKExtension: can't find referenced class org.junit.jupiter.api.extension.ParameterContext
Warning: io.mockk.junit5.MockKExtension: can't find referenced class org.junit.jupiter.api.extension.ExtensionContext
Warning: io.mockk.junit5.MockKExtension: can't find referenced class org.junit.jupiter.api.extension.ParameterContext
Warning: io.mockk.junit5.MockKExtension: can't find referenced class org.junit.jupiter.api.extension.ExtensionContext
Warning: io.mockk.junit5.MockKExtension: can't find referenced class org.junit.jupiter.api.extension.ParameterContext
Warning: io.mockk.junit5.MockKExtension: can't find referenced class org.junit.jupiter.api.extension.ExtensionContext
Warning: io.mockk.junit5.MockKExtension: can't find referenced class org.junit.jupiter.api.extension.ParameterContext
Warning: io.mockk.junit5.MockKExtension: can't find referenced class org.junit.jupiter.api.extension.ExtensionContext
Warning: io.mockk.junit5.MockKExtension: can't find referenced class org.junit.jupiter.api.extension.ParameterContext
Warning: io.mockk.junit5.MockKExtension: can't find referenced class org.junit.jupiter.api.extension.ExtensionContext
Warning: io.mockk.junit5.MockKExtension: can't find referenced class org.junit.jupiter.api.extension.ExtensionContext
Warning: io.mockk.junit5.MockKExtension: can't find referenced class org.junit.jupiter.api.extension.ExtensionContext
Note: io.mockk.impl.log.JvmLogging: can't find dynamically referenced class org.slf4j.Logger

```

can we work something out of this ?

**Comment by alphaguy4** [comment]
Fixed problem by adding 
```
-dontwarn io.mockk.**
-keep class io.mockk.** { *; }
```
into proguard-test rules

**Comment by alphaguy4** [comment]
@oleksiyp 
Added below to proguard-test rule
```
-dontwarn io.mockk.**
-keep class io.mockk.** { *; }
```
fix the compilation issue. But now while running android test i am facing below error 

```
java.lang.NoSuchMethodError: No static method getOrCreateKotlinClass(Ljava/lang/Class;)Lkotlin/reflect/KClass; in class Lkotlin/jvm/internal/Reflection; or its super classes (declaration of 'kotlin.jvm.internal.Reflection' appears in /data/app/com.citrix.mail.droid-WHhOnuTkeSA41ZghvdSzcg==/base.apk:classes4.dex)
```

I am using something below code
```
val spyObject = spyk(SomeClass(param1, param2)
``` 
It works fine when proguard is disabled.
