### ISSUE TITLE
InjectMockKs with MutableLiveData dependency throws ClassCastException

### ISSUE THREAD

**Issue by VMadalin** [mockk/mockk#388]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

The test should pass. 

### Current Behavior

Obtain mutableLiveData value throws a `java.lang.ClassCastException: java.lang.Object cannot be cast to java.lang.String`

#### Context

If you try to InjectMockKs with `MutableLiveData` dependency is impossible to obtain the mock value in your `ClassTest`. This behaviour is used especially when you use `DataSource.Factory` you can check the class [here](https://github.com/VMadalin/kotlin-sample-app/blob/master/features/characters_list/src/main/kotlin/com/vmadalin/dynamicfeatures/characterslist/ui/list/paging/CharactersPageDataSourceFactory.kt). Moreover the same sample with `Mockito` works correctly. 

* MockK version: 1.9.3
* OS: OS X
* Kotlin version: 1.3.50
* JDK version:
* JUnit version: 4.12
* Type of test: unit test 

#### Stack trace

```
java.lang.ClassCastException: java.lang.Object cannot be cast to java.lang.String

	at com.vmadalin.dynamicfeatures.characterslist.ui.list.paging.SampleTest$ClassTest.doSomething(FunTest.kt:35)
	at com.vmadalin.dynamicfeatures.characterslist.ui.list.paging.SampleTest.test(FunTest.kt:28)
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
@RelaxedMockK
    private lateinit var dependency: MutableLiveData<String>

    @InjectMockKs
    var classTest: ClassTest = ClassTest()

    @Before
    fun setup() {
        MockKAnnotations.init(this)
    }

    @Test
    fun test() {
        classTest.doSomething()
        verify { dependency.value }
    }

    class ClassTest {
        lateinit var dependency: MutableLiveData<String>
        fun doSomething() : String? {
            return dependency.value
        }
    }
```

**Comment by lawloretienne** [comment]
I am having the same problem.
