### ISSUE TITLE
@OverrideMockKs to Object

### ISSUE THREAD

**Issue by pavelaizen** [mockk/mockk#406]
I'm unable to InjectMocks to singleton (object)
```
object RealObject {
    const val TIMESTAMP = "timestamp"
    private val rect = android.graphics.Rect()
    const val KEYBOARD_ROTATION_THRESHOLD = 1000L

    fun getWidth() = rect.width()
}

class RealObjectTest {
    @RelaxedMockK("MockedRect")
    lateinit var rect: Rect

    @OverrideMockKs
    var realObject = RealObject

    @Before
    fun setUp() = MockKAnnotations.init(this, relaxUnitFun = true)

    @Test
    fun testMockedWidth() {
        spyk(realObject){
            every { rect.width() } returns 500
            val width = getWidth()
            Assert.assertEquals(500, width)
        }
    }
}


```

I'm getting:
```
java.lang.IllegalAccessException: Can not set static final android.graphics.Rect field com.example.sampleproject.RealObject.rect to android.graphics.Rect

	at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
	at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80)
	at sun.reflect.UnsafeQualifiedStaticObjectFieldAccessorImpl.set(UnsafeQualifiedStaticObjectFieldAccessorImpl.java:77)
	at java.lang.reflect.Field.set(Field.java:764)
	at io.mockk.impl.annotations.InjectionHelpers.setImmutableAny(InjectionHelpers.kt:54)
	at io.mockk.impl.annotations.MockInjector.propertiesInjection(MockInjector.kt:39)
	at io.mockk.impl.annotations.JvmMockInitializer.doInjection(JvmMockInitializer.kt:88)
	at io.mockk.impl.annotations.JvmMockInitializer.initMock(JvmMockInitializer.kt:74)
	at io.mockk.impl.annotations.JvmMockInitializer.initAnnotatedMocks(JvmMockInitializer.kt:22)
	at com.example.sampleproject.RealObjectTest.setUp(GithubTest.kt:57)
```
What am I doing wrong?

**Comment by richzeng** [comment]
Happens to me as well. Is this using @OverrideMockKs on Kotlin objects supported?
