### ISSUE TITLE
Stubbing a function/value of a mocked Object calls the actual function/value on Android 9 and below

### ISSUE THREAD

**Issue by metzgore** [mockk/mockk#407]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version (but with Objenisis 2.6, see [issue 281](https://github.com/mockk/mockk/issues/281))
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Expected Behavior

When stubbing a function of a mocked Object the "every" block does not call the actual function on all Android versions.

### Current Behavior

When stubbing a function of a mocked Object the "every" block does call the actual function on Android 8 and below.

### Failure Information (for bugs)

I'm trying to mock an Object and some functions / values within it. This works fine on Android 9 and above but somehow crashes with **lateinit property ... has not been initialized** on Android 8 and below.

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.9.3 (with Objenesis 2.6) 
* Kotlin version: 1.3.61
* JDK version: Android Studio 3.5.3 embedded JDK
* JUnit version: 4.12
* Type of test: android instrumented test

#### Stack trace

```
kotlin.UninitializedPropertyAccessException: lateinit property b has not been initialized
at com.example.myapplication.A.access$getB$p(A.kt:8)
at com.example.myapplication.A$c$2.invoke(A.kt:13)
at com.example.myapplication.A$c$2.invoke(A.kt:8)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
at com.example.myapplication.A.getC(A.kt)
at com.example.myapplication.ExampleInstrumentedTest$test$1.invoke(ExampleInstrumentedTest.kt:17)
at com.example.myapplication.ExampleInstrumentedTest$test$1.invoke(ExampleInstrumentedTest.kt:11)
at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:24)
at io.mockk.impl.eval.RecordedBlockEvaluator$enhanceWithNPERethrow$1.invoke(RecordedBlockEvaluator.kt:74)
at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:36)
at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
at io.mockk.MockKDsl.internalEvery(API.kt:92)
at io.mockk.MockKKt.every(MockK.kt:104)
at com.example.myapplication.ExampleInstrumentedTest.test(ExampleInstrumentedTest.kt:17)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:388)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1837)
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```
#### Minimal reproducible code (the gist of this issue)

Use the following code to reproduce in Android Studio:

```
object A {

    private lateinit var b: B

    val c: C by lazy {
        C(b)
    }
}
```

```class B {}```

```class C(b: B) {}```

```
@RunWith(AndroidJUnit4::class)
class ExampleInstrumentedTest {

    @Test
    fun test() {
        mockkObject(A)

        every { A.c } returns mockk()
    }
}
```

```
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.core:core-ktx:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    androidTestImplementation('io.mockk:mockk-android:1.9.3') { exclude module: 'objenesis' }
    androidTestImplementation 'org.objenesis:objenesis:2.6'
}
```

**Comment by metzgore** [comment]
Just read in the ANDROID.md that object mocks are only possible on Android P and above, so that's probably it.
