### ISSUE TITLE
Missing calls inside verify { ... } block

### ISSUE THREAD

**Issue by muetzenflo** [mockk/mockk#411]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [YES] I am running the latest version
- [YES] I checked the documentation and found no answer
- [YES] I checked to make sure that this issue has not already been filed

### Expected Behavior

No MockKException, succesful test

### Current Behavior

Running the test throws `io.mockk.MockKException: Missing calls inside verify { ... } block.`

#### Context

I already read some issues with this or a similar error message (it is also ocurring for `every {}`), but none of them took me to a success result.
Any hints or suggestions on how to get this to work?

```
compileSdkVersion 29
defaultConfig {
   minSdkVersion 19
   targetSdkVersion 29
   testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
}
```

* MockK version: 1.9.3.kotlin12
* OS: Android
* Kotlin version: 1.3.61
* JDK version: jdk1.8.0_212
* JUnit version: 4.12
* Type of test: unit test

#### Stack trace

```
io.mockk.MockKException: Missing calls inside verify { ... } block.

	at io.mockk.impl.recording.states.VerifyingState.checkMissingCalls(VerifyingState.kt:52)
	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:21)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:60)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalVerify(API.kt:118)
	at io.mockk.MockKKt.verify(MockK.kt:139)
	at io.mockk.MockKKt.verify$default(MockK.kt:136)
```

#### Minimal reproducible code (the gist of this issue)

**Koin Dependency Injection**
```
@ExperimentalCoroutinesApi
val dataModuleTesting = module {

    single { ApplicationProvider.getApplicationContext<Context>() as Context }

    single {
        Room.inMemoryDatabaseBuilder(get(), MyDatabase::class.java)
            .allowMainThreadQueries()
            .build()
    }
	
    single { UnitTestCoroutineDispatcher() as DispatcherProvider }
}
```
**Unit Test Coroutine Dispatcher**
```
import kotlinx.coroutines.test.TestCoroutineDispatcher

@ExperimentalCoroutinesApi
class UnitTestCoroutineDispatcher : DispatcherProvider {

    private val testDispatcher = TestCoroutineDispatcher()

    override fun default(): CoroutineDispatcher = testDispatcher
    override fun io(): CoroutineDispatcher = testDispatcher
    override fun main(): CoroutineDispatcher = testDispatcher
    override fun unconfined(): CoroutineDispatcher = testDispatcher
}
```

**Unit Test class**
```
private val database: MyDatabase by inject()
	
@Before
fun setup() {
    sut = MyAppData
}

@After
fun tearDown() {
    database.close()
}

@Test
fun logout_clearsDatabase() {
    coroutineTestRule.testDispatcher.runBlockingTest {

        // ARRANGE
        database.dataDao().insert(listOf(DataDummies()))

        // ACT
        sut.logout()
			
        // ASSERT
        verify { database.clearAllTables() }
    }
}
```

**Coroutine function**
```
suspend fun logout() {
    withContext(dispatcherProvider.io()) {
        database.clearAllTables()
    }
}
```

**Comment by muetzenflo** [comment]
On SO I got the hint that verify can only be called on a mock or on a spy. Since I want to use an inMemoryDatabase for my tests, I changed the DependencyInjection to return a spy of my database. That way the SUT and the Unit Test are using the same spy instance and I can correctly verify the method calls..
