### ISSUE TITLE
mockkObject : io.mockk.MockKException: Missing calls inside every { ... }

### ISSUE THREAD

**Issue by vipul-d** [mockk/mockk#414]
### Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

Mocking data class should succeed.

### Current Behavior

It throws Missing calls inside every { ... } block error.

### Failure Information (for bugs)

Test fails to setup mock.

#### Steps to Reproduce
1. Add  @JvmField to a Object e.g. 

object Constants {
    @JvmField
    val JVM_FIELD_CONSTANT = 0
    val NORMAL_CONSTANT = 1
}
2. Try mocking in test

#### Context
* MockK version: 1.9.3
* OS: Linux
* Kotlin version: 1.3.5
* JDK version: 8
* JUnit version: 'androidx.test.ext:junit:1.1.0'
* Type of test: unit test 

#### Failure Logs

Please include any relevant log snippets or files here.

#### Stack trace

```
io.mockk.MockKException: Missing calls inside every { ... } block.

	at io.mockk.impl.recording.states.StubbingState.checkMissingCalls(StubbingState.kt:14)
	at io.mockk.impl.recording.states.StubbingState.recordingDone(StubbingState.kt:8)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:60)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalEvery(API.kt:92)
	at io.mockk.MockKKt.every(MockK.kt:104)
	at com.example.myapplication.MainActivityTest.letsTestJvmField(MainActivityTest.kt:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.core:core-ktx:1.0.2'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    testImplementation "io.mockk:mockk:1.9.3"
}
// -----------------------[ Constants.kt ] -----------------------
object Constants {
    @JvmField
    val JVM_FIELD_CONSTANT = 0
    val NORMAL_CONSTANT = 1
}

// -----------------------[ MainActivity .kt ] -----------------------
package com.example.myapplication

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.util.Log

class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        letsPrintConstant()
    }


    fun letsPrintConstant() {
        Log.i("sample", "print jvm field constant ${Constants.JVM_FIELD_CONSTANT}")
        Log.i("sample", "print jvm field constant ${Constants.NORMAL_CONSTANT}")
    }
}


// -----------------------[ MainActivityTest.kt ] -----------------------
package com.example.myapplication

import Constants
import io.mockk.every
import io.mockk.mockkObject
import io.mockk.unmockkObject
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Before
import org.junit.Test

class MainActivityTest {

    @Test
    fun letsTestNormal() {
        assertEquals(1, Constants.NORMAL_CONSTANT)
        every { Constants.NORMAL_CONSTANT } answers { 6 }
        assertEquals(6, Constants.NORMAL_CONSTANT)
    }

    @Test
    fun letsTestJvmField() {
        assertEquals(0, Constants.JVM_FIELD_CONSTANT)
        every { Constants.JVM_FIELD_CONSTANT } answers { 5 }
        assertEquals(5, Constants.JVM_FIELD_CONSTANT)
    }

    @Before
    fun setUp() {
        mockkObject(Constants)
    }

    @After
    fun tearDown() {
        unmockkObject(Constants)
    }
}

// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by oleksiyp** [comment]
99% probability not possible todo. It is just not present in byte-code. Similar tickets alteady were opened, thats why closing this one

**Comment by vipul-d** [comment]
I found a way around this via reflection as JvmField is actually a static final field
@Throws(Exception::class)
    private fun setFinalStaticInner(clz: Class<*>, fieldName: String, newValue: Any) {
        val field = clz.getDeclaredField(fieldName)
        field.isAccessible = true
        val modifiersField = Field::class.java.getDeclaredField("modifiers")
        modifiersField.isAccessible = true
        modifiersField.setInt(field, field.modifiers and Modifier.FINAL.inv())
        field.set(null, newValue)
    }

**Comment by vipul-d** [comment]
setFinalStaticInner(Constants::class.java, "JVM_FIELD_CONSTANT", 5)
