### ISSUE TITLE
RuntimeException: Method encodeToString in android.util.Base64 not mocked.

### ISSUE THREAD

**Issue by oscargrgm** [mockk/mockk#418]
### Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Expected Behavior

MockK should mock the whole class, including Base64 methods.

### Current Behavior

A `java.lang.RuntimeException` is thrown every time I try to run the test.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Run the test.
2. Wait until it fails.

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.9.3
* Kotlin version: 1.3.61
* JDK version: 13.0.2
* JUnit version: 4.12
* Type of test: Unit test

#### Stack trace

```
java.lang.RuntimeException: Method encodeToString in android.util.Base64 not mocked. See http://g.co/androidstudio/not-mocked for details.
	at android.util.Base64.encodeToString(Base64.java)
	at com.company.cipher.Cipher.encrypt(Cipher.kt:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.mockk.proxy.jvm.advice.MethodCall.call(MethodCall.kt:14)
	at io.mockk.proxy.jvm.advice.SelfCallEliminatorCallable.call(SelfCallEliminatorCallable.kt:14)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper.handleOriginalCall(JvmMockFactoryHelper.kt:83)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper.access$handleOriginalCall(JvmMockFactoryHelper.kt:20)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1$invocation$$inlined$stdFunctions$lambda$1.invoke(JvmMockFactoryHelper.kt:28)
	at io.mockk.impl.stub.MockKStub$handleInvocation$originalPlusToString$1.invoke(MockKStub.kt:227)
	at io.mockk.impl.stub.SpyKStub.defaultAnswer(SpyKStub.kt:15)
	at io.mockk.impl.stub.MockKStub.answer(MockKStub.kt:42)
	at io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:16)
	at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)
	at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:263)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:25)
	at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:20)
	at com.company.cipher.Cipher.encrypt(Cipher.kt:44)
	at com.compay.cipher.CipherTest.Result of a simple encryption is Success(CipherTest.kt:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
package com.company.cipher

import io.mockk.confirmVerified
import io.mockk.spyk
import io.mockk.verify
import org.junit.Test
import org.junit.runner.RunWith
import org.junit.runners.JUnit4

@RunWith(JUnit4::class)
class CipherTest {

    private val cipher: Cipher = spyk(recordPrivateCalls = true)

    @Test
    fun `Result of a simple encryption is Success`() {
        val result = cipher.encrypt(RAW_TEXT)
        assert(result is CipherOperationResult.Success)

        verify { cipher.encrypt(RAW_TEXT) }
        confirmVerified(cipher)
    }

    companion object {
        private const val RAW_TEXT = "This is a simple sentence."
    }
}
```

**Comment by fabiobauer** [comment]
Hey @oscargrgm,

keep in mind that a Spy is a combination of a real object and a mock. The Spy will act as a normal instantiated Object as long as you do not overwrite anything from it. This means `val result = 
 cipher.encrypt(...)` executes your actual code.

If this is your intention then you should consider using StaticMocks in your Test. 
It'd be probably look something like that (not tested):

```
fun `Result of a simple encryption is Success`() {
    mockkStatic("android.util.Base64")
    every { Base64.encodeString(..., ...) } returns "expectedResult"
       
    ...
```

**Comment by oscargrgm** [comment]
Hi @fabiobauer!

First of all, thank you for your response and sorry for the delay. Secondly, I've found the solution to my problem.

Android unit tests are not capable of executing methods from `android.util.Base64`, so the `java.util.Base64` ones must be used instead.

Here is the `@Before` stage I have in my test class:
```
@Before
fun `Bypass android_util_Base64 to java_util_Base64`() {
    mockkStatic(Base64::class)
    val arraySlot = slot<ByteArray>()

    every {
        Base64.encodeToString(capture(arraySlot), Base64.DEFAULT)
    } answers {
        java.util.Base64.getEncoder().encodeToString(arraySlot.captured)
    }

    val stringSlot = slot<String>()
    every {
        Base64.decode(capture(stringSlot), Base64.DEFAULT)
    } answers {
        java.util.Base64.getDecoder().decode(stringSlot.captured)
    }
}
```

In this case, I am encoding and decoding `ByteArray` and `String`, but it would be valid for any other type of data.

**Comment by fabiobauer** [comment]
Hey @oscargrgm, you're welcome! Glad you found a solution :)

**Comment by IonutNegru87** [comment]
Another option would be to use Robolectric.

**Comment by PavlosMavris** [comment]
using `java.util.Base64` requires min API level 26.
