### ISSUE TITLE
can't find private function inside superclass for dynamic call

### ISSUE THREAD

**Issue by shaohui10086** [mockk/mockk#425]
### Expected Behavior

should find the private function inside superclass 

### Current Behavior

can't find function callPrivate() for dynamic call

#### Context

* MockK version: 1.9.3
* OS: Mac OS
* Kotlin version:  1.3.31
* JDK version: 1.8

#### Failure Logs
io.mockk.MockKException: can't find function callPrivate() for dynamic call

#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
	io.mockk.MockKException: can't find function callPrivate() for dynamic call

	at io.mockk.InternalPlatformDsl.dynamicCall(InternalPlatformDsl.kt:122)
	at io.mockk.MockKMatcherScope$DynamicCall.invoke(API.kt:1969)
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
class TestPrivateCall {
  open class Parent {
        fun call() {
            callPrivate()
        }
        private fun callPrivate() {}
    }

    class Child: Parent() {}

    @Test
    fun testPrivateCall() {
        val mock = spyk(Child(), recordPrivateCalls = true)

        mock.call()

        verify { mock["callPrivate"]() }
    }
}
```

**Comment by junesolar** [comment]
meet the same problem，when can it be fixed？

**Comment by NWuensche** [comment]
Furthermore, when I use `confirmVerified(mock)`, it tells me that I have not verified `Child(#1).callPrivate()`, which is really annoying.

**Comment by NWuensche** [comment]
By the way, one can still verify the call of `callPrivate` by doing the following:

```kotlin
class Test {
    open class Parent {
        fun call() {
            callPrivate()
        }
        private fun callPrivate() {}
    }

    class Child: Parent() {}

    @Test
    fun testPrivateCall() {
        val mock = spyk(Child(), recordPrivateCalls = true)

        mock.call()

        verify { mock.callPrivateFun("callPrivate") }
    }

    private fun <T : Any> T.callPrivateFun(funName: String) {
        this::class
            .superclasses
            .map { it.declaredMembers }
            .flatten()
            .first { it.name == funName }!!
            .let {
                it.isAccessible = true
                it.call(this)
            }
    }
}
```
