### ISSUE TITLE
java.lang.AssertionError: Verification failed: call 1 of 1: was not called

### ISSUE THREAD

**Issue by techartist** [mockk/mockk#434]
Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed

### Expected Behavior
verify{} or verifyAll{} runs with no Exceptions.  

Please describe the behavior you are expecting
No exception run.  

### Current Behavior
when trying to do verify of a function, I get an exception thrown that a call was not made.  

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.9.3
* OS: Android
* Kotlin version: 1.3.61
* JDK version: 1.8
* JUnit version: 4.12
* Type of test: unit test 

### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
java.lang.AssertionError: Verification failed: call 1 of 1: AutoDownloadsManager(#1).downloadsNeedsToHappenWhenNewEpisodeHappened(any(), any())) was not called

	at io.mockk.impl.recording.states.VerifyingState.failIfNotPassed(VerifyingState.kt:66)
	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:42)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:60)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalVerify(API.kt:118)
	at io.mockk.MockKKt.verify(MockK.kt:139)
	at io.mockk.MockKKt.verify$default(MockK.kt:136)
	at media.luminary.datastore.downloads.AutoDownloadsTest.downloads needs To happen when new episode happened(AutoDownloadsTest.kt:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    api project(":network")
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.2"
    implementation "com.google.android.exoplayer:exoplayer-core:$exoplayer_version"
    implementation "com.google.android.exoplayer:exoplayer-ui:$exoplayer_version"
    implementation "com.google.android.exoplayer:extension-mediasession:$exoplayer_version"
    implementation "com.google.android.exoplayer:extension-okhttp:$exoplayer_version"

    // Kotlin + coroutines
    api "androidx.work:work-runtime-ktx:$work_version"
    api "androidx.work:work-rxjava2:$work_version"


    kapt "com.squareup.moshi:moshi-kotlin-codegen:1.8.0"

    implementation 'com.jakewharton.timber:timber:4.7.1'
    api "io.reactivex.rxjava2:rxandroid:2.1.1"
    api "io.reactivex.rxjava2:rxkotlin:2.4.0"
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2.6.0'
    implementation "io.reactivex.rxjava2:rxjava:2.2.14"

    implementation "com.squareup.sqldelight:rxjava2-extensions:1.1.4"
    // Arrow
    api "io.arrow-kt:arrow-fx:$arrow_version"

    // Cannot resolve symbol for v4 media and app classes after updating firebase library
    api 'androidx.legacy:legacy-support-v4:1.0.0'

    // Segment.io
    api 'com.segment.analytics.android:analytics:4.5.0-beta.0'

    // NewRelic
    api 'com.newrelic.agent.android:android-agent:5.24.2'

    // Firebase
    api 'com.google.firebase:firebase-core:17.2.1'
    api 'com.google.firebase:firebase-auth:19.2.0'
    api 'com.google.firebase:firebase-messaging:20.1.0'

    implementation 'com.tonyodev.fetch2:fetch2:2.3.0-RC1'
    implementation 'com.tonyodev.fetch2okhttp:fetch2okhttp:2.3.0-RC1'

    // Mparticle
    api "com.mparticle:android-core:$mParticleVersion"

    // Stetho
    implementation 'com.facebook.stetho:stetho-okhttp3:1.5.1'

    implementation "com.squareup.sqldelight:android-driver:1.2.0"

    testImplementation "com.squareup.okhttp3:okhttp:$okhttp_version"
    testImplementation "com.squareup.okhttp3:mockwebserver:$okhttp_version"
    testImplementation "com.squareup.sqldelight:sqlite-driver:1.2.0"
    testImplementation 'io.kotlintest:kotlintest-runner-junit5:3.3.3'

    testImplementation "io.mockk:mockk:$mockk_version"

    //Dagger
    implementation "com.google.dagger:dagger:$dagger_version"
    implementation "com.google.dagger:dagger-android:$dagger_version"
    implementation "com.google.dagger:dagger-android-support:$dagger_version"


    api "androidx.room:room-runtime:$room_version"
    kapt "androidx.room:room-compiler:$room_version"
    api "androidx.room:room-rxjava2:$room_version"

    testImplementation 'androidx.arch.core:core-runtime:2.1.0'
    testImplementation 'androidx.arch.core:core-testing:2.1.0'
    testImplementation 'androidx.test:core:1.2.0'
    testImplementation  'androidx.test:runner:1.2.0'
    testImplementation  'androidx.test:rules:1.2.0'
    androidTestImplementation  "androidx.room:room-testing:$room_version"
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    androidTestImplementation  'androidx.test.ext:junit:1.1.1'
    androidTestImplementation "androidx.work:work-testing:$work_version"
    androidTestImplementation "androidx.arch.core:core-testing:2.1.0"
}

// -----------------------[ CODE ] -----------------------

import androidx.arch.core.executor.testing.InstantTaskExecutorRule
import io.mockk.MockKAnnotations
import io.mockk.every
import io.mockk.coEvery
import io.mockk.mockk
import io.mockk.unmockkAll
import io.mockk.verify
import io.mockk.just
import io.mockk.Runs
import io.mockk.mockkStatic
import io.mockk.impl.annotations.MockK
import junit.framework.Assert.assertEquals
import media.luminary.MediaId
import media.luminary.MediaItem
import media.luminary.MediaStore
import media.luminary.client.model.DownloadRemoveTime
import media.luminary.client.model.KeepEpisodes
import media.luminary.datastore.downloads.autodownloads.AutoDownloadsManager
import media.luminary.persistence.AutoDownloadsPreferences
import media.luminary.utils.TestUtils
import org.junit.After
import org.junit.Before
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TestRule
import org.mockito.ArgumentMatchers.any
import org.threeten.bp.LocalDateTime
import java.util.UUID
import java.util.HashMap

class AutoDownloadsTest {

  @get:Rule
  var rule: TestRule = InstantTaskExecutorRule()

  @MockK
  lateinit var downloadsDao: DownloadsDao

  @MockK
  lateinit var mediaStore: MediaStore

  @MockK
  lateinit var downloadDataManager: DownloadDataManager

  lateinit var downloadsDataRepository: DownloadsDataRepository

  val autoDownloadsManager = mockk<AutoDownloadsManager>(relaxed = true)

  val uuid1 = UUID.randomUUID().toString()
  val uuid2 = UUID.randomUUID().toString()
  val uuid3 = UUID.randomUUID().toString()

  val uuid4 = UUID.randomUUID().toString()
  val uuid5 = UUID.randomUUID().toString()
  val uuid6 = UUID.randomUUID().toString()

  val uuid1Show1 = UUID.randomUUID().toString()
  val uuid2Show2 = UUID.randomUUID().toString()

  var hashmapAutoDownloadsManagerTest: HashMap<String, HashMap<String, LocalDateTime>> = mockk()

  private val autoDownloadsPreferences = mockk<AutoDownloadsPreferences> {
    every { autoDownloadedEpisodes.get(any()) } returns HashMap<String, LocalDateTime>()
    every { autoDownloadedEpisodes.set(any(), any()) } returns Unit
    every { autoDownloadedEpisodes.put(any(), any()) } returns HashMap<String, LocalDateTime>()
    every { autoDownloadsForShows } returns HashMap<String, Boolean>()
    every { updateEpisodesToShow(any(), any(), any()) } returns Unit
    every { numberOfEpiosdesToKeep.getNumberOfEpisodes() } returns KeepEpisodes.THREE.number
    every { getOldestDownloadedPerShow(any()) } returns uuid1
    every { autoDownloadsForShows } returns HashMap<String, Boolean>()
    every { autoDownloadedEpisodes } returns HashMap<String, HashMap<String, LocalDateTime>>()
    every { frequencyOfDeletion } returns DownloadRemoveTime.HOUR
    every { frequencyOfDeletion.ordinal } returns 1
  }

  @Before
  @Throws(Exception::class)
  fun setUp() {
    TestUtils.setupRxjavaForOneThreadedTest()
    MockKAnnotations.init(this)
    downloadsDataRepository = DownloadsDataRepository(downloadsDao, mediaStore, downloadDataManager)

    // every { autoDownloadsManager.downloadsNeedsToHappenWhenNewEpisodeHappened(any(), any()) } returns Unit
    coEvery { mediaStore.mediaItemWithId(MediaId(any())) } returns MediaItem.empty
    every { downloadDataManager.sendAddDownload(any(), any()) } returns Unit
    every { downloadDataManager.removeDownload(MediaId(any())) } returns Unit

    every { autoDownloadsManager.downloadFile(any(), any()) } returns Unit
    every { autoDownloadsManager.removeDownload(any(), any()) } returns Unit

    setUpHashMaps()
  }

  private fun setUpHashMaps() {
    val hashmapAutoDownloadsManager = HashMap<String, HashMap<String, LocalDateTime>>()
    val hashMapShows1 = HashMap<String, LocalDateTime>()
    val hashMapShows2 = HashMap<String, LocalDateTime>()
    hashMapShows1.put(uuid1, LocalDateTime.now())
    hashMapShows1.put(uuid2, LocalDateTime.now())
    hashMapShows1.put(uuid3, LocalDateTime.now())
    hashMapShows2.put(uuid4, LocalDateTime.now())
    hashMapShows2.put(uuid5, LocalDateTime.now())
    hashMapShows2.put(uuid6, LocalDateTime.now())
    hashmapAutoDownloadsManager.put(uuid1Show1, hashMapShows1)
    hashmapAutoDownloadsManager.put(uuid2Show2, hashMapShows2)

    autoDownloadsPreferences.autoDownloadedEpisodes.put(uuid1Show1, hashMapShows1)
    autoDownloadsPreferences.autoDownloadedEpisodes.put(uuid2Show2, hashMapShows2)
    hashmapAutoDownloadsManagerTest = autoDownloadsPreferences.autoDownloadedEpisodes
  }

 @Test
  fun `remove downloads when`() {

    mockkStatic("media.luminary.datastore.downloads.autodownloads.AutoDownloadsManager")
    every { autoDownloadsManager.downloadsNeedsToBeDeletedOnFinishPlay(any(), any()) } just Runs

    verify(exactly = 1) { autoDownloadsManager.downloadsNeedsToBeDeletedOnFinishPlay(any(), any()) }
  }

  @Test
  fun `downloads needs To happen when new episode happened`() {
    mockkStatic("media.luminary.datastore.downloads.autodownloads.AutoDownloadsManager")
    every { autoDownloadsManager.downloadsNeedsToHappenWhenNewEpisodeHappened(any(), any()) } just Runs
    verify { autoDownloadsManager.downloadsNeedsToHappenWhenNewEpisodeHappened(any(), any()) }
  }

  @After
  fun tearDownAll() {
    unmockkAll()
  }

**Comment by oleksiyp** [comment]
I am indeed not able to see method being called, but the code is pretty convoluted.

The best approach to take would be to minimize test that doesn't work as much as possible (potentially if possible to few lines of code).

**Comment by techartist** [comment]
@oleksiyp This is the code that is failing: 

`
 @Test
  fun `remove downloads when`() {

    mockkStatic("media.luminary.datastore.downloads.autodownloads.AutoDownloadsManager")
    every { autoDownloadsManager.downloadsNeedsToBeDeletedOnFinishPlay(any(), any()) } just Runs

    verify(exactly = 1) { autoDownloadsManager.downloadsNeedsToBeDeletedOnFinishPlay(any(), any()) }
  }

  @Test
  fun `downloads needs To happen when new episode happened`() {
    mockkStatic("media.luminary.datastore.downloads.autodownloads.AutoDownloadsManager")
    every { autoDownloadsManager.downloadsNeedsToHappenWhenNewEpisodeHappened(any(), any()) } just Runs
    verify { autoDownloadsManager.downloadsNeedsToHappenWhenNewEpisodeHappened(any(), any()) }
  }`

**Comment by techartist** [comment]
Here is the method it is trying to verify: 

`  fun downloadsNeedsToBeDeletedOnFinishPlay(podcastUuid: String, uuid: String) {
    when (autoDownloadsPreference.frequencyOfDeletion) {
      DownloadRemoveTime.IMMEDIATE -> removeDownload(podcastUuid, uuid)
      DownloadRemoveTime.HOUR -> setWorkManager(uuid, DownloadRemoveTime.HOUR.timeInMillis)
      DownloadRemoveTime.DAY -> setWorkManager(uuid, DownloadRemoveTime.DAY.timeInMillis)
      DownloadRemoveTime.WEEK -> setWorkManager(uuid, DownloadRemoveTime.WEEK.timeInMillis)
      DownloadRemoveTime.NEVER -> return
    }
  }`

**Comment by techartist** [comment]
[https://stackoverflow.com/questions/61543273/mockk-java-lang-assertionerror-verification-failed-call-1-of-1-was-not-called](https://stackoverflow.com)
