### ISSUE TITLE
Unit tests fail while running in parallel

### ISSUE THREAD

**Issue by vidhithakrar** [mockk/mockk#441]
Hello,

We are building an android application and trying to run unit tests in parallel. But we have seen that tests are randomly failing mainly around coEvery() with the below error trace:

```
// -----------------------[ STACK STARTS STARTS ] -----------------------
io.mockk.MockKException: every/verify {} block were run several times. Recorded calls count differ between runs
Round 1: class kotlinx.coroutines.Dispatchers.getDefault(), Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@701361bc, 1646506454, 69a1710526a31616, false, continuation {})
Round 2: class kotlinx.coroutines.Dispatchers.getDefault(), Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@61d249dd, -2142762796, 3db83aa5c0a6e689, true, continuation {})
Round 3: class kotlinx.coroutines.Dispatchers.getDefault(), Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@3bb0a4f9, 327815314, 30b3193d14a66153, false, continuation {})
Round 4: class kotlinx.coroutines.Dispatchers.getDefault(), Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@2aa0f680, -149144682, -65cb16f67bb63441, true, continuation {})
Round 5: class kotlinx.coroutines.Dispatchers.getDefault(), Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@ce15e48, 887782693, 2d87efda651ee452, true, continuation {})
Round 6: class kotlinx.coroutines.Dispatchers.getDefault(), Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@1eafab7d, 1685595042, 23ba9f5ded53d25, false, continuation {})
Round 7: class kotlinx.coroutines.Dispatchers.getDefault(), Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@f266c6c, 1786425005, 66c203d398a540e6, false, continuation {})
Round 8: class kotlinx.coroutines.Dispatchers.getDefault(), Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@5d45fd24, -1130733160, -573bf63f4fe048e3, false, continuation {})
Round 9: class kotlinx.coroutines.Dispatchers.getDefault(), Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@5f5e4527, 619769015, -16283545fae2ba0d, false, continuation {})
Round 10: class kotlinx.coroutines.Dispatchers.getDefault(), Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@4643b304, 8423907, 1d27af22fb622b6, true, continuation {})
Round 11: class kotlinx.coroutines.Dispatchers.getDefault(), Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@611a6d87, -440260358, 2b4c66500e4f5259, false, continuation {})
Round 12: class kotlinx.coroutines.Dispatchers.getDefault(), Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@1f6a3403, 1495051356, -3f3f4d11dd20860f, true, continuation {})
Round 13: class kotlinx.coroutines.Dispatchers.getDefault(), Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@7b16bf04, -202181733, 2ff6a35f484518b, true, continuation {})
Round 14: class kotlinx.coroutines.Dispatchers.getDefault(), Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@22703b73, -1638366947, -28f6c6f0da06454d, true, continuation {})
Round 15: class kotlinx.coroutines.Dispatchers.getDefault(), Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@4fb9f19b, -303834399, 47161c97a73de49, true, continuation {})
Round 16: class kotlinx.coroutines.Dispatchers.getDefault(), Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@6bde6a7a, 1610566939, -2098b61faf6bb1fc, false, continuation {})
Round 17: class kotlinx.coroutines.Dispatchers.getDefault(), Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@6d2f88f1, 79759958, -3df3f3a5dec74d92, false, continuation {})
Round 18: class kotlinx.coroutines.Dispatchers.getDefault(), Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@43f2e425, 1225745276, 626a9dfea2d44264, true, continuation {})
Round 19: class kotlinx.coroutines.Dispatchers.getDefault(), Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@314fcd71, -950554108, 44b3bf6e194019cc, false, continuation {})
Round 20: class kotlinx.coroutines.Dispatchers.getDefault(), Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@7032f2e1, -2117606186, -3f7eee8c271b4ad6, false, continuation {})
Round 21: class kotlinx.coroutines.Dispatchers.getDefault(), Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@4a935c5c, -1381261588, -3c7c9ef2316eb7c9, false, continuation {})
Round 22: Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@76d41a99, -74630799, 2416e75f63402f51, false, continuation {})
Round 23: Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@6b534f33, 2110398398, 7e6bcde5b6fe6f29, true, continuation {})
Round 24: Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@b9144e3, -418035249, -41bec1ba7c63e113, false, continuation {})
Round 25: Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@39127547, -1494836925, 437c51b00f9221c0, true, continuation {})
Round 26: Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@77963450, -1807175020, 60cbfa9a0f9769ec, false, continuation {})
Round 27: Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@1e69310c, -1115792911, -478ccb8f03d5fb4c, false, continuation {})
Round 28: Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@14b15e9e, 2044864458, 32dd5133770743e5, true, continuation {})
Round 29: Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@bb5560, 215170926, -6fc7edf96776652d, false, continuation {})
Round 30: Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@3dff4c3a, 1798162857, b668fe543e971c1, false, continuation {})
Round 31: Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@7be6f058, -1181863026, a0049da23e4ac90, false, continuation {})
Round 32: Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@197fd5ad, 1795931532, -19847d748b5769a3, true, continuation {})
Round 33: Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@24a8e32, -357140562, -b66d525ce7762ef, false, continuation {})
Round 34: Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@2745a4f5, 321197425, 494a11836be7bbb3, false, continuation {})
Round 35: Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@1a90cf38, 1412980170, 4b51d7463f85fd6c, true, continuation {})
Round 36: Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@50232204, 1150936744, 6e73c8b61522e4a1, false, continuation {})
Round 37: Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@61ba67fb, -945134582, 161ab55a41c8d3c3, true, continuation {})
Round 38: Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@5543ba09, 127164353, 289b863524403aef, true, continuation {})
Round 39: Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@5a0b60c6, -660896120, -750de411e697dcc8, true, continuation {})
Round 40: Foo(#1016).doSomething(io.mockk.renamed.java.util.List$Subclass16@5ee59dbe, 1914202033, -60b99102f5a0a262, false, continuation {})
at io.mockk.impl.recording.SignatureMatcherDetector$detect$1.invoke(SignatureMatcherDetector.kt:25)
at io.mockk.impl.recording.SignatureMatcherDetector.detect(SignatureMatcherDetector.kt:86)
at io.mockk.impl.recording.states.RecordingState.signMatchers(RecordingState.kt:39)
at io.mockk.impl.recording.states.RecordingState.round(RecordingState.kt:31)
at io.mockk.impl.recording.CommonCallRecorder.round(CommonCallRecorder.kt:50)
at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:59)
at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
at io.mockk.MockKDsl.internalCoEvery(API.kt:98)
at io.mockk.MockKKt.coEvery(MockK.kt:116)
at com.sample.mobile.FooTest.setUp(FooTest.kt:114)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:532)
at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.invokeMethodInExtensionContext(ClassTestDescriptor.java:436)
at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$synthesizeBeforeEachMethodAdapter$14(ClassTestDescriptor.java:424)
at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachMethods$2(TestMethodTestDescriptor.java:136)
at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:156)
at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachMethods(TestMethodTestDescriptor.java:135)
at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:110)
at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:108)
at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:170)
at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

// -----------------------[ STACK TRACE ENDS ] -----------------------
```

#### Context

* MockK version: 1.10.0
* OS: macOS 10.15.4
* Kotlin version: 1.3.60
* JDK version: 1.8
* JUnit version: junit5
* Type of test: unit test

Junit parallel configuration:
```
systemProperties["junit.jupiter.execution.parallel.enabled"] = true
systemProperties["junit.jupiter.execution.parallel.mode.default"] = "same_thread"
systemProperties["junit.jupiter.execution.parallel.mode.classes.default"] = "concurrent"
```

Sorry, I tried but could not reproduce on a minimal version. We have ~4700 tests, where we are facing this problem.

PS: I am new to mockk, hope I am not missing something obvious.

**Comment by vidhithakrar** [comment]
Does not look like a bug in mockk. It is capturing Dispatchers.getDefault() in CallRound because it is mocked in some of the tests and it is static that's why it is creating this problem.

Closing this issue.
