### ISSUE TITLE
re: java.lang.VerifyError on trying to mock an object

### ISSUE THREAD

**Issue by coolaneasy** [mockk/mockk#448]
Hi guys
I'm just trying to create a mock and I get the below error. The class is not final or anything. It has a private static method and its a java class but don't think that matters. 
What's going on? Any thoughts? The same mocking works in Mockito.

java.lang.VerifyError
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
	at io.mockk.proxy.jvm.transformation.InlineInstrumentation.execute(InlineInstrumentation.kt:39)
	at io.mockk.proxy.jvm.ProxyMaker.inline(ProxyMaker.kt:88)
	at io.mockk.proxy.jvm.ProxyMaker.proxy(ProxyMaker.kt:30)
	at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:34)
	at io.mockk.impl.instantiation.AbstractMockFactory.newProxy$default(AbstractMockFactory.kt:28)
	at io.mockk.impl.instantiation.AbstractMockFactory.mockk(AbstractMockFactory.kt:53)

Happy to contribute a fix, if it happens to be a bug. Just need to understand whats going on.

Thanks

**Comment by LikeTheSalad** [comment]
I'd like to point out that I'm facing the same issue when trying to mock a particular class from a Java library I'm using in my project. I hope it helps if I point out which class it is: http://jsdp.sourceforge.net/api/net/sourceforge/jsdp/SessionDescription.html

I noticed that if I don't try to mock that class, everything works with no issues. However, I need to be able to mock it, and I was wondering if this is something we could avoid by adding some config on our side? I noticed in previous bugs they say it might be a Kotlin compile issue: https://github.com/mockk/mockk/issues/419 But it seems like this is not the case because it all works well at runtime, and also, I took the time to try to mock the same class using Mockito, and it succeeded. So I was wondering if it's something that could be addressed on the mocking framework?

A few details of the environment in case it helps:

MockK version: 1.10.0
OS: Debian GNU/Linux 8 (jessie) 64-bit
Kotlin version: 1.3.72
JDK version: 1.7.0_221
JUnit version: 4.12
Type of test: unit test

Regards,
Cesar.

**Comment by oleksiyp** [comment]
Seems to me like a byte buddy error. Verification error mostly always refer to that level. Mockk and mockito use bytebuddy a bit differently by default. The idea of fixing such bug is to understand what is so special about this class and try to minimaize this thing. After this thing is found most probably you will need to submit ByteBuddy issue.

**Comment by LikeTheSalad** [comment]
I see, thanks @oleksiyp for your feedback. I'm not familiar with ByteBuddy, so I think I won't be able to check what's wrong with this class unless I get some free time to learn about it, though in any case, I was wondering that most likely the ByteBuddy guys would also want to know why their tool works fine with other frameworks and frankly, it would be a good argument for them to get away with it, because is quite a good point. So in the case I wanted to take a deeper look by myself on this, could you let me know more or less what exactly is this difference between the way Mockito and Mockk use ByteBuddy that you mentioned, so that myself or whoever goes to ByteBuddy can use as a valid reason for asking them to solve this issue?

Regards,
Cesar.

**Comment by AlexaForApps** [comment]
@LikeTheSalad Thanks Cesar for the much valuable details. I wish I could provide the class in my case. I saw yours to see if something common stood out but it didn't, not to my eyes.

@oleksiyp Do you think still think it's a ByteBuddy issue considering it works with Mockito? Or are you suggesting Mockk's use is proper and so ByteBuddy should fix it?

@oleksiyp Same question as Cesar. Can you tell us the difference in usage?

**Comment by coolaneasy** [comment]
@LikeTheSalad Thanks Cesar for the much valuable details. I wish I could provide the class in my case. I saw yours to see if something common stood out but it didn't, not to my eyes.

@oleksiyp Do you think still think it's a ByteBuddy issue considering it works with Mockito? Or are you suggesting Mockk's use is proper and so ByteBuddy should fix it?

@oleksiyp Same question as Cesar. Can you tell us the difference in usage?

**Comment by oleksiyp** [comment]
The problem here why I identify it as a ByteBuddy error is that "verify error" for ByteBuddy is like "compiler internal error" for "compiler" i.e. just produced non-digestible by VM code.

You can try to enable "inline" mode in Mockito. This mode is similar to what MockK is doing to byte code. Maybe the problem will reproduce. But the first argument(about verify error) is stronger probably anyway even if it is non-reproducible. 

https://mvnrepository.com/artifact/org.mockito/mockito-inline

**Comment by LikeTheSalad** [comment]
I already use mockito-inline, it's needed for kotlin because it's the only way to mock final classes. Anyways I guess based on what you say, if I got it right, this error happens after ByteBuddy does its job and it's when the VM tries to read ByteBuddy's output. I guess that if MockK doesn't make any changes to ByteBuddy's output then it'd all point to be a ByteBuddy's issue. I suppose with this is enough to raise a bug on their side, maybe they know about some config that could avoid this without having to make a new release. It still kinda weird that things work well on Mockito if they also use ByteBuddy, but anyway I hope the ByteBuddy guys know what it could be happening.

**Comment by coolaneasy** [comment]
@LikeTheSalad Cesar unless you have created issue with ByteBuddy already, I'm happy to coordinate an issue there. Let me know. Let's definitely use this thread as reference. I do wish to know the outcome 😛 (and hopefully a fix)

**Comment by LikeTheSalad** [comment]
Hi @coolaneasy, yeah sorry I left it open for a while, I just created a an issue on ByteBuddy's repo: https://github.com/raphw/byte-buddy/issues/883 hopefully we'll hear from them soon 🤞

**Comment by raphw** [comment]
So, I believe that Mokk's advice templates use class constants of the sort `Some.class`. Those constants were only introduced in Java 5 and `SessionDescription` is a version 4 class file.

Byte Buddy can remedy this, simply register a `TypeConstantAdjustment` in the agent builder. The fine difference is that the replacement construct throws a `ClassNotFoundException` and not a `NoClassDefFoundError` in case a class is not available at runtime.

**Comment by coolaneasy** [comment]
Hi @raphw. Thanks for the update. It seems you're suggesting a fix in the 1.10.11 release. Any idea when we can expect this?

Btw, I still don't understand why the old class causes problems. If the project sdk is set to 1.8 shouldn't that build the class in that version?

Thanks

**Comment by raphw** [comment]
I just mark the version this question applies to. This needs to be fixed in Mockk.

**Comment by coolaneasy** [comment]
@oleksiyp

**Comment by coolaneasy** [comment]
Hello @oleksiyp 

Any comments/thoughts from your end regarding the fix needed in Mockk?
Just wanted to check.

Thank you

**Comment by distante** [comment]
Are there news about this?

I can reproduce this error when trying to mocking a Kotlin `data class`

**Comment by LikeTheSalad** [comment]
Seems like we were ignored

**Comment by Raibaz** [comment]
Hi, sorry about this.

Any chance you can provide a reproducible test case for me to start looking into it?

**Comment by pedorro** [comment]
HI - thx for the kick-ass Mockk framework :)

I seem to be getting this error pretty consistently mocking `javax.mail.internet.MimeMessage`
```
    @Test
    internal fun `MimeMessage - VerifyError`() {
        mockk<javax.mail.internet.MimeMessage>()
    }
```

Produces:
> java.lang.VerifyError
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:167)
	at io.mockk.proxy.jvm.transformation.JvmInlineInstrumentation.retransform(JvmInlineInstrumentation.kt:28)
	at io.mockk.proxy.common.transformation.RetransformInlineInstrumnetation$execute$1.invoke(RetransformInlineInstrumnetation.kt:19)
	at io.mockk.proxy.common.transformation.RetransformInlineInstrumnetation$execute$1.invoke(RetransformInlineInstrumnetation.kt:6)
	at io.mockk.proxy.common.transformation.ClassTransformationSpecMap.applyTransformation(ClassTransformationSpecMap.kt:41)
	at io.mockk.proxy.common.transformation.RetransformInlineInstrumnetation.execute(RetransformInlineInstrumnetation.kt:16)
	at io.mockk.proxy.jvm.ProxyMaker.inline(ProxyMaker.kt:88)
	at io.mockk.proxy.jvm.ProxyMaker.proxy(ProxyMaker.kt:30)
	at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:34)
	at io.mockk.impl.instantiation.AbstractMockFactory.newProxy$default(AbstractMockFactory.kt:29)
	at io.mockk.impl.instantiation.AbstractMockFactory.mockk(AbstractMockFactory.kt:59)
	at service.job.objectlock.ObjectLockJobServiceTest.MimeMessage - VerifyError$peanut_hamper_server(ObjectLockJobServiceTest.kt:690)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at ..... <omitted>

What's odd is that the line referenced in my test class (ObjectLockJobServiceTest.kt:690) is not a real line number.  That test file only has 392 lines in it total

**Comment by pedorro** [comment]
Bump... To prevent marking stale.

Any chance this can be marked important? I'm pretty sure it's a real thing.

**Comment by Raibaz** [comment]
Yep, seems like it's an actual bug indeed.

A possible fix would be registering a `TypeConstantAdjustment` like @raphw suggested.

**Comment by coolaneasy** [comment]
Thanks @Raibaz for marking it important.

**Comment by wfan3** [comment]
Any news for this? I've had this error when I tried to stubbing... (Changed to mockito and works. But using mockito in Kotlin required more works & more code... e.g. mock an object in kotlin)

**Comment by tbotalla** [comment]
The same problem here, any workaround?

**Comment by ToufiPF** [comment]
Same issue as well, it happens when mocking pretty much any class from `javax.mail`. 
For instance:
```kotlin
import io.mockk.mockk
import javax.mail.Session

val session: Session = mockk(relaxed = true)
```
produces
```
java.lang.VerifyError
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:169)
	at io.mockk.proxy.jvm.transformation.JvmInlineInstrumentation.retransform(JvmInlineInstrumentation.kt:28)
	at io.mockk.proxy.common.transformation.RetransformInlineInstrumentation$execute$1.invoke(RetransformInlineInstrumentation.kt:19)
	at io.mockk.proxy.common.transformation.RetransformInlineInstrumentation$execute$1.invoke(RetransformInlineInstrumentation.kt:16)
	at io.mockk.proxy.common.transformation.ClassTransformationSpecMap.applyTransformation(ClassTransformationSpecMap.kt:41)
	at io.mockk.proxy.common.transformation.RetransformInlineInstrumentation.execute(RetransformInlineInstrumentation.kt:16)
	at io.mockk.proxy.common.ProxyMaker.inline(ProxyMaker.kt:104)
	at io.mockk.proxy.common.ProxyMaker.proxy(ProxyMaker.kt:48)
	at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:34)
	at io.mockk.impl.instantiation.AbstractMockFactory.newProxy$default(AbstractMockFactory.kt:24)
	at io.mockk.impl.instantiation.AbstractMockFactory.mockk(AbstractMockFactory.kt:59)
	at ch.epfl.smsproxy.relay.EmailServiceTest.init(EmailServiceTest.kt:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:108)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

Could we have a bit more detail on the fix @Raibaz proposed above? Is it for us users to do or in the mockk library itself?

**Comment by HarshitPersona** [comment]
I am also getting similar error while trying to mock Volley- 
```
java.lang.VerifyError
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(Unknown Source)
	at io.mockk.proxy.jvm.transformation.JvmInlineInstrumentation.retransform(JvmInlineInstrumentation.kt:28)
	at io.mockk.proxy.common.transformation.RetransformInlineInstrumentation$execute$1.invoke(RetransformInlineInstrumentation.kt:19)
	at io.mockk.proxy.common.transformation.RetransformInlineInstrumentation$execute$1.invoke(RetransformInlineInstrumentation.kt:16)
	at io.mockk.proxy.common.transformation.ClassTransformationSpecMap.applyTransformation(ClassTransformationSpecMap.kt:41)
	at io.mockk.proxy.common.transformation.RetransformInlineInstrumentation.execute(RetransformInlineInstrumentation.kt:16)
	at io.mockk.proxy.common.ProxyMaker.inline(ProxyMaker.kt:104)
	at io.mockk.proxy.common.ProxyMaker.proxy(ProxyMaker.kt:48)
	at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:34)
	at io.mockk.impl.instantiation.AbstractMockFactory.newProxy$default(AbstractMockFactory.kt:24)
	at io.mockk.impl.instantiation.AbstractMockFactory.temporaryMock(AbstractMockFactory.kt:127)
	at io.mockk.impl.recording.states.RecordingState$call$temporaryMock$1.invoke(RecordingState.kt:69)
	at io.mockk.impl.instantiation.JvmAnyValueGenerator$anyValue$2.invoke(JvmAnyValueGenerator.kt:35)
	at io.mockk.impl.instantiation.AnyValueGenerator.anyValue(AnyValueGenerator.kt:34)
	at io.mockk.impl.instantiation.JvmAnyValueGenerator.anyValue(JvmAnyValueGenerator.kt:31)
	at io.mockk.impl.recording.states.RecordingState.call(RecordingState.kt:75)
	at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)
	at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:269)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:24)
	at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:21)
	at io.persona3.android.pms.ads.services.VolleyClient.post(VolleyClient.kt:48)
	at io.persona3.android.pms.ads.components.adeventscomponent.AdEventServiceTest$sendAdImpressionEvent$2.invokeSuspend(AdEventServiceTest.kt:329)
	at io.persona3.android.pms.ads.components.adeventscomponent.AdEventServiceTest$sendAdImpressionEvent$2.invoke(AdEventServiceTest.kt)
	at io.persona3.android.pms.ads.components.adeventscomponent.AdEventServiceTest$sendAdImpressionEvent$2.invoke(AdEventServiceTest.kt)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$2$1.invokeSuspend(RecordedBlockEvaluator.kt:27)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$2$1.invoke(RecordedBlockEvaluator.kt)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$2$1.invoke(RecordedBlockEvaluator.kt)
	at io.mockk.InternalPlatformDsl$runCoroutine$1.invokeSuspend(InternalPlatformDsl.kt:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at io.mockk.InternalPlatformDsl.runCoroutine(InternalPlatformDsl.kt:22)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$2.invoke(RecordedBlockEvaluator.kt:27)
	at io.mockk.impl.eval.RecordedBlockEvaluator$enhanceWithRethrow$1.invoke(RecordedBlockEvaluator.kt:76)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:39)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalCoEvery(API.kt:100)
	at io.mockk.MockKKt.coEvery(MockK.kt:169)
	at io.persona3.android.pms.ads.components.adeventscomponent.AdEventServiceTest.sendAdImpressionEvent(AdEventServiceTest.kt:329)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:108)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```
