### ISSUE TITLE
Subclass verification failure when using any<T>

### ISSUE THREAD

**Issue by rojanthomas** [mockk/mockk#449]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

MockK can distinguish which subclass was passed into the method, so that I can verify a certain subclass was passed

### Current Behavior

MockK cannot currently distinguish between different subclasses

### Failure Information (for bugs)

Not sure if it's a bug or a known limitation, apologies if it is

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Run minimal reproducible code

#### Stack trace

```
java.lang.AssertionError: Verification failed: call 1 of 1: SomeInterface(sut#1).doSomething(any())) should not be called

Calls:
1) SomeInterface(sut#1).doSomething(SubclassVerificationFailure$SomeClass$A@3b77a04f)

Stack traces:
1)                                 io.mockk.impl.InternalPlatform.captureStackTrace                                                          (InternalPlatform.kt:121)             
                                     io.mockk.impl.stub.MockKStub.handleInvocation                                                           (MockKStub.kt:247)                    
   io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation                                                                 (JvmMockFactoryHelper.kt:25)          
                            io.mockk.proxy.jvm.advice.Interceptor.call                                                                       (Interceptor.kt:20)                   
                             io.mockk.proxy.jvm.advice.BaseAdvice.handle                                                                     (BaseAdvice.kt:42)                    
           io.mockk.proxy.jvm.advice.jvm.JvmMockKProxyInterceptor.interceptNoSuper                                                           (JvmMockKProxyInterceptor.java:45)    
              SubclassVerificationFailure$SomeInterface$Subclass0.doSomething                                                                (-:-1)                                
                                      SubclassVerificationFailure.given A is passed as a parameter to the sut, B should not have been passed (SubclassVerificationFailure.kt:28)   
                             sun.reflect.NativeMethodAccessorImpl.invoke0                                                                    (NativeMethodAccessorImpl.java:-2)N   
                             sun.reflect.NativeMethodAccessorImpl.invoke                                                                     (NativeMethodAccessorImpl.java:62)    
                         sun.reflect.DelegatingMethodAccessorImpl.invoke                                                                     (DelegatingMethodAccessorImpl.java:43)
                                         java.lang.reflect.Method.invoke                                                                     (Method.java:498)                     
                        org.junit.runners.model.FrameworkMethod$1.runReflectiveCall                                                          (FrameworkMethod.java:50)             
              org.junit.internal.runners.model.ReflectiveCallable.run                                                                        (ReflectiveCallable.java:12)          
                          org.junit.runners.model.FrameworkMethod.invokeExplosively                                                          (FrameworkMethod.java:47)             
               org.junit.internal.runners.statements.InvokeMethod.evaluate                                                                   (InvokeMethod.java:17)                
                 org.junit.internal.runners.statements.RunBefores.evaluate                                                                   (RunBefores.java:26)                  
                                   org.junit.runners.ParentRunner.runLeaf                                                                    (ParentRunner.java:325)               
                         org.junit.runners.BlockJUnit4ClassRunner.runChild                                                                   (BlockJUnit4ClassRunner.java:78)      
                         org.junit.runners.BlockJUnit4ClassRunner.runChild                                                                   (BlockJUnit4ClassRunner.java:57)      
                                 org.junit.runners.ParentRunner$3.run                                                                        (ParentRunner.java:290)               
                                 org.junit.runners.ParentRunner$1.schedule                                                                   (ParentRunner.java:71)                
                                   org.junit.runners.ParentRunner.runChildren                                                                (ParentRunner.java:288)               
                                   org.junit.runners.ParentRunner.access$000                                                                 (ParentRunner.java:58)                
                                 org.junit.runners.ParentRunner$2.evaluate                                                                   (ParentRunner.java:268)               
                                   org.junit.runners.ParentRunner.run                                                                        (ParentRunner.java:363)               
                                       org.junit.runner.JUnitCore.run                                                                        (JUnitCore.java:137)                  
                         com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs                                                        (JUnit4IdeaTestRunner.java:68)        
                    com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs                                                        (IdeaTestRunner.java:33)              
                               com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart                                                     (JUnitStarter.java:230)               
                               com.intellij.rt.junit.JUnitStarter.main                                                                       (JUnitStarter.java:58)                

	at io.mockk.impl.recording.states.VerifyingState.failIfNotPassed(VerifyingState.kt:66)
	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:42)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:60)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalVerify(API.kt:118)
	at io.mockk.MockKKt.verify(MockK.kt:139)
	at io.mockk.MockKKt.verify$default(MockK.kt:136)
	at SubclassVerificationFailure.given A is passed as a parameter to the sut, B should not have been passed(SubclassVerificationFailure.kt:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
import io.mockk.MockKAnnotations
import io.mockk.impl.annotations.RelaxedMockK
import io.mockk.verify
import org.junit.Before
import org.junit.Test

class SubclassVerificationFailure {

    interface SomeClass {
        object A : SomeClass
        object B : SomeClass
    }

    interface SomeInterface {
        fun doSomething(clazz: SomeClass)
    }

    @RelaxedMockK
    lateinit var sut: SomeInterface

    @Before
    fun setUp() {
        MockKAnnotations.init(this)
    }

    @Test
    fun `given A is passed as a parameter to the sut, B should not have been passed`() {
        sut.doSomething(SomeClass.A)

        verify(exactly = 1) { sut.doSomething(any<SomeClass.A>()) }
        verify(exactly = 0) { sut.doSomething(any<SomeClass.B>()) }
    }
}
```

Appreciate any time you guys can put into the read into my issue. If it's a known limitation, apologies! It seems to be that the generics for the any<T> I'm passing in are lost when it comes to the verification.

**Comment by rojanthomas** [comment]
@oleksiyp Would you be able to provide any insight? Is it a limitation of the library?

**Comment by thomashorta** [comment]
Hey @rojanthomas, I ran into the same issue in the past and I believe what you want is to verify that the method is being called with an argument of a specific type, not really caring about the reference or content itself, right?

For that, you cannot use the `any()` matcher. Instead, MockK offers an `ofType()` matcher that does what you need.

Example (using the gist posted):
```kotlin
    @Test
    fun `given A is passed as a parameter to the sut, B should not have been passed`() {
        sut.doSomething(SomeClass.A)

        verify(exactly = 1) { sut.doSomething(ofType<SomeClass.A>()) }
        verify(exactly = 0) { sut.doSomething(ofType<SomeClass.B>()) }
    }
}
```

**Comment by rojanthomas** [comment]
Hey @thomashorta this is exactly what I was looking for.

It makes sense now, thanks a lot 😀
