### ISSUE TITLE
mockkConstructor doesn't work as expected

### ISSUE THREAD

**Issue by liuzhenhuanet** [mockk/mockk#456]
mockk version: 1.9

when I write this code in androidTest:
```
mockkConstructor(XXX::class)
every { anyConstructed<XXX>().foo() } returns results
```
It doesn't work as expected, just print some warnings in logcat, eg:

```
2020-06-19 21:01:30.926 12552-12552/com.fenbi.tutor.webview.test W/or.webview.tes: Verification error in void com.fenbi.tutor.live.jsinterface.plugin.WebSpeakingPlugin.<clinit>()
2020-06-19 21:01:30.926 12552-12552/com.fenbi.tutor.webview.test W/or.webview.tes: void com.fenbi.tutor.live.jsinterface.plugin.WebSpeakingPlugin.<clinit>() failed to verify: void com.fenbi.tutor.live.jsinterface.plugin.WebSpeakingPlugin.<clinit>(): [0x27] copy1 v3<-v5 type=Undefined cat=3
2020-06-19 21:01:30.926 12552-12552/com.fenbi.tutor.webview.test W/or.webview.tes: Verification error in void com.fenbi.tutor.live.jsinterface.plugin.WebSpeakingPlugin.<init>(android.app.Activity, com.fenbi.tutor.live.engine.speaking.AudioRecorder, com.fenbi.tutor.live.jsinterface.plugin.WebSpeakingPlugin$IWebSpeakingAudioDenied, int, kotlin.jvm.internal.DefaultConstructorMarker)
2020-06-19 21:01:30.926 12552-12552/com.fenbi.tutor.webview.test W/or.webview.tes: void com.fenbi.tutor.live.jsinterface.plugin.WebSpeakingPlugin.<init>(android.app.Activity, com.fenbi.tutor.live.engine.speaking.AudioRecorder, com.fenbi.tutor.live.jsinterface.plugin.WebSpeakingPlugin$IWebSpeakingAudioDenied, int, kotlin.jvm.internal.DefaultConstructorMarker) failed to verify: void com.fenbi.tutor.live.jsinterface.plugin.WebSpeakingPlugin.<init>(android.app.Activity, com.fenbi.tutor.live.engine.speaking.AudioRecorder, com.fenbi.tutor.live.jsinterface.plugin.WebSpeakingPlugin$IWebSpeakingAudioDenied, int, kotlin.jvm.internal.DefaultConstructorMarker): [0x31] copy1 v3<-v8 type=Reference: com.fenbi.tutor.live.jsinterface.plugin.WebSpeakingPlugin$IWebSpeakingAudioDenied cat=1
2020-06-19 21:01:30.934 12552-12552/com.fenbi.tutor.webview.test W/or.webview.tes: FAILURE TO RETRANFORM Unable to perform redefinition of 'Lcom/fenbi/tutor/live/jsinterface/plugin/WebSpeakingPlugin;': Failed to verify class. Error was: Verifier rejected class com.fenbi.tutor.live.jsinterface.plugin.WebSpeakingPlugin: void com.fenbi.tutor.live.jsinterface.plugin.WebSpeakingPlugin.<clinit>() failed to verify: void com.fenbi.tutor.live.jsinterface.plugin.WebSpeakingPlugin.<clinit>(): [0x27] copy1 v3<-v5 type=Undefined cat=3
2020-06-19 21:01:30.934 12552-12552/com.fenbi.tutor.webview.test W/or.webview.tes:  void com.fenbi.tutor.live.jsinterface.plugin.WebSpeakingPlugin.<init>(android.app.Activity, com.fenbi.tutor.live.engine.speaking.AudioRecorder, com.fenbi.tutor.live.jsinterface.plugin.WebSpeakingPlugin$IWebSpeakingAudioDenied, int, kotlin.jvm.internal.DefaultConstructorMarker) failed to verify: void com.fenbi.tutor.live.jsinterface.plugin.WebSpeakingPlugin.<init>(android.app.Activity, com.fenbi.tutor.live.engine.speaking.AudioRecorder, com.fenbi.tutor.live.jsinterface.plugin.WebSpeakingPlugin$IWebSpeakingAudioDenied, int, kotlin.jvm.internal.DefaultConstructorMarker): [0x31] copy1 v3<-v8 type=Reference: com.fenbi.tutor.live.jsinterface.plugin.WebSpeakingPlugin$IWebSpeakingAudioDenied cat=1
2020-06-19 21:01:30.936 12552-12552/com.fenbi.tutor.webview.test W/idInlineInstrumentation: Failed to transform classes TransformationRequest(classes=[class com.fenbi.tutor.live.jsinterface.plugin.WebSpeakingPlugin], type=CONSTRUCTOR, untransform=false)
    java.lang.RuntimeException: Could not retransform classes: 62
        at io.mockk.proxy.android.JvmtiAgent.nativeRetransformClasses(Native Method)
        at io.mockk.proxy.android.JvmtiAgent.requestTransformClasses(JvmtiAgent.kt:64)
        at io.mockk.proxy.android.transformation.AndroidInlineInstrumentation.retransform(AndroidInlineInstrumentation.kt:15)
        at io.mockk.proxy.common.transformation.RetransformInlineInstrumnetation.execute(RetransformInlineInstrumnetation.kt:23)
        at io.mockk.proxy.android.ConstructorProxyMaker.constructorProxy(ConstructorProxyMaker.kt:19)
        at io.mockk.impl.instantiation.JvmConstructorMockFactory$ConstructorInvocationHandler.push(JvmConstructorMockFactory.kt:115)
        at io.mockk.impl.instantiation.JvmConstructorMockFactory.constructorMockk(JvmConstructorMockFactory.kt:172)
        at com.fenbi.tutor.live.jsinterface.plugin.WebSpeakingPluginTest$test$1.invokeSuspend(WebSpeakingPluginTest.kt:96)
        at com.fenbi.tutor.live.jsinterface.plugin.WebSpeakingPluginTest$test$1.invoke(Unknown Source:10)
        at com.fenbi.tutor.live.jsinterface.plugin.ProtoTestContext$Companion$create$1.invokeSuspend(ProtoTestContext.kt:67)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**Comment by zuhriyansauqi** [comment]
Confirmed. I got this error either by using the same steps as @liuzhenhuanet did.
I think this error happened due to the mocked class have companion objects.

**Comment by erikhuizinga** [comment]
So you're saying that a class like the following would reproduce the issue?

```kotlin
class XXX {
	fun foo() {}
	companion object {}
}
```

**Comment by zuhriyansauqi** [comment]
@erikhuizinga yeah. 
```kotlin
class XXX {
  fun foo() { }
  companion object {
    const val A = ...
    const val B = ...
  }
}
```
Current workaround
```kotlin
class XXX {
  val a = ...
  val b = ...

  fun foo() { }
}
```

**Comment by GuffyChen** [comment]
I also encountered the same problem. After testing, I found that as long as there is companion object, the `mockkConstructor` would not work.

**Comment by SmallBearBeast** [comment]
I reproduce the bug with similar error log as @liuzhenhuanet with androidTestImplementation "io.mockk:mockk-android:1.11.0".
But in testImplementation 'io.mockk:mockk:1.11.0', it can work. What is difference between the  testImplementation and androidTestImplementation in same version.

**Comment by victormpineda** [comment]
I get this same error when trying to spy an interface class:
```
   var spy = spyk(myInterface)
            coEvery { spy.myMethod(allAny()) } returns myData
            ````

**Comment by DarkSherlock** [comment]
class {
 val a lazy by {
  xxx()
  }
}

lazy filed also make this error

**Comment by mandy-xie** [comment]
I got same error when I recently upgrade my project's kotlin version to 1.9.22

**Comment by SnyersK** [comment]
Having the same error here
Seems to be due to a companion object being present indeed

Has anyone found a fix for this?

**Comment by williscool** [comment]
I have this issue . is there a fix?

**Comment by ron-lbb** [comment]
A very frustrating issue
