### ISSUE TITLE
Crash: java.lang.ClassNotFoundException: io.mockk.proxy.MockKAgentFactory

### ISSUE THREAD

**Issue by igorwojda** [mockk/mockk#459]
### Expected Behavior

Mocking works

### Current Behavior

Crash

### Failure Information (for bugs)

Using kotest framework

#### Steps to Reproduce

Run test using Kotest plugin

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.10.0
* OS: MacOS 10.15.5
* Kotlin version: 1.3.72
* JDK version: 1.8
* JUnit version: 5
* Type of test: unit test

#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
io/mockk/proxy/MockKAgentFactory
java.lang.NoClassDefFoundError: io/mockk/proxy/MockKAgentFactory
	at io.mockk.impl.JvmMockKGateway.<init>(JvmMockKGateway.kt:184)
	at io.mockk.impl.JvmMockKGateway.<clinit>(JvmMockKGateway.kt:172)
	at com.tokbox.opentokdemo.presentation.screen.intro.JoinMeetingViewModelSpec$1.invokeSuspend(JoinMeetingViewModelSpec.kt:92)
	at com.tokbox.opentokdemo.presentation.screen.intro.JoinMeetingViewModelSpec$1.invoke(JoinMeetingViewModelSpec.kt)
	at io.kotest.core.spec.Spec$beforeTest$1.beforeTest(Spec.kt:78)
	at io.kotest.core.runtime.CallbacksKt.invokeBeforeTest(callbacks.kt:70)
	at io.kotest.core.runtime.TestCaseExecutor.executeActiveTest(TestCaseExecutor.kt:123)
	at io.kotest.core.runtime.TestCaseExecutor$intercept$2.invokeSuspend(TestCaseExecutor.kt:75)
	at io.kotest.core.runtime.TestCaseExecutor$intercept$2.invoke(TestCaseExecutor.kt)
	at io.kotest.core.runtime.TestCaseExecutor.executeIfActive(TestCaseExecutor.kt:89)
	at io.kotest.core.runtime.TestCaseExecutor.intercept(TestCaseExecutor.kt:75)
	at io.kotest.core.runtime.TestCaseExecutor.execute(TestCaseExecutor.kt:56)
	at io.kotest.core.engine.SingleInstanceSpecRunner.runTest(SingleInstanceSpecRunner.kt:60)
	at io.kotest.core.engine.SingleInstanceSpecRunner$execute$2$invokeSuspend$$inlined$invoke$lambda$1.invokeSuspend(SingleInstanceSpecRunner.kt:70)
	at io.kotest.core.engine.SingleInstanceSpecRunner$execute$2$invokeSuspend$$inlined$invoke$lambda$1.invoke(SingleInstanceSpecRunner.kt)
	at io.kotest.core.engine.SpecRunner$runParallel$$inlined$map$lambda$1$1.invokeSuspend(SpecRunner.kt:51)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at io.kotest.core.engine.SpecRunner$runParallel$$inlined$map$lambda$1.run(SpecRunner.kt:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: io.mockk.proxy.MockKAgentFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 30 more
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    testImplementation("io.kotest:kotest-runner-junit5-jvm:4.1.1")
    testImplementation("io.kotest:kotest-assertions-core-jvm:4.1.1")
    testImplementation("io.kotest:kotest-property-jvm:4.1.1")
    testImplementation("io.kotest:kotest-runner-console-jvm:4.1.1")
    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.3.7")
    testImplementation("io.mockk:mockk:1.10.0")
    testImplementation("androidx.arch.core:core-testing:2.1.0")
    testImplementation("")


}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
import androidx.arch.core.executor.ArchTaskExecutor
import androidx.arch.core.executor.TaskExecutor
import com.tokbox.opentokdemo.presentation.screen.joinmeeting.JoinMeetingViewModel
import com.tokbox.opentokdemo.presentation.util.NavManager
import io.kotest.core.listeners.TestListener
import io.kotest.core.spec.Spec
import io.kotest.core.spec.style.ShouldSpec
import io.mockk.mockk

class JoinMeetingViewModelSpec : ShouldSpec() {

    lateinit var navManager: NavManager
    lateinit var cut: JoinMeetingViewModel

    init {
        listener(InstantExecutorListener())

        beforeTest {
            navManager = mockK() // This fails
            cut = JoinMeetingViewModel(navManager)
        }

        should("navigate to tokbox faq wep page") {
            //...
        }
    }
}
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by igorwojda** [comment]
I am attaching Android project [MockkKoTest.zip](https://github.com/mockk/mockk/files/4852801/MockkKoTest.zip)

When running using `kotest` plugin 1.0.2
1. JoinMeetingViewModelSpec1 fails because of `MockKAgentFactory` problem
2. JoinMeetingViewModelSpec2 fails because of other problem

When running from cdm `./gradlew test` there is not indication about tests. where tests found? where tests runned at all?

**Comment by Sergioct** [comment]
Same error here using kotest 4.1.1 trying to debug

**Comment by kevc** [comment]
I'm also seeing this issue with the same setup. From what I can tell, tests are still run via CLI (`./gradlew test...`).

**Comment by Reevn** [comment]
Same issue here. Works when run with gradle tasks, but crashes when using the Kotest 1.0.5 IntelliJ plugin.

**Comment by carterhudson** [comment]
Same issue here. I opened an issue (https://github.com/mockk/mockk/issues/467) before I found this.

**Comment by carterhudson** [comment]
Turns out it's a Kotest plugin issue. Working snapshot here: https://github.com/kotest/kotest/issues/1603#issuecomment-666724979

**Comment by Reevn** [comment]
Works with the latest version of the Kotest plugin (`1.1.9`)
