### ISSUE TITLE
mockk + Kotest = Caused by: java.lang.NoClassDefFoundError: io/mockk/proxy/MockKAgentFactory

### ISSUE THREAD

**Issue by carterhudson** [mockk/mockk#467]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

Test runs without issue

### Current Behavior

Tests fail with `java.lang.NoClassDefFoundError: io/mockk/proxy/MockKAgentFactory`

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.10.0
* OS: MacOS Catalina
* Kotlin version: 1.3.72
* JDK version: 1.8
* JUnit version: 5
* Type of test: Unit

#### Stack trace

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at io.kotest.core.engine.InstantiateSpecKt.javaReflectNewInstance(instantiateSpec.kt:22)
	at io.kotest.core.engine.InstantiateSpecKt.instantiateSpec(instantiateSpec.kt:16)
	at io.kotest.core.engine.SpecExecutor.createInstance(SpecExecutor.kt:95)
	at io.kotest.core.engine.SpecExecutor.execute(SpecExecutor.kt:35)
	at io.kotest.core.engine.KotestEngine$submitBatch$$inlined$forEach$lambda$1$1.invokeSuspend(KotestEngine.kt:66)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at io.kotest.core.engine.KotestEngine$submitBatch$$inlined$forEach$lambda$1.run(KotestEngine.kt:65)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: io/mockk/proxy/MockKAgentFactory
	at io.mockk.impl.JvmMockKGateway.<init>(JvmMockKGateway.kt:184)
	at io.mockk.impl.JvmMockKGateway.<clinit>(JvmMockKGateway.kt:172)
	at com.syf.synchronysdk.architecture.SubscriptionManagerTest.<init>(SubscriptionManagerTest.kt:38)
	... 23 more
Caused by: java.lang.ClassNotFoundException: io.mockk.proxy.MockKAgentFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 26 more
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at io.kotest.core.engine.InstantiateSpecKt.javaReflectNewInstance(instantiateSpec.kt:22)
	at io.kotest.core.engine.InstantiateSpecKt.instantiateSpec(instantiateSpec.kt:16)
	at io.kotest.core.engine.SpecExecutor.createInstance(SpecExecutor.kt:95)
	at io.kotest.core.engine.SpecExecutor.execute(SpecExecutor.kt:35)
	at io.kotest.core.engine.KotestEngine$submitBatch$$inlined$forEach$lambda$1$1.invokeSuspend(KotestEngine.kt:66)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at io.kotest.core.engine.KotestEngine$submitBatch$$inlined$forEach$lambda$1.run(KotestEngine.kt:65)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: io/mockk/proxy/MockKAgentFactory
	at io.mockk.impl.JvmMockKGateway.<init>(JvmMockKGateway.kt:184)
	at io.mockk.impl.JvmMockKGateway.<clinit>(JvmMockKGateway.kt:172)
	at com.syf.synchronysdk.architecture.SubscriptionManagerTest.<init>(SubscriptionManagerTest.kt:38)
	... 23 more

Caused by: java.lang.ClassNotFoundException: io.mockk.proxy.MockKAgentFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 26 more

java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at io.kotest.core.engine.InstantiateSpecKt.javaReflectNewInstance(instantiateSpec.kt:22)
	at io.kotest.core.engine.InstantiateSpecKt.instantiateSpec(instantiateSpec.kt:16)
	at io.kotest.core.engine.SpecExecutor.createInstance(SpecExecutor.kt:95)
	at io.kotest.core.engine.SpecExecutor.execute(SpecExecutor.kt:35)
	at io.kotest.core.engine.KotestEngine$submitBatch$$inlined$forEach$lambda$1$1.invokeSuspend(KotestEngine.kt:66)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at io.kotest.core.engine.KotestEngine$submitBatch$$inlined$forEach$lambda$1.run(KotestEngine.kt:65)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: io/mockk/proxy/MockKAgentFactory
	at io.mockk.impl.JvmMockKGateway.<init>(JvmMockKGateway.kt:184)
	at io.mockk.impl.JvmMockKGateway.<clinit>(JvmMockKGateway.kt:172)
	at com.syf.synchronysdk.architecture.SubscriptionManagerTest.<init>(SubscriptionManagerTest.kt:38)
	... 23 more
Caused by: java.lang.ClassNotFoundException: io.mockk.proxy.MockKAgentFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 26 more


Process finished with exit code 255

Spec failed
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
dependencies {
    // (Required) Writing and executing Unit Tests on the JUnit Platform
    testImplementation "org.junit.jupiter:junit-jupiter-api:5.6.2"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:5.6.2"

    // (Optional) If you also have JUnit 4-based tests
    testImplementation "junit:junit:4.13"
    testRuntimeOnly "org.junit.vintage:junit-vintage-engine:5.6.2"

    testImplementation 'io.kotest:kotest-runner-junit5-jvm:4.1.0' // for kotest framework
    testImplementation 'io.kotest:kotest-assertions-core-jvm:4.1.0' // for kotest core jvm assertions
    testImplementation 'io.kotest:kotest-property-jvm:4.1.0' // for kotest property test
    testImplementation 'io.kotest:kotest-runner-console-jvm:4.1.0' //for gutter |> icons w/ kotest plugin

    testImplementation "io.mockk:mockk:1.10.0"
}

class SubscriptionManagerTest : StringSpec() {

    data class RenderState(val doubleCount: Int) : State

    val store = createStore(CounterState(), counterReducer)

    val manager = object : SubscriptionManager<CounterState>(store) {}

    val component = mockk<ViewComponent<RenderState>>()

    init {

        "can subscribe component for distinct states" {
            manager.subscribe(component) {
                RenderState(it.count * 2)
            }

            manager.dispatch(object : Event {})
            verify(atMost = 1) { component.render(allAny()) }
        }
    }
}
```

**Comment by carterhudson** [comment]
Turns out it's a Kotest plugin issue - https://github.com/kotest/kotest/issues/1603#issuecomment-666724979
