### ISSUE TITLE
Bug: Cannot mock static function with Robolectric 4.4

### ISSUE THREAD

**Issue by lcdsmao** [mockk/mockk#480]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

Mock static function should success when using Robolectric 4.4

### Current Behavior

Mock static function failure when using Robolectric 4.4

### Failure Information (for bugs)

Stacktrace:
```
io.mockk.MockKException: Missing calls inside every { ... } block.

	at io.mockk.impl.recording.states.StubbingState.checkMissingCalls(StubbingState.kt:14)
	at io.mockk.impl.recording.states.StubbingState.recordingDone(StubbingState.kt:8)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:60)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalEvery(API.kt:92)
	at io.mockk.MockKKt.every(MockK.kt:104)
	at pkg.FooTest.test(FooTest.kt:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.9.3
* OS: MacOS 10.15.6 (19G2021)
* Kotlin version: 1.3.72
* JDK version: 11
* JUnit version: 
* Robolectric version: 4.4
* Type of test: Robolectric unit test

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    testImplementation "org.robolectric:robolectric:4.4"
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------

// Test target (pkg.Fookt):

class Foo
fun Foo.test() = "foo"

// Test code
@RunWith(AndroidJUnit4::class)
class FooTest {

  @Test
  fun test() {
    mockkStatic("pkg.FooKt")
    val foo: Foo = mockk()
    every { foo.test() } returns "bar" // Fail here
    println(foo.test())
    // Remove @RunWith(AndroidJUnit4::class) will print bar
  }
}

// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by JiongBull** [comment]
![image](https://user-images.githubusercontent.com/4413502/96120448-183e3700-0f21-11eb-879f-067c5f989327.png)


![image](https://user-images.githubusercontent.com/4413502/96120390-0361a380-0f21-11eb-98d9-a56fe6e7171c.png)

**Comment by mpost** [comment]
We see the same issue with a mocked extension function using mockk. On robolectric 4.4 using the `every {...}` directive does not work but instead calls through to the original implementation failing our tests.

**Comment by anticafe** [comment]
Hmm, if this bug is not resolved yet, I think better not to upgrade Robolectric to v4.4.

**Comment by aquintiliano** [comment]
+1

**Comment by baspartovi** [comment]
+1

**Comment by Leskevicius** [comment]
+1

**Comment by tyborg** [comment]
+1

**Comment by ahna92** [comment]
+1

**Comment by ahna92** [comment]
A workaround would be using MockitoJUnitRunner, 

but unfortunately if you need to use some static Android sdk methods MockitoJUnitRunner will fail

**Comment by RobertKeazor** [comment]
+1

**Comment by rmayobre** [comment]
+1

**Comment by anticafe** [comment]
Hi all, according to [this answer](https://github.com/robolectric/robolectric/issues/5994#issuecomment-715713102), use `mockkStatic(Class.forName("...").kotlin)` as a workaround to fix it.

**Comment by kingargyle** [comment]
A lot of the mockk issues seem to come from this https://github.com/robolectric/robolectric/pull/5754, but the Robolectric devs say they need more input from the mockk devs on what should be excluded and what shouldn't in regards to mockk.

Be nice if the two teams could touch base.

**Comment by Raibaz** [comment]
Looks like robolectric/robolectric#5754 is actually excluding the whole io.mockk package from compilation, so it's unlikely this can be solved by changing Mockk.

I'd be glad to get in touch with the Robolectric team, though.

In the meantime, closing this issue as it has a workaround.

**Comment by kingargyle** [comment]
@Raibaz the open issue if you want to comment on it on Robolectric is here. https://github.com/robolectric/robolectric/issues/5994
