### ISSUE TITLE
How to run tests in /jvm folder?

### ISSUE THREAD

**Issue by IgorGanapolsky** [mockk/mockk#484]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] I am running the latest version
- [x ] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed

### Expected Behavior

We should be able to run unit tests in /jvm folder in this project.

### Current Behavior

There is no instructions, and it is unclear how to run the unit tests in /jvm folder.

### Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Load the project in Intellij
2. Expand **/jvm** folder
3. See that there is no way to run these tests

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: latest master branch
* OS: MacOS
* Kotlin version: latest
* JDK version: 1.8
* JUnit version: 5
* Type of test: unit test OR android instrumented test
Unit test

#### Failure Logs

Please include any relevant log snippets or files here.

#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
Error:Internal error: (java.lang.ClassNotFoundException) javax.xml.bind.annotation.XmlSchema
java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:157)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:76)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:82)
	at org.jetbrains.jps.android.AndroidJpsUtil.getAndroidTarget(AndroidJpsUtil.java:405)
	at org.jetbrains.jps.android.AndroidJpsUtil.getAndroidPlatform(AndroidJpsUtil.java:481)
	at org.jetbrains.jps.android.builder.AndroidPreDexBuildTarget.computeRootDescriptors(AndroidPreDexBuildTarget.java:111)
	at org.jetbrains.jps.builders.impl.BuildRootIndexImpl.addRoots(BuildRootIndexImpl.java:72)
	at org.jetbrains.jps.builders.impl.BuildRootIndexImpl.<init>(BuildRootIndexImpl.java:62)
	at org.jetbrains.jps.cmdline.BuildRunner.load(BuildRunner.java:83)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:274)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:130)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:232)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    testCompile group: 'org.apache.kafka', name: 'kafka_2.12', version: '1.1.0'
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
package io.mockk.gh

import io.mockk.every
import io.mockk.mockk
import org.apache.kafka.common.KafkaFuture
import kotlin.test.Test

class Issue69Test {

    @Test
    fun test() {
        val kafkaFuture: KafkaFuture<Void> = mockk()
        every { kafkaFuture.get(any(), any()) } returns mockk()
        kafkaFuture.get(10, TimeUnit.MILLISECONDS)
    }

}
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by IgorGanapolsky** [comment]
What is the solution?

**Comment by Raibaz** [comment]
I have been able to run the tests in the /jvm folder in IntelliJ by right-clicking the src/main/kotlin folder and clicking "Run tests in 'Kotlin'":

![image](https://user-images.githubusercontent.com/1030142/101406973-7876a700-38da-11eb-8455-05da4a72653e.png)

**Comment by IgorGanapolsky** [comment]
This doesn't even build in Intellij:
> A problem occurred configuring project ':mockk-agent-android'.
> Failed to notify project evaluation listener.
   > NDK not configured. Download it with SDK manager. Preferred NDK version is '20.0.5594570'. Log: /workspace/git/mockk/mockk/agent/android/.cxx/ndk_locator_record.json
   > missing components to publish

**Comment by TopHatCroat** [comment]
@Raibaz  I believe this one can be closed with the documentation I've added to Wiki ^

**Comment by Raibaz** [comment]
@TopHatCroat thanks!
