### ISSUE TITLE
kotlin 1.4.0 java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by AbdElraoufSabri** [mockk/mockk#486]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

AndroidX JVM unit tests passed successfully.

### Current Behavior

Test fails

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.10.0
* OS: Ubuntu 20.04
* Kotlin version: 1.4.0 also tested with 1.3.72
* JDK version: 1.8.0_232.fx also tested with 8.0.265.fx
* JUnit version: 4.13
* Type of test: unit test

#### Stack trace

```
java.lang.ExceptionInInitializerError
	at me.abdelraoufsabri.ClassTest<init>(ClassTest.kt:51)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:250)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:260)
	at org.junit.runners.BlockJUnit4ClassRunner$2.runReflectiveCall(BlockJUnit4ClassRunner.java:309)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@737996a0
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:613)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:586)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:538)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:515)
	at io.mockk.proxy.jvm.JvmMockKAgentFactory.initInstrumentation(JvmMockKAgentFactory.kt:134)
	at io.mockk.proxy.jvm.JvmMockKAgentFactory.init(JvmMockKAgentFactory.kt:34)
	at io.mockk.impl.JvmMockKGateway.<init>(JvmMockKGateway.kt:46)
	at io.mockk.impl.JvmMockKGateway.<clinit>(JvmMockKGateway.kt:172)
	... 26 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.bytebuddy.agent.Attacher.install(Attacher.java:106)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:608)
	... 33 more
Caused by: com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file: target process not responding or HotSpot VM not loaded
	at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:106)
	at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:63)
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
	... 39 more

```

##### Gradle script
```groovy
dependencies {
    testImplementation "io.mockk:mockk:1.10.0"
}
```
##### Kotlin code
```kotlin
package me.abdelraoufsabri

import io.mockk.mockk
import me.abdelraoufsabri.CustomThread
import org.junit.Test

class ClassTest {
    private val thread: CustomThread = mockk()

    @Test
    fun `dummy test`() {

    }
}
```

**Comment by leonzhuhi** [comment]
i got the same problem.
try to add  java VM option with -XX:+StartAttachListener.
 see https://stackoverflow.com/questions/25438983/com-sun-tools-attach-attachnotsupportedexception-unable-to-open-socket-file-ta/25439003

**Comment by dlitvak98** [comment]
I'm getting similar error messages and I'm pretty sure it's because I'm trying to mock a class that has no constructors. I'm still trying to figure out a solution

**Comment by Raibaz** [comment]
@AbdElraoufSabri can you please share your CustomThread class as well? Just to be sure if you're hitting @dlitvak98's case of a class that has no constructors

**Comment by AbdElraoufSabri** [comment]
Thanks, @Raibaz, I went through the project again, and there were no problems. I think it's a false positive.
