### ISSUE TITLE
Concurrent test fail, pass indpendently

### ISSUE THREAD

**Issue by Dig-Doug** [mockk/mockk#487]
### Prerequisites

I found [an existing issue](https://github.com/mockk/mockk/issues/239) though it looked fixed... I setting the tmp dir, but that didn't work.

### Expected Behavior

I am building and running this code using Bazel. I'm seeing a weird error where 2 tests can run independently and pass, but when run concurrently they fail.

### Current Behavior

2+ tests running at the same time fail. If you run them separately, they pass.

### Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

#### Steps to Reproduce

I've created a simple reproduction [here](https://github.com/Dig-Doug/mockk_bug).

Run concurrently, fails:

```bash
bazel test --cache_test_results=no //...:all
```

Run independently, passes:

```bash
bazel test --cache_test_results=no //:test1
bazel test --cache_test_results=no //:test2
```

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.10.0
* OS: Ubuntu 20.04
* Kotlin version: 1.3
* JDK version:
* JUnit version:
* Type of test: unit test

#### Stack trace

```bash
INFO: Invocation ID: ae57ae8b-3d3d-4a63-804d-304ec77de1be
INFO: Analyzed 3 targets (0 packages loaded, 0 targets configured).
INFO: Found 1 target and 2 test targets...
FAIL: //:test1 (see /home/doug/.cache/bazel/_bazel_doug/e6b12c7162b63214378ba1140a7cc7df/execroot/mockkbug/bazel-out/k8-fastbuild/testlogs/test1/test.log)
INFO: From Testing //:test1:
==================== Test output for //:test1:
JUnit4 Test Runner
.E
Time: 0.222
There was 1 failure:
1) runTest(src.Test)
java.lang.NoClassDefFoundError: io/mockk/proxy/jvm/dispatcher/JvmMockKDispatcher
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader$4.run(BuiltinClassLoader.java:711)
	at java.base/jdk.internal.loader.BuiltinClassLoader$4.run(BuiltinClassLoader.java:706)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:719)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader$4.run(BuiltinClassLoader.java:711)
	at java.base/jdk.internal.loader.BuiltinClassLoader$4.run(BuiltinClassLoader.java:706)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:719)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at io.mockk.proxy.jvm.transformation.SubclassInstrumentation$AdviceBuilder.build(SubclassInstrumentation.kt:32)
	at io.mockk.proxy.jvm.transformation.SubclassInstrumentation.<init>(SubclassInstrumentation.kt:37)
	at io.mockk.proxy.jvm.JvmMockKAgentFactory$init$Initializer.init(JvmMockKAgentFactory.kt:95)
	at io.mockk.proxy.jvm.JvmMockKAgentFactory.init(JvmMockKAgentFactory.kt:130)
	at io.mockk.impl.JvmMockKGateway.<init>(JvmMockKGateway.kt:46)
	at io.mockk.impl.JvmMockKGateway.<clinit>(JvmMockKGateway.kt:172)
	at src.Test.<init>(Test.kt:27)
	... 24 trimmed
Caused by: java.lang.ClassNotFoundException: io.mockk.proxy.jvm.dispatcher.JvmMockKDispatcher
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 56 more

FAILURES!!!
Tests run: 1,  Failures: 1


BazelTestRunner exiting with a return value of 1
JVM shutdown hooks (if any) will run now.
The JVM will exit once they complete.

-- JVM shutdown starting at 2020-09-07 16:48:52 --

================================================================================
INFO: Elapsed time: 0.838s, Critical Path: 0.76s
INFO: 2 processes: 2 linux-sandbox.
INFO: Build completed, 1 test FAILED, 3 total actions
//:test2                                                                 PASSED in 0.7s
//:test1                                                                 FAILED in 0.5s
  /home/doug/.cache/bazel/_bazel_doug/e6b12c7162b63214378ba1140a7cc7df/execroot/mockkbug/bazel-out/k8-fastbuild/testlogs/test1/test.log

INFO: Build completed, 1 test FAILED, 3 total actions
```

**Comment by raniejade** [comment]
I'm seeing something similar in Spek `2.0.13`. Tests are executed using coroutines, but by default it uses a Dispatcher that is backed by a single thread (runBlocking).

If I run the tests individually they pass however when I execute them in parallel they fail.

```kotlin
class StringProvider {
    suspend fun world() = "world"
}

class Example(
    private val stringProvider: StringProvider
) {

    suspend fun hello(): String {
        delay(250)
        return stringProvider.world()
    }
}

object ExampleTest : Spek(
    {
        val stringProvider by memoized {
            mockk<StringProvider> {
                coEvery { world() } returns "world 2"
            }
        }
        val example by memoized {
            Example(stringProvider)
        }

        describe("ExampleTest") {

            it("should work ;)") {
                runBlocking {
                    println(example.hello())
                }

                coVerify {
                    stringProvider.world()
                }
            }
        }
    }
)

object ExampleTest2 : Spek(
    {
        val stringProvider by memoized {
            mockk<StringProvider> {
                coEvery { world() } returns "world 2"
            }
        }
        val example by memoized {
            Example(stringProvider)
        }

        describe("ExampleTest") {

            it("should work ;)") {
                runBlocking {
                    println(example.hello())

                    coVerify {
                        stringProvider.world()
                    }
                }
            }
        }
    }
)
```

The tests are run using a single threaded dispatcher, but at any point execution can be suspended and yield to another coroutine.
