### ISSUE TITLE
`@JvmField` annotation causing `io.mockk.MockKException: Missing calls inside every { ... } block`

### ISSUE THREAD

**Issue by ExpensiveBelly** [mockk/mockk#488]
### Expected Behavior

No exception being thrown

### Current Behavior

MockKException is being thrown

#### Steps to Reproduce

1. Add a `@JvmField` annotated property to a class you want to mock.
2. Use `every { ... }` to set the return of the property.
3. Run the test

#### Context

* MockK version: 1.10.0
* OS: Mac
* Kotlin version: 1.4.0
* JDK version: 1.8
* JUnit version: 1.4
* Type of test: unit test

#### Stack trace

```
Missing calls inside every { ... } block.
io.mockk.MockKException: Missing calls inside every { ... } block.
	at io.mockk.impl.recording.states.StubbingState.checkMissingCalls(StubbingState.kt:14)
	at io.mockk.impl.recording.states.StubbingState.recordingDone(StubbingState.kt:8)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:60)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalEvery(API.kt:92)
	at io.mockk.MockKKt.every(MockK.kt:98)
	at mockkissue.MockkJvmFieldIssue.jvmfield throws mock exception(MockkJvmFieldIssue.kt:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:745)
```

#### Minimal reproducible code (the gist of this issue)

```
dependencies {
   testImplementation "io.mockk:mockk:1.10.0"
}
```
```
import io.mockk.every
import io.mockk.mockk
import org.junit.Test

class MockkJvmFieldIssue {

    private class JvmFieldClass(@JvmField val success: Boolean)

    @Test
    fun `jvmfield throws mock exception`() {
        mockk<JvmFieldClass>() {
            every { success } returns true
        }
    }
}
```

**Comment by Raibaz** [comment]
This looks like a bug indeed, stalebot please unstale it.

**Comment by barnhill** [comment]
Still got this issue as well.  Anyone figured out a workaround at least?

**Comment by RyeBread87** [comment]
I've used the workaround of making an extention function to return the property value, and then mocking that function's return value. It's a pain & won't work if you can't update the property reads you're testing to use the extension function instead. Worked in our case, but it's not ideal to make changes like this just for testing. Interested in a fix or better solution.

**Comment by vrumvrumich** [comment]
Face this issue as well. Would be very grateful to get fix :)

**Comment by rooton** [comment]
Annoying issue, just face this

**Comment by Yuri999** [comment]
> Still got this issue as well. Anyone figured out a workaround at least? Version: 1.13.2

I'm using `ReflectionTestUtils.setField(..)` for that.

**Comment by trenthudy** [comment]
I just got stuck with this as well.

**Comment by TregubArtem** [comment]
@trenthudy just in case you don't need to test the behavior of `ApolloResponse` itself, have you tried just calling `ApolloResponse.Builder`?
E.g.:
```kotlin
private fun setUpApolloResponse(data: Data = mockk(relaxed = true)) {
    apolloResponse = ApolloResponse.Builder(
        operation = mockk(relaxed = true),
        requestUuid = mockk(relaxed = true),
        data = data
    ).build()
}
```

**Comment by prawnpie** [comment]
I'm running into this issue with mockk version 1.13.17
