### ISSUE TITLE
`verify` affected by other case in same `@TestFactory`

### ISSUE THREAD

**Issue by youzipi** [mockk/mockk#491]
The verify assert is affected by other case in same `@TestFactory`.

I debugged and found the `callRecord`,
how can i clear this record in testFactory case?

# Expected Behavior

cases in  `first passed, second fail` all passed.

### Current Behavior

cases in  `first passed, second fail`.
the second case failed and throw Error: 
```
java.lang.AssertionError: Verification failed: call 1 of 1: Tested(#1).f2(any())) should not be called
```

### Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

#### Steps to Reproduce

run the test

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.10.0
* OS: OSX 10.13.6
* Kotlin version: 1.4.10
* JDK version: 1.8
* JUnit version: 5.7.0
* Type of test: unit test

#### Failure Logs

```
f1 calledf2 called11:05:41.549 [main] DEBUG io.mockk.impl.recording.states.AnsweringState - Answering null on Tested(#1).f2(1)
11:05:41.550 [main] DEBUG io.mockk.impl.recording.states.AnsweringState - Answering null on Tested(#1).f1(1)

f1 called11:05:41.664 [main] DEBUG io.mockk.impl.recording.states.AnsweringState - Answering null on Tested(#1).f1(0)


java.lang.AssertionError: Verification failed: call 1 of 1: Tested(#1).f2(any())) should not be called

Calls:
1) Tested(#1).f2(1)


Stack traces:
1)                                                                           io.mockk.impl.InternalPlatform.captureStackTrace           (InternalPlatform.kt:121)                          
                                                                               io.mockk.impl.stub.MockKStub.handleInvocation            (MockKStub.kt:247)                                 
                                             io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation                  (JvmMockFactoryHelper.kt:25)                       
                                                                      io.mockk.proxy.jvm.advice.Interceptor.call                        (Interceptor.kt:20)                                
                                                                                        test.factory.Tested.f2                          (Tested.kt:17)                                     
                                                                                        test.factory.Tested.f1                          (Tested.kt:11)                                     
                                                                       sun.reflect.NativeMethodAccessorImpl.invoke0                     (NativeMethodAccessorImpl.java:-2)N                
                                                                       sun.reflect.NativeMethodAccessorImpl.invoke                      (NativeMethodAccessorImpl.java:62)                 
                                                                   sun.reflect.DelegatingMethodAccessorImpl.invoke                      (DelegatingMethodAccessorImpl.java:43)             
                                                                                   java.lang.reflect.Method.invoke                      (Method.java:498)                                  
                                                                       io.mockk.proxy.jvm.advice.MethodCall.call                        (MethodCall.kt:14)                                 
                                                       io.mockk.proxy.jvm.advice.SelfCallEliminatorCallable.call                        (SelfCallEliminatorCallable.kt:14)                 
                                                           io.mockk.impl.instantiation.JvmMockFactoryHelper.handleOriginalCall          (JvmMockFactoryHelper.kt:83)                       
                                                           io.mockk.impl.instantiation.JvmMockFactoryHelper.access$handleOriginalCall   (JvmMockFactoryHelper.kt:20)                       
   io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1$invocation$$inlined$stdFunctions$lambda$1.invoke                      (JvmMockFactoryHelper.kt:28)                       
                                       io.mockk.impl.stub.MockKStub$handleInvocation$originalPlusToString$1.invoke                      (MockKStub.kt:227)                                 
                                                                                io.mockk.impl.stub.SpyKStub.defaultAnswer               (SpyKStub.kt:15)                                   
                                                                               io.mockk.impl.stub.MockKStub.answer                      (MockKStub.kt:42)                                  
                                                              io.mockk.impl.recording.states.AnsweringState.call                        (AnsweringState.kt:16)                             
                                                                 io.mockk.impl.recording.CommonCallRecorder.call                        (CommonCallRecorder.kt:53)                         
                                                                               io.mockk.impl.stub.MockKStub.handleInvocation            (MockKStub.kt:263)                                 
                                             io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation                  (JvmMockFactoryHelper.kt:25)                       
                                                                      io.mockk.proxy.jvm.advice.Interceptor.call                        (Interceptor.kt:20)                                
                                                                                        test.factory.Tested.f1                          (Tested.kt:13)                                     
                                                                  test.factory.TestFactoryTest$inner test$1.execute                     (TestFactoryTest.kt:54)                            
                                              org.junit.jupiter.engine.descriptor.DynamicTestTestDescriptor.lambda$execute$0            (DynamicTestTestDescriptor.java:52)                
                         org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed                     (InvocationInterceptorChain.java:131)              
                                                      org.junit.jupiter.api.extension.InvocationInterceptor.interceptDynamicTest        (InvocationInterceptor.java:161)                   
                                              org.junit.jupiter.engine.descriptor.DynamicTestTestDescriptor.lambda$execute$1            (DynamicTestTestDescriptor.java:58)                
                              org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptorCall.lambda$ofVoid$0             (InvocationInterceptorChain.java:78)               
                        org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed                     (InvocationInterceptorChain.java:106)              
                                              org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed                     (InvocationInterceptorChain.java:64)               
                                              org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke              (InvocationInterceptorChain.java:45)               
                                              org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke                      (InvocationInterceptorChain.java:37)               
                                              org.junit.jupiter.engine.descriptor.DynamicTestTestDescriptor.execute                     (DynamicTestTestDescriptor.java:57)                
                                              org.junit.jupiter.engine.descriptor.DynamicTestTestDescriptor.execute                     (DynamicTestTestDescriptor.java:31)                
                                                org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5 (NodeTestTask.java:139)                            
                                          org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute                     (ThrowableCollector.java:73)                       
                                                org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7 (NodeTestTask.java:129)                            
                                                        org.junit.platform.engine.support.hierarchical.Node.around                      (Node.java:137)                                    
                                                org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8 (NodeTestTask.java:127)                            
                                          org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute                     (ThrowableCollector.java:73)                       
                                                org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively          (NodeTestTask.java:126)                            
                                                org.junit.platform.engine.support.hierarchical.NodeTestTask.execute                     (NodeTestTask.java:84)                             
                   org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit                      (SameThreadHierarchicalTestExecutorService.java:32)
                     org.junit.platform.engine.support.hierarchical.NodeTestTask$DefaultDynamicTestExecutor.execute                     (NodeTestTask.java:212)                            
                     org.junit.platform.engine.support.hierarchical.NodeTestTask$DefaultDynamicTestExecutor.execute                     (NodeTestTask.java:192)                            
                                                                                         java.util.Optional.ifPresent                   (Optional.java:159)                                
                                              org.junit.jupiter.engine.descriptor.TestFactoryTestDescriptor.lambda$invokeTestMethod$1   (TestFactoryTestDescriptor.java:106)               
                                          org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute                     (ThrowableCollector.java:73)                       
                                              org.junit.jupiter.engine.descriptor.TestFactoryTestDescriptor.invokeTestMethod            (TestFactoryTestDescriptor.java:93)                
                                               org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute                     (TestMethodTestDescriptor.java:131)                
                                               org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute                     (TestMethodTestDescriptor.java:65)                 
                                                org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5 (NodeTestTask.java:139)                            
                                          org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute                     (ThrowableCollector.java:73)                       
                                                org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7 (NodeTestTask.java:129)                            
                                                        org.junit.platform.engine.support.hierarchical.Node.around                      (Node.java:137)                                    
                                                org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8 (NodeTestTask.java:127)                            
                                          org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute                     (ThrowableCollector.java:73)                       
                                                org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively          (NodeTestTask.java:126)                            
                                                org.junit.platform.engine.support.hierarchical.NodeTestTask.execute                     (NodeTestTask.java:84)                             
                                                                                        java.util.ArrayList.forEach                     (ArrayList.java:1257)                              
                   org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll                   (SameThreadHierarchicalTestExecutorService.java:38)
                                                org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5 (NodeTestTask.java:143)                            
                                          org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute                     (ThrowableCollector.java:73)                       
                                                org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7 (NodeTestTask.java:129)                            
                                                        org.junit.platform.engine.support.hierarchical.Node.around                      (Node.java:137)                                    
                                                org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8 (NodeTestTask.java:127)                            
                                          org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute                     (ThrowableCollector.java:73)                       
                                                org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively          (NodeTestTask.java:126)                            
                                                org.junit.platform.engine.support.hierarchical.NodeTestTask.execute                     (NodeTestTask.java:84)                             
                                                                                        java.util.ArrayList.forEach                     (ArrayList.java:1257)                              
                   org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll                   (SameThreadHierarchicalTestExecutorService.java:38)
                                                org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5 (NodeTestTask.java:143)                            
                                          org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute                     (ThrowableCollector.java:73)                       
                                                org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7 (NodeTestTask.java:129)                            
                                                        org.junit.platform.engine.support.hierarchical.Node.around                      (Node.java:137)                                    
                                                org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8 (NodeTestTask.java:127)                            
                                          org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute                     (ThrowableCollector.java:73)                       
                                                org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively          (NodeTestTask.java:126)                            
                                                org.junit.platform.engine.support.hierarchical.NodeTestTask.execute                     (NodeTestTask.java:84)                             
                   org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit                      (SameThreadHierarchicalTestExecutorService.java:32)
                                    org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute                     (HierarchicalTestExecutor.java:57)                 
                                      org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute                     (HierarchicalTestEngine.java:51)                   
                                               org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute                     (EngineExecutionOrchestrator.java:108)             
                                               org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute                     (EngineExecutionOrchestrator.java:88)              
                                               org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0            (EngineExecutionOrchestrator.java:54)              
                                               org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams      (EngineExecutionOrchestrator.java:67)              
                                               org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute                     (EngineExecutionOrchestrator.java:52)              
                                                           org.junit.platform.launcher.core.DefaultLauncher.execute                     (DefaultLauncher.java:96)                          
                                                           org.junit.platform.launcher.core.DefaultLauncher.execute                     (DefaultLauncher.java:75)                          
                                                                   com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs         (JUnit5IdeaTestRunner.java:71)                     
                                                              com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs         (IdeaTestRunner.java:33)                           
                                                                         com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart      (JUnitStarter.java:220)                            
                                                                         com.intellij.rt.junit.JUnitStarter.main                        (JUnitStarter.java:53)                             

	at io.mockk.impl.recording.states.VerifyingState.failIfNotPassed(VerifyingState.kt:66)
	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:42)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:60)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalVerify(API.kt:118)
	at io.mockk.MockKKt.verify(MockK.kt:146)
	at io.mockk.MockKKt.verify$default(MockK.kt:143)
	at test.factory.TestFactoryTest$inner test$1.execute(TestFactoryTest.kt:60)
	at org.junit.jupiter.engine.descriptor.DynamicTestTestDescriptor.lambda$execute$0(DynamicTestTestDescriptor.java:52)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.api.extension.InvocationInterceptor.interceptDynamicTest(InvocationInterceptor.java:161)
	at org.junit.jupiter.engine.descriptor.DynamicTestTestDescriptor.lambda$execute$1(DynamicTestTestDescriptor.java:58)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptorCall.lambda$ofVoid$0(InvocationInterceptorChain.java:78)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.descriptor.DynamicTestTestDescriptor.execute(DynamicTestTestDescriptor.java:57)
	at org.junit.jupiter.engine.descriptor.DynamicTestTestDescriptor.execute(DynamicTestTestDescriptor.java:31)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$DefaultDynamicTestExecutor.execute(NodeTestTask.java:212)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$DefaultDynamicTestExecutor.execute(NodeTestTask.java:192)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.junit.jupiter.engine.descriptor.TestFactoryTestDescriptor.lambda$invokeTestMethod$1(TestFactoryTestDescriptor.java:106)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestFactoryTestDescriptor.invokeTestMethod(TestFactoryTestDescriptor.java:93)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
        testImplementation("org.springframework.boot:spring-boot-starter-test:2.1.6.RELEASE") {
            exclude group: "org.mockito", module: "mockito-core"
            exclude group: "junit"
            exclude group: "org.junit.vintage", module: "junit-vintage-engine"
        }
        testImplementation(platform('org.junit:junit-bom:5.7.0'))
        testImplementation('org.junit.jupiter:junit-jupiter')
        testImplementation("io.mockk:mockk:1.10.0")
```

```kotlin
class Tested {
    fun f1(a: Int) {
        print("f1 called")
        if (a == 1) {
            f2(a)
        }
    }

    fun f2(a: Int) {
        print("f2 called")
    }

}
```

```kotlin

import io.mockk.spyk
import io.mockk.verify
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.DynamicTest
import org.junit.jupiter.api.TestFactory
 
class TestFactoryTest {
    lateinit var tested: Tested

    @BeforeEach
    fun setup() {
        tested = spyk(Tested())
    }

    data class TestCase(
            val description: String,
            val a: Int,
    )


    @TestFactory
    fun `first passed, second fail`(): List<DynamicTest> {
        return listOf(
                TestCase("call f2", 1),
                TestCase("won't call f2", 0),
        ).map {
            it.`inner test`()
        }
    }

    @TestFactory
    fun `all passed`(): List<DynamicTest> {
        return listOf(
                TestCase("won't call f2", 0),
                TestCase("call f2", 1),
        ).map {
            it.`inner test`()
        }
    }

    private fun TestCase.`inner test`(): DynamicTest {
        return DynamicTest.dynamicTest(description) {
            tested.f1(a)
            if (a == 1) {
                verify {
                    tested.f2(any())
                }
            } else {
                verify(exactly = 0) {
                    tested.f2(any())
                }
            }


        }
    }
}

```

**Comment by Raibaz** [comment]
This may have been fixed by #570.

**Comment by darylcrypto** [comment]
i got this problem too

**Comment by Yg0R2** [comment]
I'm having the same issue with [1.13.16](https://github.com/mockk/mockk/releases/tag/1.13.16) version.

### Here is my simple code
```kotlin
package org.example

import io.mockk.every
import io.mockk.impl.annotations.InjectMockKs
import io.mockk.impl.annotations.MockK
import io.mockk.junit5.MockKExtension
import io.mockk.verify
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.DynamicTest
import org.junit.jupiter.api.TestFactory
import org.junit.jupiter.api.extension.ExtendWith

@ExtendWith(MockKExtension::class)
class DummyTest {

    @MockK
    private lateinit var dummyService: DummyService

    @InjectMockKs
    private lateinit var underTest: DummyController

    @TestFactory
    fun test() =
        listOf(
            "value1",
            "value2"
        ).map {
            DynamicTest.dynamicTest("$it") {
                every { dummyService.get() } returns it

                assertEquals(it, underTest.get())

                verify(exactly = 1) {
                    dummyService.get()
                }
            }
        }

}

class DummyController(
    private val dummyService: DummyService
) {

    fun get(): String =
        dummyService.get()

}

class DummyService {

    fun get(): String =
        "Hello World!"

}
```

### Error response on 2nd value
```
Verification failed: call 1 of 1: DummyService(dummyService#1).get()). 2 matching calls found, but needs exactly 1 calls
Calls:
1) DummyService(dummyService#1).get()
2) DummyService(dummyService#1).get()
```

**Comment by Yg0R2** [comment]
@better-dmitriy 
The only workaround that I found is to use `clearAllMocks()` inside the `DynamicTest`.
```
    @TestFactory
    fun test() =
        listOf(
            "value1",
            "value2"
        ).map {
            DynamicTest.dynamicTest("$it") {
                clearAllMocks()

                every { dummyService.get() } returns it

                assertEquals(it, underTest.get())

                verify(exactly = 1) {
                    dummyService.get()
                }
            }
        }
```
