### ISSUE TITLE
io.mockk.MockKException: Failed matching mocking signature for left matchers: [any()]

### ISSUE THREAD

**Issue by StasonicK** [mockk/mockk#497]
**Prerequisites**

Please answer the following questions for yourself before submitting an issue.

- [+] I am running the latest version
- [+] I checked the documentation and found no answer
- [+] I checked to make sure that this issue has not already been filed

**Explanation/Details**
I have an interface, its implementation and some additional classes. I am at first time trying to validate behavior of RxJava-like functions. Not matter objects are spyKs or mockKs - error the same on every{} methods.

**Example Class + Unit Test**
```
@ExtendWith(MockKExtension::class)
class TVRepositoryImplTest {

    @get:Rule
    val instantTaskExecutorRule: TestRule = InstantTaskExecutorRule()

    private lateinit var repository: TVRepository

    //    @MockK
    private lateinit var groupDao: GroupDao

    //    @MockK
    private lateinit var channelDao: ChannelDao

    //    @MockK
    private lateinit var programDao: ProgramDao

    //    @MockK
    private lateinit var tvApi: TVApi

    //  verify on interface
    private lateinit var tvNetworkDataSource: TVNetworkDataSource

    //    @MockK
    private lateinit var programMapper: ProgramMapper

    @Before
    fun init() {
//        MockKAnnotations.init(this, relaxUnitFun = true)
        groupDao = spyk()
        channelDao = spyk()
        programDao = spyk()
        tvApi = spyk()
        tvNetworkDataSource = TVNetworkDataSource(tvApi)
        programMapper = spyk()
        mockkObject(GroupMapper)
        repository =
            TVRepositoryImpl(groupDao, channelDao, programDao, tvNetworkDataSource, programMapper)
    }

    @After
    fun finish() {
        unmockkAll()
    }

    @Test
    @Throws(Exception::class)
    fun saveProgramsFromApiToDb() {
        //  Arrange
        val id = 1
        val count = 10
        val channelId = "1"
        val programResponses = Result.success(TestUtil.generateTestProgramResponses(1, count))
        val programEntities = TestUtil.generateTestProgramEntities(id, count, channelId)

        every { tvNetworkDataSource.getProgramsFromApi(any()) } returns Single.just(programResponses)
        every { programMapper.setChannelId(channelId) } just Runs
        every { programMapper.map(programResponses.data) } returns programEntities
        every { programDao.insertPrograms(programEntities) } returns Completable.complete()

        //  Act
        repository.saveProgramsFromApiToDb(id.toString(), channelId).blockingAwait()

        //  Assert
        verify(exactly = 1) { tvNetworkDataSource.getProgramsFromApi(id.toString()) }
        verify(exactly = 1) { programMapper.setChannelId(channelId) }
        verify(exactly = 1) { programMapper.map(programResponses.data) }
        verify(exactly = 1) { programDao.insertPrograms(programEntities) }
    }

}
```
```
class TVRepositoryImpl @Inject constructor(
    private val groupDao: GroupDao,
    private val channelDao: ChannelDao,
    private val programDao: ProgramDao,
    private val tvNetworkDataSource: TVNetworkDataSource,
    private val programMapper: ProgramMapper
) : TVRepository {
    override fun saveProgramsFromApiToDb(id: String, channelId: String): Completable {
        return tvNetworkDataSource.getProgramsFromApi(id)
            .map { it.data }
            .flatMapCompletable { list ->
                programMapper.setChannelId(channelId)
                val programEntities = programMapper.map(list)
                programDao.insertPrograms(programEntities)
            }
            .subscribeOn(Schedulers.io())
    }
}
```
```
class TVNetworkDataSource @Inject constructor(private val tvApi: TVApi) {
    fun getProgramsFromApi(id: String): Single<com.eburg_soft.televisionbroadcasting.core.datatype.Result<List<ProgramResponse>>> {
        return Single.create {
            tvApi.getProgramsFromApi(id)
                .subscribeOn(Schedulers.io())
                .subscribe({ com.eburg_soft.televisionbroadcasting.core.datatype.Result.success(it) }, {
                    com.eburg_soft.televisionbroadcasting.core.datatype.Result.error<Exception>(
                        handleNetworkExceptions(Exception(it))
                    )
                })
        }
    }
}
```
```
class ProgramMapper : BaseMapper<List<ProgramResponse>, List<ProgramEntity>> {

    private var channelId = ""

    fun setChannelId(id: String) {
        channelId = id
    }

    override fun map(type: List<ProgramResponse>?): List<ProgramEntity> {
        val programEntities = mutableListOf<ProgramEntity>()
        type?.let { list ->
            list.forEach { programResponse ->
                programEntities.add(ProgramEntity(programResponse.id, channelId, programResponse.name))
            }
        }
        return programEntities
    }
}
```
```
@Dao
interface ProgramDao {
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    fun insertPrograms(programs: List<ProgramEntity>): Completable
}
```

**Expected Behavior**
I expect to verify all inner methods while calling testing method that consumes them (see code above).

**Current Behavior**
Mocking a obj. method returns an error about leftover matchers when running inside an unit test ("test" folder)

**Context**
Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

MockK version: Tried on 1.10.0
OS: Android 5.0
Kotlin version: 1.4.10
JDK version: 8
JUnit version: 4
Type of test: Unit test

**Failure Logs**

```
io.mockk.MockKException: Failed matching mocking signature for

left matchers: [any()]

	at io.mockk.impl.recording.SignatureMatcherDetector.detect(SignatureMatcherDetector.kt:99)
	at io.mockk.impl.recording.states.RecordingState.signMatchers(RecordingState.kt:39)
	at io.mockk.impl.recording.states.RecordingState.round(RecordingState.kt:31)
	at io.mockk.impl.recording.CommonCallRecorder.round(CommonCallRecorder.kt:50)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:59)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalCoEvery(API.kt:98)
	at io.mockk.MockKKt.coEvery(MockK.kt:116)
	at com.eburg_soft.televisionbroadcasting.data.repository.TVRepositoryImplTest.saveProgramsFromApiToDb(TVRepositoryImplTest.kt:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```

**Comment by Rinat-Suleimanov** [comment]
Hi @StasonicK, I just reviewed you code and it looks like you're using `tvNetworkDataSource = TVNetworkDataSource(tvApi)` like a normal object. I believe it should be `mockk` or `spyk` instance to be able to make verifications around it.
