### ISSUE TITLE
mockk Javalin context sometimes works sometimes doesn't

### ISSUE THREAD

**Issue by acmattos** [mockk/mockk#502]
### Prerequisites
- [ X ] I am running the latest version
- [ X ] I checked the documentation and found no answer
- [ X ] I checked to make sure that this issue has not already been filed

### Expected Behavior
Javalin Context object mocked as expected every time I run the test.

### Current Behavior
Sometimes context is mocked as expected, some it's not.

### Failure Information (for bugs)
When it fails, seams that I'm testing the Context object itself instead of the mocked version

#### Steps to Reproduce

1. Unzip the sample test code
[context.zip](https://github.com/mockk/mockk/files/5323490/context.zip)
2. Open it in IntelliJ
3. Run the test
4. If everything runs just fine, tests will finish without a stack trace. If not, you will see the stack trace presented bellow.
4.1. No error scenario:
![image](https://user-images.githubusercontent.com/5035530/95019751-95be9900-063d-11eb-880d-5f66896a08ad.png)
4.2 Error scenario:
![image](https://user-images.githubusercontent.com/5035530/95019772-a969ff80-063d-11eb-9833-beaaf10357a6.png)

#### Context

* MockK version: 1.10.2
* OS: Windows 10 Home
* Kotlin version: 1.3.72
* JDK version: 14.0.1
* JUnit version: org.spekframework.spek2:spek-dsl-jvm:2.0.13, org.spekframework.spek2:spek-runner-junit5:2.0.13
* Type of test: Spek (Gerkin Style)

#### Stack trace

```
Expecting code not to raise a throwable but caught
<"java.lang.IllegalArgumentException: Parameter specified as non-null is null: method io.javalin.http.util.ContextUtil.pathParamOrThrow, parameter pathParams
at io.javalin.http.util.ContextUtil.pathParamOrThrow(ContextUtil.kt)
at io.javalin.http.Context.pathParam(Context.kt:195)
at context.ContexTest$1$1$1$2$1$1.invoke(ContextTest.kt:23)
at context.ContexTest$1$1$1$2$1$1.invoke(ContextTest.kt:12)
at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:24)
at io.mockk.impl.eval.RecordedBlockEvaluator$enhanceWithNPERethrow$1.invoke(RecordedBlockEvaluator.kt:74)
at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:36)
at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
at io.mockk.MockKDsl.internalEvery(API.kt:92)
at io.mockk.MockKKt.every(MockK.kt:98)
at context.ContexTest$1$1$1$2$1.call(ContextTest.kt:23)
at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:62)
at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:750)
at org.assertj.core.api.AssertionsForClassTypes.assertThatCode(AssertionsForClassTypes.java:721)
at org.assertj.core.api.Assertions.assertThatCode(Assertions.java:1140)
at context.ContexTest$1$1$1$2.invoke(ContextTest.kt:22)
at context.ContexTest$1$1$1$2.invoke(ContextTest.kt:12)
at org.spekframework.spek2.runtime.scope.TestScopeImpl.execute(scopes.kt:136)
at org.spekframework.spek2.runtime.Executor$execute$result$2$exception$1$job$1.invokeSuspend(Executor.kt:74)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.3.72'
    id 'application'
}

repositories {
    jcenter()
}

dependencies {
    implementation platform('org.jetbrains.kotlin:kotlin-bom')
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8'
    testImplementation 'org.jetbrains.kotlin:kotlin-test'

    implementation "io.javalin:javalin:3.10.1"
    testImplementation "org.spekframework.spek2:spek-dsl-jvm:2.0.13"
    testRuntimeOnly "org.spekframework.spek2:spek-runner-junit5:2.0.13"
    testImplementation "io.mockk:mockk:1.10.2"
    testImplementation "org.assertj:assertj-core:3.16.1"
}

application {
    mainClassName = 'context.AppKt'
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
package context

import io.javalin.http.Context
import io.mockk.every
import io.mockk.mockk
import org.assertj.core.api.AbstractThrowableAssert
import org.assertj.core.api.Assertions.assertThatCode
import org.spekframework.spek2.Spek
import org.spekframework.spek2.style.gherkin.Feature
import java.nio.charset.IllegalCharsetNameException

object ContexTest : Spek({
    Feature("${Context::class.java} mocking failures") {
        lateinit var context: Context
        lateinit var assertion: AbstractThrowableAssert<*, out Throwable>

        Scenario("Mock context throws exception for #pathParam") {
            Given("""a mockked context""") {
                context = mockk<Context>()
            }
            When("""a mockk is defined for #pathParam""") {
                assertion = assertThatCode {
                    every { context.pathParam(any()) } returns "123"
                }
            }
            Then("an exception is thrown") {
                //assertion.hasMessage("Parameter specified as non-null is null: method io.javalin.http.util.ContextUtil.pathParamOrThrow, parameter pathParams")
                assertion.doesNotThrowAnyException()
            }
        }

        Scenario("Mock context throws exception for #queryParam") {
            Given("""a mockked context""") {
                context = mockk<Context>()
            }
            When("""a mockk is defined for #queryParam""") {
                assertion = assertThatCode {
                    every { context.body() } returns "123"
                }
            }
            Then("an exception is thrown") {
                //assertion.doesNotThrowAnyException()
                assertion.hasMessage("")
            }
        }
    }
})
```

**Comment by acmattos** [comment]
This is an important issue. I think it deserves an important label

**Comment by Zemke** [comment]
Are we sure the issue is in Mockito? It could be, but I don’t know. It could be in Kotlin compiler or Byte Buddy as well. I’m continuing to copy/paste some analysis I did over at Javlin.

> The issue is, firstly, with all inline functions in Context as they cannot be mocked at all due to their inline nature. Inlining to the call-site and therefore getting called immediately.
Secondly, all methods with the same name and parameters as those inline functions. For reasons I could not figure out, they’re nondeterministically confused with one another. Using reified generics makes it possible in Kotlin to have a method with the same name and parameter in the same class. But one that makes MockK as well as Mockito confuse them. The issue could be Kotlin compiler, Java compiler, bytecode amendments by the Mocking frameworks.

>  One method returns String, the other Validator. In Mockito I saw this causing ClassCastException when Mockito mocked the wrong of the two methods/functions and it’s kind of a path to figure out that the inline function versus method with same parameter is causing this behavior.

**Comment by Davidonium** [comment]
I stumbled into this issue as well, I created an example repo to reproduce it https://github.com/Davidonium/javalin-mockk-header-bug

**Comment by yaselp** [comment]
Hello. It does not seem that this issue has been addressed. 
Any suggested workaround for mocking the request headers?

**Comment by Davidonium** [comment]
This was fixed in https://github.com/tipsy/javalin/pull/1162
