### ISSUE TITLE
How to mock code block that throws exception

### ISSUE THREAD

**Issue by firefinchdev** [mockk/mockk#526]
Consider the code:
```
object Env {
    @JvmStatic
    lateinit var logger: Logger
        private set

    fun initialize() {
        this.logger = Logger()
    }
}

val <T : Any> T.log: Logger
    get() = Env.logger

class A(
    private val depen: Depen
):  {

     fun execute(input: String) {
        ....
        log.info("Beginning Abcd")
        ...
    }
}

class TestA {
        @Test
        fun test() {
                mockkObject(Env)
                every { Env.logger } returns mockk()

                val depen: Depen = mockk()
                val a = A(depen)
                a.execute("something")
                verify {
                        ...
                }
        }
}
```

The above program crashes at line `every { LambdaEnvironment.logger } returns mockk()`

```
kotlin.UninitializedPropertyAccessException: lateinit property logger has not been initialized

	at com.abcd.xyz.Env.getLogger(Env.kt)
	at com.abcd.xyz.ExtensionsKt.getLog(Extensions.kt)
	at com.abcd.xyz.A.execute(A.kt:5)
	at com.abcd.xyz.Test.test(A.kt:9)
```

### Explanation:
`every { Env.logger } returns mockk()` makes a call to lateinit `Env.logger` and exception is thrown because it is not initialized. But I want to mock `Env.logger` so that calls to `log.info()` etc should not do anything.

**Comment by firefinchdev** [comment]
Ok, this was resolved. I had to use `mockkStatic()` instead of `mockkObject()` for static (`@JvmStatic`) variables.
