### ISSUE TITLE
IllegalStateException: No lock present for object in Micronaut test with kotest

### ISSUE THREAD

**Issue by mfickett** [mockk/mockk#527]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

I'm copying over an issue from Micronaut: https://github.com/micronaut-projects/micronaut-core/issues/3334 .

### Expected Behavior

Mockk can be used within Micronaut test using kotest, with different mock behavior per test case.

### Current Behavior

In the below example, an `ExecutionException` is thrown (stack trace below). Moving the `every` clause out of the test case makes the exception go away, but then the mock can only have one behavior per test file, which isn't very usable.

Commentary from Micronaut devs is: "Seems to be some weird issue where the kotlin mocking library is introducing coroutines into the picture which introduces a concurrency issue where the lock is not visible from the couroutine thread. Why a mocking library needs to introduce concurrency and coroutines a Kotlin expert would need to explain."

#### Steps to Reproduce

Run `MyServiceTest` in the project linked below for a repro case.

#### Context

* MockK version: 1.10.1
* Type of test: kotest unit test

#### Stack trace

```
No lock present for object: MyClient(#1)
java.lang.IllegalStateException: No lock present for object: MyClient(#1)
	at io.micronaut.runtime.context.scope.refresh.RefreshScope.getLock(RefreshScope.java:158)
	at io.micronaut.runtime.context.scope.refresh.RefreshInterceptor.intercept(RefreshInterceptor.java:46)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)
	at micronaut.issue.$MyServiceTest$MyClientMock0Definition$Intercepted.getSomeFoos(Unknown Source)
	at micronaut.issue.MyService.getFoos(MyService.kt:9)
	at micronaut.issue.MyServiceTest$1.invokeSuspend(MyServiceTest.kt:24)
	at micronaut.issue.MyServiceTest$1.invoke(MyServiceTest.kt)
	at io.kotlintest.runner.jvm.TestCaseExecutor$executeTest$supervisorJob$1$invokeSuspend$$inlined$map$lambda$1.invokeSuspend(TestCaseExecutor.kt:121)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

#### Minimal reproducible code (the gist of this issue)

https://github.com/theHacker/micronaut-issue-notlockpresent

Copying the test case from that link here:

```kt
package micronaut.issue

import io.kotlintest.specs.StringSpec
import io.micronaut.test.annotation.MicronautTest
import io.micronaut.test.annotation.MockBean
import io.micronaut.test.extensions.kotlintest.MicronautKotlinTestExtension.getMock
import io.mockk.every
import io.mockk.mockk


@MicronautTest
class MyServiceTest(
        private val myClient: MyClient,
        private val myService: MyService
) : StringSpec() {

    @MockBean(MyClient::class)
    fun myClientMock(): MyClient = mockk()

    init {
        "MyService uses the MyClient" {
            every { getMock(myClient).getSomeFoos() } returns listOf(Foo(42, "Foo"))

            assert(myService.getFoos().size == 1)
        }
    }
}
```

**Comment by ASAPHAANING** [comment]
@mfickett Did you figure this out by any chance?

**Comment by mfickett** [comment]
I ended up not mocking clients, but instead installing them in a test factory. So in my test directory with the service test, there's a sibling file with the factory class. Then I'm using testcontainers to start a SQL db, and populate test data in each test case.

SearchServiceTest.kt:

```kt
import com.....search.SearchRequest
import com.....search.SearchResponse
import com.....search.SearchServiceGrpcKt
import com.....search.OrderBy
import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain
import io.micronaut.test.extensions.kotest.annotation.MicronautTest
import javax.inject.Inject

@MicronautTest
class SearchServiceTest : StringSpec() {

    // installed in the test GrpcServiceFactory
    @Inject lateinit var searchClient: SearchServiceGrpcKt.SearchServiceCoroutineStub

    init {
        "test that a search with one match returns the correct result" {
            val query = "My Query"

            val response = searchClient.search(
                SearchRequest.newBuilder()
                    .setQuery(query)
                    .setOrderBy(OrderBy.UPLOAD_TIME_DESC)
                    .build()
            )
        ...
```

GrpcServiceFactory.kt:

```kt
import com.....collection.CollectionListServiceGrpcKt
import com.....detail.DetailServiceGrpcKt
import com.....resources.ResourcesServiceGrpcKt
import com.....search.SearchServiceGrpcKt
import io.grpc.ManagedChannel
import io.micronaut.context.annotation.Factory
import io.micronaut.grpc.annotation.GrpcChannel
import io.micronaut.grpc.server.GrpcServerChannel
import javax.inject.Singleton

/**
 * A Bean Factory for the gRPC services used in tests.
 *
 * https://docs.micronaut.io/latest/guide/index.html#factories
 *
 * When adding new gRPC services (used in tests), you must add a new factory method here!
 */
@Factory
internal class GrpcServiceFactory {
    @Singleton
    fun getSearchService(
        @GrpcChannel(GrpcServerChannel.NAME) channel: ManagedChannel
    ):  
        SearchServiceGrpcKt.SearchServiceCoroutineStub {
            return SearchServiceGrpcKt.SearchServiceCoroutineStub(channel)
        }
}
```

I did end up using mocks in another context, for an custom `ResourceController` class which uses an AWS client, like this:

```kt
import com.nhaarman.mockitokotlin2.any
import com.nhaarman.mockitokotlin2.doAnswer
import com.nhaarman.mockitokotlin2.mock
import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe
import io.micronaut.test.extensions.kotest.annotation.MicronautTest
import software.amazon.awssdk.services.s3.S3Client
import software.amazon.awssdk.services.s3.model.ListObjectsRequest
import software.amazon.awssdk.services.s3.model.ListObjectsResponse

@MicronautTest
class ResourcesControllerTest : StringSpec() {

    init {

        "test to get s3 Response with a valid id" { 
            val mockS3Client = mock<S3Client> {
                on { listObjects(any<ListObjectsRequest>()) } doAnswer {
                    // Copy the prefix from the request to the response so we can verify that the Controller is using
                    // the correct prefix for the given model version ID.
                    // The prefix isn't usually used in the response we just verify it as a way of verifying controller behavior.
                    invocation ->
                    ListObjectsResponse
                        .builder()
                        .prefix((invocation.getArgument(0) as ListObjectsRequest).prefix())
                        .build()
                }
            }
            val controller = ResourcesController(mockS3Client)

            val output = controller.fetchObjectsInS3(24164) as ListObjectsResponse

            output.prefix() shouldBe "myexpectedvalue"
        }
}
```

All the testing stuff was a big pain to figure out so I hope this helps you!

**Comment by ASAPHAANING** [comment]
I figured it out:

```
@MicronautTest
class SomeTest(
....
): FunSpec({
...
}) {
    @MockBean(DefaultHttpClient::class)
    @Replaces(SomeHttpClient::class)
    fun mockSomeHttpClient(): SomeHttpClient = mockk(relaxed = true)
}

```

**Comment by rg-mns** [comment]
> I realize this is rather old, but given the trouble it took me to track this down, I thought it was worth adding a comment:
> 
> One thing that can cause this exception is calling `getMock` for the first time inside the lambda for `every` or `coEvery` (or other setup functions). The reason is that this will trigger the bean being created and used as the key in Micronaut's hash map for the refresh locks. Since you are in mock set up mode, the `hashcode` method (at least in some cases) returns 0 instead of the correct hashcode, which can cause the map entry to be stored in the wrong bucket of the hash map.
> 
> So, instead of:
> 
> ```
>     every { getMock(bean).m() } returns "value"
> ```
> 
> You need to do:
> 
> ```
>    var mockBean = getMock(bean)
>    every { mockBean.m() } returns "value"
> ```

i still get the same issue even with this approach
