### ISSUE TITLE
java.lang.NoSuchMethodError exception with simple mockk and Android desugaring

### ISSUE THREAD

**Issue by bio007** [mockk/mockk#530]
Running `mockk 1.10.0` I'm experiencing `java.lang.NoSuchMethodError` crashes when using mockk and Android's java-8 desugaring. This only happens in release build as debug (or `debugable = true`) build is not stripping unused code from final apk.

### Expected Behavior

Tests in release configuration should not crash.

### Current Behavior

Tests run in release configuration are crashing with:
```
java.lang.NoSuchMethodError: No direct method <init>(IF)V in class Lj$/util/concurrent/ConcurrentHashMap; or its super classes (declaration of 'j$.util.concurrent.ConcurrentHashMap' appears in /data/app/.../base.apk!classes.dex)
        at com.android.dx.rop.type.Type.<clinit>(Type.java:35)
```

### Failure Information (for bugs)

Mockk is internally using some reflection or low level access to classes what subsequently calls `ConcurrentHashMap` 3 parameter constructor [(int initialCapacity, float loadFactor, int concurrencyLevel)](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html#ConcurrentHashMap-int-float-int-)

If this constructor is not used in main project directly (rarely is) and is not referenced from anywhere within the project, release build removes this constructor. This of course causes exception as **the constructor is called** after all **form dx code via mockk**.

#### Steps to Reproduce

1. step 1 - checkout https://bitbucket.org/bio007/mockk_and_desugar
2. step 2 - run `./gradlew :test:connectedReleaseAndroidTest -PtestBuildType=release`
3. observe the test crash

_note that running `-PtestBuildType=debug` will succeed_

#### Context

* MockK version: 1.10.0
* OS: macOS 10.15.7
* Kotlin version: 1.3.71, 1.4.10 (doesn't matter)
* Java version: 8
* JUnit version: 4
* Type of test: android instrumented test

#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
java.lang.NoSuchMethodError: No direct method <init>(IF)V in class Lj$/util/concurrent/ConcurrentHashMap; or its super classes (declaration of 'j$.util.concurrent.ConcurrentHashMap' appears in /data/app/.../base.apk!classes.dex)
        at com.android.dx.rop.type.Type.<clinit>(Type.java:35)
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

#### Minimal reproducible code (the gist of this issue)

https://bitbucket.org/bio007/mockk_and_desugar

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
android {

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    if (project.hasProperty("testBuildType")) {
        testBuildType project.testBuildType
    }

    compileOptions {
        coreLibraryDesugaringEnabled true

        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    coreLibraryDesugaring "com.android.tools:desugar_jdk_libs:1.1.1"

    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.3.2'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    androidTestImplementation 'io.mockk:mockk-android:1.10.0'
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
package com.example.test

import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import io.mockk.every
import io.mockk.mockk
import org.junit.Assert.assertEquals
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class ExampleInstrumentedTest {
    @Test
    fun useAppContext() {
        val mock = mockk<Car>()
        every { mock.engine } returns "3.0"

        val appContext = InstrumentationRegistry.getInstrumentation().targetContext
        assertEquals("com.example.test.test", appContext.packageName)
    }

    private class Car {
        val engine: String = "2.0"
    }
}
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by bio007** [comment]
ping...

**Comment by bio007** [comment]
ping 2...
