### ISSUE TITLE
`verify` does't work correctly on verifying that a private function call from a lambda was made

### ISSUE THREAD

**Issue by yama-6** [mockk/mockk#535]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

`verify` verifies that private function call from lambda was made.
In the code below, both test_f and test_g are expected to pass because both outputs contain 'p', or a private function p is called in both cases.

### Current Behavior

`verify` does't work correctly on verifying that a private function call from a lambda was made.
In the code below, test_f passed but test_g failed.

Reproducible code:

```kotlin
import io.mockk.spyk
import io.mockk.verify
import org.junit.Before
import org.junit.Test

class Tested {
    // function
    fun f() {
        print("f")
        p()
    }

    // lambda
    val g: () -> Unit = {
        print("g")
        p()
    }

    // private function
    private fun p() {
        print("p")
    }
}

class Testing {

    lateinit var tested: Tested

    @Before
    fun setUp() {
        tested = spyk(Tested(), recordPrivateCalls = true)
    }

    @Test
    fun test_f() {
        tested.f() // output: fp
        verify { tested["p"]() } // pass
    }

    @Test
    fun test_g() {
        tested.g() // output: gp
        verify { tested["p"]() } // fail
    }
}
```

#### Context

* MockK version: 1.10.2
* OS: macOS Catalina 10.15.7
* Kotlin version: 1.4
* JDK version: 11
* JUnit version: 4.12
* Type of test: unit test

#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
Verification failed: call 1 of 1: Tested(#2).p()) was not called.

Calls to same mock:
1) Tested(#2).getG()


Stack traces:
1)                                                           io.mockk.impl.InternalPlatform.captureStackTrace (InternalPlatform.kt:121)                  
                                                               io.mockk.impl.stub.MockKStub.handleInvocation  (MockKStub.kt:247)                         
                             io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation        (JvmMockFactoryHelper.kt:25)               
                                                      io.mockk.proxy.jvm.advice.Interceptor.call              (Interceptor.kt:20)                        
                                                                                     Tested.getG              (Testing.kt:14)                            
                                                                                    Testing.test_g            (Testing.kt:42)                            
                                              jdk.internal.reflect.NativeMethodAccessorImpl.invoke0           (NativeMethodAccessorImpl.java:-2)N        
                                              jdk.internal.reflect.NativeMethodAccessorImpl.invoke            (NativeMethodAccessorImpl.java:62)         
                                          jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke            (DelegatingMethodAccessorImpl.java:43)     
                                                                   java.lang.reflect.Method.invoke            (Method.java:566)                          
                                                  org.junit.runners.model.FrameworkMethod$1.runReflectiveCall (FrameworkMethod.java:50)                  
                                        org.junit.internal.runners.model.ReflectiveCallable.run               (ReflectiveCallable.java:12)               
                                                    org.junit.runners.model.FrameworkMethod.invokeExplosively (FrameworkMethod.java:47)                  
                                         org.junit.internal.runners.statements.InvokeMethod.evaluate          (InvokeMethod.java:17)                     
                                           org.junit.internal.runners.statements.RunBefores.evaluate          (RunBefores.java:26)                       
                                                             org.junit.runners.ParentRunner.runLeaf           (ParentRunner.java:325)                    
                                                   org.junit.runners.BlockJUnit4ClassRunner.runChild          (BlockJUnit4ClassRunner.java:78)           
                                                   org.junit.runners.BlockJUnit4ClassRunner.runChild          (BlockJUnit4ClassRunner.java:57)           
                                                           org.junit.runners.ParentRunner$3.run               (ParentRunner.java:290)                    
                                                           org.junit.runners.ParentRunner$1.schedule          (ParentRunner.java:71)                     
                                                             org.junit.runners.ParentRunner.runChildren       (ParentRunner.java:288)                    
                                                             org.junit.runners.ParentRunner.access$000        (ParentRunner.java:58)                     
                                                           org.junit.runners.ParentRunner$2.evaluate          (ParentRunner.java:268)                    
                                                             org.junit.runners.ParentRunner.run               (ParentRunner.java:363)                    
                         org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass      (JUnitTestClassExecutor.java:110)          
                         org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute           (JUnitTestClassExecutor.java:58)           
                         org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute           (JUnitTestClassExecutor.java:38)           
                org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass  (AbstractJUnitTestClassProcessor.java:62)  
                              org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass  (SuiteTestClassProcessor.java:51)          
                                              jdk.internal.reflect.NativeMethodAccessorImpl.invoke0           (NativeMethodAccessorImpl.java:-2)N        
                                              jdk.internal.reflect.NativeMethodAccessorImpl.invoke            (NativeMethodAccessorImpl.java:62)         
                                          jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke            (DelegatingMethodAccessorImpl.java:43)     
                                                                   java.lang.reflect.Method.invoke            (Method.java:566)                          
                                            org.gradle.internal.dispatch.ReflectionDispatch.dispatch          (ReflectionDispatch.java:36)               
                                            org.gradle.internal.dispatch.ReflectionDispatch.dispatch          (ReflectionDispatch.java:24)               
                                    org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch          (ContextClassLoaderDispatch.java:33)       
             org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke            (ProxyDispatchAdapter.java:94)             
                                                                      com.sun.proxy.$Proxy2.processTestClass  (-:-1)                                     
                                    org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass  (TestWorker.java:118)                      
                                              jdk.internal.reflect.NativeMethodAccessorImpl.invoke0           (NativeMethodAccessorImpl.java:-2)N        
                                              jdk.internal.reflect.NativeMethodAccessorImpl.invoke            (NativeMethodAccessorImpl.java:62)         
                                          jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke            (DelegatingMethodAccessorImpl.java:43)     
                                                                   java.lang.reflect.Method.invoke            (Method.java:566)                          
                                            org.gradle.internal.dispatch.ReflectionDispatch.dispatch          (ReflectionDispatch.java:36)               
                                            org.gradle.internal.dispatch.ReflectionDispatch.dispatch          (ReflectionDispatch.java:24)               
   org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch          (MessageHubBackedObjectConnection.java:182)
   org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch          (MessageHubBackedObjectConnection.java:164)
                                 org.gradle.internal.remote.internal.hub.MessageHub$Handler.run               (MessageHub.java:412)                      
                       org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute         (ExecutorPolicy.java:64)                   
                                       org.gradle.internal.concurrent.ManagedExecutorImpl$1.run               (ManagedExecutorImpl.java:48)              
                                                    java.util.concurrent.ThreadPoolExecutor.runWorker         (ThreadPoolExecutor.java:1128)             
                                             java.util.concurrent.ThreadPoolExecutor$Worker.run               (ThreadPoolExecutor.java:628)              
                     org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run               (ThreadFactoryImpl.java:56)                
                                                                           java.lang.Thread.run               (Thread.java:834)                          
java.lang.AssertionError: Verification failed: call 1 of 1: Tested(#2).p()) was not called.

Calls to same mock:
1) Tested(#2).getG()


Stack traces:
1)                                                           io.mockk.impl.InternalPlatform.captureStackTrace (InternalPlatform.kt:121)                  
                                                               io.mockk.impl.stub.MockKStub.handleInvocation  (MockKStub.kt:247)                         
                             io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation        (JvmMockFactoryHelper.kt:25)               
                                                      io.mockk.proxy.jvm.advice.Interceptor.call              (Interceptor.kt:20)                        
                                                                                     Tested.getG              (Testing.kt:14)                            
                                                                                    Testing.test_g            (Testing.kt:42)                            
                                              jdk.internal.reflect.NativeMethodAccessorImpl.invoke0           (NativeMethodAccessorImpl.java:-2)N        
                                              jdk.internal.reflect.NativeMethodAccessorImpl.invoke            (NativeMethodAccessorImpl.java:62)         
                                          jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke            (DelegatingMethodAccessorImpl.java:43)     
                                                                   java.lang.reflect.Method.invoke            (Method.java:566)                          
                                                  org.junit.runners.model.FrameworkMethod$1.runReflectiveCall (FrameworkMethod.java:50)                  
                                        org.junit.internal.runners.model.ReflectiveCallable.run               (ReflectiveCallable.java:12)               
                                                    org.junit.runners.model.FrameworkMethod.invokeExplosively (FrameworkMethod.java:47)                  
                                         org.junit.internal.runners.statements.InvokeMethod.evaluate          (InvokeMethod.java:17)                     
                                           org.junit.internal.runners.statements.RunBefores.evaluate          (RunBefores.java:26)                       
                                                             org.junit.runners.ParentRunner.runLeaf           (ParentRunner.java:325)                    
                                                   org.junit.runners.BlockJUnit4ClassRunner.runChild          (BlockJUnit4ClassRunner.java:78)           
                                                   org.junit.runners.BlockJUnit4ClassRunner.runChild          (BlockJUnit4ClassRunner.java:57)           
                                                           org.junit.runners.ParentRunner$3.run               (ParentRunner.java:290)                    
                                                           org.junit.runners.ParentRunner$1.schedule          (ParentRunner.java:71)                     
                                                             org.junit.runners.ParentRunner.runChildren       (ParentRunner.java:288)                    
                                                             org.junit.runners.ParentRunner.access$000        (ParentRunner.java:58)                     
                                                           org.junit.runners.ParentRunner$2.evaluate          (ParentRunner.java:268)                    
                                                             org.junit.runners.ParentRunner.run               (ParentRunner.java:363)                    
                         org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass      (JUnitTestClassExecutor.java:110)          
                         org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute           (JUnitTestClassExecutor.java:58)           
                         org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute           (JUnitTestClassExecutor.java:38)           
                org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass  (AbstractJUnitTestClassProcessor.java:62)  
                              org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass  (SuiteTestClassProcessor.java:51)          
                                              jdk.internal.reflect.NativeMethodAccessorImpl.invoke0           (NativeMethodAccessorImpl.java:-2)N        
                                              jdk.internal.reflect.NativeMethodAccessorImpl.invoke            (NativeMethodAccessorImpl.java:62)         
                                          jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke            (DelegatingMethodAccessorImpl.java:43)     
                                                                   java.lang.reflect.Method.invoke            (Method.java:566)                          
                                            org.gradle.internal.dispatch.ReflectionDispatch.dispatch          (ReflectionDispatch.java:36)               
                                            org.gradle.internal.dispatch.ReflectionDispatch.dispatch          (ReflectionDispatch.java:24)               
                                    org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch          (ContextClassLoaderDispatch.java:33)       
             org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke            (ProxyDispatchAdapter.java:94)             
                                                                      com.sun.proxy.$Proxy2.processTestClass  (-:-1)                                     
                                    org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass  (TestWorker.java:118)                      
                                              jdk.internal.reflect.NativeMethodAccessorImpl.invoke0           (NativeMethodAccessorImpl.java:-2)N        
                                              jdk.internal.reflect.NativeMethodAccessorImpl.invoke            (NativeMethodAccessorImpl.java:62)         
                                          jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke            (DelegatingMethodAccessorImpl.java:43)     
                                                                   java.lang.reflect.Method.invoke            (Method.java:566)                          
                                            org.gradle.internal.dispatch.ReflectionDispatch.dispatch          (ReflectionDispatch.java:36)               
                                            org.gradle.internal.dispatch.ReflectionDispatch.dispatch          (ReflectionDispatch.java:24)               
   org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch          (MessageHubBackedObjectConnection.java:182)
   org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch          (MessageHubBackedObjectConnection.java:164)
                                 org.gradle.internal.remote.internal.hub.MessageHub$Handler.run               (MessageHub.java:412)                      
                       org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute         (ExecutorPolicy.java:64)                   
                                       org.gradle.internal.concurrent.ManagedExecutorImpl$1.run               (ManagedExecutorImpl.java:48)              
                                                    java.util.concurrent.ThreadPoolExecutor.runWorker         (ThreadPoolExecutor.java:1128)             
                                             java.util.concurrent.ThreadPoolExecutor$Worker.run               (ThreadPoolExecutor.java:628)              
                     org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run               (ThreadFactoryImpl.java:56)                
                                                                           java.lang.Thread.run               (Thread.java:834)                          
	at io.mockk.impl.recording.states.VerifyingState.failIfNotPassed(VerifyingState.kt:66)
	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:42)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:60)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalVerify(API.kt:118)
	at io.mockk.MockKKt.verify(MockK.kt:149)
	at io.mockk.MockKKt.verify$default(MockK.kt:146)
	at Testing.test_g(Testing.kt:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:834)

Testing > test_g FAILED
    java.lang.AssertionError at Testing.kt:43
2 tests completed, 1 failed
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

#### GRADLE DEFINITIONS

```kotlin
dependencies {
    implementation 'junit:junit:4.12'
    testImplementation "io.mockk:mockk:1.10.2"
}
```

**Comment by yama-6** [comment]
As with lambda, if you use anonymous object like below, test fails.

```kotlin
import io.mockk.spyk
import io.mockk.verify
import org.junit.Before
import org.junit.Test

class TestClass {
    val i = object : I {
        override fun h() {
            print("h")
            p()
        }
    }

    // private function
    private fun p() {
        print("p")
    }
}

interface I {
    fun h()
}

class Test {

    lateinit var t: TestClass

    @Before
    fun setUp() {
        t = spyk(TestClass(), recordPrivateCalls = true)
    }

    @Test
    fun test_h() {
        t.i.h() // output: hp
        verify { t["p"]() } // fail
    }
}
```

**Comment by yama-6** [comment]
I found a solution to this problem. If you partially replace the above code with the following code, the test will pass.
However, in this case, the spyk method uses the default constructor to create the target object. If you want to pass arguments to the target object, the problem remains.
```kotlin
    fun setUp() {
        tested = spyk(recordPrivateCalls = true)
        // or
        // tested = spyk<Tested>(recordPrivateCalls = true)
    }
```

**Comment by yama-6** [comment]
I resubmitted issue #537
