### ISSUE TITLE
Bug: Mocking Lambda NullpointerException in Robolectric

### ISSUE THREAD

**Issue by Kerooker** [mockk/mockk#54]
When a class receives a lambda as a parameter, one might want to mock the received lambda, so it may be possible to verify its behaviour.

But, unfortunately, there's a NullPointerException when trying to mock a lambda:

```
 class LambdaClass(val lambda: (Int) -> Unit) {
        
        fun doStuff() {
            lambda(5)
        }
    }
    
    @Test
    fun testLambda() {
        val mockedLambda: (Int) -> Unit = mockk()
        val klass = LambdaClass(mockedLambda)
        klass.doStuff()
        
        verify { mockedLambda(5) }
    }
```

> java.lang.NullPointerException
	at io.mockk.proxy.MockKProxyInterceptor.intercept(MockKProxyInterceptor.java:16)
	at kotlin.jvm.functions.Function1$ByteBuddy$5kfph9ys$ByteBuddy$wGXaV9Md.invoke(Unknown Source)
	at my.package.Playground$LambdaClass.doStuff(Playground.kt:26)
	at my.package.Playground.testLambda(Playground.kt:34)

**Comment by oleksiyp** [comment]
I copy pasted this example and getting:
```
io.mockk.MockKException: no answer found for: Function1(#1).invoke(5)

	at io.mockk.impl.stub.MockKStub.defaultAnswer(MockKStub.kt:89)
	at io.mockk.impl.stub.MockKStub.answer(MockKStub.kt:42)
	at io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:15)
	at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:48)
	at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:191)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invoke(JvmMockFactoryHelper.kt:24)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invoke(JvmMockFactoryHelper.kt:20)
	at io.mockk.impl.instantiation.JvmMockFactoryKt$sam$MockKInvocationHandler$4dff1f07.invocation(JvmMockFactory.kt)
	at io.mockk.proxy.MockKProxyInterceptor.intercept(MockKProxyInterceptor.java:20)
	at kotlin.jvm.functions.Function1$ByteBuddy$BdupK1R3$ByteBuddy$GcvMty5H.invoke(Unknown Source)
	at io.mockk.gh.Issue54Test$LambdaClass.doStuff(Issue54Test.kt:10)
	at io.mockk.gh.Issue54Test.lambda(Issue54Test.kt:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by oleksiyp** [comment]
When I add following:
```
        every { mockedLambda(5) } just Runs
```
it is passing.

**Comment by Kerooker** [comment]
This may be an issue with Android then. The call is being made from a Robolectric Runner

**Comment by oleksiyp** [comment]
Oh, may be. This is second Roboelectric issue. First one with spies. It can be tricky

**Comment by oleksiyp** [comment]
I dont know if there is still Roboelectric issues. Please open new ticket for it. Closing because of small attention to Roboelectric in recent issues
