### ISSUE TITLE
coVerify throwing method not called when upgrading coroutines

### ISSUE THREAD

**Issue by sendoav** [mockk/mockk#589]
Upgrading coroutines from something above 1.3.9 makes some of the tests using coVerify to fail. It is strange because if I run them one by one they all pass. The problem comes when running all or some of them

### Expected Behavior

Running the following code works well when using kotlinx-corotine 1.3.9

`coVerify (timeout = 500, verifyBlock = {sellPartialBetSlipUseCase.execute(any(), any(), any(), any(), any(), any(), any(), any(), any(), any(), any(), any()) })`

Where the use case is a suspend function

### Current Behavior

After upgrading kotlinx-coroutines to 1.4.3 coVerify is throwing 
```
Verification failed: call 1 of 1: SellPartialCashoutBetSlipUseCaseContract(#20).execute(any(), any(), any(), any(), any(), any(), any(), any(), any(), any(), any(), any(), any())) was not called (timeout = 500 ms) 
```

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version:1.11.0
* Kotlin version:1.4.30
* kotlinx-coroutine: 1.4.3
* Type of test: unit test 

#### Stack trace

```
Verification failed: call 1 of 1: SellPartialCashoutBetSlipUseCaseContract(#20).execute(any(), any(), any(), any(), any(), any(), any(), any(), any(), any(), any(), any(), any())) was not called (timeout = 500 ms)
java.lang.AssertionError: Verification failed: call 1 of 1: SellPartialCashoutBetSlipUseCaseContract(#20).execute(any(), any(), any(), any(), any(), any(), any(), any(), any(), any(), any(), any(), any())) was not called (timeout = 500 ms)
	at io.mockk.impl.recording.states.VerifyingState.failIfNotPassed(VerifyingState.kt:66)
	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:42)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:64)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalCoVerify(API.kt:143)
	at io.mockk.MockKKt.coVerify(MockK.kt:175)
	at io.mockk.MockKKt.coVerify$default(MockK.kt:172)
	at ekasa.com.retabet.presentation.betslips.cashout.logic.BetSlipCashoutSellPresenterTest

```

**Comment by Raibaz** [comment]
This looks pretty nasty, thanks for sending this through.

**Comment by duberton** [comment]
Having the same issue over here with the same specs/versions as @sendoav, except for kotlin (1.5.0).

**Comment by je-ramos-acc** [comment]
bug still exists for me. this is related to this https://github.com/mockk/mockk/issues/554
