### ISSUE TITLE
Bug: Mocking kotlin objects which has variables initialization

### ISSUE THREAD

**Issue by BharathMG** [mockk/mockk#59]
Ex:

          object Real {
            var filePath = getExternalStorage("dir").path
          }

Now when trying to mock this using, `objectMockk(Real).mock()`, I get,

           java.lang.ExceptionInInitializerError,
          Caused by: java.lang.IllegalStateException: getExternalStorage("dir") must not be null

for trying to access external storage. Is there any way to mock these kind of objects?

**Comment by oleksiyp** [comment]
Thanks for reporting it. I will check. Quite weird case. Can you post more code in a gist. Ideally all code required of to run it

**Comment by BharathMG** [comment]
Nope. It is just unit test. Test code is,

   ```
class FileDownloaderTest {
    val FAKE_URL = "www.fakeUrl.com"
    val mockContext = mockk<Context>()
    val mockAndroidUtils = mockk<AndroidUtils>()
    lateinit var fileDownloader: FileDownloader

    @Before
    fun setup() {
        objectMockk(DownloadConfig).mock()
        objectMockk(RxDownload).mock()
        fileDownloader = FileDownloader(false, mockContext, mockAndroidUtils)
    }

    @Test
    fun testisDownloadInProgress_shouldReturnTrueIfExistsAndDownloading() {
        every { RxDownload.isExists(FAKE_URL) } returns Maybe.just(true)
        every { RxDownload.create(FAKE_URL) } returns Flowable.just(mockk<Downloading>())

        assertTrue { fileDownloader.isDownloadInProgress(FAKE_URL) }
    }
```

Here, it fails in when I do `objectMockk(DownloadConfig).mock()` it fails with,
```
         java.lang.ExceptionInInitializerError
	at io.app.fileDownloader.FileDownloaderTest.setup(FileDownloaderTest.kt:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)

Caused by: java.lang.IllegalStateException: getExternalStoragePublic…tory(DIRECTORY_DOWNLOADS) must not be null
	at zlc.season.rxdownload3.core.DownloadConfig.<clinit>(DownloadConfig.kt:29) 
```

**Comment by oleksiyp** [comment]
Doesn't look like a mockk bug, please reopen ticket if needed
