### ISSUE TITLE
java.lang.ClassCastException in chained calls 

### ISSUE THREAD

**Issue by kamenskyen** [mockk/mockk#592]
### Current Behavior

Got error when update from v1.10.0 to 1.10.1 and higher 

* MockK version: from 1.10.1 to 1.11.0
* OS: macOs 10.15.7 (19H524)
* Kotlin version: 1.4.10
* JDK version: 1.8.0_281
* JUnit version:4.13
* Type of test: unit test

#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.util.List
	at com.example.Golder.getStrings(IssueTest.kt:27)
	at com.example.IssueTest.test holder(IssueTest.kt:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

// -----------------------[ GRADLE DEFINITIONS ] -----------------------
Gradle version: 6.8.1

```
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
import com.google.common.truth.Truth
import io.mockk.every
import io.mockk.mockk
import org.junit.Test

class IssueTest {

    @Test
    fun `test holder`() {
        val holder = mockk<Holder>()
        // val holder = mockk<Holder>(relaxed = true) - not work
        every { holder.golder.strings.size } returns 5
        // every { holder.golder.strings.hint(Int::class).size } returns 5 - not work
        // every { holder.golder.hint(String::class).strings.hint(Int::class).size } returns 5 - not work
        val actual = holder.golder.strings.size
        Truth.assertThat(actual).isEqualTo(5)
    }
}

class Holder(
    var golder: Golder
)

class Golder(
    var strings: List<String>
)

// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by MrXlebNick** [comment]
It seems that the reason for that is that `size` is not a method that is called but rather a Java field. Field mocking is not possible in MockK as it follows from #252 , particularly [this comment](https://github.com/mockk/mockk/issues/252#issuecomment-462950373). 

What you can do though is to mock the `strings` field because it is a Kotlin variable, and all Kotlin variables are received via getter, which is a method:

Instead of
`every { holder.golder.strings.size } returns 5`

use
`every { holder.golder.strings } returns (0 until 5).map { "" }`

A little workaround-y, but the test gets passed

**Comment by ionel-sirbu-crunch** [comment]
This still replicates in `1.12.0`. Code like `every { someList.size } returns 3` used to work just fine before upgrading. & it totally makes sense to still support that when the business logic code only makes use of the `size` property, ignoring the actual contents of the list. Was there a compelling reason for dropping this functionality?

**Comment by rfn123** [comment]
this also still replicates in 1.13.2 . Will this be fixed at any point?
