### ISSUE TITLE
Mocking java.io.File constructor throws StackOverflowError

### ISSUE THREAD

**Issue by anggrayudi** [mockk/mockk#603]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

Can mock `java.io.File` constructor.

### Current Behavior

Throws `StackOverflowError`

#### Steps to Reproduce

Just run the following snippets:
```kotlin
    @Test
    fun abc() {
        mockkConstructor(File::class)
    }
```

#### Context
* MockK version: 1.11.0
* OS: MacOS Big Sur 11.2.3
* Kotlin version: 1.4.32
* JDK version: 1.8.0_262
* JUnit version: 5.7.1
* Type of test: unit test

#### Stack trace

```
Exception in thread "main" java.lang.StackOverflowError
	at sun.misc.URLClassPath.getResource(URLClassPath.java:247)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:405)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at io.mockk.impl.instantiation.JvmConstructorMockFactory$ConstructorInvocationHandler.invocation(JvmConstructorMockFactory.kt:171)
	at io.mockk.proxy.jvm.advice.BaseAdvice.constructorDone(BaseAdvice.kt:33)
	at java.io.File.<init>(File.java:376)
	at sun.misc.URLClassPath$FileLoader.getResource(URLClassPath.java:1374)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:249)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at io.mockk.impl.instantiation.JvmConstructorMockFactory$ConstructorInvocationHandler.invocation(JvmConstructorMockFactory.kt:171)
	at io.mockk.proxy.jvm.advice.BaseAdvice.constructorDone(BaseAdvice.kt:33)
``

**Comment by anggrayudi** [comment]
Stalebot, please unstale it.

**Comment by anggrayudi** [comment]
Stalebot, please unstale it.
