### ISSUE TITLE
Bug: ClassCastException with Robolectric 4.4 and higher when using generic methods

### ISSUE THREAD

**Issue by dpasek-senacor** [mockk/mockk#606]
### Expected Behavior

mockk should be able to mock methods with generic signatures in a Robolectric environment.

Example of such a signature (standard pattern often used in Java based frameworks)
Kotlin:
``` Kotlin
interface WebClient {
    fun <T> get(url: String, clazz: Class<T>) : T
}
``` 
Java:
``` Java
public interface WebClient {
    <T> T get(String url, Class<T> clazz);
}
``` 

### Current Behavior

When mocking methods using generic method signatures mockk will throw a `ClassCastException`

### Failure Information (for bugs)

Exception has todo with classloader hierarchy of Robolectric. The problematic class with the type information is loaded by two different classloaders by Robolectric.

#### Steps to Reproduce

See attached sample project using Robolectric
[RobolectricMockkIssue.zip](https://github.com/mockk/mockk/files/6366830/RobolectricMockkIssue.zip)

#### Context
mockK version: 1.11.0 (and older versions)
Robolectric version: >= 4.4
Kotlin version 1.4.x
JDK >= 8

#### Failure Logs

See attachment

#### Stack trace

```
io.mockk.MockKException: Class cast exception happened.
Probably type information was erased.
In this case use `hint` before call to specify exact return type of a method.


	at io.mockk.impl.InternalPlatform.prettifyRecordingException(InternalPlatform.kt:70)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:66)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalEvery(API.kt:92)
	at io.mockk.MockKKt.every(MockK.kt:98)
	at com.example.robolectricmockk.FooServiceTest.testMockK(FooServiceTest.kt:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:278)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: com.example.robolectricmockk.Foo cannot be cast to com.example.robolectricmockk.Foo
	at com.example.robolectricmockk.FooServiceTest$testMockK$1.invoke(FooServiceTest.kt:34)
	at com.example.robolectricmockk.FooServiceTest$testMockK$1.invoke(FooServiceTest.kt:17)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:25)
	at io.mockk.impl.eval.RecordedBlockEvaluator$enhanceWithRethrow$1.invoke(RecordedBlockEvaluator.kt:78)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:40)
	... 21 more
```

**Comment by marcosalis** [comment]
Getting the same issue with the new Android Studio 4.2 and any recent MockK version.

Tried with gradle wrapper `6.7.1` and `7.0`, no changes unfortunately. It looks like it might be related to the new Studio using Java 11 as bytecode target level.

**Comment by leggomymeggos** [comment]
Can you please re-open add an `important` label? This is still happening a year later with Robolectric `4.5.1` and a Kotlin `value` class
