### ISSUE TITLE
ArrayIndexOutOfBoundException in verifyOrder when no call was recorded

### ISSUE THREAD

**Issue by dirkbolte** [mockk/mockk#614]
The following code throws an ArrayIndexOutOfBoundsException in verifyOrder when no call was recorded.

From what I see in `io.mockk.impl.verify.LCSMatchingAlgo:52`, `allCalls` is an empty list, thus `nEdits[-1]` is called.

#### Minimal reproducible code

```kotlin
import io.mockk.mockk
import io.mockk.verifyOrder
import org.junit.jupiter.api.Test

class MockkTest {
  @Test
  fun `verifyOrder does not throw ArrayIndexOutOfBounds`() {
    val mock: Something = mockk(relaxed = true, relaxUnitFun = true)

    verifyOrder {
      mock.doSomething()
    }
  }

  open class Something {
    fun doSomething() {}
  }
}
```

#### Context: 

* MockK version: 1.10.5 (sorry, can't upgrade ATM)
* OS: MacOS 11.3
* Kotlin version: 1.4.20
* JDK version: 11
* JUnit version: 5.7.0

#### Logs and Stack trace

```
INFO: Using test instance lifecycle mode 'PER_CLASS' set via the 'junit.jupiter.testinstance.lifecycle.default' configuration parameter.
16:52:28.484 [main] DEBUG io.mockk.impl.instantiation.AbstractMockFactory - Creating mockk for Something name=#1

java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0

	at io.mockk.impl.verify.LCSMatchingAlgo.lcs(LCSMatchingAlgo.kt:52)
	at io.mockk.impl.verify.VerificationHelpers.reportCalls$default(VerificationHelpers.kt:61)
	at io.mockk.impl.verify.OrderedCallVerifier$verify$1.invoke(OrderedCallVerifier.kt:28)
	at io.mockk.impl.verify.OrderedCallVerifier$verify$1.invoke(OrderedCallVerifier.kt:12)
	at io.mockk.impl.recording.CommonCallRecorder.safeExec(CommonCallRecorder.kt:72)
	at io.mockk.impl.log.SafeToString.exec(SafeToString.kt:10)
	at io.mockk.impl.verify.OrderedCallVerifier.verify(OrderedCallVerifier.kt:26)
	at io.mockk.impl.recording.states.VerifyingState$recordingDone$outcome$1.invoke(VerifyingState.kt:31)
	at io.mockk.impl.recording.states.VerifyingState$recordingDone$outcome$1.invoke(VerifyingState.kt:11)
	at io.mockk.impl.recording.CommonCallRecorder.safeExec(CommonCallRecorder.kt:72)
	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:30)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:60)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalVerify(API.kt:118)
	at io.mockk.MockKDsl.internalVerify$default(API.kt:109)
	at io.mockk.MockKDsl.internalVerifyOrder(API.kt:182)
	at io.mockk.MockKKt.verifyOrder(MockK.kt:218)
	at io.mockk.MockKKt.verifyOrder$default(MockK.kt:215)
        at MockkTest.verifyOrder does not throw ArrayIndexOutOfBounds(MockkTest.kt:12)
```

**Comment by Raibaz** [comment]
Yep, this is indeed a bug and it should not be too hard to fix: we should check if `allCalls` is empty in `LCSMatchingAlgo` and, if so, return a proper error message saying that the test fails because no functions were mocked and users should either specify their desired behavior with `every` or use a `spyk`.
