### ISSUE TITLE
Cannot mock `NavHostController` for JetPack Compose tests

### ISSUE THREAD

**Issue by Michael-MF** [mockk/mockk#624]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

I should be able to mock `NavHostController`

### Current Behavior

Providing a relaxed mock of `NavHostController` to a composable results in the following exception:
```
androidx.navigation.Navigator_1_Proxy cannot be cast to androidx.navigation.compose.ComposeNavigator
```

#### Steps to Reproduce

1. Add the gradle definitions provided in the example
2. Add the example compose widget
3. Add the example test
4. Run the example test

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: `1.11.0`
* OS: macOS Catalina, 10.15.7
* Kotlin version: `1.4.32`
* JDK version: `11`
* JUnit version: `4`
* Type of test: Android Instrumented Test

#### Stack trace

<details>
    <summary>Stack trace</summary>

```
java.lang.ClassCastException: androidx.navigation.Navigator_1_Proxy cannot be cast to androidx.navigation.compose.ComposeNavigator
	at androidx.navigation.compose.NavGraphBuilderKt.composable(NavGraphBuilder.kt:76)
	at androidx.navigation.compose.NavGraphBuilderKt.composable$default(NavGraphBuilder.kt:35)
	at com.matchesfashion.shoppingbag.feature.ui.ExampleComposableKt$ExampleComposable$1$1.invoke(ExampleComposable.kt:16)
	at com.matchesfashion.shoppingbag.feature.ui.ExampleComposableKt$ExampleComposable$1$1.invoke(ExampleComposable.kt:16)
	at androidx.navigation.compose.NavHostControllerKt.createGraph(NavHostController.kt:162)
	at androidx.navigation.compose.NavHostKt.NavHost(NavHost.kt:67)
	at com.matchesfashion.shoppingbag.feature.ui.ExampleComposableKt.ExampleComposable(ExampleComposable.kt:16)
	at com.matchesfashion.shoppingbag.feature.ui.ExampleTest$test$1.invoke(ExampleTest.kt:22)
	at com.matchesfashion.shoppingbag.feature.ui.ExampleTest$test$1.invoke(ExampleTest.kt:21)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.ui.platform.ComposeView.Content(ComposeView.android.kt:346)
	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:202)
	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:201)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:193)
	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:148)
	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:114)
	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:113)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:193)
	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:106)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:162)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:161)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:193)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:161)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:144)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.ComposerKt.invokeComposable(Composer.kt:3233)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:2513)
	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:2477)
	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:453)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:702)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:409)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:144)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:135)
	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:687)
	at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:135)
	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:187)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:196)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:142)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:135)
	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:751)
	at android.view.View.dispatchAttachedToWindow(View.java:20479)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3489)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5278)
	at android.view.ViewGroup.addView(ViewGroup.java:5064)
	at android.view.ViewGroup.addView(ViewGroup.java:5036)
	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:486)
	at android.app.Activity.setContentView(Activity.java:3504)
	at androidx.activity.ComponentActivity.setContentView(ComponentActivity.java:394)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule_androidKt.setContent(AndroidComposeTestRule.android.kt:504)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$setContent$2.invoke(AndroidComposeTestRule.android.kt:257)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$setContent$2.invoke(AndroidComposeTestRule.android.kt:256)
	at androidx.compose.ui.test.junit4.AndroidSynchronization_androidKt$sam$java_util_concurrent_Callable$0.call(Unknown Source:2)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.app.Instrumentation$SyncRunnable.run(Instrumentation.java:2223)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

</details>

#### Minimal reproducible code (the gist of this issue)

**Gradle definitions**
```groovy
dependencies {
    implementation "androidx.compose.ui:ui:1.0.0-beta06"
    implementation "androidx.compose.foundation:foundation:1.0.0-beta06"
    implementation "androidx.compose.material:material:1.0.0-beta06"
    implementation 'androidx.activity:activity-compose:1.3.0-alpha07'
    implementation "androidx.navigation:navigation-compose:1.0.0-alpha10"

    androidTestImplementation "io.mockk:mockk-android:1.11.0"
    androidTestImplementation "androidx.compose.ui:ui-test-junit4:1.0.0-beta06"
    debugImplementation "androidx.compose.ui:ui-test-manifest:1.0.0-beta06"
}
```

**Example composable**
```kotlin
import androidx.compose.foundation.layout.Column
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.navigation.NavHostController
import androidx.navigation.compose.NavHost
import androidx.navigation.compose.composable
import androidx.navigation.compose.rememberNavController

@Composable
fun ExampleComposable(
    navController: NavHostController = rememberNavController(),
) {
    Column {
        NavHost(navController, startDestination = "route") { composable("route") { Text("Hi") } }
    }
}
```

**Example test**
```kotlin
import androidx.compose.ui.test.junit4.createComposeRule
import androidx.compose.ui.test.onNodeWithText
import androidx.navigation.NavHostController
import androidx.test.ext.junit.runners.AndroidJUnit4
import io.mockk.mockk
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class ExampleTest {
    @get:Rule
    val composeTestRule = createComposeRule()

    private val mockNavController: NavHostController = mockk(relaxed = true)

    @Test
    fun test() {
        composeTestRule.setContent {
            ExampleComposable(mockNavController)
        }
        composeTestRule.onNodeWithText("Hi").assertExists()
    }
}
```

**Comment by ggeetha** [comment]
Encountered into the same problem. Here is the description:

**Expected Behavior**
I should be able to mock NavHostController

**Current Behavior**
Providing a relaxed mock of NavHostController to composable results in the following exception:

androidx.navigation.Navigator_1_Proxy cannot be cast to androidx.navigation.compose.ComposeNavigator

**Steps to Reproduce**
Add the gradle definitions provided in the example
Add the example compose widget
Add the example test
Run the example test
Context
Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

MockK version: 1.12.2
OS: Windows 10
Kotlin version: 1.6.0
JDK version: 11
JUnit version: 4
Type of test: Android Instrumented Test
Stack trace
Stack trace
Minimal reproducible code (the gist of this issue)
Gradle definitions

dependencies {
    implementation "androidx.compose.ui:ui:1.1.0-rc01"
    implementation "androidx.compose.foundation:foundation:1.1.0-rc01"
    implementation "androidx.compose.material:material:1.1.0-rc01"
    implementation 'androidx.activity:activity-compose:1.3.0-alpha07'
    implementation "androidx.navigation:navigation-compose:1.0.0-alpha10"

    androidTestImplementation "io.mockk:mockk-android:1.12.2"
    androidTestImplementation "androidx.compose.ui:ui-test-junit4:1.1.0-rc01"
    debugImplementation "androidx.compose.ui:ui-test-manifest:1.1.0-rc01"
}
Example composable

import androidx.compose.foundation.layout.Column
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.navigation.NavHostController
import androidx.navigation.compose.NavHost
import androidx.navigation.compose.composable
import androidx.navigation.compose.rememberNavController

@Composable
fun ExampleComposable(
    navController: NavHostController = rememberNavController(),
) {
    Column {
        NavHost(navController, startDestination = "route") { composable("route") { Text("Hi") } }
    }
}
Example test

import androidx.compose.ui.test.junit4.createComposeRule
import androidx.compose.ui.test.onNodeWithText
import androidx.navigation.NavHostController
import androidx.test.ext.junit.runners.AndroidJUnit4
import io.mockk.mockk
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class ExampleTest {
    @get:Rule
    val composeTestRule = createComposeRule()

    private val mockNavController: NavHostController = mockk(relaxed = true)

    @Test
    fun test() {
        composeTestRule.setContent {
            ExampleComposable(mockNavController)
        }
        composeTestRule.onNodeWithText("Hi").assertExists()
    }
}
