### ISSUE TITLE
Concurrent test fail, pass indpendently

### ISSUE THREAD

**Issue by Kernald** [mockk/mockk#627]
Copy-pasting from #487 that has been closed for inactivity, but is still an issue as of today:

> ### Prerequisites
> I found [an existing issue](https://github.com/mockk/mockk/issues/239) though it looked fixed... I setting the tmp dir, but that didn't work.
> 
> ### Expected Behavior
> I am building and running this code using Bazel. I'm seeing a weird error where 2 tests can run independently and pass, but when run concurrently they fail.
> 
> ### Current Behavior
> 2+ tests running at the same time fail. If you run them separately, they pass.
> 
> ### Failure Information (for bugs)
> Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.
> 
> #### Steps to Reproduce
> I've created a simple reproduction [here](https://github.com/Dig-Doug/mockk_bug).
> 
> Run concurrently, fails:
> 
> ```shell
> bazel test --cache_test_results=no //...:all
> ```
> 
> Run independently, passes:
> 
> ```shell
> bazel test --cache_test_results=no //:test1
> bazel test --cache_test_results=no //:test2
> ```
> 
> #### Context
> Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.
> 
> * MockK version: 1.10.0
> * OS: Ubuntu 20.04
> * Kotlin version: 1.3
> * JDK version:
> * JUnit version:
> * Type of test: unit test
> 
> #### Stack trace
> ```shell
> INFO: Invocation ID: ae57ae8b-3d3d-4a63-804d-304ec77de1be
> INFO: Analyzed 3 targets (0 packages loaded, 0 targets configured).
> INFO: Found 1 target and 2 test targets...
> FAIL: //:test1 (see /home/doug/.cache/bazel/_bazel_doug/e6b12c7162b63214378ba1140a7cc7df/execroot/mockkbug/bazel-out/k8-fastbuild/testlogs/test1/test.log)
> INFO: From Testing //:test1:
> ==================== Test output for //:test1:
> JUnit4 Test Runner
> .E
> Time: 0.222
> There was 1 failure:
> 1) runTest(src.Test)
> java.lang.NoClassDefFoundError: io/mockk/proxy/jvm/dispatcher/JvmMockKDispatcher
> 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
> 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader$4.run(BuiltinClassLoader.java:711)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader$4.run(BuiltinClassLoader.java:706)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:719)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
> 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
> 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader$4.run(BuiltinClassLoader.java:711)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader$4.run(BuiltinClassLoader.java:706)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:719)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
> 	at io.mockk.proxy.jvm.transformation.SubclassInstrumentation$AdviceBuilder.build(SubclassInstrumentation.kt:32)
> 	at io.mockk.proxy.jvm.transformation.SubclassInstrumentation.<init>(SubclassInstrumentation.kt:37)
> 	at io.mockk.proxy.jvm.JvmMockKAgentFactory$init$Initializer.init(JvmMockKAgentFactory.kt:95)
> 	at io.mockk.proxy.jvm.JvmMockKAgentFactory.init(JvmMockKAgentFactory.kt:130)
> 	at io.mockk.impl.JvmMockKGateway.<init>(JvmMockKGateway.kt:46)
> 	at io.mockk.impl.JvmMockKGateway.<clinit>(JvmMockKGateway.kt:172)
> 	at src.Test.<init>(Test.kt:27)
> 	... 24 trimmed
> Caused by: java.lang.ClassNotFoundException: io.mockk.proxy.jvm.dispatcher.JvmMockKDispatcher
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
> 	... 56 more
> 
> FAILURES!!!
> Tests run: 1,  Failures: 1
> 
> 
> BazelTestRunner exiting with a return value of 1
> JVM shutdown hooks (if any) will run now.
> The JVM will exit once they complete.
> 
> -- JVM shutdown starting at 2020-09-07 16:48:52 --
> 
> ================================================================================
> INFO: Elapsed time: 0.838s, Critical Path: 0.76s
> INFO: 2 processes: 2 linux-sandbox.
> INFO: Build completed, 1 test FAILED, 3 total actions
> //:test2                                                                 PASSED in 0.7s
> //:test1                                                                 FAILED in 0.5s
>   /home/doug/.cache/bazel/_bazel_doug/e6b12c7162b63214378ba1140a7cc7df/execroot/mockkbug/bazel-out/k8-fastbuild/testlogs/test1/test.log
> 
> INFO: Build completed, 1 test FAILED, 3 total actions
> ```

**Comment by gi-wg2** [comment]
I am struggling with the exact same issue...

It seems for me like setting `local = True` in the `java_tests` removes the problem, so it seems to be triggered by  
Bazel's sandboxing. I haven't been able to figure out exactly what the issue is...

Have you had any progress?

**Comment by Kernald** [comment]
I didn't have much time to investigate. I only have two tests showing the issue at the moment so marked them as flaky (which allows Bazel to retry them up to three times, and has been enough for me).

**Comment by Kernald** [comment]
This is still an issue and shouldn't be closed. @oleksiyp @Raibaz any of you could set the proper labels please?

**Comment by fmeum** [comment]
The issue arises because `ByteBuddyAgent.install()` returns `null` in all but one of the concurrent test runs: https://github.com/raphw/byte-buddy/issues/1111

**Comment by fmeum** [comment]
This is likely caused by https://github.com/bazelbuild/bazel/issues/3236, with the preferred workaround being https://github.com/bazelbuild/bazel/issues/3236#issuecomment-587752609.

**Comment by AlexandreBrown** [comment]
Still an issue, I'm using Kotest to run my tests concurrently and getting failing tests only when running multiple test classes concurrently.  

The failing tests are always in the same test class, the tests in the tests class only contain `coVerify` (maybe 'coVerify` is not safe for concurrent execution?).  
 
The tests fail when setting parallelism > 1 but always pass with parallelism = 1.
I made sure it's not a matter of state, every objects used for each tests are being created in their test body and the code that is being tested is very simple, it's a function with 1 line of code where the class under teset calls a dependency that is mocked under test (simpleset mock call possible).  
```kotlin
class MyClass(private val myDependency: Dependency) {
    
    fun execute() {
        myDependency.execute()  
    }
}
````
Tested on latest version of Mockk (1.12.4) and Kotest (5.3.0)

**Comment by picaso** [comment]
Yea given all the issues, we are disabling mockk across our org going fwd. It is a shame
