### ISSUE TITLE
Missing calls inside verify { ... } block using spyK on Android API 21 but test passing on API 30

### ISSUE THREAD

**Issue by christophehenry** [mockk/mockk#637]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

The test should pass on both API 21 and API 30.

### Current Behavior

Getting `io.mockk.MockKException: Missing calls inside verify { ... } block` on API 21

### Failure Information (for bugs)

A project demonstring the bug with a minimal code is avaiblable [here](https://github.com/christophehenry/MockkMrb)

#### Steps to Reproduce

1. Clone the provided repo
2. Launch Android studio
3. Lauch instrumented tests on API 21 to reproduce

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.11.0
* OS: Linux Fedora 33
* Kotlin version: reproduces on 1.4.32 and 1.5.20-M1
* JDK version: reproduces on 1.8 and 11
* JUnit version: 4.13.2
* Type of test: android instrumented test

#### Failure Logs

Please include any relevant log snippets or files here.

#### Stack trace

```
io.mockk.MockKException: Missing calls inside verify { ... } block.
at io.mockk.impl.recording.states.VerifyingState.checkMissingCalls(VerifyingState.kt:52)
at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:21)
at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:64)
at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
at io.mockk.MockKDsl.internalVerify(API.kt:118)
at io.mockk.MockKKt.verify(MockK.kt:149)
at io.mockk.MockKKt.verify$default(MockK.kt:146)
at fr.chenry.ExampleInstrumentedTest.useAppContext(ExampleInstrumentedTest.kt:22)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:154)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1837)
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    implementation("androidx.core:core-ktx:1.5.0")
    implementation("androidx.appcompat:appcompat:1.3.0")
    implementation("com.google.android.material:material:1.3.0")
    testImplementation("junit:junit:4.13.2")
    androidTestImplementation("io.mockk:mockk-android:1.11.0")
    androidTestImplementation("androidx.test.ext:junit:1.1.2")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.3.0")
}// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
package fr.chenry

// This also reproduce with a SAM interface
class FailExample(private val cb: FailExample.() -> Unit) {
    init {
        cb(this)
    }
}

//// TEST ////
package fr.chenry

import androidx.test.ext.junit.runners.AndroidJUnit4
import io.mockk.confirmVerified
import io.mockk.spyk
import io.mockk.verify
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class ExampleInstrumentedTest {
    @Test
    fun useAppContext() {
        val mock = spyk<FailExample.() -> Unit>({})
        val failExample = FailExample(mock)

        verify { mock(failExample) }
        confirmVerified(mock)
    }
}

// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by christophehenry** [comment]
Please put an `important` label.

**Comment by daugavetQM** [comment]
probably duplicate of https://github.com/mockk/mockk/issues/182

**Comment by christophehenry** [comment]
So if I understand correctly, this happens because some methods can't be mocked on Android pre-P?
Can you please put an `important` label on this so it won't be forgotten?
