### ISSUE TITLE
Race condition - can't find stub LocalDateTime(temporary mock)

### ISSUE THREAD

**Issue by hrach** [mockk/mockk#649]
### Prerequisites

We are observing weird behavior - probably some race condition - our tests randomly fail on `io.mockk.MockKException: can't find stub LocalDateTime(temporary mock)` exception. It does not happen with any other type (e.g. LocalDate) (interesting). This (Joda's) LocalDateTime has mocked its static factory LocalDateTime.now() to return predefined (not-mocked) instance of LocalDateTime. (This happend in tests before)

```kotlin
mockkStatic(LocalDateTime::class)
every { LocalDateTime.now() } returns now
```

We observe this issue among many unit-tests. The stack trace is different for each test case, yet same for every flaky run.

It seems that the stub gets somehow unregistered, but no idea why/how/...

<details><summary>Stacktrace 1</summary>

```
    io.mockk.MockKException: can't find stub LocalDateTime(temporary mock)
        at io.mockk.impl.stub.StubRepository.stubFor(StubRepository.kt:16)
        at io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:13)
        at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)
        at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:266)
        at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:23)
        at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:21)
        at org.joda.time.LocalDateTime.equals(LocalDateTime.java:682)
        at kotlin.jvm.internal.Intrinsics.areEqual(Intrinsics.java:167)
        at io.mockk.InternalPlatformDsl.deepEquals(InternalPlatformDsl.kt:61)
        at io.mockk.EqMatcher.match(Matchers.kt:23)
        at io.mockk.InvocationMatcher.match(API.kt:3750)
        at io.mockk.impl.stub.MockKStub.answer(MockKStub.kt:41)
        at io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:16)
        at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)
        at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:266)
        at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:23)
        at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:21)
        at ***.UnitsHelper.formatTimeWithPattern(UnitsHelper.kt:253)
        at ***.SeatInfoRequestFactory.getDateTime(SeatInfoRequestFactory.kt:44)
        at ***.SeatInfoRequestFactory.create(SeatInfoRequestFactory.kt:27)
        at ***.SeatInfoRequestFactoryTest.whenCreate_thenQuery(SeatInfoRequestFactoryTest.kt:54)
```

</details>
<details><summary>Stacktrace 2</summary>

```
    io.mockk.MockKException: can't find stub LocalDateTime(temporary mock)
        at io.mockk.impl.stub.StubRepository.stubFor(StubRepository.kt:16)
        at io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:13)
        at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)
        at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:266)
        at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:23)
        at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:21)
        at org.joda.time.LocalDateTime.equals(LocalDateTime.java:682)
        at kotlin.jvm.internal.Intrinsics.areEqual(Intrinsics.java:167)
        at ***.TravelSegment$Point.equals(TravelSegment.kt)
        at kotlin.jvm.internal.Intrinsics.areEqual(Intrinsics.java:167)
        at ***.TravelSegment.equals(TravelSegment.kt)
        at java.util.AbstractList.equals(AbstractList.java:523)
        at org.hamcrest.core.IsEqual.areEqual(IsEqual.java:40)
        at org.hamcrest.core.IsEqual.matches(IsEqual.java:23)
        at org.hamcrest.core.Is.matches(Is.java:25)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:10)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at ***.AssertTestAspect.assertThat(AssertTestAspect.kt:18)
        at ***TestUtilsBaseTest.assertThat(TestUtilsBaseTest.kt)
        at ***.SegmentsFactoryTest.whenUmbrella_whenAirport_thenTravelSegment(SegmentsFactoryTest.kt:140)
```

</details>

<details><summary>Stacktrace 3</summary>

```
    io.mockk.MockKException: can't find stub LocalDateTime(temporary mock)
        at io.mockk.impl.stub.StubRepository.stubFor(StubRepository.kt:16)
        at io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:13)
        at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)
        at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:266)
        at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:23)
        at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:21)
        at org.joda.time.LocalDateTime.equals(LocalDateTime.java:682)
        at kotlin.jvm.internal.Intrinsics.areEqual(Intrinsics.java:167)
        at ***.TravelSegment$Point.equals(TravelSegment.kt)
        at kotlin.jvm.internal.Intrinsics.areEqual(Intrinsics.java:167)
        at ***.TravelSegment.equals(TravelSegment.kt)
        at java.util.AbstractList.equals(AbstractList.java:523)
        at org.hamcrest.core.IsEqual.areEqual(IsEqual.java:40)
        at org.hamcrest.core.IsEqual.matches(IsEqual.java:23)
        at org.hamcrest.core.Is.matches(Is.java:25)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:10)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at ***.AssertTestAspect.assertThat(AssertTestAspect.kt:18)
        at ***.TestUtilsBaseTest.assertThat(TestUtilsBaseTest.kt)
        at ***.SegmentsFactoryTest.whenUmbrella_whenNullLayover_thenNullTransfer(SegmentsFactoryTest.kt:102)
```

</details>

<details><summary>Stacktrace 4</summary>

This one is different, though it is flaky too. Maybe related?

```
    io.mockk.MockKException: no answer found for: LocalDateTime(child of static LocalDateTime#4180).toDateTime(UTC)
        at io.mockk.impl.stub.MockKStub.defaultAnswer(MockKStub.kt:93)
        at io.mockk.impl.stub.MockKStub.answer(MockKStub.kt:42)
        at io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:16)
        at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)
        at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:266)
        at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:23)
        at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:21)
        at org.joda.time.LocalDateTime.toDateTime(LocalDateTime.java:750)
        at ***.JodaTimeExtensionsKt.toDateTimeInUtc(JodaTimeExtensions.kt:65)
        at ***.JodaTimeExtensionsKt.getMillis(JodaTimeExtensions.kt:50)
        at ***.JodaTimeExtensionsKt.getSeconds(JodaTimeExtensions.kt:53)
        at ***V1TestRepo$FlightSegment.brnoToPrague(UmbrellaV1TestRepo.kt:23)
        at ***V1TestRepo$FlightSegment.brnoToPrague$default(UmbrellaV1TestRepo.kt:19)
        at ***.SegmentsFactoryTest.whenFlightResponseSegment_thenTravelSegment(SegmentsFactoryTest.kt:337)
```

</details>

<details><summary>Stacktrace 5</summary>

```
    io.mockk.MockKException: can't find stub LocalDateTime(temporary mock)
        at io.mockk.impl.stub.StubRepository.stubFor(StubRepository.kt:16)
        at io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:13)
        at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)
        at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:266)
        at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:23)
        at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:21)
        at org.joda.time.LocalDateTime.equals(LocalDateTime.java:682)
        at kotlin.jvm.internal.Intrinsics.areEqual(Intrinsics.java:167)
        at ***.TravelSegment$Point.equals(TravelSegment.kt)
        at kotlin.jvm.internal.Intrinsics.areEqual(Intrinsics.java:167)
        at ***.TravelSegment.equals(TravelSegment.kt)
        at java.util.AbstractList.equals(AbstractList.java:523)
        at org.hamcrest.core.IsEqual.areEqual(IsEqual.java:40)
        at org.hamcrest.core.IsEqual.matches(IsEqual.java:23)
        at org.hamcrest.core.Is.matches(Is.java:25)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:10)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at ***.AssertTestAspect.assertThat(AssertTestAspect.kt:18)
        at ***.TestUtilsBaseTest.assertThat(TestUtilsBaseTest.kt)
        at ***.SegmentsFactoryTest.whenUmbrella_whenTrainStation_thenTravelSegment(SegmentsFactoryTest.kt:178)
```

</details>

I am not including any other source code since I don't think it is relavant, this happens in many codepaths and it is flaky. Any idea how to debug? Currently trying to make the logging work, but the possibility to enable it seems quite limited.

Version: latest MockK (master)
Env: JDK 11 & JDK 1.8

**Comment by hrach** [comment]
So I have finally managed to reproduce and make minimal repro. See #650.
The good thing is that this is not flaky, but rather requires correct test run ordering. So this PR has a test suite running A and then B to provide the error.

The issue employs these three things:
- A test case: `mockkStatic()`, no `unmockStatic()`
- B test case: 
  - having mock with with explicitly defined every on method call defined with `LocalDateTime` instance
  - the `LocalDateTime` instance has to be defined outside the testcase

Currently possible workaround: call `unmockkStatic()` in the A test case.

Sadly, I have no idea where to fix this. Any help appreciated.

**Comment by hrach** [comment]
I'd guess that this is important :)

**Comment by adamfils** [comment]
In the before test func mock the LocalDateTime constructor.
This should get rid of the error.

@Before
fun setUp() {
   mockkConstructor(LocalDateTime::class)
}

**Comment by varunajaygupta** [comment]
The above solution is not working for me either.

io.mockk.MockKException: can't find stub Throwable(temporary mock)  
at io.mockk.impl.stub.StubRepository.stubFor(StubRepository.kt:16)  
at io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:13)  
at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)  
at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:269)  
at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:24)  
at app//io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:21)  
at java.base@17.0.9/java.lang.Throwable.toString(Throwable.java:497)  
at java.base@17.0.9/java.lang.Throwable.\<init>(Throwable.java:317)  
at java.base@17.0.9/java.lang.Exception.\<init>(Exception.java:103)  
at java.base@17.0.9/java.util.concurrent.ExecutionException.\<init>(ExecutionException.java:90)  
at java.base@17.0.9/java.util.concurrent.FutureTask.report(FutureTask.java:122)  
at java.base@17.0.9/java.util.concurrent.FutureTask.get(FutureTask.java:191)  
at app//org.robolectric.internal.bytecode.Sandbox.runOnMainThread(Sandbox.java:107)  
at app//org.robolectric.internal.bytecode.Sandbox.runOnMainThread(Sandbox.java:97)  
at app//org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:252)  
at app//org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)  
at app//org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)  
at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)  
at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)  
at app//org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)  
at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)  
at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)  
at app//org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)  
at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)  
at app//org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:101)  
at app//org.junit.runners.ParentRunner.run(ParentRunner.java:413)  
at app//androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:162)  
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:108)  
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)  
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)  
at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60)  
at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)  
at java.base@17.0.9/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  
at java.base@17.0.9/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)  
at java.base@17.0.9/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  
at java.base@17.0.9/java.lang.reflect.Method.invoke(Method.java:568)  
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)  
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)  
at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)  
at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)  
at jdk.proxy2/jdk.proxy2.$Proxy5.processTestClass(Unknown Source)  
at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)  
at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)  
at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)  
at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)  
at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)  
at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)  
at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)  
at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)  
at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)  
 

[@Raibaz](https://github.com/Raibaz) - Can you please help with this?
