### ISSUE TITLE
Stubbings sometimes not called with kotlin 1.5

### ISSUE THREAD

**Issue by ghus-raba** [mockk/mockk#651]
### Expected Behavior

Everything should keep working after upgrading to kotlin 1.5

### Current Behavior

After updating from kotlin 1.4.32 to 1.5.20, some stubbings are not called, but instead return null.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Use code provided below
2. Run the test

#### Context

* MockK version: 1.11.0
* OS: macOS
* Kotlin version: 1.5.20
* JDK version: adoptopenjdk 11
* JUnit version: 4.13.2
* Type of test: unit test

#### Stack trace

```
The publisher returned is null
java.lang.NullPointerException: The publisher returned is null
	at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
	at io.reactivex.internal.operators.flowable.FlowableSwitchMap$SwitchMapSubscriber.onNext(FlowableSwitchMap.java:113)
	at io.reactivex.processors.BehaviorProcessor$BehaviorSubscription.test(BehaviorProcessor.java:640)
	at io.reactivex.processors.BehaviorProcessor$BehaviorSubscription.emitFirst(BehaviorProcessor.java:586)
	at io.reactivex.processors.BehaviorProcessor.subscribeActual(BehaviorProcessor.java:250)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableSwitchMap.subscribeActual(FlowableSwitchMap.java:49)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.Flowable.blockingFirst(Flowable.java:5698)
	at sk.ferini.mockktest.FooViewModel.getInitialLoaded(FooViewModel.kt:49)
	at sk.ferini.mockktest.FooTest.isInitialLoaded should be false(ExampleUnitTest.kt:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:121)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    implementation "io.reactivex.rxjava2:rxjava:2.2.21"
    implementation "com.jakewharton.timber:timber:4.7.1"
    implementation "io.reactivex.rxjava2:rxkotlin:2.4.0"

    testImplementation 'junit:junit:4.13.2'
    testImplementation "io.mockk:mockk:1.11.0"
    testImplementation "androidx.arch.core:core-testing:2.1.0"
    testImplementation "org.jetbrains.kotlin:kotlin-test-junit:1.5.20"
}

// -----------------------[ IMPLEMENTATION ] -----------------------
package sk.ferini.mockktest

import io.reactivex.Flowable
import io.reactivex.processors.BehaviorProcessor
import timber.log.Timber

abstract class GrandParent<T> {
    abstract val initialLoad: Flowable<Boolean>
}

abstract class Parent<T> : GrandParent<T>() {
    final override val initialLoad: BehaviorProcessor<Boolean> = BehaviorProcessor.create()
}

class FooDataSource : Parent<Unit>()

abstract class DataSourceFactory<T, S : GrandParent<T>> {
    abstract val dataSource: BehaviorProcessor<S>
}

abstract class FooDataSourceFactory : DataSourceFactory<Unit, FooDataSource>()

abstract class BarViewModel<T, S : GrandParent<T>> {

    abstract fun createDataSourceFactory(): DataSourceFactory<T, S>

    private val dataSourceFactory: DataSourceFactory<T, S> by lazy { createDataSourceFactory() }

    protected val dataSource: BehaviorProcessor<S> by lazy { dataSourceFactory.dataSource }

    val initialLoad: Flowable<Boolean>
        get() {
            Timber.d("BarViewModel dataSource: $dataSource")
            val ds = dataSource.value
            Timber.d("  value = $ds")
            Timber.d("  initialLoad = ${ds?.initialLoad}") // this returns null
            return dataSource.switchMap { it.initialLoad }
        }
}

class FooViewModel(private val dataSourceFactory: FooDataSourceFactory) : BarViewModel<Unit, FooDataSource>() {

    val initialLoaded: Boolean
        get() {
            Timber.d("FooViewModel dataSource: $dataSource")
            val ds = dataSource.value
            Timber.d("  value = $ds")
            Timber.d("  initialLoad = ${ds?.initialLoad}")  // this is stubbed correctly
            return initialLoad.blockingFirst()
        }

    override fun createDataSourceFactory(): DataSourceFactory<Unit, FooDataSource> = dataSourceFactory
}

// -----------------------[ TEST ] -----------------------
import androidx.arch.core.executor.testing.InstantTaskExecutorRule
import io.mockk.MockKAnnotations
import io.mockk.every
import io.mockk.impl.annotations.MockK
import io.reactivex.processors.BehaviorProcessor
import org.junit.After
import org.junit.Before
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TestRule
import timber.log.Timber
import kotlin.test.assertFalse

class FooTest {

    @get:Rule val executorRule: TestRule = InstantTaskExecutorRule()

    @MockK private lateinit var dataSourceFactory: FooDataSourceFactory
    @MockK private lateinit var dataSource: FooDataSource

    private val initialLoadingState = BehaviorProcessor.create<Boolean>()

    @Before
    fun before() {
        Timber.plant(object : Timber.Tree() {
            override fun log(priority: Int, tag: String?, message: String, t: Throwable?) {
                println(message)
            }
        })

        MockKAnnotations.init(this)

        every { dataSourceFactory.dataSource } returns BehaviorProcessor.createDefault(dataSource)
        every { dataSource.initialLoad } returns initialLoadingState
    }

    @After
    fun after() {
        Timber.d("after: dataSource = $dataSource")
        Timber.d("after: dataSource.initialLoad = ${dataSource.initialLoad}")
    }

    @Test
    fun `isInitialLoaded should be false`() {
        val viewModel = FooViewModel(dataSourceFactory)

        initialLoadingState.onNext(false)
        Timber.d("starting test, datasource: $dataSource")
        Timber.d("  dataSource.initialLoad: ${dataSource.initialLoad}")

        val isInitialLoaded = viewModel.initialLoaded
        assertFalse(isInitialLoaded, "isInitialLoaded should be false")
    }
}
```

Logs from the above code look like this:
```
starting test, datasource: FooDataSource(dataSource#1)
  dataSource.initialLoad: io.reactivex.processors.BehaviorProcessor@38904c79
FooViewModel dataSource: io.reactivex.processors.BehaviorProcessor@42c7d02a
  value = FooDataSource(dataSource#1)
  initialLoad = io.reactivex.processors.BehaviorProcessor@38904c79
BarViewModel dataSource: io.reactivex.processors.BehaviorProcessor@42c7d02a
  value = FooDataSource(dataSource#1)
  initialLoad = null
after: dataSource = FooDataSource(dataSource#1)
after: dataSource.initialLoad = io.reactivex.processors.BehaviorProcessor@38904c79
```
We can see that both `FooViewModel` and its parent `BarViewModel` receive the same mock `FooDataSource(dataSource#1)`, but when calling `dataSource.initialLoad`, the `FooViewModel` recevies the stubbed value, while `BarViewModel` receives null, thus breaking the rx contract. Also later when same is called from `@After`, stubbed value is again returned correctly.

Same code runs ok with kotlin 1.4.

**Comment by ghus-raba** [comment]
Still valid also with recent mockk 1.12.0

**Comment by YakushevVV** [comment]
is actual

**Comment by ulx** [comment]
@Stuie set this problem as important
