### ISSUE TITLE
how to make a slot for Map<String, String>

### ISSUE THREAD

**Issue by lannyf77** [mockk/mockk#669]
using mockk 1.9.3

having a function to be verified
```
class EventLogger private constructor()

    fun logUserEvent(eventName: String?, eventParamMap: MutableMap<String, String>?) {
       ......
        internaLogEventImpl(eventName, eventParamMap)
    }
   
   internal fun internaLogEventImpl(eventName: String?, customParams: MutableMap<String, String>?) {
        System.out.println("+++ internaLogEventImpl(), $eventName $customParams") 
        ......
    }

    companion object {
         @Volatile
         private var sEventLoggerSingleton: EventLogger? = null

         @JvmStatic
        val instance: EventLogger
            get() {
                if (sEventLoggerSingleton == null) {
                    sEventLoggerSingleton = EventLogger()
                }
                return sEventLoggerSingleton!!
            }
    }
```
got compiler error at `every {eventLogger.internaLogEventImpl(any(), mapSlot)}`
![image](https://user-images.githubusercontent.com/19765258/125330737-1caf4900-e315-11eb-880b-47524d2bbf46.png)

```
Type mismatch.
Required: MutableMap<String, String>?
Found: CapturingSlot<MutableMap<String, String>>
```

when trying this below :
```
class TestK {

    lateinit var eventLogger: EventLogger
    lateinit var application: Application

    val mapSlot = slot<MutableMap<String, String>>()

    @Before
    fun setUp() {
        application = ApplicationProvider.getApplicationContext<Application>()
        eventLogger = spyk(EventLogger.instance)
        
    }

    @After
    fun cleanUp() {
        
    }

    @Test
    fun test_log() {

        val testMap = hashMapOf("action" to "open")

        every {eventLogger.internaLogEventImpl(any(), mapSlot)} answers { //<=== got compiler error on the mapSlot
            println(mapSlot.captured)
            assert(mapSlot.captured["action"] == "open")
        }
        eventLogger.logUserEvent("test_event", testMap)
    }
}
```

**Comment by Raibaz** [comment]
Your `every` call should be like this:

```
every {eventLogger.internaLogEventImpl(any(), capture(mapSlot))} answers { //<=== notice the capture function here
       ...
}
```

Let me know if this helps.

**Comment by lannyf77** [comment]
@Raibaz thanks for the help and the compiler error is gone with `capture(mapSlot)`. However the `answers` block seems not being called.
```
    @Test
    fun test_log() {

        val testMap = hashMapOf("action" to "open")
        eventLogger.logUserEvent("test", testMap)

        io.mockk.every {eventLogger.internaLogEventImpl(any(), capture(mapSlot))} answers {
            println("+++" + mapSlot.captured)
            println("+++"+mapSlot.captured["action"])
            assert(mapSlot.captured["action"] == "open")
        }
    }

the result:

[Robolectric] com.xxx.TestK.test_log: sdk=28; resources=BINARY
Called loadFromPath(/system/framework/framework-res.apk, true); mode=binary sdk=28
+++ internaLogEventImpl(), test {action=open}

Process finished with exit code 0

```
and if do it without the `answers` block it got error:

```
    @Test
    fun test_log() {

        val testMap = hashMapOf("action" to "open")
        eventLoggerTestImpl.logUserEvent("test", testMap)

        io.mockk.every {eventLoggerTestImpl.logUserEvent(any(), capture(mapSlot))}
        
        println("+++" + mapSlot.captured)
        println("+++"+mapSlot.captured["action"])
        assert(mapSlot.captured["action"] == "open2")
        
    }

the result:

[Robolectric] com.xxx.test_log: sdk=28; resources=BINARY
Called loadFromPath(/system/framework/framework-res.apk, true); mode=binary sdk=28
+++ internaLogEventImpl(), test {action=open}

kotlin.UninitializedPropertyAccessException: lateinit property captured has not been initialized

	at io.mockk.CapturingSlot.getCaptured(API.kt:2529)
	at com.xxx.TestK.test_log(ShadowfaxAnalyticsTestK.kt:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by lannyf77** [comment]
using `verify` works for this case:
```
    @Test
    fun test_log() {

        val testMap = hashMapOf("action" to "open")
        eventLoggerTestImpl.logUserEvent("test", testMap)

//        io.mockk.every {eventLoggerTestImpl.internaLogEventImpl(any(), anyMap())} just Runs

        verify(exactly = 1) {eventLoggerTestImpl.logUserEvent(any(), capture(mapSlot))}

        println("+++" + mapSlot.captured)
        println("+++"+mapSlot.captured["action"])
        assert(mapSlot.captured["action"] == "open2")
    }
```

by the way what does the `just run` mean? I tried with or without it does not have impact. Does it mean it will stub the function with doing nothing, or means `just run the original method`?

Thanks for you help!

**Comment by Raibaz** [comment]
`just run` is used for methods returning `Unit` (i.e., not returning a value) on strict mocks.

If you create a mock that is not relaxed and invoke a method on it that has not being stubbed with an `every` block, MockK will throw an exception.

To stub a method returning unit, you can do 
```
every { myObject.myMethod() } just runs
```

**Comment by lannyf77** [comment]
so it is like the `.thenCallRealMethod();` in mockito, and it just runs the real method.
Thanks!

**Comment by Raibaz** [comment]
No, it doesn't :)

It `just runs`, meaning it does not do anything.

To run the real method you can use `answers { callOriginal() }`.

**Comment by lannyf77** [comment]
thanks for clarifying, will go back to retest (why it does not have impact on the test result when use it)
