### ISSUE TITLE
Test Coroutine Flow

### ISSUE THREAD

**Issue by FarshidABZ** [mockk/mockk#678]
The main question is How to test Coroutine Flow with the mokk. 

Here is the implementation of the UseCase and Test class: 

UseCase: 

`
  fun loginUser(loginUserRequestModel: LoginUserRequestModel): Flow<ResponseState<LoginUserResponse>> {
        val deviceId = DeviceProperty.deviceId
        return client.createFlowRequest(deviceId, loginUserRequestModel)
  }
 `
 
 The test class and method: 
 
    class UseCaseTest : KoinTest {
    @RelaxedMockK
    lateinit var baseClient: BaseFlowClient

    private lateinit var usecase: MyUseCase

    @ExperimentalCoroutinesApi
    @get:Rule
    val coroutineRule = CoroutinesTestRule()

    @get:Rule
    val instantExecutorRule = InstantTaskExecutorRule()

    @Before
    fun setup() {
        MockKAnnotations.init(this)
        ....
    }

    @ExperimentalCoroutinesApi
    @Test
    fun testLoginUser() = runBlocking {
        every { DeviceProperty.deviceId } returns ""

        every { baseClient.createFlowRequest<LoginUserResponse>(loginParams) } returns flow {
            emit(responseLoginUser)
        }

        val flow: Flow<ResponseState<LoginUserResponse>> = usecase.loginUser(loginUserRequestModel)

        verify(exactly = 0) {
            coroutineRule.testDispatcher.runBlockingTest {
                flow.collect {
                }
            }
        }
    }
 }
 
When I run the test I get Missing calls inside every { ... } block error:

io.mockk.MockKException: Missing calls inside every { ... } block.

	at io.mockk.impl.recording.states.StubbingState.checkMissingCalls(StubbingState.kt:14)
	at io.mockk.impl.recording.states.StubbingState.recordingDone(StubbingState.kt:8)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:60)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalCoEvery(API.kt:98)
	at io.mockk.MockKKt.coEvery(MockK.kt:115)
	at com.test.MyUseCaseTest$testLoginUser$1.invokeSuspend(MyUseCaseTest.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) 
	
	
If change the every block from  "baseClient.createFlowRequest<LoginUserResponse>(loginParams)" to "usecase.loginUser(loginUserRequestModel)" I will get this error: 

java.lang.ClassCastException: class kotlinx.coroutines.flow.SafeFlow cannot be cast to class java.lang.String (kotlinx.coroutines.flow.SafeFlow is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')

**Comment by Moes81** [comment]
For such cases I use `flowOf(responseLoginUser)` and a [self written `FlowTestObserver`](https://gist.github.com/Moes81/3d4017f1d152638e99cb9fe56a1be69c).


Your test can then work this way:
```
testCoroutineScope.runBlockingTest {
    every { baseClient.createFlowRequest<LoginUserResponse>(loginParams) } returns flow {
        emit(responseLoginUser)
    }

    usecase.loginUser(loginUserRequestModel).test(this)
        .assertValue(responseLoginUser)
        //or .assertValueCount(0)  depending on what you want to test
        .finish()

    verify { mockClient.createFlowRequest(deviceId, loginUserRequestModel) }
}
```
