### ISSUE TITLE
Impossible to mock library with `Void` return type

### ISSUE THREAD

**Issue by Kleinendorst** [mockk/mockk#69]
I try to mock a library, which has a method returning `Void`.
The signature of this method looks like this:

```java
public abstract T get(long timeout, TimeUnit unit) throws InterruptedException, ExecutionException,
        TimeoutException;
```

This object is constructed like this in the library:

```java
public KafkaFuture<Void> all() {
        return KafkaFuture.allOf(futures.values().toArray(new KafkaFuture[0]));
    }
```

Which is setting `T` as `java.lang.Void`.

Each time I try to mock this function, as:

```java
val kafkaFuture: KafkaFuture<Void> = mockk()
every { kafkaFuture.get(any(), any()) } returns mockk<Void>()
```
I get: `io.mockk.MockKException: Class cast exception. Probably type information was erased.
In this case use `hint` before call to specify exact return type of a method.`

I tried hinting like this: `every { kafkaFuture.get(any(), any()).hint(Void::class) } throws mockk<Void>()`
But unfortunately this doesn't work. Also I tried to return a Void object created using reflection, as seen [here](https://stackoverflow.com/questions/643906/uses-for-the-java-void-reference-type#answer-644730) But unfortunately this didn't work neither.

When I write this however:
```java
val kafkaFuture: KafkaFuture<Void> = mockk(relaxed = true)
```
The call does work, which makes me believe this should be possible.
Any help on how to accomplish this?

**Comment by oleksiyp** [comment]
Please note you have `throws`, but probably want `returns`.

**Comment by Kleinendorst** [comment]
@oleksiyp Yes you are correct, this is a mistake I made in the post, but the actual code already had `returns`. In another test case I need to throw an exception and this also return the `io.mockk.MockKException`.

**Comment by oleksiyp** [comment]
I will check it later. 
Correct hinting construct should be following:
```
every { kafkaFuture.hint(Void::class).get(any(), any()) } throws mockk<Void>()
```

**Comment by Kleinendorst** [comment]
Using `hint` like that unfortunately still doesn't work.

**Comment by oleksiyp** [comment]
Following code for me is passing.

Please provide the full, but minimal piece of code that is not working.
I always hit this issue with reproducibility.

```
package io.mockk.gh

import io.mockk.every
import io.mockk.mockk
import org.apache.kafka.common.KafkaFuture
import kotlin.test.Test

class Issue69Test {

    @Test
    fun test() {
        val kafkaFuture: KafkaFuture<Void> = mockk()
        every { kafkaFuture.get(any(), any()) } returns mockk()
        kafkaFuture.get(10, TimeUnit.MILLISECONDS)
    }

}
```

**Comment by oleksiyp** [comment]
JFYI I've created a template for issues https://github.com/oleksiyp/mockk/blob/master/.github/issue_template.md :smile: (You don't need to follow it)

**Comment by Kleinendorst** [comment]
Ah, thanks for the help.
To the relevant questions in the template:

I'm using the latest version: `1.7.15` of Mockk, on Kotlin `1.2.31` for JVM target version `1.8`.
I looked at  other issues, the documentation, and I assume this would be a bug since I used this amazing framework to mock similar libraries.  

The library I'm running into trouble with is the [Project Reactor Kafka client](https://github.com/reactor/reactor-kafka), but I would assume this report applies to all functions returning `java.util.Void` or even other types which are non initializable. 

## The Error:

Actually the posted test already throws the error
![image](https://user-images.githubusercontent.com/8981635/39447125-0f9d642e-4cc1-11e8-8d16-96c9bc7dbbf6.png)

### Full stack trace:
```
io.mockk.MockKException: Class cast exception. Probably type information was erased.
In this case use `hint` before call to specify exact return type of a method. 

	at io.mockk.impl.InternalPlatform.prettifyRecordingException(InternalPlatform.kt:83)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:50)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:25)
	at eu.example.schedule.kafka.KafkaAdminImplTest.mockkVoidReturnFails(KafkaAdminImplTest.kt:301)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassCastException: kotlin.Unit cannot be cast to java.lang.Void
	at eu.example.schedule.kafka.KafkaAdminImplTest$mockkVoidReturnFails$1.invoke(KafkaAdminImplTest.kt:87)
	at eu.example.schedule.kafka.KafkaAdminImplTest$mockkVoidReturnFails$1.invoke(KafkaAdminImplTest.kt:24)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:22)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:31)
	... 25 more
```

> Note: I also ran this using Kotlin 1.2.40, but the problem persists.

**Comment by oleksiyp** [comment]
This is a tricky bug because it is working well for me.

**Comment by oleksiyp** [comment]
Going to sleep and get back to the issue in the morning. Tomorrow is a public holiday, so will have some time.
