### ISSUE TITLE
`java.lang.VerifyError` when using mockk in androidTest with proguard on android 11

### ISSUE THREAD

**Issue by ShivamPokhriyal** [mockk/mockk#691]
Getting `java.lang.verifyError` while using mockk-android in androidTests with proguard enabled. 
Below are the proguard rules: 
```
-keep class kotlin.collections.ArraysKt { *; }
-keep class io.mockk.** { *; }
```

Below is the stacktrace: 
```
java.lang.VerifyError: Verifier rejected class kotlin.reflect.jvm.internal.ReflectionFactoryImpl: kotlin.reflect.KDeclarationContainer 
kotlin.reflect.jvm.internal.ReflectionFactoryImpl.getOrCreateKotlinPackage(java.lang.Class, java.lang.String) failed to verify: kotlin.reflect.KDeclarationContainer 
kotlin.reflect.jvm.internal.ReflectionFactoryImpl.getOrCreateKotlinPackage(java.lang.Class, java.lang.String): [0x5]  can't 
resolve returned type 'Unresolved Reference: kotlin.reflect.KDeclarationContainer' or 'Precise Reference: 
kotlin.reflect.jvm.internal.KPackageImpl' (declaration of 'kotlin.reflect.jvm.internal.ReflectionFactoryImpl' appears in 
/data/app/~~EgtdWl5fjjDp3s4oaZsALA==/<package_name>-Mq5Jb8WURusXh0cakQqlpw==/base.apk)
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at java.lang.Class.forName(Class.java:379)
	at kotlin.jvm.internal.Reflection.<clinit>(SourceFile:26)
	at kotlin.jvm.internal.Reflection.getOrCreateKotlinClass(SourceFile:54)
	at io.mockk.impl.JvmMockKGateway.<clinit>(JvmMockKGateway.kt:19)
```

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: `mockk-android:1.12.0`
* OS: `android 11`
* Kotlin version: `1.3.72`
* JDK version: `1.8`
* Type of test: android instrumented test

#### Minimal reproducible code (the gist of this issue)

```groovy
dependencies {
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'io.mockk:mockk-android:1.12.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test:rules:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-intents:3.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-contrib:3.2.0'
    androidTestImplementation 'androidx.test.espresso.idling:idling-concurrent:3.4.0'
}

**Comment by gmazzo** [comment]
We just facing this issue with R8, does anyone found a fix/workaround for it?
