### ISSUE TITLE
Mockk can't find stubs on Ubuntu 20.04 (but can on Ubuntu 18.04)

### ISSUE THREAD

**Issue by pmwmedia** [mockk/mockk#692]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version **(tested with Mockk 1.11 and 1.12)**
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

Mockk should find stubs on Ubuntu 20.04 and all tests should pass.

### Current Behavior

Mockk can't find any stubs on Ubuntu 20.04. However, it can find all stubs on Ubuntu 18.04 and all my tests pass.

### Failure Information (for bugs)

I'm using GitHub Actions for compiling and testing my project.

Works with Ubuntu 18.04:
https://github.com/tinylog-org/tinylog/runs/3561544826#step:5:1035

But fails with Ubuntu 20.04:
https://github.com/tinylog-org/tinylog/runs/3561486190#step:5:1038

The only difference is the operating system as you can see in my commit list:
https://github.com/tinylog-org/tinylog/commits/v2.4

I have executed the runs multiple times on Ubuntu 18.04 and 20.04 with Mockk 1.11 and 1.12. The behavior is reproducible since this month. However, Mockk was still working on Ubuntu 20.04 until at least August 26. I assume that the latest update for Ubuntu 20.04 has broken compatibility with Mockk.

#### Steps to Reproduce

1. Create a GitHub workflow with Ubuntu 20.04 as OS
2. Write any JUnit test with Mockk
3. Let your GitHub workflow run

#### Context

* MockK version: 1.11.0 and 1.12.0 (both tested)
* OS: Ubuntu 20.04
* Kotlin version: 1.3.72
* JDK version: 9.0.7
* JUnit version: 4.13.2
* Type of test: unit test

#### Stack trace

```
java.lang.ExceptionInInitializerError
	at org.tinylog.kotlin.LoggerTest$Logging.applyLoggingProvider(LoggerTest.kt:125)
Caused by: io.mockk.MockKException: can't find stub LoggingProvider(temporary mock)
	at org.tinylog.kotlin.LoggerTest$Logging.applyLoggingProvider(LoggerTest.kt:125)
```

**Comment by shavinda** [comment]
@pmwmedia I am facing a similar issue with the latest image changes made to Github Runner environment on ubuntu-20.04.

All my tests used to pass with the 202202XXX image, but since they updated it to 20220330XXX image (but same version of ubuntu), my tests that use Mockk have started failing.

Did you ever manage to resolve this issue? Any tips?

**Comment by pmwmedia** [comment]
I have switched from `mockk` to `mockito-kotlin`. With Mockito, I don't run into this issue.
