### ISSUE TITLE
InternalPlatformDsl.dynamicCall can't find private function with nullable argument when passing null

### ISSUE THREAD

**Issue by polynesia** [mockk/mockk#693]
### Expected Behavior

test1 pass;
test2 pass;
test3 pass;

### Current Behavior

test1 pass;
test2 fail;
test3 pass;

### Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.10.6
* OS: MAC OS
* Kotlin version: 1.4.0
* JDK version: 7
* JUnit version: 4
* Type of test: unit test

#### Failure Logs

Please include any relevant log snippets or files here.

#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
io.mockk.MockKException: can't find function testString2(null) for dynamic call

	at io.mockk.InternalPlatformDsl.dynamicCall(InternalPlatformDsl.kt:122)
	at com.ttt.test2(Test.kt:174)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    testCompile group: 'org.apache.kafka', name: 'kafka_2.12', version: '1.1.0'
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
package io.mockk.gh

import io.mockk.InternalPlatformDsl
import io.mockk.Runs
import io.mockk.every
import io.mockk.just
import io.mockk.mockk
import io.mockk.mockkObject
import io.mockk.spyk
import io.mockk.verify
import org.json.JSONObject
import org.junit.After
import org.junit.Assert
import org.junit.Before
import org.junit.Test

class Issue69Test {

    class MyClass {
        fun testString(input: String?) {
            testFun1()
        }

        private fun testString2(input: String?) {
            testFun1()
        }

        fun testFun1() {}
    }

    @Test
    fun test1() {
        val myClass: MyClass = spyk()
        myClass.testString(null)
        verify { myClass.testFun1() }
    }

    @Test
    fun test2() {
        val myClass: MyClass = spyk()
        InternalPlatformDsl.dynamicCall(myClass, "testString2", arrayOf(null), mockk())
        verify { myClass.testFun1() }
    }

    @Test
    fun test3() {
        val myClass: MyClass = spyk()
        InternalPlatformDsl.dynamicCall(myClass, "testString2", arrayOf("test"), mockk())
        verify { myClass.testFun1() }
    }

}
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by polynesia** [comment]
similar issue: Bug: captureNullable is broken #353

**Comment by yanjiepeng** [comment]
any solution about this issue?
