### ISSUE TITLE
Bug: StackOverflowError related to spyk'ing objects that call super method

### ISSUE THREAD

**Issue by TomBell-Trove** [mockk/mockk#704]
### Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed*

*a similar, but possibly not quite exact error is [here](https://github.com/mockk/mockk/issues/337), people point to the JVM being the culprit which does not appear to be the issue here hence new issue

### Expected Behavior

I am trying to spyk a class which calls a method in its super class.  The class should then be mockable/verifiable.

### Current Behavior

The tests fail to run with a java.lang.StackOverflowError.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. download repro project attached.
2. run HomePresenterTest
3. StackOverflowError

#### Context

* MockK version: 1.12.0
* OS: MacOS 11.3.1
* Kotlin version: 1.5.21, 1.5.30
* JDK version: 11.0.12 (x86_64) "Eclipse Temurin" - "Eclipse Temurin 11".  However also reproducible on following versions:
    16.0.2 (x86_64) "Homebrew" - "OpenJDK 16.0.2" 
    11.0.10 (x86_64) "UNDEFINED" - "OpenJDK 11.0.10" 
* JUnit version: 4.13.2
* Type of test: unit test 
* Robolectric version: 4.5.1

#### Stack trace

```
java.lang.StackOverflowError
	at kotlin.reflect.jvm.internal.impl.types.AbstractClassTypeConstructor.equals(AbstractClassTypeConstructor.java:76)
	at kotlin.jvm.internal.Intrinsics.areEqual(Intrinsics.java:167)
	at kotlin.reflect.jvm.internal.impl.types.checker.ClassicTypeSystemContext$DefaultImpls.isEqualTypeConstructors(ClassicTypeSystemContext.kt:216)
	at kotlin.reflect.jvm.internal.impl.types.checker.SimpleClassicTypeSystemContext.isEqualTypeConstructors(NewKotlinTypeChecker.kt:33)
	at kotlin.reflect.jvm.internal.impl.types.AbstractStrictEqualityTypeChecker.strictEqualSimpleTypes(AbstractStrictEqualityTypeChecker.kt:44)
	at kotlin.reflect.jvm.internal.impl.types.AbstractStrictEqualityTypeChecker.strictEqualTypesInternal(AbstractStrictEqualityTypeChecker.kt:29)
	at kotlin.reflect.jvm.internal.impl.types.AbstractStrictEqualityTypeChecker.strictEqualTypes(AbstractStrictEqualityTypeChecker.kt:13)
	at kotlin.reflect.jvm.internal.impl.types.checker.StrictEqualityTypeChecker.strictEqualTypes(NewKotlinTypeChecker.kt:45)
	at kotlin.reflect.jvm.internal.impl.types.KotlinType.equals(KotlinType.kt:117)
	at kotlin.jvm.internal.Intrinsics.areEqual(Intrinsics.java:167)
	at kotlin.reflect.jvm.internal.impl.renderer.DescriptorRendererImpl.renderSimpleType(DescriptorRendererImpl.kt:161)
	at kotlin.reflect.jvm.internal.impl.renderer.DescriptorRendererImpl.renderNormalizedTypeAsIs(DescriptorRendererImpl.kt:156)
	at kotlin.reflect.jvm.internal.impl.renderer.DescriptorRendererImpl.renderNormalizedType(DescriptorRendererImpl.kt:134)
	at kotlin.reflect.jvm.internal.impl.renderer.DescriptorRendererImpl.renderType(DescriptorRendererImpl.kt:116)
	at kotlin.reflect.jvm.internal.ReflectionObjectRenderer.renderType(ReflectionObjectRenderer.kt:122)
	at kotlin.reflect.jvm.internal.KTypeImpl.toString(KTypeImpl.kt:125)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper.toDescription$mockk(JvmMockFactoryHelper.kt:129)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:25)
	at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:21)
	at com.example.mockkstackoverflowexceptiondemo.base.HomePresenter.onViewAttached(Base.kt:40)
        at com.example.mockkstackoverflowexceptiondemo.base.HomePresenter.onViewAttached(Base.kt:33)
... snip ...
```

#### Minimal reproducible code (the gist of this issue)

Project code
```kotlin
package com.example.mockkstackoverflowexceptiondemo.base

import androidx.annotation.CallSuper


abstract class MvpPresenter<V : MvpView> {
    var view: V? = null

    fun attachView(view: V) {
        this.view = view
        onViewAttached(view)
    }

    fun detachView() { view = null }

    @CallSuper
    open fun onViewAttached(view: V) {
        // not reproducible if abstract.
    }
}

interface MvpView

class HomePresenter : MvpPresenter<HomeView>() {

    override fun onViewAttached(view: HomeView) {
        super.onViewAttached(view)
    }
}

interface HomeView : MvpView
```

Test code
```
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [28])
class HomePresenterTest {

    @Test fun someTest() {
        val presenter = spyk(HomePresenter())
        val view = mockk<HomeView>(relaxed = true)
        presenter.attachView(view)
    }
}
```
[mockkstackoverflowexceptiondemo.zip](https://github.com/mockk/mockk/files/7240648/mockkstackoverflowexceptiondemo.zip)

**Comment by Michael-MF** [comment]
I'm having the same issue, no Roboeletric involved for me though, just a simple JUnit4 test

**Comment by TomBell-Trove** [comment]
This is still an issue and should not be closed without investigation. I've
attached a sample above to repro.

**Comment by TomBell-Trove** [comment]
Important please, this is still an issue.

**Comment by TomBell-Trove** [comment]
Still an issue

**Comment by kcdev90** [comment]
I'm still having this issue as of May 2023.
