### ISSUE TITLE
at java 11 compiler, Failed matching mocking signature for left matchers: [any()]

### ISSUE THREAD

**Issue by ricky-buzzni** [mockk/mockk#721]
> Just be aware about usual MockK support pattern. 
> Tickets are checked from time to time, replied, discussed, labeled, e.t.c.
> But real fixes are applied in a month-two month period in a bunch.
> If you think this is unacceptable, go on, join the project, change the world.

## Please remove sections wisely

Below information is actually needed to make all the process of fixing faster.
Choose main points. Don't blindly follow this as a set of rules. 
Don't waste much time. Usually, the main thing is to have a good reproducible minimal code.

### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version (1.12.0)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

`Any<View>().____()` logic inside every block should be mocked normally.

### Current Behavior

mockking failed

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
I'm using RxBinding and mockK together, and I'm trying to mockking the `RxBinding.clicks()` as an answer.

2. step 2
at java 11 `step 1` code failed...

3. you get it...

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.12.0
* OS: mac
* Kotlin version: 1.5.21
* JDK version: 11
* JUnit version: 4.12
* Type of test: unit test OR android instrumented test

#### Failure Logs

Please include any relevant log snippets or files here.

#### Stack trace

```
Failed matching mocking signature for

left matchers: [any()]
io.mockk.MockKException: Failed matching mocking signature for

left matchers: [any()]
	at io.mockk.impl.recording.SignatureMatcherDetector.detect(SignatureMatcherDetector.kt:99)
	at io.mockk.impl.recording.states.RecordingState.signMatchers(RecordingState.kt:39)
	at io.mockk.impl.recording.states.RecordingState.round(RecordingState.kt:31)
	at io.mockk.impl.recording.CommonCallRecorder.round(CommonCallRecorder.kt:50)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:63)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalEvery(API.kt:92)
	at io.mockk.MockKKt.every(MockK.kt:98)
	at ****.AndroidBaseTest.setupContext(AndroidBaseTest.kt:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:278)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// RxViewEx.kt

fun View.singleClicks(): Observable<Any> = RxView.clicks(this)
    .doOnNext { ... }
    .throttleFirst(600, TimeUnit.MILLISECONDS)

...

// AndroidBaseTest.kt (with robolectric 4.5.1)
@Before
fun setupContext() {
    appContext = ApplicationProvider.getApplicationContext()

    // ignore View throttleFirst
    mockkStatic(",,,,.RxViewEx")
    every { any<View>().singleClicks() } answers { call: Call ->
        RxView.clicks(call.invocation.args[0] as View)
    }
}
```

**Comment by ricky-buzzni** [comment]
@Raibaz Thank you very much. I'll try it once and close it if it goes well.
