### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class io.mockk.impl.JvmMockKGateway

### ISSUE THREAD

**Issue by Psijic** [mockk/mockk#724]
It looks like [this issue ](https://github.com/mockk/mockk/issues/454) but I have it with my 
mockk = 1.12.0
JDK = 11.0.10

```
java.lang.NoClassDefFoundError: io/mockk/proxy/MockKAgentFactory

	at io.mockk.impl.JvmMockKGateway.<init>(JvmMockKGateway.kt:198)
	at io.mockk.impl.JvmMockKGateway.<clinit>(JvmMockKGateway.kt:186)
```

`java.lang.NoClassDefFoundError: Could not initialize class io.mockk.impl.JvmMockKGateway`

**Comment by gregorycollins** [comment]
We encountered this with Azul JDK 15 + Bazel on the `ubuntu-latest` github runners. Our tentative workaround is to supply `-javaagent` pointing at the `byte-buddy-agent` in the bazel rule:

```
TEST_MAIN_CLASS = "org.junit.platform.console.ConsoleLauncher"
COMMON_TEST_ARGS = [
    "--select-package=com.foocorp",
    "--disable-ansi-colors",
    "--fail-if-no-tests",
]
COMMON_TEST_DEPS = [...]

def custom_kt_test(name, args = [], data = [], deps = [], runtime_deps = [], jvm_flags = [], **kwargs):
    kt_jvm_test(
        name = name,
        args = args + COMMON_TEST_ARGS,
        data = data + [
            "@maven//:net_bytebuddy_byte_buddy_agent",
        ],
        deps = deps + COMMON_TEST_DEPS,
        main_class = TEST_MAIN_CLASS,
        runtime_deps = runtime_deps + [
            "@maven//:net_bytebuddy_byte_buddy_agent",
        ],
        jvm_flags = jvm_flags + [
            "-Djdk.attach.allowAttachSelf=true",
            "-javaagent:$(rootpath @maven//:net_bytebuddy_byte_buddy_agent)",
        ],
        **kwargs
    )
```

Here are our relevant workspace pins, I think they're all latest:

```
        "io.mockk:mockk:1.12.1",
        "net.bytebuddy:byte-buddy:1.12.6",
        "net.bytebuddy:byte-buddy-agent:1.12.6",
        "org.mockito:mockito-core:4.2.0",
        "org.mockito:mockito-inline:4.2.0",
        "org.objenesis:objenesis:3.2",
```

**Comment by ZSmallX** [comment]
> After I updated Graddle from 4 to 7, errors dissapeared.

I think it has none business with Gradle. I met the same problem and upgrading the Gradle version didn't help.

When I specified the JDK from JBR to Oracle JDK, it worked well.

See https://github.com/mockk/mockk/issues/454
