### ISSUE TITLE
Using @JvmStatic annotation makes Mockk to throw an exception 

### ISSUE THREAD

**Issue by VictorAlbertos** [mockk/mockk#76]
First I want to thank you for this amazing library, as far as I know it's the only mock framework made purely with Kotlin. 

Now the bad news :D

If an `Object` has one of its methods annotated with `@JvmStatic`, when trying to mock that method, an exception is thrown.

### Code to reproduce the bug

```kotlin
object ObjectAnnotated {
    @JvmStatic fun foo() = "foo"
}
```

```kotlin
class ObjectAnnotatedTest {
    @Test
    fun verifyFoo() {
        objectMockk(ObjectAnnotated).mock()
        every { ObjectAnnotated.foo() } returns "bar"
        assert(ObjectAnnotated.foo() == "bar")
    }
}
```

### Stacktrace

```
io.mockk.MockKException: Missing calls inside every { ... } block.
	at io.mockk.impl.recording.states.StubbingState.checkMissingCalls(StubbingState.kt:14)
	at io.mockk.impl.recording.states.StubbingState.recordingDone(StubbingState.kt:8)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:42)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:48)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:25)
	at com.mufumbo.android.recipe.search.provider_login.ObjectAnnotatedTest.verifyFoo(ObjectAnnotatedTest.kt:25)
```

I'm using latest version -> **1.8**

Please let me know if you need further support.

**Comment by oleksiyp** [comment]
Just try static mock on that object class

**Comment by VictorAlbertos** [comment]
I don't know what you mean by `static mock`. Can you share the implementation based on my previous example?

**Comment by oleksiyp** [comment]
Can't check right now this code(hope it works):
```
class ObjectAnnotatedTest {
    @Test
    fun verifyFoo() {
        staticMockk<ObjectAnnotated>().use {
            every { ObjectAnnotated.foo() } returns "bar"
            assert(ObjectAnnotated.foo() == "bar")
       }
    }
}
```

**Comment by VictorAlbertos** [comment]
It works, thanks @oleksiyp for the support 👍
