### ISSUE TITLE
MockK fails with NullPointerException if an extension function call on a mock is passed as an argument directly when stubbing another mock

### ISSUE THREAD

**Issue by pavlo-tr** [mockk/mockk#762]
Hi!
I'm experiencing a strange behaviour with MockK.
Not sure if it's a bug or I'm just not getting something.
Couldn't find anything about the problem, so posting it here.

The problem is that if an extension function call on a mock is passed as an argument directly when stubbing another mock, a NPE is thrown.
But if the result of such extension function call is saved in a variable and this variable is then passed as an argument, everything works fine.

This is reproducible when using both Kotlin `1.5.31` and `1.6.0` with MockK `1.12.1`

Please note that in order to make the example shorter I'm not putting the code inside a test.

#### Minimal reproducible code (the gist of this issue)

```kotlin
import io.mockk.every
import io.mockk.mockk
import java.time.Instant

class Version {
    lateinit var creationDate: Instant
}

class Document {
    lateinit var versions: List<Version>
}

fun Document.latestVersion() = versions.maxByOrNull(Version::creationDate)!!

class Processor {
    fun processVersion(version: Version) = println("Processing $version")
}

fun main() {
    val version = mockk<Version> {
        every { creationDate } returns Instant.EPOCH
    }
    val document = mockk<Document> {
        every { versions } returns listOf(version)
    }

    val processor = mockk<Processor> {
        every { processVersion(document.latestVersion()) } returns Unit
    }

    processor.processVersion(document.latestVersion())
}
```

#### Stack trace

```
Exception in thread "main" java.lang.NullPointerException
	at TestKt.latestVersion(test.kt:47)
	at TestKt$main$processor$1$1.invoke(test.kt:28)
	at TestKt$main$processor$1$1.invoke(test.kt:28)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:25)
	at io.mockk.impl.eval.RecordedBlockEvaluator$enhanceWithRethrow$1.invoke(RecordedBlockEvaluator.kt:78)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:40)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalEvery(API.kt:92)
	at io.mockk.MockKKt.every(MockK.kt:98)
	at TestKt.main(test.kt:28)
	at TestKt.main(test.kt)
```

If instead of passing `document.latestVersion()` directly when stubbing a separate variable is used, code runs without any problems:
```kotlin
val versionToProcess = document.latestVersion()
val processor = mockk<Processor> {
    every { processVersion(versionToProcess) } returns Unit
}

processor.processVersion(document.latestVersion())
```

**Comment by pavlo-tr** [comment]
Updated the issue, as the actual problem here is wrong stub being created.

`document.versions` somehow returns empty list in the lambda passed to `every` function when mocking `Processor`. That's why `Document.latestVersion()` returns `null`, so the wrong stub is being created.
But in the call of `processVersion` the mock of `Version` is being passed, not `null`.

**Comment by altairmizuchi** [comment]
I think I have the same issue but in my case I do not even use extension functions
`    data class ContentOwner(val content: Content)

    class Consumer {
        fun consume(owner: ContentOwner) {
            //code consuming content fields and methods
        }
    }

    fun test() {
        val content = mockk<Content>("namedContent")
        every { content.processedUrl() } returns "something"
        val owner = mockk<ContentOwner>("namedOwner")
        every { owner.content } returns content
        val consumer = Consumer()
        consumer.consume(owner) //error no answer found Content(child of namedOwner#42#46).processedUrl()
    }`
    
   It also works strange with verify statements
   `val processor = mockk<Processor>()
        verify(exactly = 1) { processor.process(content) } //works
        verify(exactly = 1) { processor.process(owner.content) } //reports there were 2 calls of process and arguments for one of them do not match`

**Comment by pavlo-tr** [comment]
@Raibaz
Would be great if you could have a look at this issue. 🙂 

Sorry for tagging. 🙈 
And especially if you're not the right person to ask.

**Comment by Raibaz** [comment]
@pavlo-tr, sorry for the late reply.

Given that I kind of understand the issue you are speaking about here, I don't really understand what you are trying to test here.

Specifically, this sounds a lot like a code smell to me:

```
every { processVersion(document.latestVersion()) } returns Unit
```

Why are you calling another function to determine the parameter you want to pass to `processVersion`?

IMHO, the rationale of the stubbing here should be to determine how `processVersion` should behave under some set conditions, I don't really see the reason to try stubbing two different functions in the same place.

I'd probably write your stubbing declaration using a matcher of some sorts, i.e.

```
every { processVersion(any()) } returns Unit
```

Or with a more specific matcher in case it was needed, and then stub the behavior for `latestVersion()` separately.

Does this make sense?

**Comment by pavlo-tr** [comment]
@Raibaz
Thanks for the answer!

Actually you're right, calling another function to determine parameter is not wise.
The right approach would be `every { processVersion(version) } returns Unit`, as I know exactly which version I expect.

Though I don't understand the second part of your message.
I didn't try to stub the behaviour of `latestVersion()`, I was only trying to stub `processVersion()`.

When writing `every { processVersion(document.latestVersion()) } returns Unit` I was expecting `document.latestVersion()` to return me the `Version` mock, as `document` is already mocked before.
And the second code snippet proves that `document` is already working as expected by the moment I'm defining the `Processor` mock.

So I don't understand why exception is being thrown.
I was expecting `document.latestVersion()` to behave the same both inside the `every()` call when mocking `Processor` (first code snippet) and outside of it (second code snippet).

**Comment by Raibaz** [comment]
Yep I see what you mean, the thing is that inside an `every` block mockk actually uses the stubbed methods, if any, which is why your call to `document.latestVersion()` inside the `every` block is not behaving as you expect.

**Comment by Raibaz** [comment]
It is indeed a weird behavior 😅 

I've been debugging your example as well, and noticed that outside of the `every { processVersion(document.latestVersion)) }` block, `document.versions` is indeed populated, while inside the block the behavior is the one you are showing in your screenshots.

My interpretation is that having two mocks, `processor` and `document` in the same `every` block messes up with the argument matcher, which only matches the first of the two mocks: in fact, digging deeper in what happens inside the `every` block, I found this:

![image](https://user-images.githubusercontent.com/1030142/149585197-7fe203ec-016d-4fec-b953-bca421cbdad0.png)

As you can see, what the call recorder is matching is `Processor(#5).processVersion(null())`.

This being said, it is still a weird usage to use two mocks in a single `every` block.

Perhaps the correct behavior for Mockk should be to be aware of this and to signal it to the user, but I honestly don't know how hard it would be to detect the presence of more than one mocked object in a stubbing block.

**Comment by pavlo-tr** [comment]
@Raibaz 
It seems that inside the lambda which is passed to `every()` properties of the mocks are returning incorrect values.

When running
```kotlin
val processor = mockk<Processor> {
    every {
        println("Creation data is ${version.creationDate}.")
        processVersion(version)
    } returns Unit
}
```
I see
<img width="822" alt="Screenshot 2022-01-17 at 10 36 56" src="https://user-images.githubusercontent.com/90606143/149744841-b1388270-384d-4165-9196-1dcfb1eafaaf.png">
and

> Creation data is .

is printed to the output. 😅 

Sure, I totally agree that two mocks should not be used in a single `every` block. 🙂 

Yes, it might be the correct behaviour, but it doesn't sound to me that implementing this would be easy.
I guess it will be even harder to make two mocks work in a single `every` block. 😄 
Maybe it would be enough for now to update the documentation to warn users about potential problems. 😉

**Comment by pavlo-tr** [comment]
@Raibaz 
Sorry for tagging once again. 🙈 
Just wanted to make sure that it's OK from your perspective if issue becomes stale.

**Comment by Raibaz** [comment]
Yep you're right, it shouldn't be stale.

I don't have time to work on it personally ATM, but I'd gladly review a PR updating the docs with some further details about this.
