### ISSUE TITLE
Verification Failed of Mocked

### ISSUE THREAD

**Issue by atif-afridi** [mockk/mockk#767]
- [Y] I am running the latest version "io.mockk:mockk:1.12.1"
- [Y] I checked the documentation and found no answer
- [Y] I checked to make sure that this issue has not already been filed

### Expected Behavior

Sometimes test passes sometimes fails

### Current Behavior

A very basic test is getting failed on coEvery which say " was not called " mentioned in details.

### Failure Information (for bugs)

Verification failed: call 1 of 1: OrderApiService(#4).getOrderCancelReasonList(any())) was not called
java.lang.AssertionError

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. just run and its there.

#### Context

We are using mockk for project unit testing , this bug is for api call for our backend which is MVVM pattern project and is running fine on android devices but unit test are not working correct.

* MockK version: 1.12.1
* OS: Android 10 but i am running unit tests no need for device
* Kotlin version: 1.5.20
* JDK version: 11.0.10
* JUnit version: 4.13.2
* Type of test: unit test 

#### Failure Logs

Verification failed: call 1 of 1: OrderApiService(#4).getOrderCancelReasonList(any())) was not called
java.lang.AssertionError

#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
iVerification failed: call 1 of 1: OrderApiService(#4).getOrderCancelReasonList(any())) was not called
java.lang.AssertionError: Verification failed: call 1 of 1: OrderApiService(#4).getOrderCancelReasonList(any())) was not called
	at io.mockk.impl.recording.states.VerifyingState.failIfNotPassed(VerifyingState.kt:66)
	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:42)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:64)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalCoVerify(API.kt:143)
	at io.mockk.MockKKt.coVerify(MockK.kt:175)
	at io.mockk.MockKKt.coVerify$default(MockK.kt:172)
	at com.teo.mocktestapplication.OrderViewModelTest.api failed case 400(OrderViewModelTest.kt:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at com.teo.mocktestapplication.CoroutinesTestRule$apply$1.evaluate(CoroutinesTestRule.kt:22)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:121)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:834)
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    testImplementation "io.mockk:mockk:1.12.1"
    testImplementation 'junit:junit:4.13.2'
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
package com.teo.mocktestapplication

import io.mockk.coEvery
import io.mockk.coVerify
import io.mockk.impl.annotations.InjectMockKs
import io.mockk.impl.annotations.RelaxedMockK
import io.mockk.mockk
import io.mockk.spyk
import kotlinx.coroutines.ExperimentalCoroutinesApi
import org.amshove.kluent.shouldBeNull
import org.junit.Test
import retrofit2.Response

@ExperimentalCoroutinesApi
class OrderViewModelTest : BaseUnitTest() {


    @InjectMockKs
    lateinit var viewModel: OrderViewModel

    @Test
    fun `api failed case 400`() {

            viewModel = spyk(viewModel)

            val orderApiService = mockk<OrderApiService>(relaxed = true)

            coEvery {
                orderApiService.getOrderCancelReasonList()
            } returns successResponse

            viewModel.getOrderCancellationReasons()

            coVerify(exactly = 1) {
                orderApiService.getOrderCancelReasonList()
            }
    }

}
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by Raibaz** [comment]
I think the reason why this is happening is that your `OrderApiService` mock is being created after `@InjectMocks` is called.

Can you please try defining your `OrderApiService` with an annotation, i.e.:

```
@ExperimentalCoroutinesApi
class OrderViewModelTest : BaseUnitTest() {

    @RelaxedMockK
    lateinit var orderApiService: OrderApiService

    @InjectMockKs
    lateinit var viewModel: OrderViewModel

    @Test
    fun `api failed case 400`() {

            viewModel = spyk(viewModel)

            coEvery {
                orderApiService.getOrderCancelReasonList()
            } returns successResponse

            viewModel.getOrderCancellationReasons()

            coVerify(exactly = 1) {
                orderApiService.getOrderCancelReasonList()
            }
    }

}
```

**Comment by fobidlim** [comment]
I've resolved issue with `runTest { }`
```kotlin
@Test
fun `api failed case 400`() {

    viewModel = spyk(viewModel)

    val orderApiService = mockk<OrderApiService>(relaxed = true)

    coEvery {
        orderApiService.getOrderCancelReasonList()
    } returns successResponse

    // it is important to use coVerify
    runTest {
        viewModel.getOrderCancellationReasons()
    }

    coVerify(exactly = 1) {
        orderApiService.getOrderCancelReasonList()
    }
}
```
