### ISSUE TITLE
Regression: capturing subtypes in verify block fails in v1.12.1

### ISSUE THREAD

**Issue by m-burst** [mockk/mockk#774]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

The code below works correctly in v1.9.3, capturing the single call argument with type `Impl2` into the slot.

### Current Behavior

After upgrading from v1.9.3 to v1.12.1, the code started throwing an exception with the stack trace below.
If I try to capture in a `mutableListOf<Impl2>()`, the verification succeeds, but the resulting list contains 2 elements: one of type Impl1 and one of type Impl2.

#### Steps to Reproduce

* Mock a method that can receive arguments of different types
* Verify that the call with one specific type happened only once, and capture the argument in a slot

See code below

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.12.1
* OS: macOS 
* Kotlin version: 1.6.10
* JDK version: 11
* JUnit version: 5.8.2
* Type of test: unit test

#### Stack trace

```
Service(#1).method(slotCapture<Impl2>())) execution is being verified more than once and its arguments are being captured with a slot.
This will store only the argument of the last invocation in the slot.
If you want to store all the arguments, use a mutableList to capture arguments.
io.mockk.MockKException: Service(#1).method(slotCapture<Impl2>())) execution is being verified more than once and its arguments are being captured with a slot.
This will store only the argument of the last invocation in the slot.
If you want to store all the arguments, use a mutableList to capture arguments.
	at app//io.mockk.impl.verify.UnorderedCallVerifier.matchCall(UnorderedCallVerifier.kt:62)
	at app//io.mockk.impl.verify.UnorderedCallVerifier.verify(UnorderedCallVerifier.kt:38)
	at app//io.mockk.impl.recording.states.VerifyingState$recordingDone$outcome$1.invoke(VerifyingState.kt:31)
	at app//io.mockk.impl.recording.states.VerifyingState$recordingDone$outcome$1.invoke(VerifyingState.kt:11)
	at app//io.mockk.impl.recording.CommonCallRecorder.safeExec(CommonCallRecorder.kt:72)
	at app//io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:30)
	at app//io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at app//io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:64)
	at app//io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
	at app//io.mockk.MockKDsl.internalVerify(API.kt:118)
	at app//io.mockk.MockKKt.verify(MockK.kt:149)
	at app//io.mockk.MockKKt.verify$default(MockK.kt:146)
	at app//MockkBugTest.test(MockkBugTest.kt:33)
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    testImplementation("io.mockk:mockk:1.12.1")
    testImplementation("org.junit.jupiter:junit-jupiter:5.8.2")
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
import io.mockk.every
import io.mockk.just
import io.mockk.mockk
import io.mockk.runs
import io.mockk.slot
import io.mockk.verify
import org.junit.jupiter.api.Test

interface Interface

class Impl1 : Interface

class Impl2 : Interface

interface Service {
    fun method(obj: Interface)
}

class MockkBugTest {

    @Test
    fun test() {
        val service = mockk<Service> {
            every { method(any()) } just runs
        }

        service.method(Impl1())
        service.method(Impl2())
        
        verify(exactly = 1) { service.method(ofType<Impl2>()) } // works OK

        val slot = slot<Impl2>()
        verify(exactly = 1) { service.method(capture(slot)) } // throws
    }
}
```

**Comment by m-burst** [comment]
This is still an issue as far as I can tell, not `stale`.

**Comment by m-burst** [comment]
This is still an issue in v1.12.4, not `stale`.
