### ISSUE TITLE
Cannot call a function with default argument value delegated to a dependency

### ISSUE THREAD

**Issue by angryziber** [mockk/mockk#784]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

You can mock/call/verify such functions.
The default parameter code should be an implementation detail that is not called on the mock.

Maybe mockk should create the default value as mockk itself.
Or maybe fields should be initialized with mocks by default.

Sample code:

```kotlin
class OfferService(private val decisionRepository: DecisionRepository) {
  fun prepareOffer(decision: Decision? = decisionRepository.latestByApplication(app.id)): Offer {
     ...
  }
}

fun test() {
  val offerService = mockk<OfferService>()

  // this crashes with NPE (logical, but could be better)
  every { offerService.prepareOffer() } returns offer

  // this doesn't crash
  every { offerService.prepareOffer(any()) } returns offer

  // now the call of the mock, again produces NPE
  offerService.prepareOffer()
}
```

### Current Behavior

NPE (decisionRepository is null)

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.12.2
* OS: Linux
* Kotlin version: 1.6.10
* JDK version: 17
* JUnit version: 5.8.1
* Type of test: unit test

#### Stack trace

```
Cannot invoke "decisions.DecisionRepository.latestByApplication(java.util.UUID)" because "<parameter1>.decisionRepository" is null
java.lang.NullPointerException: Cannot invoke "decisions.DecisionRepository.latestByApplication(java.util.UUID)" because "<parameter1>.decisionRepository" is null
	at offers.OfferService.prepareOffer$default(OfferService.kt:16)
	at decisions.DecisionsRoutes.defaultOffer(DecisionsRoutes.kt:44)
```

**Comment by Raibaz** [comment]
I think the best workaround here would be to mock the `DecisionRepository` rather than the `OfferService` and provide a mocked behavior for `latestByApplication`.

**Comment by easimon** [comment]
Not an actual solution, but another workaround: instead of using default arguments, implement the telescoping methods explicitly. These work as expected and can then be mocked individually.

```kotlin
class OfferService(private val decisionRepository: DecisionRepository) {
  fun prepareOffer(decision: Decision?): Offer {
     ...
  }
  fun prepareOffer() = prepareOffer(decisionRepository.latestByApplication(app.id)
}
```
