### ISSUE TITLE
io.mockk.MockKException: can't find stub Disposable(temporary mock)

### ISSUE THREAD

**Issue by periva101** [mockk/mockk#786]
### Expected Behavior

test pass
### Current Behavior

io.mockk.MockKException: can't find stub Disposable(temporary mock)

### Failure Information (for bugs)

io.mockk.MockKException: can't find stub Disposable(temporary mock)
	at app//io.mockk.impl.stub.StubRepository.stubFor(StubRepository.kt:16)
	at app//io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:13)
	at app//io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)
	at app//io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:266)
	at app//io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:23)
	at app//io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:21)
	at app//io.mockk.proxy.jvm.advice.BaseAdvice.handle(BaseAdvice.kt:42)
	at app//io.mockk.proxy.jvm.advice.jvm.JvmMockKProxyInterceptor.intercept(JvmMockKProxyInterceptor.java:31)
	at app//io.reactivex.disposables.Disposable$Subclass2.equals(Unknown Source)
	at app//io.reactivex.internal.util.OpenHashSet.add(OpenHashSet.java:64)
	at app//io.reactivex.disposables.CompositeDisposable.add(CompositeDisposable.java:108)
	at app//com.benoholding.beno.app.extensions.RxExtensionsKt.plusAssign(RxExtensions.kt:7)
	at app//com.benoholding.beno.presentation.ui.features.more.account.accountInfo.AccountInfoViewModel.getAccountInfo(AccountInfoViewModel.kt:95)
	at app//com.benoholding.beno.presentation.ui.features.more.account.AccountInfoViewModelTest.given  init state , when getAccountInfoUseCase success , then active state should be emit(AccountInfoViewModelTest.kt:61)
	at java.base@11.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.11/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.11/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at app//org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at app//org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at app//org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at app//org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at app//org.koin.test.mock.MockProviderRule$apply$1.evaluate(MockProviderRule.kt:28)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at app//org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at app//org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at app//org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base@11.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.11/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.11/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version:1.12.0
* OS:windows
* Kotlin version:1.6
* JDK version:1.8
* JUnit version:
* Type of test: unit test 

}

the function impletation
     disposable.add( getSavedLocationUseCase.execute())

**Comment by Raibaz** [comment]
Please provide at least the test function, otherwise there is no way to determine what's going wrong here.

**Comment by periva101** [comment]
@Test
    fun `given  init state , when SaveAccountInfoUseCase fail , then SubmissionError state should be emit`() {
        // arrange
        val accountInfo = fakePresentationAccountInfo()
        saveAccountInfoUseCaseReturnFail()
        // act
        subject.saveAccountInfo()
        // assert
        val submissionError = AccountUiState.SubmissionError(accountInfo, "error")

        Truth.assertThat(subject.uiUiState.value)
            .isInstanceOf(AccountUiState.SubmissionError::class.java)
    }
    
    the the code is
       fun saveAccountInfo() {
        val accountInfo = _uiState.value.accountInfo
        disposable += saveAccountInfoDataUseCase.execute(
            accountInfo.fromPresentationToDomain()
        )

**Comment by periva101** [comment]
@Raibaz

**Comment by enzobelli** [comment]
I have the same issue when using `disposable +=`. Please note that the test is flaky, sometimes it passes, sometimes it fails with the exception `io.mockk.MockKException: can't find stub Disposable(temporary mock)`

Context
Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

MockK version: 1.12.2
OS: MacOS
Kotlin version: 1.5.31
JDK version: 1.8
JUnit version:
Type of test: unit test

**Comment by periva101** [comment]
@Raibaz

**Comment by adamfils** [comment]
In the before test function mock the Disposable constructor.
This should get rid of the error.

@Before
fun setUp() {
   mockkConstructor(Disposable::class)
}

**Comment by blazmag** [comment]
Tried above, but unfotrunately it doesn't seem to do the trick, we're still getting the flaky error. Our setUp looks like:

```
@Before
    fun setUp() {
        MockKAnnotations.init(this, relaxUnitFun = true, relaxed = true)
        mockkConstructor(Disposable::class)
        //viewModel construction here
    }
```

**Comment by shivamrathore-toast** [comment]
Seeing similar exceptions when using an `object class` that is pulled from a dependency. Again, the issue happens at times, doesn't happen at other times.
But we are not mocking the object class anywhere (and don't want to since it's only doing validations) so I'm not sure why we get this.

**Comment by swati-bajaj** [comment]
I am facing similar issues with my tests. The tests are flaky. Sometimes they pass, other times they fail. Below is the log:
Caused by:
              io.mockk.MockKException: can't find stub Recaptcha(object Recaptcha)
                  at app//io.mockk.impl.stub.StubRepository.stubFor(StubRepository.kt:16)
                  at app//io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:13)
                  at app//io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)
                  at app//io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:270)
                  at app//io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:24)
                  at app//io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:21)
                  at app//com.google.android.recaptcha.Recaptcha.getClient-BWLJW6A(Unknown Source)
                  at app//com.shutterfly.android.commons.usersession.recaptcha.RecaptchaClientManager$initializeRecaptchaClient$1.invokeSuspend(RecaptchaClientManager.kt:36)
                  at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                  at app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                  at app//kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
                  at app//kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
                  at app//kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
                  at app//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
                  at app//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
                  at app//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)

**Comment by AtlassianDinesh** [comment]
Is there any way to solve this problem. I'm also facing same problem
