### ISSUE TITLE
io.mockk.MockKException: no answer found for: CoroutineDispatcher(child of static Dispatchers#1).plus(CoroutineId(3))

### ISSUE THREAD

**Issue by JunfengGuo** [mockk/mockk#790]
### Expected Behavior
no exceptions

### Current Behavior
io.mockk.MockKException: no answer found for: CoroutineDispatcher(child of static Dispatchers#1).plus(CoroutineId(3))

when i use 
```
coEvery { ... } returns ...
```
after
```
mockkStatic(Dispatchers::class)
every { Dispatchers.Default } answers { TestCoroutineDispatcher() }
```

### Failure Infoemation(for bugs)
```
no answer found for: CoroutineDispatcher(child of static Dispatchers#1).plus(CoroutineId(3))
io.mockk.MockKException: no answer found for: CoroutineDispatcher(child of static Dispatchers#1).plus(CoroutineId(3))
	at io.mockk.impl.stub.MockKStub.defaultAnswer(MockKStub.kt:93)
	at io.mockk.impl.stub.MockKStub.answer(MockKStub.kt:42)
	at io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:16)
	at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)
	at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:266)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:23)
	at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:21)
	at io.mockk.proxy.jvm.advice.BaseAdvice.handle(BaseAdvice.kt:42)
	at io.mockk.proxy.jvm.advice.jvm.JvmMockKProxyInterceptor.intercept(JvmMockKProxyInterceptor.java:31)
	at kotlinx.coroutines.CoroutineDispatcher$Subclass0.plus(Unknown Source)
	at kotlinx.coroutines.CoroutineContextKt.newCoroutineContext(CoroutineContext.kt:34)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at cn.hualala.unittestdemo.mockk.advance.RegisterSystem.tryRegister(RegisterSystem.kt:21)
	at cn.hualala.unittestdemo.mockk.advance.CoroutineDispatcherUnitTest.tryRegister_mockDefault_registerSuccess(CoroutineDispatcherUnitTest.kt:46)
```

### Context
- MockK version:1.12.0
- OS:windows
- Kotlin version:1.5.21
- Kotlin coroutines version:1.5.2
- JDK version:1.8
- JUnit version:
- Type of test: unit test

### Code
```
@DelicateCoroutinesApi
class RegisterSystem {

	var registerSuccess = false

	fun tryRegister(
		dispatcher: CoroutineDispatcher
	) {
		GlobalScope.launch(dispatcher) {
			println("registered = true")
			registerSuccess = true
		}
	}
}
```

### UnitTest Code
```
@ExperimentalCoroutinesApi
@DelicateCoroutinesApi
class CoroutineDispatcherUnitTest {
	@Before
	fun setup() {
		MockKAnnotations.init(this, relaxUnitFun = true)
	}

	@After
	fun teardown() {
		unmockkAll()
	}

	@Test
	fun tryRegister_mockDefault_registerSuccess() {
		// Arrange
		mockkStatic(Dispatchers::class)
		every { Dispatchers.Default } answers { TestCoroutineDispatcher() }

		val registerSystemV4Mock = mockk<RegisterSystem>()
		coEvery { registerSystemV4Mock.tryRegister(any()) } returns Unit

		val registerSystem = RegisterSystem()

		// Act
		registerSystem.tryRegister(Dispatchers.Default)

		// Assert
		Assert.assertTrue(registerSystem.registerSuccess)
	}
}
```

### Extra info

1. Mock Dispatchers.IO can work.
```
mockkStatic(Dispatchers::class)
every { Dispatchers.IO } answers { TestCoroutineDispatcher() }
coEvery { ... } returns ...
```
2. Use every{} instead of coEvery{} after mock Dispatcher.default, it can work.
```
mockkStatic(Dispatchers::class)
every { Dispatchers.Default } answers { TestCoroutineDispatcher() }
every { ... } returns ...
```
3. Use mock Dispatcher.Default after coEvery{}, it can work.
```
coEvery { ... } returns ...
mockkStatic(Dispatchers::class)
every { Dispatchers.Default } answers { TestCoroutineDispatcher() }
```

**Comment by aiueoH** [comment]
same problem +1

don't want to use DispatchersProvider of proxy, so i'm trying mock Dispatchers

**Comment by DjakaTechnology** [comment]
I found a work-around, I havent checked the internal code of the co every but I suspect there's a code that do something like
`Dispatchers.Default + Something` so it breaks the mock.

Try to add this after mocking Dispatchers.Default
` every { Dispatchers.Default.fold<Any>(any(), any()) } returns testDispatcher`

Example:


```
        val testDispatcher = UnconfinedTestDispatcher()
        Dispatchers.setMain(testDispatcher)
        
        mockkStatic(Dispatchers::class)
        every { Dispatchers.IO } returns testDispatcher
        every { Dispatchers.IO.fold<Any>(any(), any()) } returns testDispatcher
        every { Dispatchers.Default } returns testDispatcher
        every { Dispatchers.Default.fold<Any>(any(), any()) } returns testDispatcher
        
        val test = mockk<Test>()

        coEvery { test.suspendTest() } returns "test"
        println("Test equal to " + runBlocking { test.suspendTest() })
```
