### ISSUE TITLE
Upgrade to 1.12.3 leads to 'Failed matching mocking signature for'

### ISSUE THREAD

**Issue by knyttl** [mockk/mockk#793]
### Expected Behavior

Since upgrade from 1.12.2 to 1.12.3 we are getting `Failed matching mocking signature for` errors on:

```
every { spyEm.after(any()) } answers { firstArg<() -> Any>().invoke() }
                    ^^^^^
```

Where after method is defined as:

```
    open fun after(body: () -> Any) {
        TransactionSynchronizationManager.registerSynchronization(
            object : TransactionSynchronizationAdapter() {
                override fun afterCommit() {
                    body()
                }
            }
        )
    }

```

### Current Behavior

Method cannot be mocked:

```
io.mockk.MockKException: Failed matching mocking signature for

left matchers: [any()]

	at io.mockk.impl.recording.SignatureMatcherDetector.detect(SignatureMatcherDetector.kt:99)
	at io.mockk.impl.recording.states.RecordingState.signMatchers(RecordingState.kt:39)
	at io.mockk.impl.recording.states.RecordingState.round(RecordingState.kt:31)
	at io.mockk.impl.recording.CommonCallRecorder.round(CommonCallRecorder.kt:50)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:63)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalEvery(API.kt:93)
	at io.mockk.MockKKt.every(MockK.kt:98)
```

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.12.3
* OS: Linux + Mac
* Kotlin version: 1.6.10
* JDK version: 17
* Type of test: unit test

**Comment by knyttl** [comment]
This is caused by springmockk.
