### ISSUE TITLE
mockk can't coVerify when a delay is used inside a Kotlin Coroutine

### ISSUE THREAD

**Issue by gerardoepitacio** [mockk/mockk#810]
### Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

Be able to use `coVerify`

### Current Behavior

`coVerify`  can't be used.

#### Steps to Reproduce

1. create a mock with `mockk()` from a tes double scenario
2. call a method in a ViewModel which launch a new coroutine and inside uses a `delay`.
3. after de `delay` call, call a method(it can be a method with suspend or not) from the injected test double created with `mockk()`

#### Context

* MockK version: 1.12.3
* OS: MacOS Big Sur 11.6.2
* Kotlin version: 1.6.10
* JDK version: 11.0.11
* JUnit version: 4.13.2
* Type of test: unit test
* 
#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------

Verification failed: call 1 of 1: InterfaceTest(#3).method()) was not called
java.lang.AssertionError: Verification failed: call 1 of 1: InterfaceTest(#3).method()) was not called
	at io.mockk.impl.recording.states.VerifyingState.failIfNotPassed(VerifyingState.kt:66)
	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:42)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:64)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalCoVerify(API.kt:143)
	at io.mockk.MockKKt.coVerify(MockK.kt:175)
	at io.mockk.MockKKt.coVerify$default(MockK.kt:172)
	at com.example.mockkdelayissue.ViewModelTestTest.initialize(ViewModelTestTest.kt:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)


// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS build.gradle(project)] -----------------------

plugins {
    id 'com.android.application' version '7.1.2' apply false
    id 'com.android.library' version '7.1.2' apply false
    id 'org.jetbrains.kotlin.android' version '1.6.10' apply false
}

// -----------------------[ GRADLE DEFINITIONS build.gradle(app)] -----------------------
plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    compileSdk 31

    defaultConfig {
        applicationId "com.example.mockkdelayissue"
        minSdk 21
        targetSdk 31
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {

    implementation 'androidx.core:core-ktx:1.7.0'
    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'com.google.android.material:material:1.5.0'

    // kotlin coroutines
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.2"
    implementation "androidx.lifecycle:lifecycle-viewmodel-compose:2.4.0"

    testImplementation "io.mockk:mockk:1.12.0"
    testImplementation "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.4.2"

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
package com.example.mockkdelayissue

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch


interface InterfaceTest {

    suspend fun method()
}

class ViewModelTest(
    private val interfaceTest: InterfaceTest,
    private val dispatcher: CoroutineDispatcher = Dispatchers.IO
    ): ViewModel() {

    companion object {

        const val DELAY_TIME = 1000L
    }

    fun initializeFailed() {

        this.viewModelScope.launch(this.dispatcher) {

            delay(DELAY_TIME)

            interfaceTest.method()
        }
    }

    fun initializeSuccess() {

        this.viewModelScope.launch(this.dispatcher) {

            interfaceTest.method()
        }
    }
}

TESTS
package com.example.mockkdelayissue

import io.mockk.coVerify
import io.mockk.mockk
import kotlinx.coroutines.test.TestCoroutineDispatcher
import org.junit.Test

class ViewModelTestTest {

    @Test
    fun initialize() {

        val dispatcher = TestCoroutineDispatcher()

        val mockk: InterfaceTest = mockk()

        val viewModel = ViewModelTest(mockk, dispatcher)

        viewModel.initializeFailed()

        // ERROR - failed to verify
        coVerify {

            mockk.method()
        }
    }

    @Test
    fun initializeSuccess() {

        val dispatcher = TestCoroutineDispatcher()

        val mockk: InterfaceTest = mockk()

        val viewModel = ViewModelTest(mockk, dispatcher)

        viewModel.initializeSuccess()

        // SUCCESS - verified
        coVerify {

            mockk.method()
        }
    }
}

// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

Minimal reproducible Android project here.
https://github.com/gerardoepitacio/mockk-issue

**Comment by Raibaz** [comment]
I see two potential workarounds here:

1) set the `timeout` parameter to `coVerify` to make sure the verification does not expire while the delay is running.
2) use `runBlockingTest` in your test to make sure delays are skipped.

Does this make sense to you?

**Comment by gerardoepitacio** [comment]
I have updated my tests in the following variants, and still failing.

<img width="387" alt="image" src="https://user-images.githubusercontent.com/6610535/161765123-b5bc709a-6e92-4406-afe8-015d8482822b.png">


```

class ViewModelTestTest {

    val dispatcher = TestCoroutineDispatcher()

    @Test
    fun initializeFail01() {

        val mockk: InterfaceTest = mockk()

        val viewModel = ViewModelTest(mockk, this.dispatcher)

        viewModel.initializeFailed()

        // ERROR - failed to verify
        coVerify {

            mockk.method()
        }
    }

    @Test
    fun initializeFail02() = this.dispatcher.runBlockingTest {

        val mockk: InterfaceTest = mockk()

        val viewModel = ViewModelTest(mockk, dispatcher)

        viewModel.initializeFailed()

        // ERROR - failed to verify
        coVerify {

            mockk.method()
        }
    }

    @Test
    fun initializeFail03() = runBlockingTest {

        val mockk: InterfaceTest = mockk()

        val viewModel = ViewModelTest(mockk, dispatcher)

        viewModel.initializeFailed()

        // ERROR - failed to verify
        coVerify {

            mockk.method()
        }
    }

    @Test
    fun initializeFail04() {

        val mockk: InterfaceTest = mockk()

        val viewModel = ViewModelTest(mockk, dispatcher)

        viewModel.initializeFailed()

        // ERROR - failed to verify
        coVerify(timeout = DELAY_TIME*2) {

            mockk.method()
        }
    }

    @Test
    fun initializeSuccess() {

        val dispatcher = TestCoroutineDispatcher()

        val mockk: InterfaceTest = mockk()

        val viewModel = ViewModelTest(mockk, dispatcher)

        viewModel.initializeSuccess()

        // SUCCESS - verified
        coVerify {

            mockk.method()
        }
    }
}
```

**Comment by Raibaz** [comment]
Yep, this makes sense: according to the [doc](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-test/kotlinx.coroutines.test/-test-coroutine-dispatcher/index.html) of the (now-deprecated) `TestCoroutinesDispatcher`.

> If they were scheduled with a delay, the virtual clock-time must be advanced via one of the methods on the dispatcher's [scheduler](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-test/kotlinx.coroutines.test/-test-coroutine-dispatcher/scheduler.html).

This means that to have your delay pass you need to manually advance the clock; I missed this detail earlier.

To do so, you can call `advanceUntilIdle()` on your `dispatcher`:

```
@Test
    fun initialize() {

        val dispatcher = TestCoroutineDispatcher()

        val mockk: InterfaceTest = mockk()

        val viewModel = ViewModelTest(mockk, dispatcher)

        viewModel.initializeFailed()
        dispatcher.advanceUntilIdle() // Notice this

        // This now passses
        coVerify {
            mockk.method()
        }
    }
```

Also note that `TestCoroutineDispatcher` and `advanceUntilIdle()` have been deprecated: take a look at the [migration guide](https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-test/MIGRATION.md) to see how to replace them.
