### ISSUE TITLE
Duplicate class io.mockk.ValueClassSupportKt 

### ISSUE THREAD

**Issue by dgaillard2** [mockk/mockk#828]
- I am running the latest version
- I checked the documentation and found no answer
- I checked to make sure that this issue has not already been filed

### Expected Behavior

Trying to launch android instrumented test with my android compose project using cucumber + mockk

### Current Behavior

When launching my test, i got this error stacktrace :

```
Execution failed for task ':app:checkDebugAndroidTestDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class io.mockk.ValueClassSupportKt found in modules jetified-mockk-agent-android-1.12.4-runtime (io.mockk:mockk-agent-android:1.12.4) and jetified-mockk-agent-jvm-1.12.4 (io.mockk:mockk-agent-jvm:1.12.4)
     
     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.
```

#### Steps to Reproduce

Add in build.gradle.kts (or build.gradle equivalent)

```
    androidTestImplementation("io.mockk:mockk-android:1.12.4")
    androidTestImplementation("io.mockk:mockk-agent-jvm:1.12.4")
```
    
Launch Android Instrumented Test
    
#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.12.4
* OS: Android
* Kotlin version: 1.6.21
* JDK version: 11
* Type of test: Android instrumented test

#### Stack trace

```
Execution failed for task ':app:checkDebugAndroidTestDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class io.mockk.ValueClassSupportKt found in modules jetified-mockk-agent-android-1.12.4-runtime (io.mockk:mockk-agent-android:1.12.4) and jetified-mockk-agent-jvm-1.12.4 (io.mockk:mockk-agent-jvm:1.12.4)
     
     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.
```

I have found this topic who was talking about : https://github.com/mockk/mockk/issues/722

But the solution was to remove mockk-agent-jvm (by excluding or not)
If i exclude (or remove it), i get this error : 

```
Caused by: io.mockk.proxy.MockKAgentException: MockK could not self-attach a jvmti agent to the current VM. This feature is required for inline mocking.
This error occured due to an I/O error during the creation of this agent: java.io.IOException: Unable to dlopen libmockkjvmtiagent.so: dlopen failed: library "libmockkjvmtiagent.so" not found

Potentially, the current VM does not support the jvmti API correctly
at io.mockk.proxy.android.AndroidMockKAgentFactory.init(AndroidMockKAgentFactory.kt:67)
at io.mockk.impl.JvmMockKGateway.<init>(JvmMockKGateway.kt:46)
at io.mockk.impl.JvmMockKGateway.<clinit>(JvmMockKGateway.kt:186)
... 42 more
Caused by: java.io.IOException: Unable to dlopen libmockkjvmtiagent.so: dlopen failed: library "libmockkjvmtiagent.so" not found
at dalvik.system.VMDebug.nativeAttachAgent(Native Method)
at dalvik.system.VMDebug.attachAgent(VMDebug.java:572)
at android.os.Debug.attachJvmtiAgent(Debug.java:2563)
```

**Comment by jknair0** [comment]
I think it was supposed to be 
```kotlin
androidTestImplementation("io.mockk:mockk-agent-android:1.12.4")
```
instead of 
```kotlin
androidTestImplementation("io.mockk:mockk-agent-jvm:1.12.4")
```
for instrumented tests.

**Comment by jknair0** [comment]
Was able to reproduce the issue.  You might not need to add
```kotlin
  androidTestImplementation("io.mockk:mockk-agent-jvm:1.12.4")
```
The dependency to `mockk-android` itself comes with `agent-android` AFAIK.

Also if you face any issue relating to jvmti after changes. do check this comment https://github.com/mockk/mockk/issues/297#issuecomment-1139481833

I think something has creeped into version 1.12.4.

**Comment by jknair0** [comment]
> Hi, I tried the same solution from @jknair0 to remove the `androidTestImplementation "io.mockk:mockk-android:$mockk_version"` now the instrumentation tests run, thanks for that! but the tests I have use Mocck lib function `every` and now the import doesn't work ` import io.mocck.every` . How can I import functions from Mocck now? is there a way to do some valid import now that it comes from `agent-android` ?

Weird! I am able to import `io.mocck.every` and able to mock. Are we talking about androidTest src ? Here is a repo where i tried to test this.

https://github.com/jknair0/SampleMockkReproduce/blob/7f899f9b00ce7b3576ffc75ef80860aae551ffc4/app/src/androidTest/java/tech/jknair/samplemockkreproduce/ExampleInstrumentedTest.kt#L1

**Comment by sarn0ld** [comment]
Using just this single dependency works fine: 
`androidTestImplementation("io.mockk:mockk-android:1.12.3")`

**Comment by dgaillard2** [comment]
Solved it with 
`
testOptions {
        packagingOptions {
            jniLibs {
                useLegacyPackaging = true
            }
        }
    }
`
With only : 
`
androidTestImplementation("io.mockk:mockk-android:1.12.4")
`

And of course : 
`
        testInstrumentationRunner = "io.cucumber.android.runner.CucumberAndroidJUnitRunner"
        `
