### ISSUE TITLE
MockK fails to stub generic interface with methods with close signatures

### ISSUE THREAD

**Issue by dzharikhin** [mockk/mockk#846]
### Expected Behavior

Mocking should work ok for such configuration

### Current Behavior
io.mockk.MockKException: Class cast exception happened.

### Failure Information (for bugs)
The minimal example is in https://github.com/dzharikhin/mockk-issue
It seems the proxy implements only last method (if switch order methods positions - target type of ClassCastException also changes), so maybe bytebuddy is related itself
Also, the issue may be related to https://github.com/mockk/mockk/issues/321 but I'm not sure

#### Steps to Reproduce

Launch test in https://github.com/dzharikhin/mockk-issue

#### Context

* MockK version: 1.12.4
* OS: macos 12.2.1
* Kotlin version: 1.7.10
* JDK version: OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode)
* JUnit version: 5.6.0
* Type of test: unit test

#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
io.mockk.MockKException: Class cast exception happened.
Probably type information was erased.
In this case use `hint` before call to specify exact return type of a method.

	at app//io.mockk.impl.InternalPlatform.prettifyRecordingException(InternalPlatform.kt:74)
	at app//io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:66)
	at app//io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at app//io.mockk.MockKDsl.internalEvery(API.kt:93)
	at app//io.mockk.MockKKt.every(MockK.kt:98)
	at app//MockIssueTest.test(MockIssueTest.kt:11)
...
Caused by: java.lang.ClassCastException: class ResultContainerOne cannot be cast to class ResultContainerTwo (ResultContainerOne and ResultContainerTwo are in unnamed module of loader 'app')
	at Executor$Subclass0.process(Unknown Source)
	at Executor$Subclass0.process(Unknown Source)
	at MockIssueTest$test$1.invoke(MockIssueTest.kt:12)
	at MockIssueTest$test$1.invoke(MockIssueTest.kt:11)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:25)
	at io.mockk.impl.eval.RecordedBlockEvaluator$enhanceWithRethrow$1.invoke(RecordedBlockEvaluator.kt:78)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:40)
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

**Comment by dzharikhin** [comment]
I investigated and the issue is really in bytebuddy.
By default it uses `MethodGraph.Compiler.DEFAULT = MethodGraph.Compiler.Default.forJavaHierarchy()`
In java 
```java
interface Executor {
    <Result> ResultContainerOne<Result> process(Request<ResultContainerOne<Result>> request);
    <Result> ResultContainerTwo<Result> process(Request<ResultContainerTwo<Result>> request);
}
```
is invalid because both methods have same name and argument types. So bytebuddy merges two methods.
But nevertheless it is valid in kotlin, so it seems in mockk we need to use Default.forJVMHierarchy() which adds return type to method signature and will distinct methods
