### ISSUE TITLE
Support Spying and Mocking HashMaps on JDK 16+

### ISSUE THREAD

**Issue by aSemy** [mockk/mockk#864]
The tests in `HashMapMockTest.kt` fail on more recent (16+) JDK versions.

https://github.com/mockk/mockk/blob/02a6d4546d79da9d362b61376dae64ff656de7b1/mockk/jvm/src/test/kotlin/io/mockk/jvm/HashMapMockTest.kt#L36-L43

https://github.com/mockk/mockk/runs/7519107510?check_suite_focus=true#step:7:393

```none
HashMapMockTest > concurrentHashMap_shouldBeSpied_Successfully() FAILED
    java.lang.IllegalAccessException: class io.mockk.impl.InternalPlatform cannot access a member of class java.util.concurrent.ConcurrentHashMap (in module java.base) with modifiers "transient volatile"
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:[392])
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
        at java.base/java.lang.reflect.Field.checkAccess(Field.java:1102)
        at java.base/java.lang.reflect.Field.get(Field.java:423)
        at io.mockk.impl.InternalPlatform.copyFields$copy(InternalPlatform.kt:114)
        at io.mockk.impl.InternalPlatform.copyFields(InternalPlatform.kt:121)
        at io.mockk.impl.instantiation.AbstractMockFactory.spyk(AbstractMockFactory.kt:107)
        at io.mockk.jvm.HashMapMockTest.concurrentHashMap_shouldBeSpied_Successfully(HashMapMockTest.kt:126)
```

This was discovered in https://github.com/mockk/mockk/pull/444#discussion_r523808327 and #829.

For now, so I can make progress on #863, I've disabled the tests on JDK16+. I'm making this issue to link in the source code.

**Comment by omerates760** [comment]
@aSemy Hi, The problem continues. Is there an update?
