### ISSUE TITLE
Mockk produces incorrect bytecode when running with coverage

### ISSUE THREAD

**Issue by zuevmaxim** [mockk/mockk#873]
Mockk fails to transform bytecode after Kover. [Original issue in Kover](https://github.com/Kotlin/kotlinx-kover/issues/88)

#### Minimal reproducible code

Please see [MockkReproducer.zip](https://github.com/mockk/mockk/files/9234161/MockkReproducer.zip)
In `build.gradle.kts` file, the Kover plugin is enabled, so all the tests are running with coverage.

### Failure Information (for bugs)

In Kover we have investigated the issue: we have analysed the bytecode of the problem class `okhttp3.Response` on the different stages of instrumentation. Please see the `data` folder in the attached project. The class files inside this folder were gained by stopping the program via debugger at this line: [InliningClassTransformer.kt#L91](https://github.com/mockk/mockk/blob/6ce0616e16e63a5430b7f2989b0e3f0de666dd5a/agent/jvm/src/main/kotlin/io/mockk/proxy/jvm/transformation/InliningClassTransformer.kt#L91)
Here we have printed `classfileBuffer`  content to  `before_mockk/Responce.class`, and `type.bytes`  to  `after_mockk/Responce.class`  with coverage enabled (in `coverage` subfolder) and coverage disabled (in `no_coverage` subfolder, please comment Kover pluggin in `build.gradle.kts` to disable coverage)
Then we have decompiled the class files to `bytecode.txt`  file in each of the cases via `javap -c -l -v Response.class`  command.

### Expected Behavior

Mockk runs successfully with [Kover plugin](https://github.com/Kotlin/kotlinx-kover) enabled

### Current Behavior

Classfile produced by mockk `data/coverage/after_mockk/Responce.class` fails the verification, while the classfile on all the other stages is correct.

The `return` statement after `kotlin/collections/CollectionsKt.emptyList:()Ljava/util/List; ` method call is transformed into a single `goto`  instruction, so the stack map is incorrect, as the `okhttp3/Headers`  element in unexpected on the stack. It is correct to replace `return`  with `astore, pop, aload, goto`  sequence

#### Steps to Reproduce

1. run `:test --tests "MockkCoverageTest.testMockingResponse"` task in the attached project
2. you will get a VerifyError

Alternatively, 
1. Running the `InliningClassTransformer#transform`  method with the contents of `coverage/before_mockk/Responce.class`  (**which contains correct bytecode**) as a `classfileBuffer`  parameter leads to the incorrect bytecode in the output, which can be found in the `coverage/after_mockk/Responce.class`  file

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.12.5
* OS: macOS 12.4
* Kotlin version: 1.7.10
* JDK version: 11
* JUnit version: 5.6
* Type of test: unit test

#### Stack trace

```
java.lang.VerifyError
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:167)
	at io.mockk.proxy.jvm.transformation.JvmInlineInstrumentation.retransform(JvmInlineInstrumentation.kt:28)
	at io.mockk.proxy.common.transformation.RetransformInlineInstrumentation$execute$1.invoke(RetransformInlineInstrumentation.kt:19)
	at io.mockk.proxy.common.transformation.RetransformInlineInstrumentation$execute$1.invoke(RetransformInlineInstrumentation.kt:16)
	at io.mockk.proxy.common.transformation.ClassTransformationSpecMap.applyTransformation(ClassTransformationSpecMap.kt:41)
	at io.mockk.proxy.common.transformation.RetransformInlineInstrumentation.execute(RetransformInlineInstrumentation.kt:16)
	at io.mockk.proxy.jvm.ProxyMaker.inline(ProxyMaker.kt:88)
	at io.mockk.proxy.jvm.ProxyMaker.proxy(ProxyMaker.kt:30)
	at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:34)
	at io.mockk.impl.instantiation.AbstractMockFactory.newProxy$default(AbstractMockFactory.kt:24)
	at io.mockk.impl.instantiation.AbstractMockFactory.mockk(AbstractMockFactory.kt:59)
	at MockkCoverageTest.testMockingResponse(MockkCoverageTest.kt:24)
```

Verification error when running `java okhttp3.Response` in the `data/coverage/after_mockk` directory
```
Error: Unable to initialize main class okhttp3.Response
Caused by: java.lang.VerifyError: Inconsistent stackmap frames at branch target 296
Exception Details:
  Location:
    okhttp3/Response.challenges()Ljava/util/List; @269: goto
  Reason:
    Current frame's stack size doesn't match stackmap.
  Current Frame:
    bci: @269
    flags: { }
    locals: { 'okhttp3/Response', 'java/util/concurrent/Callable', 'okhttp3/Response', '[I' }
    stack: { 'okhttp3/Headers', 'java/util/List' }
  Stackmap Frame:
    bci: @296
    flags: { }
    locals: { 'okhttp3/Response', 'java/util/concurrent/Callable' }
    stack: { 'java/util/List' }
  Bytecode:
    0000000: 2ab6 015a 1301 5ca6 0035 03bd 0004 be04
    0000010: a000 1303 bd00 0403 3213 015c a600 0701
    0000020: a700 4c03 bd00 04be 05a0 0013 03bd 0004
    0000030: 0432 1301 5ca6 0007 01a7 0033 1401 5d2a
    0000040: b801 634c 2bc6 000b 2b2a b601 679a 0007
    0000050: 01a7 001b 2b2a 1202 1301 a203 bd01 6ab6
    0000060: 016e 03bd 0004 b601 72a7 0003 4c2b c600
    0000070: 0701 a700 b62a 4d00 b200 6ac7 000b 126c
    0000080: b800 72b3 006a b200 6a4e 2d11 002b 5c2e
    0000090: 0460 4f2c b400 8a2d 1100 2c5c 2e04 604f
    00000a0: 2cb4 007a a700 272d 1100 2f5c 2e04 604f
    00000b0: a700 342d 1100 2e5c 2e04 604f a700 362d
    00000c0: 1100 2d5c 2e04 604f a700 39ab ffff fff4
    00000d0: 0000 0002 0000 0191 ffff ffdc 0000 0197
    00000e0: ffff ffe8 2d11 0030 5c2e 0460 4f12 ffa7
    00000f0: 0021 2d11 0031 5c2e 0460 4f13 0101 a700
    0000100: 122d 1100 325c 2e04 604f b801 06a7 001b
    0000110: 2d11 002c 5c2e 0460 4f2d 1100 2b5c 2e04
    0000120: 604f b801 0ca7 0003 4d2b c600 0d2b b901
    0000130: 7801 00c0 018d 4da7 0003 2cb0          
  Stackmap Table:
    same_frame(@35)
    same_frame(@60)
    append_frame(@80,Object[#352])
    same_frame(@84)
    full_frame(@108,{Object[#2]},{Object[#372]})
    append_frame(@117,Object[#372])
    append_frame(@119,Object[#2])
    same_frame(@134)
    full_frame(@167,{Object[#2],Object[#372],Object[#2],Object[#123]},{Object[#140]})
    same_locals_1_stack_item_frame(@179,Object[#140])
    same_locals_1_stack_item_frame(@191,Object[#140])
    full_frame(@203,{Object[#2],Object[#372],Object[#2],Object[#123]},{Object[#140],Integer})
    same_locals_1_stack_item_frame(@228,Object[#140])
    same_locals_1_stack_item_frame(@242,Object[#140])
    same_locals_1_stack_item_frame(@257,Object[#140])
    full_frame(@272,{Object[#2],Object[#372],Object[#2],Object[#123]},{Object[#140],Object[#151]})
    full_frame(@296,{Object[#2],Object[#372]},{Object[#397]})
    append_frame(@297,Object[#397])
    same_frame(@311)
    same_frame(@314)

```

**Comment by zuevmaxim** [comment]
Please put an important label
