### ISSUE TITLE
Is it possible to test or capture arguments in mocked constructor?

### ISSUE THREAD

**Issue by joy0520** [mockk/mockk#875]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

Capable of mocking a constructor and capturing its arguments, or some other means to test them.

### Current Behavior

Seems it cannot be done, or I just haven't found the correct way.

#### Steps to Reproduce

Here is a minimized example of a class that I want to test with.

```
/**
 * Should be mocked in a unit test.
 */
class AndroidData(val value: Float)

/**
 * Target class to be tested.
 */
class MyHelper() {
    fun createData(flag: Boolean): AndroidData {
        // simplified logic
        return if (flag) AndroidData(20f) else AndroidData(10f)
    }
}
```

I want to test that an `AndroidData` instance with the correct field `value` will be returned in each case. I tried 2 ways so these are my test cases:

```

class LargerThan15Matcher: Matcher<Float> {
    override fun match(arg: Float?): Boolean {
        return if (arg == null) false else arg >= 15f
    }
}

class MyHelperTest : TestCase() {
    @Test
    fun testCreateData1() {
        mockkConstructor(AndroidData::class)

        val helper = mockk<MyHelper>(relaxed = true)
        val createdData = helper.createData(true)

        println("createdData=$createdData")  // AndroidData(child of #1#2)
        println("createdData.value=${createdData.value}")  // 0.0

        // test if the argument in AndroidData's constructor was larger than 15
        assertTrue(createdData.value >= 15f)  // assertion failed
    }

    @Test
    fun testCreateData2() {
        mockkConstructor(AndroidData::class)
        // Missing mocked calls inside every { ... } block: make sure the object inside the block is a mock
        every {
            constructedWith<AndroidData>(LargerThan15Matcher())
        }

        val helper = mockk<MyHelper>(relaxed = true)
        val createdData = helper.createData(true)

        println("createdData=$createdData")  // AndroidData(child of #1#2)
        println("createdData.value=${createdData.value}")  // 0.0

        // test if the argument in AndroidData's constructor was larger than 15
        assertTrue(createdData.value >= 15f)
    }
}
```

Please be noted that the `AndroidData` would simulate an Android class that would be stubbed in a unit test. That is, I have to mock that class in a unit test, right?

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.12.5
* OS: Ubuntu 18.04 LTS
* Kotlin version: 1.6.0
* JDK version: 1.8
* JUnit version: JUnit 4
* Type of test: unit test

#### Stack trace

The second test case (testCreateData2) would produce this
```
Missing mocked calls inside every { ... } block: make sure the object inside the block is a mock
io.mockk.MockKException: Missing mocked calls inside every { ... } block: make sure the object inside the block is a mock
	at io.mockk.impl.recording.states.StubbingState.checkMissingCalls(StubbingState.kt:14)
	at io.mockk.impl.recording.states.StubbingState.recordingDone(StubbingState.kt:8)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:64)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalEvery(API.kt:93)
	at io.mockk.MockKKt.every(MockK.kt:98)
	at com.omnieyes.eventproducer.sid.util.iot.MyHelperTest.testCreateData2(MyHelperTest.kt:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:177)
	at junit.framework.TestCase.runBare(TestCase.java:142)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:750)
```

#### Minimal reproducible code (the gist of this issue)
just right-click on the test file and press `Run 'MyHelperTest.kt'` 

```
package com.omnieyes.eventproducer.sid.util.iot

import io.mockk.Matcher
import io.mockk.every
import io.mockk.mockk
import io.mockk.mockkConstructor
import junit.framework.TestCase
import org.junit.Test

/**
 * Should be mocked in a unit test.
 */
class AndroidData(val value: Float)

/**
 * Target class to be tested.
 */
class MyHelper() {
    fun createData(flag: Boolean): AndroidData {
        // simplified logic
        return if (flag) AndroidData(20f) else AndroidData(10f)
    }
}

class LargerThan15Matcher: Matcher<Float> {
    override fun match(arg: Float?): Boolean {
        return if (arg == null) false else arg >= 15f
    }
}

class MyHelperTest : TestCase() {
    @Test
    fun testCreateData1() {
        mockkConstructor(AndroidData::class)

        val helper = mockk<MyHelper>(relaxed = true)
        val createdData = helper.createData(true)

        println("createdData=$createdData")  // AndroidData(child of #1#2)
        println("createdData.value=${createdData.value}")  // 0.0

        // test if the argument in AndroidData's constructor was larger than 15
        assertTrue(createdData.value >= 15f)  // assertion failed
    }

    @Test
    fun testCreateData2() {
        mockkConstructor(AndroidData::class)
        // Missing mocked calls inside every { ... } block: make sure the object inside the block is a mock
        every {
            constructedWith<AndroidData>(LargerThan15Matcher())
        }

        val helper = mockk<MyHelper>(relaxed = true)
        val createdData = helper.createData(true)

        println("createdData=$createdData")  // AndroidData(child of #1#2)
        println("createdData.value=${createdData.value}")  // 0.0

        // test if the argument in AndroidData's constructor was larger than 15
        assertTrue(createdData.value >= 15f)
    }
}
```

**Comment by joy0520** [comment]
For someone who has the same need. I found an **alternative** to test the simple logic in `createData()` and its returned `AndroidData` instance. This is the one that fits my purpose mostly.

```
mockkConstructor(AndroidData::class)
every {
    constructedWith<AndroidData>(LargerThan15Matcher()).value
} returns 20f

val helper = MyHelper()
val createdData = helper.createData(true)

assertTrue(createdData.value >= 15f)
```
With this I can finally test the simple logic in `createData()`.

However, it seems still impossible to directly "capture" the `value` in the returned `AndroidData` object, which should be the most intuitive way. I really hope that `mockk` can support that.

This is my post on the [StackOverflow](https://stackoverflow.com/questions/73329861/is-it-possible-to-test-arguments-in-mocked-constructor-with-mockk). Thanks to [Karsten Gabriel](https://stackoverflow.com/users/15375588/karsten-gabriel)

**Comment by joy0520** [comment]
BTW it sucks that capturing must be used in an `every` block, which must alter (by `returns` or `answer`) the original behavior. I mean, we should have the right to decide, instead of being forced to do it.

**Comment by Raibaz** [comment]
Not sure if this applies to your case since your example is minimized, but: do you really need to mock the `AndroidData` class?

If it's a data class, or a class you don't need to test the behavior for in this context, would it make sense for you to just do something like

```
val shouldBe20 = MyHelper().createData(true)
assertEquals(20, shouldBe20.value)

val shouldBe10 = MyHelper().createData(false)
assertEquals(10, shouldBe10.value)
```

If you just want to test the content of the object being created by `createData`, you may not even need mocks.

**Comment by Raibaz** [comment]
(also, note that capturing can also be used in `verify` blocks)
