### ISSUE TITLE
mockkObject : io.mockk.MockKException: Missing calls inside every { ... }

### ISSUE THREAD

**Issue by masoudkarimi** [mockk/mockk#877]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

When adding the `@JvmStatic` annotation to a method of an object class, it should be able to mock, like when the method hasn't the annotation.

### Current Behavior

It throws Missing calls inside every { ... } block error.

### Failure Information (for bugs)

Test fails to setup mock.

#### Steps to Reproduce

1. Create an object with an `add` function
2. Add `@JvmStatic` to `add` method
```kt
object Adder {
    @JvmStatic
    fun add(a: Int, b: Int) = a + b
}
```

4. Try to mock the object and add method

#### Context

* MockK version: 1.12.5
* OS: Windows 11
* Kotlin version: 1.6.21
* JDK version: 11
* JUnit version: 'junit:junit:4.13.1'
* Type of test: unit test

#### Failure Logs

Please include any relevant log snippets or files here.

#### Stack trace

```
io.mockk.MockKException: Missing mocked calls inside every { ... } block: make sure the object inside the block is a mock
	at app//io.mockk.impl.recording.states.StubbingState.checkMissingCalls(StubbingState.kt:14)
	at app//io.mockk.impl.recording.states.StubbingState.recordingDone(StubbingState.kt:8)
	at app//io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at app//io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:64)
	at app//io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at app//io.mockk.MockKDsl.internalEvery(API.kt:93)
	at app//io.mockk.MockKKt.every(MockK.kt:98)
	at app//ir.sep.sesoot.pol.main.domain.usecase.ObjectTest.testAddFunction(ObjectTest.kt:26)
	at java.base@11.0.12/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.12/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.12/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.12/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at app//org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at app//org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at app//org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at app//org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    testImplementation "junit:junit:4.13.1"
    testImplementation "io.mockk:mockk:1.12.5"
}
// -----------------------[ ObjectTest.kt ] -----------------------
import io.mockk.every
import io.mockk.mockkObject
import io.mockk.unmockkObject
import org.hamcrest.MatcherAssert
import org.hamcrest.core.IsEqual
import org.junit.After
import org.junit.Before
import org.junit.Test

object Adder {
    @JvmStatic
    fun add(a: Int, b: Int) = a + b
}

class ObjectTest {

    @Before
    fun setUp() {
        mockkObject(Adder)
    }

    @Test
    fun testAddFunction() {
        every { Adder.add(2, 2) } returns 10

        val result = Adder.add(2, 2)

        MatcherAssert.assertThat(result, IsEqual.equalTo(10)) // Test fails
    }

    @After
    fun tearDown() {
        unmockkObject(Adder)
    }
}
```

**Comment by kshired** [comment]
Just try use `mockkStatic` like belows

```kotlin
object Adder {
    @JvmStatic
    fun add(a: Int, b: Int) = a + b
}

class ObjTest {
    @Before
    fun setUp() {
        mockkStatic(Adder::class)
    }

    @Test
    fun testAddFunction() {
        every { Adder.add(2, 2) } returns 10
        val result = Adder.add(2, 2)
        MatcherAssert.assertThat(result, IsEqual.equalTo(10))
    }

    @After
    fun tearDown() {
        unmockkObject(Adder)
    }
}
```

**Comment by masoudkarimi** [comment]
@kshired Thank u. It works 👍.
