### ISSUE TITLE
StackOverflowError when using any matcher for value classes

### ISSUE THREAD

**Issue by bleipold** [mockk/mockk#879]
### Expected Behavior

Calling the `every` method succeed.

### Current Behavior

Calling `every` results in a `StackOverflowError`.

#### Steps to Reproduce

Just run the provided test.

#### Context

* MockK version: 1.12.5
* OS: Windows 10/Linux
* Kotlin version: 1.7.10
* JDK version: 17
* JUnit version: 5.9.0
* Type of test: unit test

#### Failure Logs

There are no logs. Just a stack trace.

#### Stack trace

```
java.lang.StackOverflowError
	at kotlin.jvm.JvmClassMappingKt.getJavaObjectType(JvmClassMapping.kt:59)
	at kotlin.reflect.jvm.internal.KClassImpl.hashCode(KClassImpl.kt:296)
	at java.base/java.util.HashMap.hash(HashMap.java:338)
	at java.base/java.util.HashMap.getNode(HashMap.java:568)
	at java.base/java.util.LinkedHashMap.get(LinkedHashMap.java:441)
	at io.mockk.ValueClassSupportDsl.getBoxedProperty(ValueClassSupportDsl.kt:73)
	at io.mockk.ValueClassSupportDsl.getBoxedClass(ValueClassSupportDsl.kt:39)
	at io.mockk.InternalPlatformDsl.unboxClass(InternalPlatformDsl.kt:221)
	at io.mockk.impl.recording.JvmSignatureValueGenerator.signatureValue(JvmSignatureValueGenerator.kt:20)
	at io.mockk.impl.recording.JvmSignatureValueGenerator.signatureValue(JvmSignatureValueGenerator.kt:21)
	at io.mockk.impl.recording.JvmSignatureValueGenerator.signatureValue(JvmSignatureValueGenerator.kt:21)
	at io.mockk.impl.recording.JvmSignatureValueGenerator.signatureValue(JvmSignatureValueGenerator.kt:21)
	at io.mockk.impl.recording.JvmSignatureValueGenerator.signatureValue(JvmSignatureValueGenerator.kt:21)
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
dependencies {
  testImplementation("org.jetbrains.kotlin:kotlin-test-junit5:1.7.10")
  testImplementation("io.mockk:mockk:1.12.5")
  testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.0")
  testImplementation("org.junit.jupiter:junit-jupiter-params:5.9.0")
  testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.9.0")
}

import io.mockk.Runs
import io.mockk.every
import io.mockk.impl.annotations.MockK
import io.mockk.junit5.MockKExtension
import io.mockk.just
import org.junit.jupiter.api.extension.ExtendWith
import kotlin.test.Test
import kotlin.time.Duration

@ExtendWith(MockKExtension::class)
class StackOverflowErrorReproducer {

  @MockK
  private lateinit var serviceMock : Service

  @Test
  fun test() {

    every { serviceMock.doSomething(any()) } just Runs

    serviceMock.doSomething(Duration.ZERO)
  }
}

interface Service {

  fun doSomething(duration : Duration)
}

**Comment by onsah** [comment]
I have also faced with this issue when using `kotlin.time.Duration`

**Comment by roeniss** [comment]
I've found this issue also happend when mocked function has nullable return value. So I think this issue has something to do with `every` function. Below code is stuck on the second `every` function:

```kotlin
internal class MyTest : ShouldSpec({
    context("sample test") {
        should("hello") {
            val a: A = mockk()
            every { a.get() } returns ValueClass(1)
            every { a.set(listOf(ValueClass(1))) } returns ValueClass(1)

            val b = a.get()
            println("b = ${b}")
            a.set(listOf(b))
        }
    }
})


@JvmInline
value class ValueClass(
    val value: Int
)

class A {
    private var a: ValueClass = ValueClass(1)

    fun get(): ValueClass{
        return a
    }
    fun set(a: List<ValueClass>):ValueClass {
        this.a = a[0]
        return this.a
    }
}
```

... with very long logs:
```bash
./gradlew :merchants-api:test test --tests "org.roeniss.myTest" --debug  

# ... very long same lines as below ... 
2022-11-15T16:53:50.312+0900 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Cross-configure project :modules:logging' started
2022-11-15T16:53:50.312+0900 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Completing Build operation 'Cross-configure project :modules:logging'
2022-11-15T16:53:50.312+0900 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Cross-configure project :modules:logging' completed
2022-11-15T16:53:50.312+0900 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker Thread 3: released lock on state of build :
2022-11-15T16:53:50.312+0900 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker Thread 3: acquired lock on state of build :
2022-11-15T16:53:50.312+0900 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Cross-configure project :modules:magic-number' started
2022-11-15T16:53:50.312+0900 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Completing Build operation 'Cross-configure project :modules:magic-number'
2022-11-15T16:53:50.313+0900 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Cross-configure project :modules:magic-number' completed
2022-11-15T16:53:50.313+0900 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker Thread 3: released lock on state of build :
2022-11-15T16:53:50.313+0900 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker Thread 3: acquired lock on state of build :
2022-11-15T16:53:50.313+0900 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Cross-configure project :modules:monitoring' started
2022-11-15T16:53:50.313+0900 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Completing Build operation 'Cross-configure project :modules:monitoring'
2022-11-15T16:53:50.313+0900 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Cross-configure project :modules:monitoring' completed
2022-11-15T16:53:50.313+0900 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker Thread 3: released lock on state of build :
2022-11-15T16:53:50.313+0900 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker Thread 3: acquired lock on state of build :
2022-11-15T16:53:50.313+0900 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Cross-configure project :tests:api' started
2022-11-15T16:53:50.313+0900 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Completing Build operation 'Cross-configure project :tests:api'
2022-11-15T16:53:50.313+0900 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Cross-configure project :tests:api' completed
2022-11-15T16:53:50.313+0900 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker Thread 3: released lock on state of build :
2022-11-15T16:53:50.313+0900 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker Thread 3: acquired lock on state of build :
2022-11-15T16:53:50.313+0900 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Cross-configure project :tests:api-use-check' started
2022-11-15T16:53:50.313+0900 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Completing Build operation 'Cross-configure project :tests:api-use-check'
2022-11-15T16:53:50.313+0900 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Cross-configure project :tests:api-use-check' completed
2022-11-15T16:53:50.313+0900 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker Thread 3: released lock on state of build :
2022-11-15T16:53:50.313+0900 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Completing Build operation 'Execute 'allprojects {}' action'
2022-11-15T16:53:50.313+0900 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Execute 'allprojects {}' action' completed
2022-11-15T16:53:50.315+0900 [DEBUG] [org.jetbrains.kotlin.gradle.plugin.KotlinGradleFinishBuildHandler] [KOTLIN] Deleted session-is-alive flag file: build/kotlin/sessions/kotlin-compiler-2627853250526088629.salive
2022-11-15T16:53:50.315+0900 [DEBUG] [org.jetbrains.kotlin.gradle.plugin.KotlinGradleBuildServices$Inject] [KOTLIN] Disposed KotlinGradleBuildServices
2022-11-15T16:53:50.315+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
2022-11-15T16:53:50.315+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build completed with 2 failures.
2022-11-15T16:53:50.319+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
2022-11-15T16:53:50.319+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 1: Task failed with an exception.
2022-11-15T16:53:50.319+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] -----------
2022-11-15T16:53:50.319+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
2022-11-15T16:53:50.319+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':myModule:test'.
2022-11-15T16:53:50.319+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > No tests found for given includes: [org.roeniss.MyTest](--tests filter)
2022-11-15T16:53:50.319+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
2022-11-15T16:53:50.319+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
2022-11-15T16:53:50.319+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Run with --stacktrace option to get the stack trace.
2022-11-15T16:53:50.319+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Run with --scan to get full insights.
2022-11-15T16:53:50.319+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] ==============================================================================
2022-11-15T16:53:50.319+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
2022-11-15T16:53:50.319+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 2: Task failed with an exception.
2022-11-15T16:53:50.319+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] -----------
2022-11-15T16:53:50.319+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
2022-11-15T16:53:50.319+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] java.lang.StackOverflowError (no error message)
2022-11-15T16:53:50.319+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
2022-11-15T16:53:50.319+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
2022-11-15T16:53:50.320+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Run with --stacktrace option to get the stack trace.
2022-11-15T16:53:50.320+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Run with --scan to get full insights.
2022-11-15T16:53:50.320+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] ==============================================================================
2022-11-15T16:53:50.320+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
2022-11-15T16:53:50.320+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
```
