### ISSUE TITLE
mockk/every not mock function with any()

### ISSUE THREAD

**Issue by luna-vulpo** [mockk/mockk#882]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior
Test should pass
### Current Behavior
Test doesn't pass

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

run sumple test

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.12.5
* OS: Android
* Kotlin version: 1.6.20
* JDK version: 11
* JUnit version: 4.13.5
* Type of test: unit test OR android instrumented test

#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
java.lang.AbstractMethodError: abstract method "boolean kotlin.reflect.KClass.isVisible()"
at io.mockk.impl.recording.JvmSinnatureValueGenerator.signatureValue(JvmSignatureValueGenerator.kt:19)
at io.mockk.impl.recording.states.RcordingState.matcher(RecordingState.kt:46)
at io.mockk.impl.recording.CommonCallrecorder.mathcer(CommonCallRecorder.kt:52)
at test.test.TestTest$test$1.invoke(TestTest,lt18)
at test.test.TestTest$test$1.invoke(TestTest,lt12)
at io.mockk.impl.eval.RecordedBLockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:25)
at io.mockk.impl.eval.RecordedBLockEvaluator$enhanceWithRethrow$1.invoke(RecordedBlockEvaluator.kt:78)
at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:40)
at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
at io.mockk.MockkDsl.internalEvery(API.kt:93)
at io.mockk.MockKKt.every(MockK.kt:98)
at test.test.TestTest$test$1.invoke(TestTest,lt12)

// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
import io.mockk.every
import io.mockk.mockk
import junit.framework.Assert.assertEquals
import org.junit.Test
import java.util.function.Function

class TestTest {
    @Test
    fun test() {
        val mock = mockk<Function<String, String>>()
        every { mock.apply(any()) } returns "test"
        assertEquals("test", mock.apply("x"))
    }
}
```

**Comment by luongvo** [comment]
+1

**Comment by pstorch** [comment]
Stumbled upon the same issue right now.

I could help myself by adding the generic type to the any() call like this:

```kotlin
        every { mock.apply(any<String>()) } returns "test"
```
