### ISSUE TITLE
`mockk-android:1.12.7` always fails with `'dispatcher.jar' not found`

### ISSUE THREAD

**Issue by kubode** [mockk/mockk#894]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

Not fails.

### Current Behavior

The instrumentation test fails with the following stack trace.

#### Context

* MockK version: 1.12.7

#### Stack trace

```
java.lang.NoClassDefFoundError: io.mockk.impl.JvmMockKGateway
at MyInstrumentationTest.tearDown(SettingsFragmentTest.kt:803)
... 37 trimmed
Caused by: java.lang.ExceptionInInitializerError
at MyInstrumentationTest.setUp(SettingsFragmentTest.kt:668)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:76)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
... 33 more
Caused by: io.mockk.proxy.MockKAgentException: 'dispatcher.jar' not found
at io.mockk.proxy.android.AndroidMockKAgentFactory.init(AndroidMockKAgentFactory.kt:47)
at io.mockk.impl.JvmMockKGateway.<init>(JvmMockKGateway.kt:46)
at io.mockk.impl.JvmMockKGateway.<clinit>(JvmMockKGateway.kt:186)
... 40 more
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
dependencies {
    androidTestImplementation("io.mockk:mockk:1.12.7")
    androidTestImplementation("io.mockk:mockk-android:1.12.7")
    // Adding the following does not change the behavior
//    androidTestImplementation("io.mockk:mockk-agent:1.12.7")
//    androidTestImplementation("io.mockk:mockk-agent-android:1.12.7")
}
```

**Comment by kubode** [comment]
In `1.12.7`, `dispatcher.jar` is not included in `.aar`. But in `1.12.5` it was included.

<img width="2004" alt="image" src="https://user-images.githubusercontent.com/5885032/186379280-40484226-1bf6-41e6-a9e7-689de90b8187.png">

**Comment by madsunrise** [comment]
+1

**Comment by Alebat** [comment]
+1
