### ISSUE TITLE
Bug: mocking of static Java function(java.time.Instant)

### ISSUE THREAD

**Issue by samirda** [mockk/mockk#92]
### Expected Behavior

Expected behavior is to get mocked result from static function in a Java class(java.time.Instant)

#### Mockk 1.7.15 returns expected result
```kotlin
val epochSeconds = 123L
staticMockk<Instant>().mock().run {
	every { Instant.now().epochSecond } returns epochSeconds
}

println(Instant.now().epochSecond) //123
```

#### Mockk 1.8.3 throws exception when using deprecated code and with new update code.
```kotlin
val epochSeconds = 123L
staticMockk<Instant>().mock().run {
	every { Instant.now().epochSecond } returns epochSeconds
}

println(Instant.now().epochSecond) //123
```
```kotlin
val epochSeconds = 123L
mockkStatic(Instant::class)
every { Instant.now().epochSecond } returns epochSeconds

println(Instant.now().epochSecond)
```

#### Stack trace
```
io.mockk.MockKException: Missing calls inside every { ... } block.

at io.mockk.impl.recording.states.StubbingState.checkMissingCalls(StubbingState.kt:14)
at io.mockk.impl.recording.states.StubbingState.recordingDone(StubbingState.kt:8)
at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:42)
at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:48)
at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:25)
```

#### Context

* MockK version: 1.8.3
* OS: Mac OS
* Kotlin version: 1.2.50
* JDK version: 8
* Type of test: unit test(JUnit 5)

**Comment by oleksiyp** [comment]
Thank you very much for reporting this issue. Indeed regression occurred. 

I converted ClassTransformer to Kotlin and forgot that classloader may be null, but nullability checks were applied, so it was failing. And because Java does not report such issues nothing was reported.

**Comment by samirda** [comment]
Np, thank you for fix.

Should I close or wait for release?

**Comment by oleksiyp** [comment]
Version 1.8.4 released, please check if everything ok and close the issue.

**Comment by samirda** [comment]
Works, thanks.

**Comment by vistiyos** [comment]
Hello there, I'm having the same issue with following Context:

- MockK version:1.8.8
- OS: Windows 10
- Kotlin version: 1.2.41
- JDK version: 9
- Type of test: Unit test (JUnit 5)

this is the code that is causing errors:

```
mockkStatic(UUID::class).run {
        every { UUID.randomUUID().toString() } returns "4578452"
 }
```

And this is the error message:
```
io.mockk.MockKException: Missing calls inside every { ... } block.

	at io.mockk.impl.recording.states.StubbingState.checkMissingCalls(StubbingState.kt:14)
	at io.mockk.impl.recording.states.StubbingState.recordingDone(StubbingState.kt:8)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:42)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:48)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:25)
	at com.pkt.users.data.repositories.UserServiceUnitTest.createUserTest(UserServiceUnitTest.kt:71)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

am I doing something wrong?

**Comment by pollux-** [comment]
I'm facing the same issue

**Comment by Vergil333** [comment]
@vistiyos I see I’m late into the party but the syntax should be 

```
mockkStatic(UUID::class)
every { UUID.randomUUID().toString() } returns “mocked-uuid”
```
