### ISSUE TITLE
AbstractMethodError when using `any()` to provide a value for a suspend lambda

### ISSUE THREAD

**Issue by roomscape** [mockk/mockk#944]
### Expected Behavior

When using `coVerify` to verify a call to a higher-order function, I can use `any()` in place of the lambda parameter.

### Current Behavior

Using `coVerify` with `any()` fails with `java.lang.AbstractMethodError: Receiver class kotlin.jvm.functions.Function1$Subclass0 does not define or inherit an implementation of the resolved method 'abstract java.lang.Object invoke(java.lang.Object)' of interface kotlin.jvm.functions.Function1`

#### Steps to Reproduce

See the minimal reproducible code below.

#### Context

* MockK version: 1.13.2
* OS: MacOS 12.6
* Kotlin version: 1.7.20
* JDK version: 17.0.3
* JUnit version: 4.13
* Type of test: unit test

#### Failure Logs

There is one WARN-level log message "Failed to transform class AbstractFilter" from `io.mockk.proxy.jvm.transformation.InliningClassTransformer`. The log line includes a `StackOverflowError` from ByteBuddy. I'm not sure if it's related to the `AbstractMethodError` that later causes the test to crash. If it is, I think this suggests the problem could be related to #920. 

```
java.lang.StackOverflowError
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.equals(TypeDescription.java:8256)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.represents(TypeDescription.java:8013)
	at net.bytebuddy.description.type.TypeDescription$ForLoadedType.represents(TypeDescription.java:8657)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfNonGenericType.represents(TypeDescription.java:3749)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfNonGenericType$ForLoadedType.represents(TypeDescription.java:3898)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor$ForAttachment.onSimpleType(TypeDescription.java:2040)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor.onNonGenericType(TypeDescription.java:1913)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor$ForAttachment.onNonGenericType(TypeDescription.java:1946)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfNonGenericType.accept(TypeDescription.java:3672)
	at net.bytebuddy.description.method.MethodDescription$Latent.getReturnType(MethodDescription.java:1462)
	at net.bytebuddy.description.method.MethodDescription$AbstractBase.toString(MethodDescription.java:1001)
	at java.base/java.lang.String.valueOf(String.java:4218)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
	at net.bytebuddy.description.TypeVariableSource$AbstractBase.findExpectedVariable(TypeVariableSource.java:174)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor$ForAttachment.onTypeVariable(TypeDescription.java:2035)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor$ForAttachment.onTypeVariable(TypeDescription.java:1946)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfTypeVariable$Symbolic.accept(TypeDescription.java:5856)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor.onParameterizedType(TypeDescription.java:1881)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor$ForAttachment.onParameterizedType(TypeDescription.java:1946)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfParameterizedType.accept(TypeDescription.java:5059)
	at net.bytebuddy.description.method.ParameterDescription$Latent.getType(ParameterDescription.java:805)
	at net.bytebuddy.description.method.ParameterList$AbstractBase.asTypeList(ParameterList.java:107)
	at net.bytebuddy.description.method.MethodDescription$AbstractBase.toString(MethodDescription.java:1006)
	at java.base/java.lang.String.valueOf(String.java:4218)
        ...
```
(The remainder of the stacktrace just repeats the above).

#### Stack trace

The test fails with this error:

```stacktrace
Exception in thread "main" java.lang.AbstractMethodError: Receiver class kotlin.jvm.functions.Function1$Subclass0 does not define or inherit an implementation of the resolved method 'abstract java.lang.Object invoke(java.lang.Object)' of interface kotlin.jvm.functions.Function1.
	at AbstractFilter.apply$suspendImpl(Example.kt:9)
	at AbstractFilter.apply(Example.kt)
	at ExampleKt$main$1.invokeSuspend(Example.kt:16)
	at ExampleKt$main$1.invoke(Example.kt)
	at ExampleKt$main$1.invoke(Example.kt)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$2$1.invokeSuspend(RecordedBlockEvaluator.kt:28)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$2$1.invoke(RecordedBlockEvaluator.kt)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$2$1.invoke(RecordedBlockEvaluator.kt)
	at io.mockk.InternalPlatformDsl$runCoroutine$1.invokeSuspend(InternalPlatformDsl.kt:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at io.mockk.InternalPlatformDsl.runCoroutine(InternalPlatformDsl.kt:22)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$2.invoke(RecordedBlockEvaluator.kt:28)
	at io.mockk.impl.eval.RecordedBlockEvaluator$enhanceWithRethrow$1.invoke(RecordedBlockEvaluator.kt:78)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:40)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalCoVerify(API.kt:144)
	at io.mockk.MockKKt.coVerify(MockK.kt:175)
	at io.mockk.MockKKt.coVerify$default(MockK.kt:166)
	at ExampleKt.main(Example.kt:16)
	at ExampleKt.main(Example.kt)
```

#### Minimal reproducible code

```kotlin
import io.mockk.coVerify
import io.mockk.mockk

interface Filter<T> {
    suspend fun apply(block: suspend () -> T): T
}

abstract class AbstractFilter<T> : Filter<T> {
    override suspend fun apply(block: suspend () -> T): T = block()
}

class ConcreteFilter : AbstractFilter<Any>()

fun main() {
    val filter = mockk<ConcreteFilter>()
    coVerify { filter.apply(any()) }
}
```

**Comment by vaibhavrdbhat** [comment]
I am encountering the same issue with coVerify

**Comment by QuinnBast** [comment]
Same issue here but on `coEvery`:

```
coEvery { someMethodAcceptingLambda(any()) } coAnswers { mockk(relaxed = true) }
```

> java.lang.AbstractMethodError: Receiver class kotlin.jvm.functions.Function1$Subclass0 does not define or inherit an implementation of the resolved method 'abstract java.lang.Object invoke(java.lang.Object)' of interface kotlin.jvm.functions.Function1.

**Comment by madsop-nav** [comment]
Maybe useful information for solving the issue: I get the same error when trying to use the slot mechanism as a workaround, as in your example

```
fun main() {
    val filter = mockk<ConcreteFilter>()
    val slot = slot<() -> T>()
    coVerify { filter.apply(capture(slot)) }
}
```

**Comment by bfollonikea** [comment]
Same issue, sad to see it's open from 2022

**Comment by MisterDerpie** [comment]
Adding another +1 here, just stumbled over it too :(

**Comment by rekaszeru** [comment]
Any update / prospect of having this fixed?

**Comment by zromano** [comment]
Still happening on latest version `1.13.12`
