### ISSUE TITLE
Returning value class from suspend method is broken

### ISSUE THREAD

**Issue by atanana** [mockk/mockk#947]
### Expected Behavior

Mock should be able to return value class from suspend method

### Current Behavior

Mock crashes

#### Context

* MockK version: 1.13.2
* OS: Linux 5.15.71-1-MANJARO
* Kotlin version: 1.7.20
* JDK version: openjdk 11.0.16 2022-07-19 LTS
* JUnit version: 4.13.2
* Type of test: unit test

#### Stack trace

```
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class TV (java.lang.Integer is in module java.base of loader 'bootstrap'; TV is in unnamed module of loader 'app')

	at ToTestTest$test$1.invokeSuspend(ToTestTest.kt:13)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at ToTestTest.test(ToTestTest.kt:11)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4")

    testImplementation("junit:junit:4.13.2")
    testImplementation("io.mockk:mockk:1.13.2")
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
import io.mockk.*
import kotlinx.coroutines.runBlocking
import org.junit.Assert.*
import org.junit.Test

class ToTest {
    suspend fun test(i: Int): TV {
        return TV(i)
    }
}

@JvmInline
value class TV(val i: Int)

class ToTestTest {

    private val test: ToTest = mockk()

    @Test
    fun test() = runBlocking {
        coEvery { test.test(any()) } returns TV(1)
        val result = test.test(1)
        assertEquals(TV(1), result)
    }
}
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by akhial** [comment]
Was struggling to find a tracking issue for this... this is it. No idea how to go about fixing it however...

**Comment by dekalo-stanislav** [comment]
+1, very annoying :(

**Comment by y9vad9** [comment]
same issue

**Comment by kejml** [comment]
This is affecting us even in the latest version:

-     MockK version: 1.13.8
-     Kotlin version: 1.9.22
-     JDK version: zulu21.30.15-ca-jdk21.0.1-linux_x64
-     JUnit version: 5.10.1
-     Type of test: unit test

**Comment by y9vad9** [comment]
still represented on 1.13.9

feels like very important miss in the mockk, no wonder why it's not fixed yet 🥲

**Comment by VasilisDrettas-tomtom** [comment]
I tested that and I think with the latest version of mockk this is not reproducible anymore. Could you check it again ?

**Comment by atanana** [comment]
@VasilisDrettas-tomtom yes, you are right. I think it should be closed now
