### ISSUE TITLE
Bug: chained call detection in some cases(spyk default arg function) is broken

### ISSUE THREAD

**Issue by TimoPtr** [mockk/mockk#95]
### Expected Behavior

Mock a method with default param which call an other method inside the spy object

### Current Behavior

Throwing io.mockk.MockKException: Failed matching mocking signature for

#### Steps to Reproduce

code : 
```
class Foo {

    fun getInterface(list: List<Boolean>) = listOf(true)

    fun bar(t:String, list: List<Boolean> = getInterface(listOf(false))):String {
        return "FOO"
    }
}


class TestingMock {

    @Test
    fun testMock() {
        val mocking = spyk(Foo())

        every { mocking.bar(any()) } returns "FOO MOCKED"

        println(mocking.bar("hello"))
    }
}
```

#### Context

* MockK version: 1.8.1
* OS: Mac OS
* Kotlin version: 1.2.41
* JDK version: 1.8
* Type of test: unit test 

#### Stack trace

```
io.mockk.MockKException: Failed matching mocking signature for
Foo@179ece50.getInterface([false])
left matchers: [any()]

	at io.mockk.impl.recording.ChainedCallDetector$detect$8.invoke(ChainedCallDetector.kt:146)
	at io.mockk.impl.recording.ChainedCallDetector.detect(ChainedCallDetector.kt:170)
	at io.mockk.impl.recording.SignatureMatcherDetector.detect(SignatureMatcherDetector.kt:29)
	at io.mockk.impl.recording.states.RecordingState.signMatchers(RecordingState.kt:38)
	at io.mockk.impl.recording.states.RecordingState.round(RecordingState.kt:30)
	at io.mockk.impl.recording.CommonCallRecorder.round(CommonCallRecorder.kt:45)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:47)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:25)
	at TestingMock.testMock(test.kt:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
```

**Comment by oleksiyp** [comment]
I am afraid such thing pretty hard or even impossible to fix. Ill check

**Comment by TimoPtr** [comment]
If this can help you it's work when there is only the default param : 

```
class Foo {

    fun getInterface(list: List<Boolean>) = listOf(true)

    fun bar(t:String, list: List<Boolean> = getInterface(listOf(false))):String {
        return "FOO"
    }

    fun bar2(list: List<Boolean> = getInterface(listOf(false))):String {
        return "FOO"
    }
}


class TestingMock {

    // Fail
    @Test
    fun testMock() {
        val mocking = spyk(Foo())

        every { mocking.bar(any()) } returns "FOO MOCKED"

        println(mocking.bar("hello"))
    }

    // Success
    @Test
    fun test2() {
        val mocking = spyk(Foo())

        every { mocking.bar2() } returns "FOO MOCKED"

        println(mocking.bar2())
    }
}
```

**Comment by oleksiyp** [comment]
Thanks a lot for a very extensive report. I checked it.

So first thing is that indeed calls happening as an argument to another call are supported(but not much documented).
Second, which for me is surprising, it works for `spyk` as a call of function by default.
Third, I know the reason why test is failing, but to fix I need to rework some internals of call chain detection. (which won't be very fast)

**Comment by oleksiyp** [comment]
I coded the first solution. 

The test you gave works, but some tests on composite matchers are failing. Going to return back to it in the evening.

**Comment by TimoPtr** [comment]
Thanks a lot ! Even if it's not fix yet, you are very reactive !

**Comment by oleksiyp** [comment]
Version 1.8.4 released, please check if everything ok and close the issue.

**Comment by TimoPtr** [comment]
Hi, so it's fix the problem for simple method call, it persist for extension method call : 
```
class Foo {

    fun getInterface(list: List<Boolean>) = listOf<Boolean>(true)

    fun bar(t:String, list: List<Boolean> = getInterface(listOf(false))):String {
        return "FOO"
    }

    fun bar2(list: List<Boolean> = getInterface(listOf(false))):String {
        return "FOO"
    }
}

fun Foo.bar3(t:String, list: List<Boolean> = getInterface(listOf(false))):String {
    return "FOO"
}

class TestingMock {

    // Sucess
    @Test
    fun testMock() {
        val mocking = spyk(Foo())

        every { mocking.bar(any()) } returns "FOO MOCKED"

        println(mocking.bar("hello"))
    }

    // Success
    @Test
    fun test2() {
        val mocking = spyk(Foo())

        every { mocking.bar2() } returns "FOO MOCKED"

        println(mocking.bar2())
    }

    // Failure
    @Test
    fun test3() {
        val mocking = spyk(Foo())

        every { mocking.bar3(any()) } returns "FOO MOCKED"

        println(mocking.bar3("hello"))
    }
}
```

**Comment by oleksiyp** [comment]
Ok will check, just note that mocking extension functions is different.(check README)

**Comment by TimoPtr** [comment]
Ok I check with your exemple and it's working. But It doesn't handle Extension at kotlin module level :

```
class Ext {
    fun Foo.bar3(t: String, list: List<Boolean> = getInterface(listOf(false))): String {
        return "FOO"
    }
}

@Test
    fun test4() {
        val mocking = spyk(Foo())
        with(mockk<Ext>()) {
            every { mocking.bar3(any()) } returns "FOO MOCKED"
            println(mocking.bar3("hello"))
        }
    }
```

**Comment by oleksiyp** [comment]
For kotlin module you need `mockkStatic` module class first

пн, 25 июня 2018 г., 11:50 Timothy <notifications@github.com>:

**Comment by TimoPtr** [comment]
Oh Thank you !!! I have miss this part so it's work like a charm ! Here the solution 

```
class Foo {

    fun getInterface(list: List<Boolean>) = listOf<Boolean>(true)

    fun bar(t: String, list: List<Boolean> = getInterface(listOf(false))): String {
        return "FOO"
    }

    fun bar2(list: List<Boolean> = getInterface(listOf(false))): String {
        return "FOO"
    }
}


fun Foo.bar3(t: String, list: List<Boolean> = getInterface(listOf(false))): String {
    return "FOO"
}

class TestingMock {

    // Sucess
    @Test
    fun testMock() {
        val mocking = spyk(Foo())

        every { mocking.bar(any()) } returns "FOO MOCKED"

        println(mocking.bar("hello"))
    }

    // Success
    @Test
    fun test2() {
        val mocking = spyk(Foo())

        every { mocking.bar2() } returns "FOO MOCKED"

        println(mocking.bar2())
    }

    // Success
    @Test
    fun test3() {
        val mocking = spyk(Foo())
        mockkStatic("TestKt")
        every { mocking.bar3(any()) } returns "FOO MOCKED"
        println(mocking.bar3("hello"))
    }
}
```
