### ISSUE TITLE
Unable to mock vararg methods where the last parameter is not variable

### ISSUE THREAD

**Issue by jebbench** [mockk/mockk#953]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Expected Behavior

I would like the code below to compile and mock the method.

```
fun method(vararg names: String, action: suspend () -> T): T {
  return action();
}

coEvery { myClass.method(*anyVararg(), any<() -> Number>()) } coAnswers { lastArg<() -> String>().invoke() }
// OR
coEvery { myClass.method(any(), any(), any<() -> Number>()) } coAnswers { lastArg<() -> String>().invoke() }
```

### Current Behavior

The code fails to compile:
```
Type mismatch: inferred type is () -> Number but String was expected
No value passed for parameter 'action'
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    testImplementation('io.mockk:mockk:1.13.2')
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
package io.mockk.gh

import io.mockk.every
import io.mockk.mockk
import kotlin.test.Test

class Issue69Test {

    class MyClass {
        fun method(vararg names: String, action: suspend () -> T): T {
          return action();
        }
    }

    @Test
    fun test() {
        val myClass = mockk<MyClass>()
        every { myClass.method(*anyVararg(), any<() -> Number>()) } coAnswers { lastArg<() -> String>().invoke() }
        // OR
        // every { myClass.method(any(), any(), any<() -> Number>()) } coAnswers { lastArg<() -> String>().invoke() }

        myClass.method("a") { 99 }
    }

}
```

**Comment by stengvac** [comment]
Yo,

It works as expected for non suspending functions Just named args has to be used. Seems readme need improvement.

```
    class TestedClass {

        fun <T> methodWithLambda(vararg names: String, action: () -> T): T {
            return action()
        }

        suspend fun <T> suspendWithLambda(vararg names: String, action: suspend () -> T): T {
            return action()
        }
}
    @Test
    fun `mockk allow to mock vararg methods with other argument types`() {
        val testedClass = mockk<TestedClass>()

        every {
            testedClass.methodWithLambda(names = varargAny<String> { true }, any<() -> Number>())
        } answers { lastArg<() -> Number>().invoke() }

        val returnedInt = testedClass.methodWithLambda("a", "b", "c") { 99 }
        assertEquals(returnedInt, 99)
}
```

But is seems there is problem with suspending functions.
```
    @Test
    fun `mockk suspending vararg`() {
        val testedClass = mockk<TestedClass>()
        coEvery {
            testedClass.suspendWithLambda(names = varargAny<String> { true }, any<() -> Number>())
        } coAnswers { lastArg<() -> Number>().invoke() }
    }
```
produce
```
kotlin.reflect.jvm.internal.KotlinReflectionInternalError: Function 'suspendConversion0' (JVM signature: invokeSuspend$suspendConversion0(Lkotlin/jvm/functions/Function0;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;) not resolved in class kotlin.jvm.internal.Intrinsics$Kotlin: no members found
	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.findFunctionDescriptor(KDeclarationContainerImpl.kt:131)
	at kotlin.reflect.jvm.internal.KFunctionImpl$descriptor$2.invoke(KFunctionImpl.kt:57)
	at kotlin.reflect.jvm.internal.KFunctionImpl$descriptor$2.invoke(KFunctionImpl.kt:56)
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
	at kotlin.reflect.jvm.internal.KFunctionImpl.getDescriptor(KFunctionImpl.kt:56)
	at kotlin.reflect.jvm.internal.KFunctionImpl.toString(KFunctionImpl.kt:186)
	at kotlin.jvm.internal.FunctionReference.toString(FunctionReference.java:130)
	at java.base/java.lang.String.valueOf(String.java:4218)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
	at java.base/java.util.AbstractCollection.toString(AbstractCollection.java:457)
	at java.base/java.lang.String.valueOf(String.java:4218)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
	at io.mockk.impl.recording.SignedCall.toString(SignedCall.kt)
	at java.base/java.lang.String.valueOf(String.java:4218)
	at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:88)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3490)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:3507)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:3506)
	at io.mockk.impl.recording.SignatureMatcherDetector.detect(SignatureMatcherDetector.kt:97)
	at io.mockk.impl.recording.states.RecordingState.signMatchers(RecordingState.kt:39)
	at io.mockk.impl.recording.states.RecordingState.round(RecordingState.kt:31)
	at io.mockk.impl.recording.CommonCallRecorder.round(CommonCallRecorder.kt:50)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:62)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalCoEvery(API.kt:100)
	at io.mockk.MockKKt.coEvery(MockK.kt:169)
```

**Comment by stengvac** [comment]
Ok found out the problem. If one of arguments is suspension function, then `any<() -> Number>()` won`t do. Is required `any<suspend () -> Number>()`

```
    @Test
    fun `mockk suspending vararg`() {
        val testedClass = mockk<TestedClass>()
        coEvery {
            testedClass.suspendWithLambda(names = varargAny<String> { true }, action = any<suspend () -> Number>())
        } coAnswers { lastArg<() -> Number>().invoke() }
    }
```

**Comment by diklimchuk** [comment]
I had the same issue because a was passing the wrong paramter to function in coEvery:
```
arg = slot<(VKIDUser) -> Unit>() // produces the issue
arg = slot<suspend (VKIDUser) -> Unit>() // works
coEvery { function(arg) } just runs
```
Fixing the type of arg resolved it
