### ISSUE TITLE
Bug: Mocking LocalDateTime static function from a JavaClass

### ISSUE THREAD

**Issue by Kerooker** [mockk/mockk#96]
Having the JavaClass that returns a LocalDateTime:
```
public class JavaClass {


    public static LocalDateTime foo(String bar) {
        throw new RuntimeException();
    }
}

```

When I'm trying to execute the following code, a null pointer exception is thrown:
```
@Test
    fun `Bug`(){
        mockkStatic(JavaClass::class)
        
        val mockedDatetime: LocalDateTime = mockk()
        every { JavaClass.foo("bar") } returns mockedDatetime
        
        assertEquals(mockedDatetime, JavaClass.foo("bar"))
        
    }
```

It was expected for the assertion to work, but it doesn't. 

Stacktrace:

```
java.lang.NullPointerException
	at java.time.LocalDateTime.hashCode(LocalDateTime.java:1950)
	at io.mockk.RecordedCall.hashCode(API.kt)
	at java.util.HashMap.hash(HashMap.java:339)
	at java.util.HashMap.put(HashMap.java:612)
	at io.mockk.impl.recording.PermanentMocker.describeCallTree(PermanentMocker.kt:98)
	at io.mockk.impl.recording.PermanentMocker.access$describeCallTree(PermanentMocker.kt:11)
	at io.mockk.impl.recording.PermanentMocker$mock$callTree$1.invoke(PermanentMocker.kt:28)
	at io.mockk.impl.recording.PermanentMocker$mock$callTree$1.invoke(PermanentMocker.kt:11)
	at io.mockk.impl.recording.CommonCallRecorder.safeExec(CommonCallRecorder.kt:66)
	at io.mockk.impl.log.SafeLog.exec(SafeLog.kt:10)
	at io.mockk.impl.recording.PermanentMocker.mock(PermanentMocker.kt:28)
	at io.mockk.impl.recording.states.RecordingState.mockPermanently(RecordingState.kt:115)
	at io.mockk.impl.recording.states.RecordingState.round(RecordingState.kt:32)
	at io.mockk.impl.recording.CommonCallRecorder.round(CommonCallRecorder.kt:45)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:47)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:25)
	at foo.bar.TestDatetime.Bug(TestDatetime.kt:155)
```

**Comment by oleksiyp** [comment]
Should be fixed in #94

**Comment by oleksiyp** [comment]
Version 1.8.4 released, please check if everything ok and close the issue.

**Comment by Kerooker** [comment]
It's fixed.

Amazing! Thanks!
