### ISSUE TITLE
StackOverflowException when mocking an interface with a generic parameter and suspend functions

### ISSUE THREAD

**Issue by FortTell** [mockk/mockk#968]
> Just be aware about usual MockK support pattern. 
> Tickets are checked from time to time, replied, discussed, labeled, e.t.c.
> But real fixes are applied in a month-two month period in a bunch.
> If you think this is unacceptable, go on, join the project, change the world.

### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version (1.13.2)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed (closest match is #143, but the error is different)

### Expected Behavior

I can mock/spy an interface with a generic parameter which has a suspend function.

### Current Behavior

I get a StackOverflowError when ByteBuddy tries to transform the interface. This causes MockK to use the real implementation and some of our tests fail.

### Failure Information (for bugs)

See below.

#### Steps to Reproduce

```
import io.kotest.core.spec.style.StringSpec
import io.mockk.coVerify
import io.mockk.spyk

class MockFailTest : StringSpec() {
    init {
        "generic+suspend fails" {
            val spy = spyk(MySuspendCommand<MyGitLabProject>())
            spy.execute(MyCommandContext(MyGitLabProject()))
            spy.execute(MyCommandContext(MyGitLabProject()))
            coVerify(exactly = 2) { spy.execute(any<MyCommandContext<MyGitLabProject>>()) }
        }

        "works without generic" {
            val spy = spyk(MyUntypedCommand())
            spy.execute(MyCommandContext(MyGitLabProject()))
            spy.execute(MyCommandContext(MyGitLabProject()))
            coVerify(exactly = 2) { spy.execute(any<MyCommandContext<MyGitLabProject>>()) }
        }

        "works without suspend" {
            val spy = spyk(MyCommand<MyGitLabProject>())
            spy.execute(MyCommandContext(MyGitLabProject()))
            spy.execute(MyCommandContext(MyGitLabProject()))
            coVerify(exactly = 2) { spy.execute(any<MyCommandContext<MyGitLabProject>>()) }
        }
    }
}

//common
class MyCommandContext<TTarget>(var target: TTarget)

data class MyExecutionResult<TTarget>(
    val target: TTarget? = null,
    var invoked: Boolean = false,
    var message: String = "",
)

data class MyGitLabProject(val id: String = "")

// works without generic
interface IMyUntypedCommand {
    suspend fun execute(
        context: MyCommandContext<MyGitLabProject>
    ): MyExecutionResult<MyGitLabProject> = MyExecutionResult()
}
class MyUntypedCommand(val value: String = "") : IMyUntypedCommand

// works without suspend
interface IMyCommand<TTarget> {
    fun execute(context: MyCommandContext<TTarget>): MyExecutionResult<TTarget> = MyExecutionResult()
}
class MyCommand<TTarget>(val value: String = "") : IMyCommand<TTarget>

// generic+suspend fails
interface IMySuspendCommand<TTarget> {
    suspend fun execute(context: MyCommandContext<TTarget>): MyExecutionResult<TTarget> = MyExecutionResult()
}

class MySuspendCommand<TTarget>(val value: String = "") : IMySuspendCommand<TTarget>
```

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.13.2
* OS: Windows 10
* Kotlin version: 1.7.20
* JDK version: 18
* JUnit version: 5.8.2
* Type of test: Kotest unit test

#### Failure Logs

Please include any relevant log snippets or files here.

#### Stack trace

(StackOverflow happens in a slightly different place each time)
```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
... i.m.p.j.t.InliningClassTransformer - Failed to transform class .../IMySuspendCommand
java.lang.StackOverflowError: null
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.equals(TypeDescription.java:8256)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.represents(TypeDescription.java:8013)
	at net.bytebuddy.description.type.TypeDescription$ForLoadedType.represents(TypeDescription.java:8657)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfNonGenericType.represents(TypeDescription.java:3749)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfNonGenericType$ForLoadedType.represents(TypeDescription.java:3898)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor$ForAttachment.onSimpleType(TypeDescription.java:2040)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor.onNonGenericType(TypeDescription.java:1913)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor$ForAttachment.onNonGenericType(TypeDescription.java:1946)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfNonGenericType.accept(TypeDescription.java:3672)
	at net.bytebuddy.description.method.MethodDescription$Latent.getReturnType(MethodDescription.java:1462)

... i.m.p.j.t.InliningClassTransformer - Failed to transform class .../IMySuspendCommand
java.lang.StackOverflowError: null
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor$ForAttachment.of(TypeDescription.java:2008)
	at net.bytebuddy.description.type.TypeList$Generic$ForDetachedTypes.attachVariables(TypeList.java:561)
	at net.bytebuddy.description.method.MethodDescription$Latent.getTypeVariables(MethodDescription.java:1455)
	at net.bytebuddy.description.TypeVariableSource$AbstractBase.findVariable(TypeVariableSource.java:157)
	at net.bytebuddy.description.TypeVariableSource$AbstractBase.findExpectedVariable(TypeVariableSource.java:172)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor$ForAttachment.onTypeVariable(TypeDescription.java:2035)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor$ForAttachment.onTypeVariable(TypeDescription.java:1946)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfTypeVariable$Symbolic.accept(TypeDescription.java:5856)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor.onParameterizedType(TypeDescription.java:1881)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor$ForAttachment.onParameterizedType(TypeDescription.java:1946)

... i.m.p.j.t.InliningClassTransformer - Failed to transform class .../IMySuspendCommand
java.lang.StackOverflowError: null
	at java.base/java.lang.StringConcatHelper.newArray(StringConcatHelper.java:494)
	at java.base/java.lang.String.join(String.java:3263)
	at java.base/java.lang.System$2.join(System.java:2477)
	at java.base/java.util.StringJoiner.toString(StringJoiner.java:174)
	at java.base/java.lang.reflect.Modifier.toString(Modifier.java:246)
	at net.bytebuddy.description.method.MethodDescription$AbstractBase.toString(MethodDescription.java:998)
	at java.base/java.lang.String.valueOf(String.java:4213)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
	at net.bytebuddy.description.TypeVariableSource$AbstractBase.findExpectedVariable(TypeVariableSource.java:174)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor$ForAttachment.onTypeVariable(TypeDescription.java:2035)
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

**Comment by FortTell** [comment]
See also https://github.com/raphw/byte-buddy/issues/1357

**Comment by stuebingerb** [comment]
I assume this is related: https://github.com/mockk/mockk/issues/920
