### ISSUE TITLE
Feature: mocking native methods alike System.currentTimeMillis()

### ISSUE THREAD

**Issue by LeoColman** [mockk/mockk#98]
I wanted to mock System.currentTimeMillis(), but it results in a Stackoverflow error.

```
@Test
    fun `System`(){
        mockkStatic(System::class)
    
        every { System.currentTimeMillis() } returns 1L
        
        assertEquals(System.currentTimeMillis(), 1L)
    }
```

```
00:18:57.851 [main] DEBUG io.mockk.proxy.jvm.StaticProxyMaker - Transforming class java.lang.System for static method interception
Exception in thread "main" java.lang.StackOverflowError
	at java.lang.Class.getDeclaredMethod(Class.java:2127)
	at java.lang.System.getSecurityManager(System.java:334)
	at java.lang.Class.checkMemberAccess(Class.java:2337)
	at java.lang.Class.getDeclaredMethod(Class.java:2127)
```

**Comment by Kerooker** [comment]
Further reading: [StackOverflow question about PowerMock and System class](https://stackoverflow.com/questions/20404276/mock-system-class-to-get-system-properties)

**Comment by oleksiyp** [comment]
There are two problems here.

First is that System.getSecurityManager() is called from ByteBuddy instrumented `getDeclarationMethod` and leads to recursion if intercepted. So I relaxed this by interecepting whole `System` without `getSecurityManager` function. You now(when version is released) can intercept something alike `System.getProperty(name)`. Which is itself useful.

The second issue is that `currentTimeMillis()` is `native` method. There is no support for such methods yet. I'll rename issue to `native` method support and keep it for records.

**Comment by pascalpfeil** [comment]
I would like to see this feature implemented, too.

**Comment by pascalpfeil** [comment]
Any other possibilities to mock system time?

**Comment by mylesbennett** [comment]
Closed stale thread - I know - but it still comes up in search results.
I have a workaround that is not clearly expressed elsewhere:

You can't mockkstatic `System` but you _can_ mockkstatic `Calendar`. So in your production code use:
```
Calendar.getInstance().timeInMillis
```
instead of:
```
System.currentTimeMillis()
```
then in your tests you can do something like:
```
        val calendar = mock<Calendar>()
        mockkStatic(Calendar::class)
        every { Calendar.getInstance() } returns calendar
        whenever(calendar.timeInMillis).thenReturn(System.currentTimeMillis())
```

It beats the hell out of messing around with DI.

**Comment by doodeec** [comment]
In case you don't want to create a new calendar instance everytime (by calling `Calendar.getInstance().timeInMillis`) here is another workaround:
```
object TimeHelper {
    fun getNow() = System.currentTimeMillis()
}
```

in production replace System call with the helper
```
//val now = System.currentTimeMillis()
val now = TimeHelper.getNow()
```

in test:
```
@Test
fun `whatever you want to test`() = mockkObject(TimeHelper) {
    every { TimeHelper.getNow() } returns 1234
    ...
}
```

**Comment by cmhernandezdel** [comment]
This would be good, not for System only, but for other native methods which we cannot change (SDKs for example).

**Comment by Raibaz** [comment]
Mocking the `System` class is generally a bad practice; in fact, we recently released an explicit warning message when trying to do so.
