### ISSUE TITLE
JDK proxies can't be spied anymore in Java 17

### ISSUE THREAD

**Issue by jnizet** [mockk/mockk#981]
Hello. I'm the maintainer of SpringMockK, which eases writing Spring Boot tests with MockK.
Spring Boot 3 just came out, and is now based on Java 17. One of the tests in the test suite, which passed on Java 8, now fails when running on Java 17, because JDK proxies can't be spied anymore with MockK.

### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

It should be possible to spy JDK proxies with JDK 17

### Current Behavior

JDK proxies spied by MockK fail with

```
class io.mockk.impl.InternalPlatform cannot access a member of class java.lang.reflect.Proxy (in module java.base) with modifiers "protected"
java.lang.IllegalAccessException: class io.mockk.impl.InternalPlatform cannot access a member of class java.lang.reflect.Proxy (in module java.base) with modifiers "protected"
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
	at java.base/java.lang.reflect.Field.checkAccess(Field.java:1102)
	at java.base/java.lang.reflect.Field.get(Field.java:423)
	at io.mockk.impl.InternalPlatform.copyFields$copy(InternalPlatform.kt:114)
	at io.mockk.impl.InternalPlatform.copyFields$copy(InternalPlatform.kt:118)
	at io.mockk.impl.InternalPlatform.copyFields(InternalPlatform.kt:121)
	at io.mockk.impl.instantiation.AbstractMockFactory.spyk(AbstractMockFactory.kt:107)
``` 

#### Steps to Reproduce

Compile and run the following test with Java 17 and the latest MockK version. This repro is also available as a github project: https://github.com/jnizet/mockk-proxy-bug

```kotlin
package com.example

import io.mockk.spyk
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test
import java.lang.reflect.Proxy

interface ExampleRepository {
    fun find(id: String): String
}

class ExampleRepositoryImpl: ExampleRepository {
    override fun find(id: String) = "Hello $id"
}

class ProxyBugTest {
    val realRepo = ExampleRepositoryImpl()

    val proxyRepo = Proxy.newProxyInstance(
        this::class.java.classLoader,
        arrayOf(ExampleRepository::class.java)) { _, _, _ ->
        "Test"
    } as ExampleRepository

    @Test
    // passes
    fun `real repo should work fine`() {
        assertEquals("Hello world", realRepo.find("world"))
    }

    @Test
    // passes
    fun `spied real repo should work fine`() {
        val spiedRealRepo = spyk(realRepo)
        assertEquals("Hello world", spiedRealRepo.find("world"))
    }

    @Test
    // passes
    fun `proxy repo should work fine`() {
        assertEquals("Test", proxyRepo.find("world"))
    }

    @Test
    // fails
    fun `spied proxy repo should work fine`() {
        val spiedProxyRepo = spyk(proxyRepo)
        assertEquals("Test", spiedProxyRepo.find("world"))
    }
}
```

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.13.2
* OS: macOS
* Kotlin version: 1.7.10
* JDK version: 17
* JUnit version: 5.9.1
* Type of test: unit test

#### Stack trace

```
class io.mockk.impl.InternalPlatform cannot access a member of class java.lang.reflect.Proxy (in module java.base) with modifiers "protected"
java.lang.IllegalAccessException: class io.mockk.impl.InternalPlatform cannot access a member of class java.lang.reflect.Proxy (in module java.base) with modifiers "protected"
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
	at java.base/java.lang.reflect.Field.checkAccess(Field.java:1102)
	at java.base/java.lang.reflect.Field.get(Field.java:423)
	at io.mockk.impl.InternalPlatform.copyFields$copy(InternalPlatform.kt:114)
	at io.mockk.impl.InternalPlatform.copyFields$copy(InternalPlatform.kt:118)
	at io.mockk.impl.InternalPlatform.copyFields(InternalPlatform.kt:121)
	at io.mockk.impl.instantiation.AbstractMockFactory.spyk(AbstractMockFactory.kt:107)
```

**Comment by aSemy** [comment]
> JDK proxies can't be spied anymore with MockK

I think these errors are caused by security restrictions introduced in JDK 16, so they can't be spied on at all, without adding additional build config. So it's not a MockK specific change.

Can you try following the instructions that https://github.com/mockk/mockk/pull/965 will add?

**Comment by aSemy** [comment]
I think that the proxies are in a different module to `java.lang`. Can you try adding the following?

```
jvmArgs(
  "--add-opens", "java.base/java.lang=ALL-UNNAMED",
  "--add-opens java.base/java.lang.reflect=ALL-UNNAMED".
)
```

https://github.com/mockk/mockk/issues/681#issuecomment-1297467111

**Comment by sergey-volkov-lm** [comment]
Package name should indeed be fully qualified.
`java.lang` does not work, `java.lang.reflect` does.
I'll add this remark to docs in PR
